### ISSUE TITLE
feat: AWS plugin Cost Explorer API table support 

### ISSUE THREAD

**Issue by kumaresh0** [cloudquery/cloudquery#10014]
### Which problem is this feature request solving?

The current AWS source plugin doesn't support  [Cost Explorer API  ](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_AWS_Cost_Explorer_Service.html), we can utilize the API to add a new table that helps to fetch cost details about the AWS account and even forecasted data

https://www.cloudquery.io/docs/plugins/sources/aws/tables

### Describe the solution you'd like
Discussed here: https://discord.com/channels/872925471417962546/873606591335759872/1096235185231626341

<img width="411" alt="image" src="https://user-images.githubusercontent.com/117239791/231919362-ae110eb1-3551-41ec-a206-cf65dc7c51e7.png">

As above image, we should have a separate tables for many costs ( daily, account based, tag based, service based )
aws_cost_by_*

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
@kumaresh0 - Thanks for opening up this issue! I just want to clarify that you meant to link to the [AWS Cost Explorer API](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_AWS_Cost_Explorer_Service.html) and not the AWS Pricing API? We already support the AWS Pricing API in the [awspricing plugin](https://www.cloudquery.io/docs/plugins/sources/awspricing/overview)

**Comment by kumaresh0** [comment]
@bbernays Yes, you're right. my mistake let me update the comment. looking for plugin support for https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_Operations_AWS_Cost_Explorer_Service.html

**Comment by haris81** [comment]
This feature will be very useful from a centralized cost reporting of cloud spend and utilization. 

The only design factor would be cost of .01 per paginated result.. so parameters / config will need to be introduced for historical and incremental data pulls based on date ranges, last x window - for ex: past week, month, qtr, year, etc.

**Comment by bbernays** [comment]
@haris81 - Yes you are spot on. because each request will cost users money, we have to be very careful with how we roll this out. One idea we have had is to put this into its own plugin.

**Comment by kumaresh0** [comment]
@bbernays Yes I think a good way would be adding as a separate table on the AWS plugin, whenever users want to look for the cost they can use the table.
