### ISSUE TITLE
[FR] gitlab: need `email` in `gitlab_group_members`

### ISSUE THREAD

**Issue by Hokwang** [cloudquery/cloudquery#10117]
### Which problem is this feature request solving?

Hi,

I think there's no email field.

Please add email field.

And also please take care of gitlab api.

### Describe the solution you'd like

I can see email in official docs.
Please refer to https://docs.gitlab.com/ee/api/members.html.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Hokwang** [comment]
also I found that there's no way to get project members.

**Comment by candiduslynx** [comment]
Hi @Hokwang!

Thanks for the feature request.

I've created an upstream [PR](https://github.com/xanzy/go-gitlab/pull/1702) to add this field.
Once it's merged & released we'll update the SDK we use for interactions with GitLab API.

If it takes too much time we will just switch to forked one, but I'd wait and see for the response from the maintainer of the SDK first.

**Comment by Hokwang** [comment]
@candiduslynx Thanks, and please add `ProjectMember` also.

**Comment by candiduslynx** [comment]
> @candiduslynx Thanks, and please add `ProjectMember` also.

@Hokwang could you open a separate issue for that?
Just to track the different requests in different places.

**Comment by candiduslynx** [comment]
go-gitlab [v0.83.0](https://github.com/xanzy/go-gitlab/releases/tag/v0.83.0) is released, so we can implement this now
