### ISSUE TITLE
feat: Improve Initialization Performance for AWS Plugin

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#10151]
### Which problem is this feature request solving?

When initializing AWS client with LOTS of accounts (either via Org or hardcoded) it can take upwards of 30 minutes for the sync to begin

### Describe the solution you'd like

Make it faster...

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
Sounds great! FYI for Azure I had to do a follow up to limit the concurrency via https://github.com/cloudquery/cloudquery/pull/9811 as with too many subscriptions it created network errors
