### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by LuD1161** [cloudquery/cloudquery#103]
Hi team,

It was nice using this tool.
I would like to suggest an update to the documentation as it's a bit inconsistent at places.

For example : 
Some places it's `config.yml` ( like here : [https://docs.cloudquery.io/aws/authentication](https://docs.cloudquery.io/aws/authentication) ), whereas at other places it's `config.hcl` ( like here : [https://docs.cloudquery.io/quick-start#running](https://docs.cloudquery.io/quick-start#running) )

Thanks.

**Comment by roneli** [comment]
updated documentation thanks pointing them out :)
