### ISSUE TITLE
feat: Support service and type as columns in AWS plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#10366]
### Which problem is this feature request solving?

This is both a report of a discrepancy in a past blog and a feature request. Discord user `mingfang` [reported](https://discord.com/channels/872925471417962546/873606591335759872/1100653639179173898) that the [blog post on the AWS resources view](https://www.cloudquery.io/blog/aws-resources-view) mentions `service` and `type` columns, but this is no longer available on the current view (nor in the SQL query shown in the post). 

We should either add these columns back to the view, if possible, or if not possible then at least fix the blog post to be consistent. User mingfang also requested that these columns be added to all tables by the AWS plugin, as a performance improvement over parsing ARNs in the view, but this is something we can discuss if adding it to the view turns out not to be viable.

### Describe the solution you'd like

`service` and `type` columns available on the AWS resources view

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pchaganti** [comment]
This would be really useful. Not needing to parse the ARN into corresponding tokens on the client side for large accounts can help performance.
