### ISSUE TITLE
feat: Add a Finale source plugin

### ISSUE THREAD

**Issue by gururise** [cloudquery/cloudquery#10460]
### Describe the plugin

Finale inventory management:
https://support.finaleinventory.com/hc/en-us/categories/115001160947-API-Documentation

### Link to API documentation

https://support.finaleinventory.com/hc/en-us/categories/115001160947-API-Documentation

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/finale. Please sign up there to get a notified when the plugin is available.
