### ISSUE TITLE
Error message when migration fails on `migrate_mode: safe` should be clearer

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#10545]
Many destinations currently use an error message along the lines of `tables %s with changes %v require force migration. use 'migrate_mode: forced'`. This is confusing to users as it implies that you cannot proceed without using a forced migration. However, in fact, you can also manually perform the migration and keep `migrate_mode: safe`. 

I suggest changing the messaging to something like this:

```
The following changes can not be automatically migrated in safe mode: %s.

Please perform this migration manually or set `migrate_mode: 'forced'` to do a forced migration.
```

**Comment by erezrokah** [comment]
PostgreSQL was done in https://github.com/cloudquery/cloudquery/pull/11662. Opened https://github.com/cloudquery/cloudquery/pull/12390 for others
