### ISSUE TITLE
Oracle Source Plugin: Add VNIC IPs and Block Volume Attachments

### ISSUE THREAD

**Issue by chrisfw** [cloudquery/cloudquery#10573]
Hi, I wanted to say thank you for creating this plugin!  It will definitely make keeping track of assets in our Oracle tenancy much easier.
In looking through the postgres tables I created as my destination for the oci data, I am having trouble finding vnic ips  and block volume attachments to instances to tie those assets together.

Is there a plan to add additional surface area to this plugin as the above would really be helpful information for managing these cloud assets?  I'd certainly be interested in helping to implement though as a Java developer primarily, golang is relatively new to me.  Below are a couple of references I found for the aforementioned SDK functionality.

[ListVolumeAttachments](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/VolumeAttachment/ListVolumeAttachments) 

```
https://github.com/oracle/oci-java-sdk/blob/master/bmc-examples/src/main/java/GetInstancePublicIpExample.java

     Iterable<PrivateIp> privateIpsIterable =
                    vcnClient
                            .getPaginators()
                            .listPrivateIpsRecordIterator(
                                    ListPrivateIpsRequest.builder().vnicId(vnicId).build());
            for (PrivateIp privateIp : privateIpsIterable) {
                try {
                    GetPublicIpByPrivateIpIdResponse getPublicIpResponse =
                            vcnClient.getPublicIpByPrivateIpId(
                                    GetPublicIpByPrivateIpIdRequest.builder()
                                            .getPublicIpByPrivateIpIdDetails(
                                                    GetPublicIpByPrivateIpIdDetails.builder()
                                                            .privateIpId(privateIp.getId())
                                                            .build())
                                            .build());
                    publicIps.add(getPublicIpResponse.getPublicIp().getIpAddress());
                } catch (BmcException e) {
                    // A 404 is expected if the private IP address does not have a public IP
                    if (e.getStatusCode() != 404) {
                        System.out.println(
                                String.format(
                                        "Exception when retriving public IP for private IP %s (%s)",
                                        privateIp.getId(), privateIp.getIpAddress()));
                    } else {
                        System.out.println(
                                String.format(
                                        "No public IP for private IP %s (%s)",
                                        privateIp.getId(), privateIp.getIpAddress()));
                    }
                }
            }
        }
```
Regards,
Chris Whelan

**Comment by candiduslynx** [comment]
Hi @chrisfw!

I've added the following tables in #11403:
- `oracle_compute_volume_attachments`
- `oracle_virtualnetwork_assigned_public_ips`
- `oracle_virtualnetwork_ephemeral_public_ips`
- `oracle_virtualnetwork_private_ips`
- `oracle_virtualnetwork_reserved_public_ips`

Instead of getting public IPs one by one I decided to implement 3 different tables for 3 different modes [listed in API documentation](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/PublicIp/ListPublicIps). Does this approach work for you?

**Comment by candiduslynx** [comment]
@chrisfw 
We usually release on Tuesday's.
If you need it urgently we can make an out-of-cycle release.

**Comment by chrisfw** [comment]
@candiduslynx , no rush, I just wanted to know when I should plan to grab the new release that incorporates this functionality.  I will plan to do so on Tuesday and test out the new functionality.  Thanks again!

-Chris
