### ISSUE TITLE
Feature Request: add Yandex.Cloud provider

### ISSUE THREAD

**Issue by GennadySpb** [cloudquery/cloudquery#106]
https://cloud.yandex.com - Enterprise-grade cloud platform made by Yandex.

**Comment by GennadySpb** [comment]
Started developing this provider in https://github.com/GennadySpb/cq-provider-yandex

**Comment by yevgenypats** [comment]
@GennadySpb Amazing, Thanks! We will be happy to help with that, feel free to hit us with any questions. We will also just about to open a discourse server so there will be a better medium for discussing various topics/development/issues/bugs (I'll share a link tomorrow). 

Also - Once there is an initial working version we can add this to our provider hub on our website under community providers.

Just curious are you part of the Yandex team or just a Yandex-Cloud user?

**Comment by GennadySpb** [comment]
> Also - Once there is an initial working version we can add this to our provider hub on our website under community providers.

So, right now I have got working version with one complete resource type - Compute Image.

> Just curious are you part of the Yandex team or just a Yandex-Cloud user?

I'm have both roles :) Part of Yandex team and active Yandex.Cloud user.

**Comment by GennadySpb** [comment]
So, what next steps for shine new provider? :)

**Comment by yevgenypats** [comment]
We will test it today and push it tomorrow onto our provider-hub and website (with community label) so you will be able to use it via `cloudquery init GennadySpb/cq-provider-yandex`.

**Comment by yevgenypats** [comment]
Short update: `./cloudquery_Darwin_x86_64 init GennadySpb/yandex`  almost work now. What is the matching public key that you used to sign your .txt.sum ? We can skip the verification  for community plugins for now if you don't have one currently but we will need to add this in the future for security purposes.

**Comment by GennadySpb** [comment]
Here you are https://gist.github.com/GennadySpb/2b64f248df3438a983d94ac0237899bf

**Comment by yevgenypats** [comment]
Awesome. Thx for quick reply. We will add it to our hub and fix the verification tomorrow morning to work with this key. So will ping you tomorrow once all is live! Thx again!

**Comment by GennadySpb** [comment]
So, moving is really fast. Thank you! I will wait for your ping!

**Comment by GennadySpb** [comment]
It seems to me that it would be much preferable to move the provider code to the official yandex-cloud repository. What do you say? And with git url like yandex-cloud/cq-provider-yandex add provider to Hub.

**Comment by yevgenypats** [comment]
sure, sounds good to me. ping me here when you transfer it and we will update it's easy.

**Comment by GennadySpb** [comment]
https://github.com/yandex-cloud/cq-provider-yandex - ready to go :)

**Comment by yevgenypats** [comment]
Awesome. That works now `./cloudquery init yandex-cloud/yandex` apart from the verification which we will fix tomorrow.

**Comment by yevgenypats** [comment]
This works now `./cloudquery init yandex-cloud/yandex` , will put also the link to Yandex provider on our website shortly.

**Comment by yevgenypats** [comment]
https://github.com/cloudquery/cloudquery/releases/tag/v0.13.5

**Comment by yevgenypats** [comment]
Add link on our website - https://www.cloudquery.io/

Closing this issue - and opening a follow-up issue to handle verification for community providers (not it's just skips it for the time being).

Thanks again!
