### ISSUE TITLE
Not able to fetch ingress details from eks cluster

### ISSUE THREAD

**Issue by pyelulkar** [cloudquery/cloudquery#1060]
### Discussed in https://github.com/cloudquery/cloudquery/discussions/1059

<div type='discussions-op-text'>

<sup>Originally posted by **pyelulkar** July  1, 2022</sup>

### Describe the Bug
CLoudquery k8s provider is not able to fetch kubernetes ingress resource details  from eks cluster.
I am using k8s provider v0.5.11 to fetch kubernetes resources from eks cluster. I am able to get all resources except below - 
k8s_core_service_load_balancer_ingress_ports
k8s_core_service_load_balancer_ingresses
k8s_networking_network_policy_ingress      
k8s_networking_network_policy_ingress_from 
k8s_networking_network_policy_ingress_ports

In config.hcl I have put below so that all k8s resources will be fetched - 

  // list of resources to fetch
  resources = [
  "*"]

### Expected Behavior
It should fetch these details

### CloudQuery Version
0.28.2

### Debug Output

4:38AM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
4:38AM INF Anonymous telemetry collection and crash reporting enabled. Run with --no-telemetry to disable, or check docs at https://docs.cloudquery.io/docs/cli/telemetry instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF Invocation parameters args=[] command="cloudquery fetch" core_version=0.28.2 flag:config=config.hcl flag:enable-console-log=true instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 pflag:config=config.hcl pflag:enable-console-log=true
4:38AM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
4:38AM INF An update to CloudQuery core is available: 0.30.2! instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF Syncing CloudQuery providers [k8s@v0.5.11] instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF Initializing CloudQuery Providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF downloading providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 providers=[{"Name":"k8s","Source":"cloudquery","Version":"v0.5.11"}]
4:38AM INF Downloading provider instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 name=k8s version=v0.5.11
4:38AM INF providers download successfully duration=510.977695 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 providers=[{"Name":"k8s","Source":"cloudquery","Version":"v0.5.11"}]
4:38AM INF Finished provider initialization instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF Checking available provider updates instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF checking update for provider instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s version=v0.5.11
4:38AM INF update available for provider instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 new_version=v0.5.17 provider=k8s version=v0.5.11
4:38AM INF Update available for provider k8s: v0.5.11 ➡️  v0.5.17 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF syncing provider schema instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s@v0.5.11
4:38AM INF requesting provider schema instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s@v0.5.11
4:38AM INF plugin doesn't exist, creating... alias= instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s
4:38AM INF plugin process exited instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 path=.cq/providers/cloudquery/k8s/v0.5.11-linux_amd64 pid=141
4:38AM INF Finished syncing providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF Starting provider fetch instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF received fetch request extra_fields=null instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680
4:38AM INF plugin doesn't exist, creating... alias=k8s instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s
4:38AM INF requesting provider to configure alias=k8s instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s
4:38AM INF creating k8s client for context @module=k8s context=arn:aws:eks:eu-west-1:************:cluster/************ instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 timestamp=2022-07-01T04:38:40.397Z
4:38AM INF provider configured successfully alias=k8s instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s
4:38AM INF provider started fetching resources alias=k8s instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider=k8s
4:38AM INF calculated max goroutines for fetch execution @module=k8s instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 max_goroutines=953829 timestamp=2022-07-01T04:38:40.404Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_limit_ranges:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=0 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_limit_ranges timestamp=2022-07-01T04:38:41.099Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_resource_quotas:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=0 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_resource_quotas timestamp=2022-07-01T04:38:41.101Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_networking_network_policies:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=0 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_networking_network_policies timestamp=2022-07-01T04:38:41.107Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_batch_cron_jobs:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=6 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_batch_cron_jobs timestamp=2022-07-01T04:38:41.188Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_apps_stateful_sets:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=14 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_apps_stateful_sets timestamp=2022-07-01T04:38:41.200Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_apps_daemon_sets:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=7 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_apps_daemon_sets timestamp=2022-07-01T04:38:41.223Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_namespaces:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=15 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_namespaces timestamp=2022-07-01T04:38:41.270Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_apps_replica_sets:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=90 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_apps_replica_sets timestamp=2022-07-01T04:38:41.375Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_batch_jobs:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=22 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_batch_jobs timestamp=2022-07-01T04:38:42.028Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_nodes:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=15 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_nodes timestamp=2022-07-01T04:38:42.195Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_rbac_roles:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=28 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_rbac_roles timestamp=2022-07-01T04:38:42.240Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_rbac_role_bindings:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=31 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_rbac_role_bindings timestamp=2022-07-01T04:38:42.312Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_apps_deployments:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=42 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_apps_deployments timestamp=2022-07-01T04:38:42.412Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_services:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=57 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_services timestamp=2022-07-01T04:38:42.505Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_service_accounts:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=87 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_service_accounts timestamp=2022-07-01T04:38:42.671Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_endpoints:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=57 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_endpoints timestamp=2022-07-01T04:38:43.044Z
4:38AM INF fetched successfully @module=k8s client_id=k8s_core_pods:1 context=arn:aws:eks:eu-west-1:************:cluster/************ count=207 instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 table=k8s_core_pods timestamp=2022-07-01T04:38:49.702Z

### Steps to Reproduce

```
cloudquery init
cloudquery fetch
```

### References
</div>

**Comment by bbernays** [comment]
closed as issue has been moved here: https://github.com/cloudquery/cq-provider-k8s/issues/214
