### ISSUE TITLE
cloudquery init aws fails Type: Internal Severity: Error

### ISSUE THREAD

**Issue by security101** [cloudquery/cloudquery#1062]
### Describe the Bug
Executing ./cloudquery init aws stops with an internal error

### Expected Behavior
AWS Plugin is downloaded & initialized

### CloudQuery Version
v0.30.2

### Debug Output
```
./cloudquery --enable-console-log --verbose init aws

3:49PM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=true
3:49PM INF limits (before adjustment) hard_ulimit=4096 instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 soft_ulimit=1024
3:49PM INF adjusting max ulimit instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 new_ulimit=16384 previous_ulimit=4096
3:49PM INF adjusting current ulimit instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 new_ulimit=16384 previous_ulimit=1024
3:49PM INF Anonymous telemetry collection and crash reporting enabled. Run with --no-telemetry to disable, or check docs at https://docs.cloudquery.io/docs/cli/telemetry instance_id=e56a21c0-8901-4175-bcf2-55c08140c921
3:49PM INF Invocation parameters args=["aws"] command="cloudquery init" core_version=0.30.2 flag:enable-console-log=true flag:verbose=true instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 pflag:enable-console-log=true pflag:verbose=true
3:49PM DBG found existing provider instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 provider=aws version=v0.8.5
3:49PM DBG update check succeeded, no new version instance_id=e56a21c0-8901-4175-bcf2-55c08140c921
3:49PM INF Initializing CloudQuery Providers instance_id=e56a21c0-8901-4175-bcf2-55c08140c921
3:49PM INF downloading providers instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 providers=[{"Name":"aws","Source":"cloudquery","Version":"latest"}]
3:49PM DBG Downloading required providers instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 providers=[{"Name":"aws","Source":"cloudquery","Version":"latest"}]
3:49PM INF Downloading provider instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 name=aws version=latest
3:49PM ERR ❌ failed to initialize provider: failed to download providers: Get "https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/providers/aws/versions?mask.fieldPaths=tag&orderBy=v_major+desc%2C+v_minor+desc%2C+v_patch+desc%2C+published_at+desc&pageSize=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers) instance_id=e56a21c0-8901-4175-bcf2-55c08140c921
3:49PM ERR failed to download providers: Get "https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/providers/aws/versions?mask.fieldPaths=tag&orderBy=v_major+desc%2C+v_minor+desc%2C+v_patch+desc%2C+published_at+desc&pageSize=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers) details= instance_id=e56a21c0-8901-4175-bcf2-55c08140c921 resource=[] type=Internal
Error: failed to download providers: Get "https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/providers/aws/versions?mask.fieldPaths=tag&orderBy=v_major+desc%2C+v_minor+desc%2C+v_patch+desc%2C+published_at+desc&pageSize=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Steps to Reproduce
```
cloudquery init aws
```

No config.hcl created

### Additional Context
Linux <hostname> 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### References
non

**Comment by yevgenypats** [comment]
@security101 I think it might due to some downtime in [CloudQuery Hub](https://hub.cloudquery.io) where we index which plugins are available (we use firebase). Can you try again - still the same?

**Comment by security101** [comment]
Dear @yevgenypats, thank you for your response. No, it do not work.

Brief description: 
a) I downloaded v0.30.5 and checked but still get the message: Diagnostics:
Type: Internal Severity: Error
        Summary: failed to download providers: Get "https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/providers/aws/versions?mask.fieldPaths=tag&orderBy=v_major+desc%2C+v_minor+desc%2C+v_patch+desc%2C+published_at+desc&pageSize=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

b) I checked also with v0.18.0 stating ❌ Failed to initialize provider: provider plugin aws@v0.12.24 not registered at https://hub.cloudquery.io. and 
c) I checked it also with v0.23.0 stating Type: Internal Severity: Error
        Summary: failed to download providers: Get "https://firestore.googleapis.com/v1/projects/hub-cloudquery/databases/(default)/documents/orgs/cloudquery/providers/aws/versions?mask.fieldPaths=tag&orderBy=v_major+desc%2C+v_minor+desc%2C+v_patch+desc%2C+published_at+desc&pageSize=1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by security101** [comment]
Using the link within Chrome I get the message: {
  "error": {
    "code": 403,
    "message": "Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier: eYhDkfYCu-dOCjuj8X4Am9-spkxs0-kX5YnhAJmc3PZ7pmNNfSsqtQ",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "VPC_SERVICE_CONTROLS",
            "description": "eYhDkfYCu-dOCjuj8X4Am9-spkxs0-kX5YnhAJmc3PZ7pmNNfSsqtQ"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SECURITY_POLICY_VIOLATED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "firestore.googleapis.com",
          "uid": "eYhDkfYCu-dOCjuj8X4Am9-spkxs0-kX5YnhAJmc3PZ7pmNNfSsqtQ",
          "consumer": "projects/hub-cloudquery"
        }
      }
    ]
  }
}

**Comment by erezrokah** [comment]
Hi @security101, thanks for following up, and I was just about to ask you to try and access the link via a browser :)

It seems the network you're trying to run `cloudquery` from has a security policy to block requests to firestore.
You would need to contact the systems administrator to allow outbound access, or configure a proxy:
https://docs.cloudquery.io/docs/configuration/proxy-configuration

**Comment by security101** [comment]
Yes, I make sense. Based on your advice I used a different on premise system and network. Download and installation of the aws provider worked as expected. I continue search for the root cause on my side.

**Comment by erezrokah** [comment]
Glad to know it's working, thanks for the update @security101 🙌  I'll close the issue as resolved. If you have any further questions or comments please added them to the issue.
