### ISSUE TITLE
Bug: Inconsistent log messages capitalization

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1066]
Some of our log messages start with a capital letter and some don't.
We should ensure the messages are consistent and use a single style.

See example to inconsistency in https://github.com/cloudquery/cloudquery/discussions/1059:
![image](https://user-images.githubusercontent.com/26760571/177035149-c934fdbb-3fa3-4f42-b15c-df80a9d45b38.png)

**Comment by Nightfurex** [comment]
Hey, can you let me know which style would you prefer the log messages to follow starting with Captial letters or not?

**Comment by erezrokah** [comment]
Woo @Nightfurex you're fast 🔥 Let's go with capital letters. I'm thinking that if we have a 2 sentences message (e.g `Hello world. Goodbye world`) it would be odd to have the first with a lower case letter.

Please let me know if that makes sense.

**Comment by Nightfurex** [comment]
Hey so just making sure if I understood the issue properly I have to manually change all the logs starting with non-capital words with their equivalent capital words. For eg:- "downloading providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider" this should be replaced with "Downloading providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 providers"

**Comment by erezrokah** [comment]
> Hey so just making sure if I understood the issue properly I have to manually change all the logs starting with non-capital words with their equivalent capital words. For eg:- "downloading providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 provider" this should be replaced with "Downloading providers instance_id=bb7b16a8-7bd4-4cf3-9549-359d97d11680 providers"

Yes, that's the issue 💯 Another way to do it is via [a lint rule to automatically check the messages](https://github.com/cloudquery/.github/blob/639588d77947f74af9922dd50937b6098a303f48/misc/common/.golangci.yml), but I think we can do the manual way now, and the automated way later as that could take some time to figure out.

**Comment by erezrokah** [comment]
Closing as stale due to v2 refactor
