### ISSUE TITLE
feat: Add CFN stack template body to AWS source plugin

### ISSUE THREAD

**Issue by pchaganti** [cloudquery/cloudquery#10693]
### Describe the resource

AWS plugin is currently missing CloudFormation stack template body. It should ideally be stored as JSON in one of the columns. Or if it works better, as this is a separate API call, maybe even a child table. The template body is NOT part of the describe_stacks or the stack_summary API calls and you need to make a **get_template** call. 

### Use Case

The stack template contains a lot of important information that is an essential part of a CFN stack.

### Link to API documentation

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_GetTemplate.html

### Additional Context

https://github.com/cloudquery/cloudquery/pull/10571

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by jsonpr** [comment]
For context, here's the discord thread: https://discord.com/channels/872925471417962546/873606591335759872/1105810278848921620
