### ISSUE TITLE
feat: Github Enterprise Plugin Support

### ISSUE THREAD

**Issue by JayakrishnaThota** [cloudquery/cloudquery#10696]
### Which problem is this feature request solving?

I would like to request Github Enterprise Plugin Support for syncing github meta data in our enterprise to a destination plugin. Currently, Cloudquery supports Github https://www.cloudquery.io/docs/plugins/sources/github/overview

But there is no way to either configure an endpoint to redirect to github enterprise in the github plugin or a new github enterprise plugin itself.

### Describe the solution you'd like

It would be great if we have a way to configure an endpoint in github plugin to redirect to github enterprise or a new github enterprise source plugin to sync the data from. If we go in the route of a new plugin, it would be great if it can sync the same data as Github plugin https://www.cloudquery.io/docs/plugins/sources/github/tables

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Completed in #10776
