### ISSUE TITLE
feat: observability for CloudQuery sync runs with Prometheus

### ISSUE THREAD

**Issue by kumaresh0** [cloudquery/cloudquery#10706]
### Which problem is this feature request solving?

Similar to this guide, it would be good if we have support for Prometheus 
https://www.cloudquery.io/how-to-guides/datadog-observability

This is discussed here:
https://discord.com/channels/872925471417962546/873606591335759872/1105639646249111652

### Describe the solution you'd like

observability to CloudQuery sync runs with Prometheus exporter

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by hermanschaaf** [comment]
Hi @kumaresh0, thanks for raising this request! I hope you don't mind me asking a few more questions about the request:
 - what data specifically would you like to see or query using Prometheus?
 - the Datadog example uses log ingestion, while normally Prometheus will pull its data from some defined HTTP endpoint; I'm not sure it's a good fit for a case like this where the CLI is not a long-running process? Or is there a way to do the same kind of thing with Prometheus as we're doing in the Datadog example?

I think my advice in general would be to ingest the logs in structured JSON format somewhere and then parse them for further insight. If not Datadog, then Splunk, Elasticsearch, Meilisearch or any other log platform should also work.
