### ISSUE TITLE
bug: Azure returns inconsistent case sensitive results render pks incorrect

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#10779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems Azure sometimes returns inconsistent case sensitive [results](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) which then can make duplicates in the destination.

### Expected Behavior

we need to use `to_lower` on any fields that are used as azure pks

### CloudQuery (redacted) config

-

### CloudQuery (redacted) logs

-

### CloudQuery version

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bb-mmacecek** [comment]
Just FYI: this impacts Azure `id`s only.

**Comment by erezrokah** [comment]
Related casing issues in the Azure Go SDK https://github.com/Azure/azure-sdk-for-go/issues?q=is%3Aissue+casing+. We should try and find a way to hook into the SDK and lowercase all IDs (we can make this normalization an optional configuration to avoid the breaking change)
