### ISSUE TITLE
feat: datadog source plugin to include SLO data

### ISSUE THREAD

**Issue by wh-wayfair** [cloudquery/cloudquery#10780]
### Which problem is this feature request solving?

Datadog has SLO data like it does monitors and we would like to capture that. 

I believe it would involve using SLO API the https://docs.datadoghq.com/api/latest/service-level-objectives/ and SLO corrections API https://docs.datadoghq.com/api/latest/service-level-objective-corrections/

I can contribute this feature, but I am having an issue following the contributions guide in the source plugin as it references codegen which seems to have been removed. Can someone give me some pointers to get started? 

### Describe the solution you'd like

Just add tables for SLO and SLO corrections.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by hermanschaaf** [comment]
Hey @wh-wayfair :wave: Thanks for raising this, and thanks for the tip about the outdated contribution guide. I've gone ahead and updated the guide in this PR https://github.com/cloudquery/cloudquery/pull/10816 (hopefully to be merged into main soon). If you're still open to contributing the SLO tables, hopefully this is enough to get you started :) 

In short, you'll need to:
 - create the service interface for SLOs and generate the mocks (will be easier once https://github.com/cloudquery/cloudquery/pull/10816 is merged in)
 - create the resource with a Table and a resolver function that fetches the results
 - create a mock test for this

Generally this mostly involves copy-pasting from another similar resource and tweaking the names a bit :) Also check out our developer docs, including how to run the plugin locally https://www.cloudquery.io/docs/developers/running-locally and how to write a cloudquery plugin (https://www.cloudquery.io/docs/developers/creating-new-plugin). The latter covers more than you need, but it explains all the relevant concepts and there is quite a bit of overlap.

**Comment by disq** [comment]
@wh-wayfair Hi, this was addressed in the recent [v3.0.0 release](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-datadog-v3.0.0).
