### ISSUE TITLE
feat: [gitlab] add member info when using gitlab.com saas

### ISSUE THREAD

**Issue by Hokwang** [cloudquery/cloudquery#10828]
### Which problem is this feature request solving?

Hi,
Now, cloudquery can not get member info from gitlab when using gitlab saas.

I think saas user and company rate is getting bigger, so cloudquery can handle and provide the all information using api.

### Describe the solution you'd like

how about get company's top level group name for variable?

In my case,
`gitlab.com/company` is top level group,
and I can get all users info using `billable_members` api.

I think this can be useful instead of member table.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Hokwang** [comment]
I want to add a new table `billable_members`.

**Comment by Hokwang** [comment]
@candiduslynx Hi, do you have any progress?

**Comment by candiduslynx** [comment]
Hi @Hokwang!

We've been busy porting our codebase to Apache Arrow (including sources, too): #10711 .

I'll try to take at this issue today.
