### ISSUE TITLE
enhancement: MySQL Destination Testing

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#10872]
Currently the MySQL destination is only being tested against MySQL 5.7 which will be EOL in a few months (Oct 2023). In preparation of that we should add automated testing for MySQL 8.x.

This is not to say we should drop 5.7, but most users are probably using 8.x by now so our tests should cover that use case

**Comment by erezrokah** [comment]
I would say let's drop support for 5.7 once it reaches EOF (with a breaking change).
I moved this to the relevant iteration

**Comment by erezrokah** [comment]
PRs at https://github.com/cloudquery/cloudquery/pull/17311 and https://github.com/cloudquery/cloudquery-private/pull/1663
