### ISSUE TITLE
feat: Add an OpenAI source plugin

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#10891]
### Describe the plugin

obviously there's a bunch of excitement around OpenAI's offerings. There's a proliferation of APIs associated with that and collecting that data to help manage and govern those will likely be important going forward. 

### Link to API documentation

https://github.com/sashabaranov/go-openai  https://platform.openai.com/docs/api-reference

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/openai. Please sign up there to get a notified when the plugin is available.
