### ISSUE TITLE
feat: Add invoices to HubSpot source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#10926]
### Describe the resource

Requested by a user on Discord. 

It seems like invoices are supported via the Accounting extension, but as of 28 February 2023, the accounting extension has been deprecated. Another issue is that it seems to only support getting invoices by ID, not listing all invoices, so I'm not sure if this is going to be possible unless we have a source to pull invoice IDs from. https://developers.hubspot.com/docs/api/crm/extensions/accounting

### Use Case

Export all invoices alongside other data

### Link to API documentation

https://developers.hubspot.com/docs/api/crm/extensions/accounting

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
The API migration [guide](https://developers.hubspot.com/docs/api/migrate-an-existing-account-extension-integration#migrate-the-deal-record-invoice-card) suggests that only a hook to allow viewing the invoice from the customer-supplied system should be available, other things (like search invoices) isn't available in HubSpot for now.

If this changes in the future, we can implement the invoices table, but not for now.
