### ISSUE TITLE
feat: Add a BigQuery source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#11105]
### Describe the plugin

BigQuery is currently supported as a destination plugin, but it is a popular request to also support it as a source.

### Link to API documentation

https://pkg.go.dev/cloud.google.com/go/bigquery

### Pull request (optional)

- [X] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/bigquery. Please sign up there to get a notified when the plugin is available.
