### ISSUE TITLE
feat: Investigate keeping our Arrow fork up to date with upstream main

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#11168]
### Which problem is this feature request solving?

This will also mean updating `replace` in our plugins that point to our fork.

### Describe the solution you'd like

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Done via https://github.com/cloudquery/.github/pull/400 and setting the default branch of `cloudquery/arrow` to `cqmain`
