### ISSUE TITLE
Issue - Error: destination mongodb does not support CloudQuery SDK version 1. Please upgrade to newer version of mongodb

### ISSUE THREAD

**Issue by craigleander** [cloudquery/cloudquery#11171]
Issue - 

Error: destination mongodb does not support CloudQuery SDK version 1. Please upgrade to newer version of mongodb

--
Mongo destination plugin

  registry: "github"
  path: "cloudquery/mongodb"
  version: "v2.0.1"
  spec:
    connection_string: "mongodb://localhost:27017"
    database: "mongocollection"

--
Mongo DB version

db version v6.0.6
Build Info: {
    "version": "6.0.6",
    "gitVersion": "26b4851a412cc8b9b4a18cdb6cd0f9f642e06aa7",
    "modules": [],
    "allocator": "system",
    "environment": {
        "distarch": "aarch64",
        "target_arch": "aarch64"
    }
}

**Comment by hermanschaaf** [comment]
Hi @craigleander, thanks for reporting this! We sorted it out on Discord.

For future readers, this error indicates that you need to upgrade to the latest version of the mongodb destination plugin, which at the time of writing is `v2.1.0`.
