### ISSUE TITLE
Knative eventing support

### ISSUE THREAD

**Issue by yuriy-yarosh** [cloudquery/cloudquery#11203]
### Which problem is this feature request solving?

Use CloudQuery as the respective knative eventing source/dest plugins, and vice-versa - CloudQuery could be used as an EventSource, and a Channel for Knative.

### Describe the solution you'd like

Knative Eventing uses CloudEvents out of the box, with limited in-mem processing support.
It's possible to boost processing by reusing the existing Apache Arrow shmem IPC primitives.

Even without shmem IPC, CloudQuery offloading should provide a reasonable amount of integrations for Knative adopters, including Google Cloud Run.

Already added an issue there [knative-eventing/#7000](https://github.com/knative/eventing/issues/7000) regarding Arrow support.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Closing as stale.
