### ISSUE TITLE
ERROR: duplicate key

### ISSUE THREAD

**Issue by pseymournutanix** [cloudquery/cloudquery#1120]
### Describe the Bug
Just running a basic fetch getting:-
```
Fetch Diagnostics:

Resource: backup.global_settings Type: Database Severity: Ignore
	Summary: failed to insert to table "aws_backup_global_settings": ERROR: duplicate key value violates unique constraint "aws_backup_global_settings_pk" (SQLSTATE 23505)
	Detail: bulk_insert_failed. [Repeated:4]

Provider aws fetch summary: ✓ Total Resources fetched: 6282	 ❓ Ignored issues: 1(4)
Provider aws finished with 1(4) ignored issues.
This may be normal, however, you can use `--verbose` flag to see more details.
```

### Expected Behavior
Fetch should complete without issue

### CloudQuery Version
Version: 0.31.7
Commit: 8aaacbae7ff1f4b72e5ea1ecf9b5e56d8094a473
Date: 2022-07-12T12:26:58Z

### Debug Output
```
{"level":"info","instance_id":"0c9ea8ac-2f67-45ed-8cd9-def9c1975884","path":".cq/providers/cloudquery/aws/v0.12.29-darwin_amd64","pid":6985,"time":"2022-07-14T11:53:46+01:00","message":"plugin process exited"}
{"level":"debug","instance_id":"0c9ea8ac-2f67-45ed-8cd9-def9c1975884","time":"2022-07-14T11:53:46+01:00","message":"plugin exited"}
{"level":"debug","instance_id":"0c9ea8ac-2f67-45ed-8cd9-def9c1975884","type":"Database","resource":[],"details":"bulk_insert_failed. [Repeated:4]","time":"2022-07-14T11:53:47+01:00","message":"failed to insert to table \"aws_backup_global_settings\": ERROR: duplicate key value violates unique constraint \"aws_backup_global_settings_pk\" (SQLSTATE 23505)"}
```

**Comment by pseymournutanix** [comment]
OK thank you for explaining. I wondered if it was related to this query being empty:-
```
SELECT count(*) FROM information_schema.tables
     WHERE  table_schema = 'public'
     AND    table_name   = 'aws_resources'
```

After loading the view for the Grafana dashboard but that might be unrelated.

**Comment by bbernays** [comment]
Yeah that is unrelated. `aws_resources` is a view that you have to manually create by executing this query: https://github.com/cloudquery/cq-provider-aws/blob/main/views/resources.sql

**Comment by pseymournutanix** [comment]
Yes thank you I had done that and I see all the panels populated (it's very good BTW) but it's just the "Data Source" panel is showing as "Not OK" as that query is empty and I went looking for an issue.

Anyway if unrelated to this issue I will continue to look.

**Comment by shimonp21** [comment]
Looked through the code - I really can't figure how a 'duplicate PK' can happen for this table, since the PK is `account_id` https://github.com/cloudquery/cq-provider-aws/blob/586c862cd8fcb0d3e5473c5ca9eb4ab4f9bbc380/resources/services/backup/global_settings.go#L20.
I will close this for now since we have a big refactor coming up around error-handling and database insertion that will *hopefully* remove this kind of bugs. 

If this keeps happening after the refactor than we should reopen and investifgate more thoroguhly.
