### ISSUE TITLE
Don't fail if check for update failed

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#1122]
Right now we added the `--don't-check-for-update`. I think the default behaviour should be not fail if update check failed and in that caes we can also avoid flag fatigue + the user knowing about this flag.

**Comment by yevgenypats** [comment]
cc @bernays

**Comment by bbernays** [comment]
I agree that the default behavior of that check failing should not cause fetch to stop. I also think it is important that users have a way of running CQ that doesn't require attempting to make network calls to our servers

**Comment by yevgenypats** [comment]
We don't have check for update command anymore but if we will add it in the future agree that we need to have this flag of both default command and `--no-update-check`
