### ISSUE TITLE
feat: Add kubernetes table to digitalocean source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#11349]
### Describe the resource

We need the table with kubernetes collection for digitalocean.

### Use Case

 We would like to verify certain attributes regrading kubernetes for best practices i.e. autoscaling is enabled or not and auto-upgrade status.

### Link to API documentation

https://docs.digitalocean.com/reference/api/api-reference/#operation/kubernetes_list_clusters/

### Additional Context

We would need tables for these as well
https://docs.digitalocean.com/reference/api/api-reference/#operation/kubernetes_get_cluster.
https://docs.digitalocean.com/reference/api/api-reference/#operation/kubernetes_list_nodePools

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by icio** [comment]
Looks like you resolved this in #12438. Thanks!
