### ISSUE TITLE
feat: Add SSH keys table to Digital ocean source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#11361]
### Describe the resource

We need the list for SSH keys for Digital Ocean.

### Use Case

We would like to ensure if we have unique SSH keys in our account, and check if there is no usage for SSH Keys.

### Link to API documentation

https://docs.digitalocean.com/reference/api/api-reference/#operation/sshKeys_list

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
Hi @code-vise , `digitalocean_keys` should contain the data you need.
