### ISSUE TITLE
feat: Add BackupPlanDescription to aws-rds source plugin

### ISSUE THREAD

**Issue by tech-ken** [cloudquery/cloudquery#11417]
### Describe the plugin

This resource will be added to the existed plugin of aws rds.
backup plan is used to backup AWS resources such as DB instances.

Ref:
https://docs.aws.amazon.com/aws-backup/latest/devguide/creating-a-backup-plan.html

**Use Case**
We need to use this resource to check wether RDS DB instance is covered by a backup plan or not.

Ref:
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-26

### Link to API documentation

https://docs.aws.amazon.com/aws-backup/latest/devguide/API_DescribeProtectedResource.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by jsonpr** [comment]
Hi @tech-ken!  Thanks for opening up this issue.  

I'm not as familiar with AWS Backup.  To clarify what you need for coverage, would `aws_backup_plan_selections` and `aws_backup_plans` work for you to determine whether the RDS instances are covered by a Backup plan?  We can also look to add Protected Resources if that's the information you need.

The `backup_selection` field of `aws_backup_plan_selections` should specify which resources are selected and excluded. 

https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_backup_plan_selections

**Comment by tech-ken** [comment]
Hi @jsonpr! Thanks for the comment!

What I want to do is to scan if RDS DB instance is covered by backup plan or not.  AWS sometimes uses confusing terminology so I was also confused in the first place but it seems that "RDS DB instance needs to be covered by backup plan " means that RDB DB instance needs to be protected by using a AWS resource named "aws backup", if I understood the docs correctly.

note: I might be wrong. 

Ref:
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-26
https://docs.aws.amazon.com/aws-backup/latest/devguide/creating-a-backup-plan.html

I have already tried using  aws_backup_plan_selections and aws_backup_plans which you mentioned, but I was not able to determine if RDB DB instance is covered by a backup plan or not from those tables. 

I assume that if RDS DB instance is covered by backup plan, it will be tagged in the "Protected Resource" showed in the docs below.

Ref:
https://docs.aws.amazon.com/aws-backup/latest/devguide/API_DescribeProtectedResource.html

**Comment by jsonpr** [comment]
Yes, @tech-ken - agreed.  Thanks for looking into this more.  The "protected" in the "Protected Resources" threw me off as well.  Looks like protected resources should cover what you're looking for!

From AWS on list-protected-resources, "Returns an array of resources successfully backed up by Backup, including the time the resource was saved, an Amazon Resource Name (ARN) of the resource, and a resource type."  So this should return successes (which can be indirectly used to determine if a backup plan covers it).

Our team has put in a PR that should give you what you're looking for.
