### ISSUE TITLE
feat: Add a ServiceNow source plugin

### ISSUE THREAD

**Issue by sirijagadeesh** [cloudquery/cloudquery#11525]
### Describe the plugin

To sync ServiceNow data.

### Link to API documentation

https://docs.servicenow.com/en-US/bundle/utah-api-reference/page/integrate/inbound-rest/concept/c_TableAPI.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Closing as duplicate https://github.com/cloudquery/cloudquery/issues/13317
