### ISSUE TITLE
feat: Integration With benthos.dev

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#11610]
### Which problem is this feature request solving?

[benthos.dev](https://www.benthos.dev/) is a streaming processing framework also written in Go.

`benthos` focused mostly on the transformation phase while CQ mostly on the ELT step.

I don't have an idea on top of my head on a good use-case or an elegant way to integrate the two but opening this issue mostly for community visibility and for people to weigh in if they have a use-case where using both projects makes sense.

### Describe the solution you'd like

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
I wonder if we could work with the Benthos devs to integrate calling Benthos into the CLI as a transform step? 

source --> cli --> benthos --> cli --> destination

**Comment by mihaitodor** [comment]
PS: It’s also possible to have a custom CQ input / processor / output / etc as exemplified here: https://github.com/benthosdev/benthos-plugin-example

**Comment by yevgenypats** [comment]
Closing for now due to lack of user interest/use case on CloudQuery side. may reopen in the future dependent on user feedback
