### ISSUE TITLE
Source Plugin: Hashicorp Cloud Integration

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#11625]
### Describe the plugin

Hashicorp Cloud Source Plugin

### Link to API documentation

https://www.hashicorp.com/cloud

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/hashicorp-cloud. Please sign up there to get a notified when the plugin is available.
