### ISSUE TITLE
bug: Missing `properties.keyVaultKeyUri` in `azure_cosmos_database_accounts`

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#11622]
### Describe the resource

properties.keyVaultKeyUri in https://www.cloudquery.io/docs/plugins/sources/azure/tables/azure_cosmos_database_accounts this table

### Use Case

want to check if cosmosdb account is using encryption_at_rest_using_cmk

### Link to API documentation

https://learn.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/2022-11-15-preview/database-accounts/list?tabs=HTTP&tryIt=true#code-try-0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
@code-vise do you miss this info from the properties?
Or you want this to be a top-level field in the `azure_cosmos_database_accounts` resource?

**Comment by code-vise** [comment]
yes we are missing this info from the properties. 
and no we dont want it to be a top-level field, Its just missing in the properties column of the table

**Comment by candiduslynx** [comment]
@code-vise 
We use [this object](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/cosmos/armcosmos/v2@v2.2.0#DatabaseAccountGetProperties) from Azure SDK and the spec for the `keyVaultKeyUri` is
```go
// The URI of the key vault
KeyVaultKeyURI *string `json:"keyVaultKeyUri,omitempty"`
```
so the `null` value from Azure API will be just omitted & won't be present in the output.

Kindly verify that you can see the value if you assign some Key Vault Key URI, and, if so, this just works as designed and you'll need to account for possible missing values in your queries.
Missing value == `null` in this case.

Consider this example for PostgreSQL:
```
postgres=# create table alex_test(a jsonb);
CREATE TABLE

postgres=# insert into alex_test values('{"a":123}');                                                                                                                 INSERT 0 1

postgres=# select * from alex_test;                                                                                                                                        a      
------------
 {"a": 123}
(1 row)

postgres=# select a->>'a' from alex_test;
 ?column? 
----------
 123
(1 row)

postgres=# select a->>'b' from alex_test;
 ?column? 
----------
 
(1 row)

postgres=# select (a->>'b' IS NULL) as b_is_null from alex_test;
 b_is_null 
-----------
 t
(1 row)

postgres=# select (a->>'a' IS NULL) as a_is_null, (a->>'b' IS NULL) as b_is_null from alex_test;
 a_is_null | b_is_null 
-----------+-----------
 f         | t
(1 row)
```
