### ISSUE TITLE
feat: GraphQL Source

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#11635]
### Which problem is this feature request solving?

GraphQL is designed to be a strongly typed api that is self documenting. By using introspection cloudquery should be able to sync arbitrary graphql data

### Describe the solution you'd like

Create a plugin that uses introspection to examine an Schema generate tables and then sync the data

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/graphql. Please sign up there to get a notified when the plugin is available.
