### ISSUE TITLE
feat: Add Azure OpenAi to Azure source plugin

### ISSUE THREAD

**Issue by tweaknc** [cloudquery/cloudquery#11630]
### Describe the resource

We are adding in services utilizing Azure OpenAI and would like to maintain inventory of these instances. 

### Use Case

Understand usage, model, and regional information and any related metadata to the services. 

### Link to API documentation

https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/?ef_id=_k_Cj0KCQjw7aqkBhDPARIsAKGa0oIQB_760vxJAT7oMreq_jgz_fcYNGDH79oTA3vGsIEbRv-fLPxbdWIaAkJbEALw_wcB_k_&OCID=AIDcmm5edswduu_SEM__k_Cj0KCQjw7aqkBhDPARIsAKGa0oIQB_760vxJAT7oMreq_jgz_fcYNGDH79oTA3vGsIEbRv-fLPxbdWIaAkJbEALw_wcB_k_&gad=1&gbraid=0AAAAADcJh_vtdS-GXxDETCS6MLTgznIxr&gclid=Cj0KCQjw7aqkBhDPARIsAKGa0oIQB_760vxJAT7oMreq_jgz_fcYNGDH79oTA3vGsIEbRv-fLPxbdWIaAkJbEALw_wcB

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @tweaknc and thank you for the issue. Please let me know if https://github.com/cloudquery/cloudquery/pull/11645#issuecomment-1594802053 is what you had in mind
