### ISSUE TITLE
feat: Add a AnalyticDB for PostgreSQL destination plugin

### ISSUE THREAD

**Issue by ChenpiDog** [cloudquery/cloudquery#11643]
### Describe the plugin

AnalyticDB for PostgreSQL is a massively parallel processing (MPP) data warehousing service that is designed to analyze large volumes of data online.

AnalyticDB for PostgreSQL is developed based on the open source Greenplum Database project and is enhanced with in-depth extensions by Alibaba Cloud.

### Link to API documentation

https://www.alibabacloud.com/help/en/analyticdb-for-postgresql/latest/api-reference

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
As far as I understand AnalyticsDB alibaba can be both compatible with [MySQL](https://www.alibabacloud.com/help/en/analyticdb-for-mysql) and [PostgreSQL](https://www.alibabacloud.com/help/en/analyticdb-for-postgresql) so this should be supported by our postgresql and mysql destination plugins already.

Closing. If incorrect please reopen.
