### ISSUE TITLE
feat: Add a Greenplum source plugin

### ISSUE THREAD

**Issue by ChenpiDog** [cloudquery/cloudquery#11640]
### Describe the plugin

Greenplum
  Greenplum Database (GPDB) is an advanced, fully featured, open source data warehouse, based on PostgreSQL.

### Link to API documentation

https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/landing-index.html#differences-compared-to-open-source-greenplum-database

### Pull request (optional)

- [ ] I can submit a pull request
```[tasklist]
### Tasks
```

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/greenplum. Please sign up there to get a notified when the plugin is available.
