### ISSUE TITLE
bug: Configuration Heroku Section

### ISSUE THREAD

**Issue by luanrjjj** [cloudquery/cloudquery#11681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Configuration Section of Heroku plugin isn't working

### Expected Behavior

The button "Configuration" in menu must redirect to configuration.

### CloudQuery (redacted) config

No necessary

### Steps To Reproduce

1. Access Cloudquery Website
2. After Plugins, Source, Heroku, Configuration

### CloudQuery (redacted) logs

404 page.

### CloudQuery version

Heroku version 4.0.2

### Additional Context

I understand that the button "Configuration" isn't more necessary. Because the information about configuration is in Overview section 

### Pull request (optional)

- [X] I can submit a pull request

**Comment by hermanschaaf** [comment]
Thanks for reporting this @luanrjjj! We'll get it fixed soon 👍
