### ISSUE TITLE
Feature request: AWS WAF

### ISSUE THREAD

**Issue by siniysv** [cloudquery/cloudquery#117]
Hello and thank you so much for your beautiful product.
Could you please consider adding AWS WAF? Resources - WEB ACL, rule groups, managed rule groups, rules, ACL attachments. It will help to add compliance checks for PCI DSS and maybe others.

Thank you once more! I hope I'll learn go well enough to contribute but for now I completely rely on you.

**Comment by michelvocks** [comment]
Hi @siniysv!

Thanks for opening this feature request! 

There are two PR's in review right now that implement both the support for WAF V1 and WAF V2. I tried to add all the resources you've mentioned but there were a few caveats:

* WAF V1 doesn't have managed rule groups so I instead added SubscribedRuleGroups.
* I wasn't able to find a resource that is called "acl attachments" so I skipped it. Please let me know the exact resource name so I can add it within a follow up PR.

Feel free to have a look at both PR's and comment if anything could be improved.

Cheers,
Michel

**Comment by roneli** [comment]
Hi @siniysv we added Waf V1 and V2 to AWS provider starting version [v0.4.7](https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.4.7)
