### ISSUE TITLE
feat: Add a `immudb` destination plugin

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#11703]
### Describe the plugin

If using CloudQuery to audit and store compliance information users need a way to ensure that records are not changed... This DB could be used with CQ's  `append` mode to aggregate that data for analysis

### Link to API documentation

github.com/codenotary/immudb/pkg/client

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/immudb. Please sign up there to get a notified when the plugin is available.
