### ISSUE TITLE
feat: Add a Mend source plugin

### ISSUE THREAD

**Issue by ekelson-bcove** [cloudquery/cloudquery#11704]
### Describe the plugin

I am proposing that Mend be added as a source plugin.  It is similar in function and purpose to Snyk (currently a source).  The plugin would be able to pull information from the Mend platform as process for reporting and querying.

### Link to API documentation

https://docs.mend.io/bundle/mend-api-2-0/page/index.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/mend. Please sign up there to get a notified when the plugin is available.
