### ISSUE TITLE
feat: Add droplet_list_firewalls to digital ocean source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#11725]
### Describe the resource

lists the firewall associated with the each droplet,
- retrieving the list of firewalls from the list_firewall calls is complex, since one firewall can be associated with multiple droplets.

### Use Case

need to check firewalls for each droplet

### Link to API documentation

https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_list_firewalls

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by icio** [comment]
Hi @code-vise, the [digitalocean_firewalls](https://www.cloudquery.io/docs/plugins/sources/digitalocean/tables/digitalocean_firewalls) table has a `droplet_ids` column which is a `list<item: int64, nullable>`.

You could join from the digitalocean_droplets table to the digitalocean_firewalls table in Postgres like this:

```sql
SELECT d.name AS droplet_name, f.name AS firewall_name
FROM digitalocean_droplets d
LEFT JOIN digitalocean_firewalls f ON d.id=ANY(f.droplet_ids);
```

For example:

```
postgres=# SELECT id, name, size_slug FROM digitalocean_droplets;
    id     |         name         |     size_slug      
-----------+----------------------+--------------------
 368870727 | firewalled-droplet-1 | s-1vcpu-512mb-10gb
(1 row)

postgres=# SELECT name, droplet_ids, inbound_rules FROM digitalocean_firewalls;
    name     | droplet_ids |                                     inbound_rules                                     
-------------+-------------+---------------------------------------------------------------------------------------
 only-ssh-in | {368870727} | [{"ports": "22", "sources": {"addresses": ["0.0.0.0/0", "::/0"]}, "protocol": "tcp"}]
(1 row)

postgres=# SELECT d.name AS droplet_name, f.name AS firewall_name FROM digitalocean_droplets d LEFT JOIN digitalocean_firewalls f ON d.id=ANY(f.droplet_ids);
     droplet_name     | firewall_name 
----------------------+---------------
 firewalled-droplet-1 | only-ssh-in
(1 row)
```

Let us know if this suits your needs. Thanks

**Comment by erezrokah** [comment]
Closing the issue per the comment in https://github.com/cloudquery/cloudquery/issues/11725#issuecomment-1667819247. We already have the data and querying it via a join seems preferable to sending an additional request per droplet that would slow the sync down. Please comment if this is still an issue
