### ISSUE TITLE
feat: Add App_Alert_list to Digital_ocean source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#11723]
### Describe the resource

App alert policies
List all the alerts configured for the apps in digital ocean

### Use Case

would like to check which alerts are configured for apps

### Link to API documentation

https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_list_alerts

### Additional Context

Also there should be table for listing apps only. 
https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_list

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by code-vise** [comment]
Hi ! Any update here?

**Comment by icio** [comment]
@code-vise This has now been released in v5.3.0 of the digitalocean source plugin. Please let us know how you get on with it.

If you have any further requests or problems, please do open a new issue. Thanks!
