### ISSUE TITLE
feat: custom key-value config entity added to all dest plugin tables

### ISSUE THREAD

**Issue by ybudweiser** [cloudquery/cloudquery#11768]
### Which problem is this feature request solving?

Include a custom key-value pair in the output  tables of a givin dest plugin. Specifically I would like to see this for the kafka dest plugin, however this could be useful for all dest plugins in the form of a stateless transformation
For example, if i wanted to run cloudquery for a specific organization or tenant, I would like to see a column in each table that includes the key value configured

### Describe the solution you'd like

```kind: destination
spec:
  name: "kafka"
  path: "cloudquery/kafka"
  version: "v3.1.2"
  write_mode: "append" # only supports 'append'
  additional_keys:  #key value added to each kafka record
    - organization
       foo
    - external_runId
       43245
  spec:
    brokers: ["<broker-host>:<broker-port>"]
    format: "json"

 ```

Sample JSON
```
{"_cq_id":"ea4c8768-4fe1-44db-a179-a912870965f9","_cq_parent_id":null,"_cq_source_name":"aws","_cq_sync_time":"2023-06-22 17:02:19.174448","account_id":"000000000000","arn":"arn:aws:ec2:us-east-1:000000000000:vpc/vpc-da75ed57","cidr_block":"172.31.0.0/16","cidr_block_association_set":[{"AssociationId":"vpc-cidr-assoc-00aad876","CidrBlock":"172.31.0.0/16","CidrBlockState":{"State":"associated","StatusMessage":null}}],"dhcp_options_id":"dopt-7a8b9c2d","instance_tenancy":"default","ipv6_cidr_block_association_set":[],"is_default":true,"owner_id":"000000000000","region":"us-east-1","state":"available","tags":{},"vpc_id":"vpc-da75ed57","organization":"foo","external_runId":"43245"}
```
### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
This seems like a good application for something like #11610

**Comment by yevgenypats** [comment]
This should be possible in SDK v4 (in rollout right now) initially not via `yaml` but can be done via Go code.

**Comment by Hans-HDA** [comment]
I would also be very happy with the ability to add a custom JSON object as a separate column. I would like to extend the request with the ability to add dynamic and hard coded values.

Dynamic could for instance be a timestamp, job id or schedule id.
A hard coded id could be for instance a customer id.

**Comment by erezrokah** [comment]
Hi @ybudweiser and @Hans-HDA, adding column with literal values is now supported via transformations and our basic transformer plugin, more in https://www.cloudquery.io/blog/introducing-transformer-plugins

For adding dynamic values you could write your own transformer, see example in https://github.com/cloudquery/cloudquery/tree/8f7667f78c89514203806a458dafcbf3f389e45b/plugins/transformer/basic
