### ISSUE TITLE
feat: Add an Azure AD source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#11814]
### Describe the plugin

We will need to explore the API to see what is available, but probably list users, license status, etc

Suggested by shivabasu on Discord

### Link to API documentation

https://learn.microsoft.com/en-us/graph/azuread-identity-access-management-concept-overview

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by dsmith111** [comment]
Can you assign this to me?

**Comment by dsmith111** [comment]
Created an Azure AD (now known as Microsoft Entra ID) source plugin here:

https://hub.cloudquery.io/plugins/source/year-of-the-nimbus/azure-ad/v1.0.0/docs

**Comment by yevgenypats** [comment]
Nice! Closing this as done.

**Comment by pkyarlagadda** [comment]
Hi @dsmith111 , do you have plans to support OIDC tokens in Azure AD plugin?

**Comment by mduval07** [comment]
@dsmith111 are you accepting prs for this plugin?  I would be interested in expanding the column list for the azure_ad_device_management table.  Also, adding the tenantId on each parent table would be helpful for users wanting to store information for multiple tenants.

**Comment by dsmith111** [comment]
> Hi @dsmith111 , do you have plans to support OIDC tokens in Azure AD plugin?

Hi @pkyarlagadda, I can look into this. Can you create an issue and have it assigned to me? @yevgenypats, would know the labels to add in this case.

**Comment by dsmith111** [comment]
> @dsmith111 are you accepting prs for this plugin?  I would be interested in expanding the column list for the azure_ad_device_management table.  Also, adding the tenantId on each parent table would be helpful for users wanting to store information for multiple tenants.  

Were you looking to add specific data points for the table?

**Comment by dsmith111** [comment]
> Hey does this support fetching the scopes for role assignments? I don't see it in https://hub.cloudquery.io/plugins/source/year-of-the-nimbus/azure-ad/v1.0.0/tables/azure_ad_user_role_assignments, but possible I'm not looking in the right place. Is there another table that gets the scope of the assingments or is this not supported yet? To give context I'm interested in seeing if users are over provisioned on specific resources.

Hey @adam-bedrock, not yet, but I can add it for the next update if you open an issue I can use for tracking.
