### ISSUE TITLE
feat: Add table for AWS CodeCommit repos

### ISSUE THREAD

**Issue by JohnCalhoun** [cloudquery/cloudquery#11819]
Can we Add AWS CodeCommit Repos as a table?

**Comment by JohnCalhoun** [comment]
thank you for this! I am having issues using it. when cloudquery runs I can see it run ListRepositories (in cloudtrail) but it does not run the BatchGetRepositories and then outputs not data. Permissions are correct (verified using iam simulator)

**Comment by erezrokah** [comment]
Hi @JohnCalhoun, do you mind opening a [new bug](https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E) for the issue you'r having? That ensures it will get the proper visibility
