### ISSUE TITLE
feat: Add a Notion source plugin

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#11943]
### Describe the plugin

Notion source plugin to fetch pages and content from Notion.

### Link to API documentation

https://developers.notion.com/reference/intro

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by gagan-gaurav** [comment]
@disq Hi, I just wanted to know if this assigned to anyone. If not, I can work on this notion source plugin.

**Comment by erezrokah** [comment]
Hi @gagan-gaurav! Thanks for bumping the issue 🚀 No one has started working on it, it would be great to get a contribution for it. I've assigned you to the issue. Please note we have SDK in multiple languages, see the docs in https://www.cloudquery.io/docs/developers/creating-new-plugin

**Comment by gagan-gaurav** [comment]
Hey @erezrokah! the notion source plugin in almost complete, should i make a PR ?

**Comment by erezrokah** [comment]
> Hey @erezrokah! the notion source plugin in almost complete, should i make a PR ?

That would be awesome @gagan-gaurav, see also https://github.com/cloudquery/cloudquery/blob/9d06edee4cab1360975717f37e547bc660ad99e2/contributing/adding_a_new_plugin_to_cq_monorepo.md

**Comment by gagan-gaurav** [comment]
> > Hey @erezrokah! the notion source plugin in almost complete, should i make a PR ?
> 
> That would be awesome @gagan-gaurav, see also https://github.com/cloudquery/cloudquery/blob/9d06edee4cab1360975717f37e547bc660ad99e2/contributing/adding_a_new_plugin_to_cq_monorepo.md

I am not able to perform step 6, since i am not able to login with my gmail. Need help! @erezrokah

**Comment by gagan-gaurav** [comment]
@erezrokah can you please review my PR and let me know if i am on the right track or not :)

**Comment by erezrokah** [comment]
First version is out https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-notion-v1.0.0 amazing work @gagan-gaurav 🚀

**Comment by gagan-gaurav** [comment]
> First version is out https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-notion-v1.0.0 amazing work @gagan-gaurav 🚀

Thanks a lot 😃 @erezrokah !!  Looking forward to make more contributions 🚀.
