### ISSUE TITLE
feat: Support for Snowflake Queries to import AWS / Azure Policies

### ISSUE THREAD

**Issue by KarthikVenkatraman** [cloudquery/cloudquery#11942]
### Which problem is this feature request solving?

Currently Cloudquery supports extracting Policies for Azure / AWS into PostgreSQL -https://github.com/cloudquery/cloudquery/tree/main/plugins/source/azure/policies. The queries provided use psql to dump this data into PostgreSQL database.

It would be nice to have this Policy results exported into Snowflake too by providing the relevant Queries / scripts pertaining to snowflake.

### Describe the solution you'd like

Similar to the way that Cloudquery provides out of the box SQL scripts to import the policy results into Postgres, If you can please provide the required SQL scripts / queries that will help us to import this policy results into Snowflake, that will be ideal.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
@KarthikVenkatraman We have now an alpha version of some of those policies for Snowflake and BigQuery but those are right now under premium (paid) [policies](https://www.cloudquery.io/docs/core-concepts/policies#premium-policies) given we reached our capacity on open source policies. Though pricing is pretty affordable (`$50` one time with 6 months of support and free updates). Let me know if you have any questions or need additional support here. 

Closing for now, feel free to reopen.
