### ISSUE TITLE
Okta provider docs are copied from GCP

### ISSUE THREAD

**Issue by zscholl** [cloudquery/cloudquery#12]
## Description
The current Okta provider docs are exactly the same as GCP

<img width="815" alt="Screen Shot 2020-12-19 at 8 03 09 AM" src="https://user-images.githubusercontent.com/8786230/102691261-c3dd5f00-41d0-11eb-88ab-52a90604e344.png">

I would have opened a PR but it looks like the docs are not part of the repo.

**Comment by yevgenypats** [comment]
@zscholl Thanks for the quick catch! I've pushed a fix.
