### ISSUE TITLE
Allow running policy periodically

### ISSUE THREAD

**Issue by antonbabenko** [cloudquery/cloudquery#121]
I'd like to have the possibility to run the "policy" commands periodically (AWS EventBridge => Lambda) but there is a gap with output file.

I think there is a need to extend `lambda.go` to handle "policy" commands output and store output somewhere (S3 or stdout).

In the future, it would be great to have a way to call `policy` from anywhere (eg, via API Gateway => Lambda).

**Comment by yevgenypats** [comment]
We are now using `psql` directly https://github.com/cloudquery/cq-provider-aws/tree/main/policies
