### ISSUE TITLE
website: Automate the checking for broken links

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#12109]
Current (released) version of the `broken-link-checker` marks http `308` codes as "broken" even if the redirect leads to a `200`. All of our `cloudquery.io/buy/*` have been excluded (in #12108)

**Comment by hermanschaaf** [comment]
I think this is okay; we should generally not link to redirects as it can carry SEO penalties. Where possible, we should link to the target page directly instead. And if we can't for whatever reason, we can exclude them from the links checker.

**Comment by erezrokah** [comment]
Closing this per @hermanschaaf comment. I think that's expected. It would be better if we could configure an expected status code for some links, but the broken links checker doesn't support it
