### ISSUE TITLE
feat(github): GitHub plugin should work without authentication

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#12177]
### Which problem is this feature request solving?

GitHub API is public and thus should also work without authentication. 

### Describe the solution you'd like

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Unauthenticated requests to the GitHub API have a very low rate limit (60 requests per hour). Those are limited based IP address.
I think the plugin will reach the limit quite quickly without authentication

**Comment by erezrokah** [comment]
Going to close this as stale. I think the plugin won't be usable without authentication. Please re-open if we still need this
