### ISSUE TITLE
`cloudquery completion` should not create log file by default

### ISSUE THREAD

**Issue by antonbabenko** [cloudquery/cloudquery#122]
In order to enable completion I have added this:
`cloudquery completion zsh > "${fpath[1]}/_cloudquery"`

And now I have `cloudquery.log` files in few places.

Potential solutions:
- Disable logging for this command
- Update documentation and describe how to turn it off

**Comment by roneli** [comment]
- will disable it for this command
- I will also add more documentation to https://docs.cloudquery.io/cli/overview about the cli flags and how to turn things off. the flag you are looking for is `--enable-file-logging=false`

Will update this issue once PR with solution A has been added

**Comment by roneli** [comment]
Fixed in v0.14.0 #158
