### ISSUE TITLE
feat: Add Deploy Keys to GitHub source plugin

### ISSUE THREAD

**Issue by hobietje** [cloudquery/cloudquery#12403]
### Describe the resource

Github deploy keys: https://docs.github.com/en/rest/deploy-keys/deploy-keys?apiVersion=2022-11-28#list-deploy-keys

### Use Case

We are trying to audit whether any deploy keys exist that (a) were created by former employees or (b) that are no longer in use.

### Link to API documentation

https://docs.github.com/en/rest/deploy-keys/deploy-keys?apiVersion=2022-11-28#list-deploy-keys

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @hobietje, please let us know if https://github.com/cloudquery/cloudquery/pull/12407 is what you had in mind
