### ISSUE TITLE
Feedback for “Quickstart - Windows”

### ISSUE THREAD

**Issue by kofsmg** [cloudquery/cloudquery#12542]
Could use additional details for novices trying to learn. What do I do after I download the executable via CMD/Powershell? How do I run it? start [filename] simply launches a CMD window that immediately crashes. Where do I put the .yaml config files since there is no directory on my system created for cloudquery - only an executable that doesn't seem to launch? How do I run them?

**Comment by erezrokah** [comment]
Hi @kofsmg, thank you for opening the issue 👍 Can share at which step of the guide from https://www.cloudquery.io/docs/quickstart/windows you're getting an error?

To summarize the steps in the guide:
1. [Download the CLI](https://www.cloudquery.io/docs/quickstart/windows#download-cloudquery-cli) via `curl -L https://github.com/cloudquery/cloudquery/releases/download/cli-v3.10.2/cloudquery_windows_amd64.exe -o cloudquery.exe`
2. [Create a destination config file](https://www.cloudquery.io/docs/quickstart/windows#configure-destination-plugin) in `cloudquery-config/postgresql.yml`
3. [Create a source config file](https://www.cloudquery.io/docs/quickstart/windows#configure-source-plugin) in `cloudquery-config/aws.yml`
4. [Run the sync command](https://www.cloudquery.io/docs/quickstart/windows#configure-source-plugin) via `cloudquery.exe sync ./cloudquery-config`

> I think there's a bug in the last step in the guide as the command in the guide does not have the `.exe` prefix that I added to the summary above

**Comment by erezrokah** [comment]
I opened https://github.com/cloudquery/cloudquery/pull/12545 to fix the bug in the docs

**Comment by erezrokah** [comment]
We've fixed the Windows docs to have the correct command. If that doesn't solve this issue please comment and I'll re-open
