### ISSUE TITLE
Question “Introducing AWS Resources View”

### ISSUE THREAD

**Issue by PoojaHoney** [cloudquery/cloudquery#12541]
Hi,

I am not getting the query exactly, because in my account I have only 89 resources using but from the query I am getting nearly 11000 resources list with arn what are those. 

Cloud you please help me over here.

I need only the resources list that I am using, from cloud query and how can I get it

**Comment by erezrokah** [comment]
Hi @PoojaHoney can you:

1. Confirm you used [this query](https://github.com/cloudquery/cloudquery/blob/66d2595167967f5a8bb4dd7bf1fe71ba6b5f386b/plugins/source/aws/views/resources.sql) to create the view
2. Share the YAML configuration you used to sync
3. Share the CloudQuery CLI version you used to sync
4. Explain What do you mean by `only the resources list that I am using`. CloudQuery syncs all the resources in the account and the view shows the ones that have ARNs. How would you classify a used resourced? We also have an `unused resources` policy [here](https://github.com/cloudquery/cloudquery/blob/66d2595167967f5a8bb4dd7bf1fe71ba6b5f386b/plugins/source/aws/policies/unused_resources/policy.sql)

**Comment by bbernays** [comment]
So Resource Explorer only supports a very limited number of AWS Services and Resources while CloudQuery supports many more. You can see the entire list of supported tables by [CloudQuery here](https://www.cloudquery.io/docs/plugins/sources/aws/tables) and [AWS Resource Explorer here](https://docs.aws.amazon.com/resource-explorer/latest/userguide/supported-resource-types.html).

That being said the query you are using finds all resources that have an `ARN` and some of those resources are created by default for you by AWS. For example in the `aws_ec2_instance_types` table, which shows every single EC2 instance type that is available in each region, each unique instance type has an ARN, which shows up in that view. 

To further help you out, can you share answers to the questions that @erezrokah asked above?

**Comment by PoojaHoney** [comment]
But I don't need those like ec2 instance types arns. I just need for the only services and service resources I am using

**Comment by bbernays** [comment]
If there are values or resources you are not interested in you can either not sync those tables by changing your config file [example of this can be found here](https://www.cloudquery.io/docs/plugins/sources/aws/configuration#skip-tables) or exclude them in your query for example:

```sql
select * from aws_resources where type not in ('<RESOURCE_TYPE_0>', '<RESOURCE_TYPE_1>','<RESOURCE_TYPE_2>')
```

**Comment by PoojaHoney** [comment]
Okay, thanks
I will try this, once then

Thanks.

**Comment by bbernays** [comment]
Closing this issue now that the user seems to have a reasonable path forward
