### ISSUE TITLE
feat: snowflake destination keypair support

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#12598]
### Which problem is this feature request solving?

It seems that the snowflake go driver is supporting keypairs but a bit in a confusing way - https://github.com/snowflakedb/gosnowflake/issues/302. Customers asked us to document and validate that this method of authentication is supported.

### Describe the solution you'd like

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by jsonpr** [comment]
Would also be good to document OAuth authentication as another method of authentication.
