### ISSUE TITLE
Feature Request: Azure Public IP Addresses, VMs

### ISSUE THREAD

**Issue by jbertman** [cloudquery/cloudquery#126]
The Azure Network Management API contains a PublicIPAddressesClient type that can allow CloudQuery to quickly enumerate anything with a public address. 

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.1.0+incompatible/services/network/mgmt/2020-08-01/network#PublicIPAddressesClient.ListAll

This could be a great candidate to enumerate resources with public-facing attack surface. Similar to AWS EC2, it would also be useful to enumerate Compute VMs (along with the current disks enumeration). Let me know what you think.

**Comment by roneli** [comment]
Started to add MQ https://github.com/cloudquery/cq-provider-aws/issues/92 service.

**Comment by jbertman** [comment]
Guessing that is in reference to https://github.com/cloudquery/cloudquery/issues/125 (not this issue) - but great to hear regardless, thanks!

**Comment by jbertman** [comment]
@roneli would you rather this be filed in cloudquery/cq-provider-azure?

**Comment by roneli** [comment]
@jbertman no its okay, we will be add more resources including this one very soon to azure

**Comment by roneli** [comment]
Added in  azure provider v0.3.0
