### ISSUE TITLE
feat: Add IPAM to AWS source plugin

### ISSUE THREAD

**Issue by ekelson-bcove** [cloudquery/cloudquery#12647]
### Describe the resource

AWS is changing the cost model (i.e. charging) for usage of public IP's and has released a service to track them in the AWS console called IPAM.  https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html

### Use Case

Users of the AWS plugin will be able to craft queries to generate statistics on the usage of public IP's across organizations and/or accounts.  A simple query now with the current services is complex as Public IP's in-scope for the new AWS IP policy extend beyond EC2 into RDS and various other services. https://aws.amazon.com/blogs/aws/new-aws-public-ipv4-address-charge-public-ip-insights/

### Link to API documentation

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Completed. Will be released in `v23.0.0`
