### ISSUE TITLE
bug: aws codecommit tables not loading

### ISSUE THREAD

**Issue by JohnCalhoun** [cloudquery/cloudquery#12655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

. when cloudquery runs I can see it run ListRepositories (in cloudtrail) but it does not run the BatchGetRepositories and then outputs not data. Permissions are correct (verified using iam simulator)

### Expected Behavior

codecommit tables show up in output

### CloudQuery (redacted) config

kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: v22.3.0
  tables:
    - "*"
  skip_tables:
    - aws_cloudtrail_events
  destinations:
    - s3
  concurrency: 10000
  deterministic_cq_id: true
  spec:
    regions:
      - us-east-2
      - us-east-1
      - us-west-2
      - eu-west-1
    accounts:
      - id: *
        role_arn:*
      - id: *
        role_arn: *
      - id: *
        role_arn: *
    aws_debug: true

### CloudQuery (redacted) logs

  ...

### CloudQuery version

3.10.1

### Additional Context

from #11819

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Thanks for the issue @JohnCalhoun, I believe @bbernays fixed it in https://github.com/cloudquery/cloudquery/pull/12653.
A new release with this fix should be available tomorrow. I'll update the issue once it is

**Comment by bbernays** [comment]
@JohnCalhoun Can you test out the new version of the AWS plugin ([v22.3.0](https://github.com/cloudquery/cloudquery/compare/plugins-source-aws-v22.2.0...plugins-source-aws-v22.3.0)) to see if you are still having issues syncing CodeCommit Repos?

**Comment by JohnCalhoun** [comment]
re ran (which downloaded latest v22.3.0 from releases) and sill dont see the codecommit tables. still seeing it just call list-repositories and not batchgetrepository

**Comment by JohnCalhoun** [comment]
Ok codecommit repos are showing up now, thank you!
