### ISSUE TITLE
refactor: Move docs generation to CLI

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#12706]
Currently docs generation is handled by plugin-sdk code, but as we start writing more SDKs, keeping this code in sync for multiple languages will get hairy.  We should rather use the gRPC `tables` call to get the tables and then generate docs from the CLI. This will require adding relational information as metadata to the gRPC calls first.

**Comment by erezrokah** [comment]
Related to https://github.com/cloudquery/cloudquery/issues/12270
