### ISSUE TITLE
capitalize logging

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#1270]
This is a follow-up for https://github.com/cloudquery/cloudquery/pull/1150

Capitalize log messages and setup linter. This should be done once cq v2 is merged 

https://github.com/cloudquery/cloudquery/pull/1201

**Comment by yevgenypats** [comment]
couldn't find something built-in in golanglint-ci. seems a custom plugin will be needed to revive

**Comment by erezrokah** [comment]
Last time I tried writing a custom rule for revive + integrate it with `golanglint-ci` everything went 💥 
But we can try again, maybe the issue was fixed in the latest versions.

**Comment by yevgenypats** [comment]
no I think let's close it as no-fix for now. I don't think it's important for the time being.
