### ISSUE TITLE
feat: Add a ServiceNow destination plugin

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#12727]
### Describe the plugin

Research on ServiceNow Destination

### Link to API documentation

TBD

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/servicenow. Please sign up there to get a notified when the plugin is available.
