### ISSUE TITLE
feat: replace DelegationSetId with full DelegationSet in aws_route53_hosted_zones

### ISSUE THREAD

**Issue by kfritchman46** [cloudquery/cloudquery#12738]
### Which problem is this feature request solving?

The default (not reusable) DelegationSet of AWS public HostedZones are only visible when describing the HostedZone. The DelegationSet API doesn't include them. 

### Describe the solution you'd like

DelegationSet should be added as a json field of the aws_route53_hosted_zones table so changes in Nameservers can be detected.

DelegationSetId should be removed from aws_route53_hosted_zones as it would be redundant.

PR: https://github.com/cloudquery/cloudquery/pull/12737

### Pull request (optional)

- [X] I can submit a pull request
```[tasklist]
### Tasks
```

**Comment by erezrokah** [comment]
Thanks @kfritchman46, we'll release this fix tomorrow in https://github.com/cloudquery/cloudquery/pull/12724

**Comment by erezrokah** [comment]
This issue was fixed by https://github.com/cloudquery/cloudquery/pull/12737
