### ISSUE TITLE
feat: Add azure__storage_tableacl to Azure source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#12753]
### Describe the resource

need https://learn.microsoft.com/en-us/rest/api/storageservices/get-table-acl data from this call, for checking the ACL permissions for azure storage tables

### Use Case

Would like to check acl permissions for to ensure that tables do not allow full write, delete, or read ACL permissions

### Link to API documentation

https://learn.microsoft.com/en-us/rest/api/storageservices/get-table-acl

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by RyPeck** [comment]
@code-vise is the existing `signedIdentifiers` in properties what you need?

https://github.com/cloudquery/cloudquery/issues/10142 already complete.

**Comment by erezrokah** [comment]
Closing as stale per https://github.com/cloudquery/cloudquery/issues/12753#issuecomment-1670014504. If that's not the case please comment and I'll re-open
