### ISSUE TITLE
feat: Add a Keycloak source plugin

### ISSUE THREAD

**Issue by jinseokyeo** [cloudquery/cloudquery#12796]
### Describe the plugin

keycloak Please

### Link to API documentation

https://www.keycloak.org/docs-api/18.0/rest-api/

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Go SDK: https://github.com/Nerzal/gocloak
https://pypi.org/project/python-keycloak/

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/keycloak. Please sign up there to get a notified when the plugin is available.
