### ISSUE TITLE
feat(azure): Add support for listing resources in a specific location

### ISSUE THREAD

**Issue by rsatal** [cloudquery/cloudquery#12794]
I want to sync the Azure cloud for some specific locations like for AWS cloudquery has `spec.regions`.
I am not getting the option for Azure and GCP

**Comment by erezrokah** [comment]
Thanks for the issue @rsatal, would you be able to link to the relevant Azure docs about using the REST API to list resources by location? I'm not sure all resources support it like AWS, so maybe specific the tables you'd like to have this feature

**Comment by erezrokah** [comment]
Closing as stale. If still relevant please respond to https://github.com/cloudquery/cloudquery/issues/12794#issuecomment-1669079660
