### ISSUE TITLE
feat: enable `overwrite-delete-stale` and `overwrite` in snowflake destination

### ISSUE THREAD

**Issue by zachsis** [cloudquery/cloudquery#12969]
### Which problem is this feature request solving?

Hello! 

We desperately need the ability to set the `overwrite-delete-stale` flag on our snowflake destination to have an accurate snapshot of our cloud resources. Currently we're trying to build queries using `MAX(DATE_PART('epoch', "_cq_sync_time")) AS max_cq_sync_time` to pull recent resources only, but as queries get more and more complex with joins etc, it becomes extra annoying to try and get a 'current snapshot' only of aws resources for a given table. 

Note: I am also open to any ideas on how to truncate the old data in the tables before a new run. Thanks!

### Describe the solution you'd like

enable `overwrite-delete-stale` or `overwrite` or both modes for the `snowflake` destination.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
This was completed in https://github.com/cloudquery/cloudquery/pull/14097
