### ISSUE TITLE
feat: Consider renaming AWS ElasticSearch to OpenSearch

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#12968]
### Which problem is this feature request solving?

Keep naming more in line with AWS Services.

### Describe the solution you'd like

Rename CloudQuery ElasticSearch tables to OpenSearch

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
AWS still has the `elasticsearchservice` package in the SDKs. Is there any difference other than name between [opensearch](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch) and [elasticsearchservice](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticsearchservice)?

**Comment by bbernays** [comment]
This hasn't been completed. Our AWS plugin still has resources named elasticsearch

**Comment by erezrokah** [comment]
Should we have both? The APIs in https://github.com/aws/aws-sdk-go-v2/tree/main/service/elasticsearchservice and https://github.com/aws/aws-sdk-go-v2/tree/main/service/opensearch has some differences
