### ISSUE TITLE
bug: `aws_cloudtrail_trail_event_selectors` is missing advanced selectors

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#12974]
The trail event selectors call (https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/resources/services/cloudtrail/trail_event_selectors.go) returns a response containing `EventSelectors` as well as `AdvancedEventSelectors`, but currently the `aws_cloudtrail_trail_event_selectors` table only includes the `EventSelectors`. We should add the missing advanced event selectors. Since advanced event selectors have a different schema, this may need to be done in a different table if we want to keep the change backwards-compatible.

**Comment by bbernays** [comment]
We have a breaking change that will come in the near(ish) future (#12648) lets just include this change in that
