### ISSUE TITLE
feat: <AWS> Filter with "Include" or "Exclude" the IP address range

### ISSUE THREAD

**Issue by rsatal** [cloudquery/cloudquery#12971]
### Which problem is this feature request solving?

While syncing the records, I want to include or exclude the records based on the list of IP addresses or CIDR ranges. Do we have any option to filter the records?

For example, can we filter the records synced for the [aws_ec2_instances](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_instances) table based on an IP address or IP addresses range against the column `private_ip_address` 

### Describe the solution you'd like

I want to be able to filter the records based on the list of IP addresses or CIDR range. I should be allowed to specify the list of IP addresses I want to "Include" or "Exclude" for the sync for a particular table.

### Pull request (optional)

- [ X ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @rsatal I think what's you're looking for is a table option (see `table_options` in https://www.cloudquery.io/docs/plugins/sources/aws/configuration#aws-spec).

Would that cover your use case?

**Comment by rsatal** [comment]
> table_options

Hi @erezrokah We are having 2 use cases - 

1. We want to get only the records that are included in the **"Include"** IP address range list
2. We want to get all the records except those that are excluded in the **"Exclude"** IP address range list.

I think the first use case can be covered with the `table_options` . I am checking if the 2nd would also be covered somehow with the AWS API using wildcards filters.

Yes, I would need the support of `aws_ec2_instances` table for the `table_options` feature.

**Comment by bbernays** [comment]
@rsatal - I am interested in the use case for doing the filtering at the sync level rather than syncing all instances and then just querying the database for the instances that fall in the desired range

**Comment by rsatal** [comment]
> @rsatal - I am interested in the use case for doing the filtering at the sync level rather than syncing all instances and then just querying the database for the instances that fall in the desired range

@bbernays We want to allow our users to sync data based on the given IP address CIDR range to be included or excluded.  For this, yes we can sync all the instances and then query the database. But to make syncing more efficient and fast, we want to apply the filter at the sync level.

**Comment by bbernays** [comment]
Interesting use case! When you sync the entire `aws_ec2_instances` table for your account(s) how long does it take?

**Comment by rsatal** [comment]
@bbernays We are using cloudquery for syncing our customer's cloud resources on a regular basis. We need to sync many accounts. The time for sync will depend on a customer-to-customer basis. The [aws_ec2_instances](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_instances) table is just an example. Going forward, we need to apply the same filter in many other tables as well like - [aws_ec2_subnets](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_subnets), [aws_ec2_vpcs](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_vpcs), etc.

**Comment by bbernays** [comment]
Closing this issue because there is no way to do this as the API exposed by AWS doesn't support this type of filtering. If you are looking to keep your database up to date with your infrastructure I would suggest checking out the AWS Event-based sync that is currently in open beta

https://www.cloudquery.io/blog/announcing-cloudquery-aws-event-based-sync-open-beta
