### ISSUE TITLE
bug: duplication in AWS foundational security controls for S3

### ISSUE THREAD

**Issue by obormot** [cloudquery/cloudquery#13064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently in `cloudquery/plugins/source/aws/policies/foundational_security/s3.sql` checks S3.1 and S3.8 refer to the same include file:
```
\set check_id 'S3.1'
\echo "Executing check S3.1"
\ir ../queries/s3/account_level_public_access_blocks.sql       <-- correct

\set check_id 'S3.2'
\echo "Executing check S3.2"
\ir ../queries/s3/publicly_readable_buckets.sql

[..skip..]

\set check_id 'S3.8'
\echo "Executing check S3.8"
\ir ../queries/s3/account_level_public_access_blocks.sql     <-- duplicate
```

### Expected Behavior

According to https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html :
```
[S3.8] S3 Block Public Access setting should be enabled at the bucket-level
```
..so I believe the correct file to include should be `s3/bucket_level_public_access_blocks.sql`
ie. bucket instead of the (duplicated) account 

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

(I actually don't know)

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment]
Hi @obormot!

I looked at the [S3.8](https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-8) spec as well as the [query](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/s3/bucket_level_public_access_blocks.sql) in question & you're totally right.
Seems like a typo did find its way into the policies, thanks for catching this!

#13065 should take care of this.

**Comment by candiduslynx** [comment]
@ronsh12 could please you take a look at this, too?

**Comment by jsonpr** [comment]
Hey @obormot - thanks for reporting this issue.   We had a chat internally regarding your feedback.

I agree with your understanding - there's a hierarchy of evaluation of controls that beings with Block Public Access at the account level, then the bucket level, then access point levels.  Thus to your point, if BPA is turned on at the account level, the bucket level BPA settings could be overridden by the account level blocks.  

We wrote a blog post on Block Public Access earlier this year: https://www.cloudquery.io/blog/finding-enabled-s3-acls-and-disabled-s3-block-public-access.  

Here's what we'll do:

- We will update the control for S3.8 (S3 Block Public Access setting should be enabled at the bucket-level) to point to the correct logic.  Agreed that these updates could trigger more positives for customers running the query.  We'd like these to be accurate and thanks for catching the duplicate controls.
- We try to keep our policies as close to the policy frameworks as possible.  In this case, we believe that the Foundational Security Best Practices evaluates the controls separately as there's no overlapping mention in both of them.  https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-8.  Thus, to keep our checks in line with AWS, we'll evaluate them separately as multiple layers of security.

If you'd like to evaluate if the bucket contents are public or not - that could be a custom query that evaluates all settings for a bucket - including access point settings, bucket settings, account settings, ACLs, bucket policies, and more.  

From AWS Documentation: `S3 Block Public Access provides four settings. You can apply these settings in any combination to individual access points, buckets, or entire AWS accounts. If you apply a setting to an account, it applies to all buckets and access points that are owned by that account. Similarly, if you apply a setting to a bucket, it applies to all access points associated with that bucket.`
