### ISSUE TITLE
feat: Add clarification to documentation regarding permissions for Azure and GCP

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#13108]
### Which problem is this feature request solving?

Clarify permissions for users for Azure and GCP plugins.

### Describe the solution you'd like

Clarity in documentation

### Pull request (optional)

- [X] I can submit a pull request

**Comment by ozbillwang** [comment]
different approach for this topic

https://github.com/cloudquery/cloudquery/issues/13189

**Comment by ozbillwang** [comment]
FYI

My understanding of the best practices  for Azure (No idea to GCP)

### Use case #1

If run `cloudquery sync` command in an Azure Virtual machine, we should 

1. create an Azure key vault and set a secret, such as `pg-connection-string`
2. create an Azure Virtual machine
3. assign **reader** role as **user assigned managed identity** on the nominated subscription or management group (management group can include more subscriptions or whole subscriptions in the organization). 
4. assign **key vault select user** to that VM as **managed identity** in the key vault you created above
5. in vm, run below command to get the variable
```
az login --identity
az account set -s <subscription_id_with_key_vault>
az account show

export PG_CONNECTION_STRING=$( az keyvault secret show --vault-name cloudquery --name pg-connection-string --query value -o tsv )
```
6. Now you are fine to run the sync command. 

```
cloudquery sync ./xxxx
```

**Comment by erezrokah** [comment]
I'm going to close this as non actionable as I'm not sure what clarification we need to add.
Please comment on how the existing docs can be improved and I'll re-open
