### ISSUE TITLE
feat: support metadata "Authorization Bearer Access Token" 

### ISSUE THREAD

**Issue by ozbillwang** [cloudquery/cloudquery#13189]
### Which problem is this feature request solving?

Set the azure virtual machine with proper **reader** role, I hope `cloudquery` command can get and sync resource details directly without any `az login`

sample source file for reference
```
kind: source
spec:
  # Source spec section
  name: "azure"
  path: "cloudquery/azure"
  version: "v9.0.2"
  destinations: ["postgresql"]
  concurrency: 10000
  tables: ["*"]
  spec:
    # Azure Spec section
    subscriptions: [""]
```

### Describe the solution you'd like

This is a further discussion about my question in discord: https://discord.com/channels/872925471417962546/873606591335759872/1139949622387822592

I'd like to set a Azure Virtual Machine and running in Virtual Network (optional) to collect the resource details from Whole Organization. The Virtual machine has been assigned with Reader role as user assigned managed identity on the Organization tenant's management group. 

Reason is, I don't need to maintain a new app registration and the VM can have reader permission already without any **ClientID** and **ClientSecret** to be set. That means, before I run `cloudquery` I don't need run `az login` in that VM

So I have given its reader role and it has permission to read all subscriptions' resource now. 

But there is no similar and easy way to get the permission in Azure as [AWS ec2 instance profile ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html)

The azure official solution is via **curl** call , reference this document https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-arm

```
$ curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' -H Metadata:true

{
  "access_token": "eyJ0eXAiOi...",
  "refresh_token": "",
  "expires_in": "3599",
  "expires_on": "1504130527",
  "not_before": "1504126627",
  "resource": "https://management.azure.com",
  "token_type": "Bearer"
}

# then you can use the access_token from previous command to get resource detail 
$ curl https://management.azure.com/subscriptions/<SUBSCRIPTION ID>/resourceGroups/<RESOURCE GROUP>?api-version=2016-09-01 -H "Authorization: Bearer <ACCESS TOKEN>"
```
Now I wrote a python script to do the same as curl command (you can rewrite it with Golang , since CloudQuery is written by Go), and prove the way works without `az login`

```
import requests

def get_access_token():
    url = 'http://169.254.169.254/metadata/identity/oauth2/token'
    params = {
        'api-version': '2018-02-01',
        'resource': 'https://management.azure.com/'
    }
    headers = {
        'Metadata': 'true'
    }

    response = requests.get(url, params=params, headers=headers)

    if response.status_code == 200:
        token_data = response.json()
        access_token = token_data['access_token']
        return access_token
    else:
        print(f"Access token request failed with status code: {response.status_code}")
        return None

def get_resource_group_data(subscription_id, resource_group, access_token):
    url = f"https://management.azure.com/subscriptions/{subscription_id}/resourceGroups/{resource_group}?api-version=2016-09-01"
    headers = {
        'Authorization': f'Bearer {access_token}'
    }

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        resource_group_data = response.json()
        print("Resource Group Data:")
        print(resource_group_data)
    else:
        print(f"Request failed with status code: {response.status_code}")
        try:
            error_message = response.json()["error"]["message"]
            print("Error Message:")
            print(error_message)
        except Exception as e:
            print("Failed to extract error message:", e)

if __name__ == "__main__":
    subscription_id = input("Enter Subscription ID: ")
    resource_group = input("Enter Resource Group: ")

    access_token = get_access_token()
    if access_token:
        get_resource_group_data(subscription_id, resource_group, access_token)
```

With funciton `get_access_token()`, you get Authorization Bearer **Access Token**, and for any new calls to get resource detail, you just attach the header , you can get the detail. 

Now I'd like to know if CloudQuery can be improved, when work in a VM with the reader managed identity, it can directly get details from all resources in azure without `az login` and any client Id and client secret to be set

```
# below command can be skipped
az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
```

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @ozbillwang, based on the Azure docs, the Go SDK already tries to use managed identity, see https://github.com/Azure/azure-sdk-for-go/tree/99c0a042b1a228db9cd1f0c54df095f24f13cf28/sdk/azidentity#defaultazurecredential and https://github.com/Azure/azure-sdk-for-go/tree/99c0a042b1a228db9cd1f0c54df095f24f13cf28/sdk/azidentity#managed-identity.

so assuming the environment is set up correctly everything should just work ™️ 

Maybe we already support it and it's a documentation issue. What happens if you configure managed identity on the VM and doesn't set any env variables?

**Comment by ozbillwang** [comment]
That's great. Yes, it works directly. 

My provious testing has wrong setting. I can confirm without any `az login` (In fact, I did `az logout` to confirm), the `cloudquery sync` command works directly.

**Comment by erezrokah** [comment]
Thanks for confirming @ozbillwang, I opened https://github.com/cloudquery/cloudquery/issues/13192 to improve our docs
