### ISSUE TITLE
feat(azure-docs): Improve authentication docs for Azure plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#13192]
[Apparently we support more authentication options than we document for the Azure plugin](https://github.com/cloudquery/cloudquery/issues/13189#issuecomment-1683880983). We support everything the Go SDK supports, including `Workload Identity` and `Managed Identity`.

We only document `Environment` and `Azure CLI` on our Website. We should also reference the other too options, especially `Managed Identity` as that seems the recommended way to do it in containers/VMs

**Comment by erezrokah** [comment]
Related to https://github.com/cloudquery/cloudquery/issues/13108#issuecomment-1683931246

**Comment by rranjangupta** [comment]
Hi @erezrokah 
When it will be merged?

**Comment by erezrokah** [comment]
Hi @rranjangupta I open the issue so we can triage the work. We haven't created the PR to update the docs yet. If you'd like to contribute a PR you can click the `edit this page` link in https://www.cloudquery.io/docs/plugins/sources/azure/overview
