### ISSUE TITLE
Whether to synchronize resources related to dataProc on gcpfeat: <title>

### ISSUE THREAD

**Issue by songant** [cloudquery/cloudquery#13257]
### Which problem is this feature request solving?

Whether to synchronize resources related to dataProc on gcp

### Describe the solution you'd like

Whether to synchronize resources related to dataProc on gcp

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @songant, can you better explain your feature request? Is it for a new source for the GCP plugin?
If so see https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=enhancement%2Cresource&projects=&template=new_resource.yml&title=feat%3A+Add+%3Cresource-name%3E+to+%3Cplugin-name%3E+source+plugin

**Comment by erezrokah** [comment]
Thanks for following up and opening the resource request. I'm closing this issue in favor of https://github.com/cloudquery/cloudquery/issues/13271
