### ISSUE TITLE
bug: ARN Created with local AccountID Rather than OwnerID

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#13287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently a number of ARN resolvers are using the `client.AccountID` to populate the accountID portion of the ARN. This means that if a resource is owned by another and shared, that the ARN will be wrong.

impacted functions are:

- `resolveHostArn`
- `resolveEbsSnapshotArn`
- `resolveInternetGatewayArn`
- `resolveNetworkAclArn`
- `resolveNetworkInterfaceArn`
- `resolveRouteTableArn`
- `resolveSecurityGroupArn`
- `resolveVpcEndpointServiceArn`
- `resolveVpcEndpointArn`
- `resolveVpcArn`
- `resolveSnapshotARN`
- `resolveDocumentARN`

### Expected Behavior

instead of `client.AccountID` the `arn` should use the `OwnerID` field from the API response

### CloudQuery (redacted) config

NA

### Steps To Reproduce

NA

### CloudQuery (redacted) logs

NA

### CloudQuery version

NA

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment]
`resolveVpcEndpointServiceArn` is nowhere to be found, others are addressed in the linked PRs
