### ISSUE TITLE
feat: Support JIRA issue custom fields

### ISSUE THREAD

**Issue by pilvikala** [cloudquery/cloudquery#13306]
### Which problem is this feature request solving?

When using JIRA for tracking potential or confirmed vulnerabilities, a customer uses custom fields with additional information. It is currently not possible to retrieve the values of the custom fields.

### Describe the solution you'd like

TBD

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
> It is currently not possible to retrieve the values of the custom fields.

We actually do sync these values, but it's hard to access them. You'd need to know the custom field ID and use the following query (example in Postgres):

```sql
select key, fields->>'customfield_10033' from jira_issues
```

![image](https://github.com/cloudquery/cloudquery/assets/26760571/eb4d0df6-d117-4ac4-ad93-482975fea931)

I'll look into getting the custom fields definitions so one could join over those

**Comment by erezrokah** [comment]
Ok looks like we have `jira_fields` which can be used to map the custom field key to a human friendly name:
![image](https://github.com/cloudquery/cloudquery/assets/26760571/85cf3732-6a09-404e-a146-632f0e5f6816)

Closing as already implemented. Please re-open if that's not what you were looking for

**Comment by pilvikala** [comment]
That's cool. In PostgreSQL, I can actually write it as 

```sql
select key, fields->>(select "key" from jira_fields where name='MY CUSTOM FIELD') from jira_issues
```
