### ISSUE TITLE
PathTableResolver does not resolver pointer to slice

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cloudquery#1340]
### Describe the Bug

The  `PathTableResolver`  resolver is not resolving fields correctly when they are pointers to slices.
for example if the field is `*[]StructType` the  column resolver of table that represents `StructType` relatelation gets `*[]StructType` as a resource. it should receive `StructType`.
For example we have a structure like below:
 ![image](https://user-images.githubusercontent.com/20381690/184882782-44ec4f55-5be1-4ebe-ada8-7fb1dedc6001.png)
which has a field `OriginGroups ` that is a slice of structures
When provider tries to resolve filelds of each it gets whole slice of `OriginGroups`  and not items one by one.
![image](https://user-images.githubusercontent.com/20381690/184883384-bd029201-d471-4ea0-87ad-bd308c3c7ee6.png)

### Expected Behavior

relation columns resolvers should receive items separately not the whole array.

**Comment by hermanschaaf** [comment]
We are no longer using PathTableResolver. Instead, prefer to use JSON columns.
