### ISSUE TITLE
feat: Add a OpenSearch destination plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#13470]
### Describe the plugin

Support https://opensearch.org/, specifically AWS OpenSearch.

The current Elasticsearch plugin does not support it (see https://www.elastic.co/amazon-opensearch-service), since the Go client it uses doesn't support it (seems intentionally https://github.com/elastic/go-elasticsearch/issues/515).

We can try adding it to the current Elasticsearch or create a new one

### Link to API documentation

https://opensearch.org/docs/latest/clients/go/#connecting-to-amazon-opensearch-service

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Initially this will be closed/premium feature until we understand what it involves to make it work and how much usage it has.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/opensearch. Please sign up there to get a notified when the plugin is available.

**Comment by pilvikala** [comment]
@mnorbury we can close this, right?

**Comment by mnorbury** [comment]
I think so, we can open new issues based on feedback from fidelity.
