### ISSUE TITLE
SQLAdmin API Throttling

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1351]
Default rate limit is at 180 req/min/user

Investigate and document ways that users can remediate throttling issues.

**Comment by erezrokah** [comment]
Does https://github.com/cloudquery/cloudquery/pull/5522 cover this, cc @bbernays and @yevgenypats

**Comment by bbernays** [comment]
@erezrokah That pr will alleviate some of the problems, but for users with large SQL footprint they will still run into issues with throttling because we try to resolve all of a single `table` at once rather than spreading the requests out... More information about scheduling can be found here... https://github.com/cloudquery/cloudquery/issues/5389

**Comment by yevgenypats** [comment]
Closing as stale
