### ISSUE TITLE
Add additional information to policy run output to allow mapping back to hiearchy structure such as org/folder/project

### ISSUE THREAD

**Issue by TinLe** [cloudquery/cloudquery#1352]
### Describe the bug

This is an Enhancement request.  Not a bug.

Currently the output of _policy run_ do not have information that allow us to map back to the hierarchy of projects.  E.g. we would like to be able to map back to the original org/folder/project of the projects listed in the output.

We have a very large hierarchy with many depts and environments.

### Expected Behavior

Additional information in the output to help map back to the hierarchy the reported projects are in.

### Steps to Reproduce

Run _cloudquery policy run_ to generate the JSON output.

### Possible Solution

Add more information, such as org/folder the project is in.

### Provider and CloudQuery version

CQ: v0.22.3; GCP Provider: v0.6.8

**Comment by yevgenypats** [comment]
Thanks opening this! We released a complete new version of CloudQuery and this should be solved - https://www.cloudquery.io/blog/cloudquery-v1-release.


Policies are now implemented using standard SQL and psql so this gives users direct access to any psql and SQL features.

It should be easy to customize the checks here - https://github.com/cloudquery/cloudquery/tree/main/plugins/source/gcp/policies_v1

As well as to add any additional results to the result table - https://github.com/cloudquery/cloudquery/blob/main/plugins/source/gcp/policies_v1/create_gcp_policy_results.sql

Exporting to any supported csv/json should be also possible. Example: https://stackoverflow.com/questions/48872965/postgres-copy-syntax

Closing as solved. Please reopen (or open a new issue) if it's not solved
