### ISSUE TITLE
Support for Kubernetes Engine (GKE)

### ISSUE THREAD

**Issue by ccojocar** [cloudquery/cloudquery#1354]
It would be useful to add support for following GKE related resources:
- Clusters
- Ingress and Services
- Volumes
- Workload Identity state (enabled/disabled)
- Private cluster
- Pod Security Policy state (enabled/disabled)
- Network Security Policy state (enabled/disabled)

**Comment by candiduslynx** [comment]
already supported in via `gcp_container_clusters` resource
