### ISSUE TITLE
feat(github): Support reading private key from string

### ISSUE THREAD

**Issue by patriknordlen** [cloudquery/cloudquery#13555]
### Which problem is this feature request solving?

When authenticating using Github App credentials, the `github` source plugin currently supports only reading the key material from a file via the `private_key_path` configuration directive.

In scenarios like when cloudquery is run in a CI pipeline job, any key material is typically injected via environment variables so currently one needs to have a separate build step where the contents of the environment variable holding secrets are echoed into a file, so that cloudquery can then use it. This works but is cumbersome.

### Describe the solution you'd like

I'd like to have a configuration directive `private_key` that lets me supply the private key as a string, for instance from an environment variable. This would be mutually exclusive with `private_key_path` to avoid confusion about what key material is being used.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @patriknordlen, thanks for the issue. I marked it as `good first issue` if you'd like to contribute. Please note we support env variables substitution https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution

**Comment by patriknordlen** [comment]
> Hi @patriknordlen, thanks for the issue. I marked it as `good first issue` if you'd like to contribute. Please note we support env variables substitution https://www.cloudquery.io/docs/advanced-topics/environment-variable-substitution

Great, I have an incoming PR for it. Arriving shortly. :)

**Comment by erezrokah** [comment]
Resolved by https://github.com/cloudquery/cloudquery/pull/13556 and released in https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-github-v7.3.0

Thanks @patriknordlen!
