### ISSUE TITLE
Azure source plugin migration to new Azure SDK

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1358]
Azure SDK that we have been using has been deprecated in favor of a new SDK. Any new resources or updates to existing resources should be using the new SDK.

I think we should update existing resources as we need to make changes or because we are adding cq-gen support.

Thoughts @yevgenypats @hermanschaaf

**Comment by erezrokah** [comment]
See also https://github.com/Azure/go-autorest#note-the-modules-in-this-repo-will-go-out-of-support-by-march-31-2023--additional-information-can-be-found-here

**Comment by candiduslynx** [comment]
Old Azure SDK code is being decommissioned (see the packages [here](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services@v67.1.0+incompatible))

**Comment by erezrokah** [comment]
This is done cc @candiduslynx and @yevgenypats 🚀
