### ISSUE TITLE
Support EC2 Key Pairs

### ISSUE THREAD

**Issue by jhudson10x** [cloudquery/cloudquery#1361]
### Describe the resource.

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeKeyPairs

DescribeKeyPairs API operation for Amazon Elastic Compute Cloud.

Describes the specified key pairs or all of your key pairs.

### Use Case

Audit EC2 key pairs for deny-listed fingerprints. 

### Additional context

It might be good to have the `aws_ec2_instances` table also include the fingerprint. We can join on the key_name though. It might also be good to pull the public key material if there's a use case for it.

**Comment by erezrokah** [comment]
Fixed by https://github.com/cloudquery/cloudquery/pull/1325
