### ISSUE TITLE
Improve Config Validation

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1364]
Currently this provider unmarshals the config yml into a struct in a completely transparent way. Without attaching a debugger users have no ability to understand what fields were correctly passed to the provider.

Any fields that were ignored should be logged and elevated to the user as a warning so that they can decide how to proceed. The more extreme action could be to return an error if there are any unrecognized keys. I am not as enthusiastic with this method as it means that configurations might be tied to specific versions of the provider

**Comment by yevgenypats** [comment]
This is now solved in v1 where we error out on unknown fields.
