### ISSUE TITLE
AWS::SES::IdentityDkimAttributes

### ISSUE THREAD

**Issue by RyPeck** [cloudquery/cloudquery#1367]
### Describe the resource.

Describes the state of DomainKeys Identified Mail feature of SES which helps protect senders and receivers against phishing.

https://docs.aws.amazon.com/ses/latest/APIReference/API_GetIdentityDkimAttributes.html
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ses#Client.ListIdentities
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ses#Client.GetIdentityDkimAttributes

### Use Case

Automate validation that AWS has successfully verified the DKIM tokens.

### Additional context

cloudquery/cloudquery#1401

**Comment by RyPeck** [comment]
@amanenk looks like you had a PR in the old repo and never made it here to the new repo?

**Comment by bbernays** [comment]
@RyPeck - Thank you for highlighting this! Once we get V2 out of the door we are planning on focusing on adding more coverage to all of our plugins
