### ISSUE TITLE
AWS Elasticache Support

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#1368]
### Describe the resource.

https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/

DescribeCacheClusters | ( Paginator )
DescribeCacheEngineVersions | ( Paginator )
DescribeCacheParameterGroups | ( Paginator )
DescribeCacheParameters | ( Paginator )
DescribeCacheSecurityGroups | ( Paginator )
DescribeCacheSubnetGroups | ( Paginator )
DescribeEngineDefaultParameters | ( Paginator )
DescribeEvents | ( Paginator )
DescribeGlobalReplicationGroups | ( Paginator )
DescribeReplicationGroups | ( Paginator )
DescribeReservedCacheNodes | ( Paginator )
DescribeReservedCacheNodesOfferings | ( Paginator )
DescribeServiceUpdates | ( Paginator )
DescribeSnapshots | ( Paginator )
DescribeUpdateActions | ( Paginator )
DescribeUserGroups | ( Paginator )
DescribeUsers | ( Paginator)

[DescribeCacheClusters](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheClusters)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheClustersPagesWithContext) )
[DescribeCacheEngineVersions](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheEngineVersions)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheEngineVersionsPagesWithContext) )
[DescribeCacheParameterGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheParameterGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheParameterGroupsPagesWithContext) )
[DescribeCacheParameters](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheParameters)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheParametersPagesWithContext) )
[DescribeCacheSecurityGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheSecurityGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheSecurityGroupsPagesWithContext) )
[DescribeCacheSubnetGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheSubnetGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeCacheSubnetGroupsPagesWithContext) )
[DescribeEngineDefaultParameters](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeEngineDefaultParameters)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeEngineDefaultParametersPagesWithContext) )
[DescribeEvents](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeEvents)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeEventsPagesWithContext) )
[DescribeGlobalReplicationGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeGlobalReplicationGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeGlobalReplicationGroupsPagesWithContext) )
[DescribeReplicationGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReplicationGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReplicationGroupsPagesWithContext) )
[DescribeReservedCacheNodes](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReservedCacheNodes)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReservedCacheNodesPagesWithContext) )
[DescribeReservedCacheNodesOfferings](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReservedCacheNodesOfferings)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeReservedCacheNodesOfferingsPagesWithContext) )
[DescribeServiceUpdates](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeServiceUpdates)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeServiceUpdatesPagesWithContext) )
[DescribeSnapshots](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeSnapshots)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeSnapshotsPagesWithContext) )
[DescribeUpdateActions](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUpdateActions)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUpdateActionsPagesWithContext) )
[DescribeUserGroups](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUserGroups)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUserGroupsPagesWithContext) )
[DescribeUsers](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUsers)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#ElastiCache.DescribeUsersPagesWithContext)

### Use Case

Elasticache is a large, expensive service to run so being able to view and account for various clusters would immediately benefit my organization.

**Comment by shimonp21** [comment]
@Barneyjm Hi :) I added the following resources in cloudquery-aws version `0.13.12`
```
 elasticache.clusters
 elasticache.engine_versions
 elasticache.parameter_groups
 elasticache.subnet_groups
 elasticache.global_replication_groups
 elasticache.replication_groups
elasticache.reserved_cache_nodes
elasticache.reserved_cache_nodes_offerings
elasticache.service_updates
elasticache.snapshots
elasticache.user_groups
elasticache.users
```

Please note that due to the cloudquery plugins being moved to the monorepo `cloudquery/cloudquery`, in order to be able to use this version, you need to upgrade your cloudquery CLI to version `0.32.7` or above: https://github.com/cloudquery/cloudquery/releases/tag/cli%2Fv0.32.7 (or brew).

I ran into some issues while implementing SecurityGroups, Events, EngineDefaultParameters, and UpdateActions. If this gap represents a significant hinderance for you - you can reopen the issue and I'll give them another try :)
