### ISSUE TITLE
Support Kinesis and Firehose

### ISSUE THREAD

**Issue by kvish** [cloudquery/cloudquery#1369]
### Describe the resource.

Add support for AWS Kinesis stream:
 https://aws.amazon.com/kinesis/

listStream and describStream calls

Add support for Kinesis firehose delivery streams

listDeliveryStream and describeDeliveryStream callls
https://aws.amazon.com/kinesis/data-firehose/

### Use Case

Track compliance status of these aws resources. 

### Additional context

Corresponding calls in aqua security cloudsploit

https://github.com/aquasecurity/cloudsploit/blob/master/collectors/aws/firehose/describeDeliveryStream.js
https://github.com/aquasecurity/cloudsploit/blob/master/collectors/aws/kinesis/describeStream.js

Tracking:
- [x] cloudquery/cq-provider-aws#1313
- [x] cloudquery/cq-provider-aws#1314

**Comment by bbernays** [comment]
This has been completed. Feel free to re open if you find gaps in existing coverage
