### ISSUE TITLE
AWS Cost and Usage Reports

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1370]
### Describe the resource.

AWS dumps usage data to S3 on periodic basis. For customers that have this enabled we should be able to ingest usage data

### Use Case

Understanding Usage and cost in dashboards

**Comment by jsonpr** [comment]
Commenting and adding more context as multiple customers have requested for Cost and Usage information from AWS.

**Comment by hvardhan20** [comment]
We're also very interested in this feature at my company.

**Comment by jsonpr** [comment]
Thanks @hvardhan20, we're releasing a post soon on how to query cost and usage data in Athena and correlate that with AWS infrastructure data synced by CloudQuery.  

Would be great to get your feedback!

**Comment by jsonpr** [comment]
@hvardhan20, this was completed today.  Reach out if you have any questions/comments!

https://www.cloudquery.io/how-to-guides/query-aws-cost-and-usage-athena
