### ISSUE TITLE
Provide a basic cost policy + Grafana dashboard

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#1371]
Define set of low hanging fruit around cost visibility and optimization, write SQL queries and visualize the results with Grafana dashboard to provide users a good starting point on top of CloudQuery extracted AWS config.

**Comment by erezrokah** [comment]
The unused resources policy is here https://github.com/cloudquery/cloudquery/blob/66d2595167967f5a8bb4dd7bf1fe71ba6b5f386b/plugins/source/aws/policies/unused_resources/policy.sql

**Comment by erezrokah** [comment]
We have this now via a paid policy, see https://www.cloudquery.io/docs/core-concepts/policies#aws-cost-optimization-pack
