### ISSUE TITLE
FSx: volumes

### ISSUE THREAD

**Issue by rocketbitz** [cloudquery/cloudquery#1372]
### Describe the resource.

https://docs.aws.amazon.com/cli/latest/reference/fsx/describe-volumes.html

### Use Case

Describe volumes for FSx file-systems.

**Comment by erezrokah** [comment]
Hi @rocketbitz, this resource is released in [`v0.13.16` of the AWS plugin](https://github.com/cloudquery/cloudquery/releases/tag/plugins%2Fsource%2Faws%2Fv0.13.16).

I'm keeping the issue open [pending the addition of the `administrative_actions` column](https://github.com/cloudquery/cloudquery/pull/1322#discussion_r950166606), cc @bbernays and @irmatov

**Comment by candiduslynx** [comment]
Closing as it's already completely implemented (https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/resources/services/fsx/file_systems.go#L39-L43)
