### ISSUE TITLE
feat: Add a Sisense destination plugin

### ISSUE THREAD

**Issue by edtguy** [cloudquery/cloudquery#13756]
### Describe the plugin

Sisense is an analytics and visualization tool. It can either establish a live connection to a data warehouse or build an analytics cube from multiple data sources via connectors or custom Python scripting.

### Link to API documentation

https://www.sisense.com/data-connectors/rest-api/

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
I think this can be achieved via connecting Sisense to PostgreSQL directly - https://docs.sisense.com/main/SisenseLinux/connecting-to-postgresql.htm . This way no special plugin is needed and Sisense can reuse the PostgreSQL connector while giving the user the ability to write SQL to generate new visualizations.

Closing. Feel free to reopen if I mis-understood
