### ISSUE TITLE
bug: security_groups_with_open_critical_ports.sql for multiple ingress rules

### ISSUE THREAD

**Issue by sabe6** [cloudquery/cloudquery#13767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql

[EC2.19](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-19) control.

Current sql does not have grouping by account_id and arn, so same data records got be inserted for aws_policy_result table when a SG has multiple ingress rules.

### Expected Behavior

Patch it works:

```
diff --git a/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql b/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql
index 3d1b977a1..3e6d10267 100644
--- a/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql
+++ b/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql
@@ -36,5 +36,6 @@ select
         or 9300 between from_port and to_port)
         then 'fail'
         else 'pass'
-    end
+    end as status
 from view_aws_security_group_ingress_rules
+group bY account_id, resource_id, status

```

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

main

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by ronsh12** [comment]
Added PR - https://github.com/cloudquery/cloudquery/pull/13854
thank you @sabe6
