### ISSUE TITLE
bug: ec2/security_groups_with_access_to_unauthorized_ports.sql is missing parenthesis for where statement

### ISSUE THREAD

**Issue by sabe6** [cloudquery/cloudquery#13766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/ec2/security_groups_with_access_to_unauthorized_ports.sql

[EC2.18](https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-18) control.

Like EC2.19' sql, ip condition should be conjunction with port conditions by using parenthesis at where statement.

### Expected Behavior

Patch it works:

```
diff --git a/plugins/source/aws/policies/queries/ec2/security_groups_with_access_to_unauthorized_ports.sql b/plugins/source/aws/policies/queries/ec2/security_groups_with_access_to_unauthorized_ports.sql
index f7c424fcf..f5f0d776a 100644
--- a/plugins/source/aws/policies/queries/ec2/security_groups_with_access_to_unauthorized_ports.sql
+++ b/plugins/source/aws/policies/queries/ec2/security_groups_with_access_to_unauthorized_ports.sql
@@ -9,12 +9,13 @@ SELECT
   id as resource_id,
   case when
     (ip = '0.0.0.0/0' OR ip = '::/0')
-    AND (from_port IS NULL AND to_port IS NULL) -- all prots
+    AND ((from_port IS NULL AND to_port IS NULL) -- all ports
     OR from_port IS DISTINCT FROM 80
     OR to_port IS DISTINCT FROM 80
     OR from_port IS DISTINCT FROM 443
-    OR to_port IS DISTINCT FROM 443
+    OR to_port IS DISTINCT FROM 443)
     then 'fail'
     else 'pass'
-  end
+  end as status
 FROM view_aws_security_group_ingress_rules
+GROUP BY account_id, resource_id, status

```

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

main

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by ronsh12** [comment]
Added PR - https://github.com/cloudquery/cloudquery/pull/13855
thank you @sabe6
