### ISSUE TITLE
bug: ssm/instances_should_have_association_compliance_status_of_compliant.sql grouping

### ISSUE THREAD

**Issue by sabe6** [cloudquery/cloudquery#13776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[SSM.3] https://docs.aws.amazon.com/ja_jp/securityhub/latest/userguide/ssm-controls.html#ssm-3

Current sql does not have grouping by account_id and arn, so many data records got be inserted for aws_policy_result table.

### Expected Behavior

Patch it works:

```
diff --git a/plugins/source/aws/policies/queries/ssm/instances_should_have_association_compliance_status_of_compliant.sql b/plugins/source/aws/policies/queries/ssm/instances_should_have_association_compliance_status_of_compliant.sql
index 3bcf610a9..0399bdcf3 100644
--- a/plugins/source/aws/policies/queries/ssm/instances_should_have_association_compliance_status_of_compliant.sql
+++ b/plugins/source/aws/policies/queries/ssm/instances_should_have_association_compliance_status_of_compliant.sql
@@ -1,4 +1,16 @@
 insert into aws_policy_results
+with association_compliance_status_groups as(
+    select
+        instance_arn,
+        status
+    from
+        aws_ssm_instance_compliance_items
+    where
+        compliance_type = 'Association'
+    group by
+        instance_arn,
+        status
+)
 select
     :'execution_time' as execution_time,
     :'framework' as framework,
@@ -7,9 +19,8 @@ select
     aws_ssm_instances.account_id,
     aws_ssm_instances.arn,
     case when
-        aws_ssm_instance_compliance_items.compliance_type = 'Association'
-        and aws_ssm_instance_compliance_items.status is distinct from 'COMPLIANT'
+        association_compliance_status_groups.status is distinct from 'COMPLIANT'
     then 'fail' else 'pass' end as status
 from
     aws_ssm_instances
-inner join aws_ssm_instance_compliance_items on aws_ssm_instances.arn = aws_ssm_instance_compliance_items.instance_arn
+inner join association_compliance_status_groups on aws_ssm_instances.arn = association_compliance_status_groups.instance_arn
```

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

main

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by jsonpr** [comment]
Hi @sabe6.  Thanks for reporting this.  By grouping on instance arn, that could aggregate multiple AssociationCompliance Items in a single row.  From reading https://docs.aws.amazon.com/securityhub/latest/userguide/ssm-controls.html#ssm-3 , this is evaluating AWS::SSM::AssociationCompliance resources.  Thus, we think it's better to evaluate each AWS::SSM::Association resource separately and not consolidated per instance since there may be multiple AssociationCompliances per instance.

We've made some changes to our logic based off your feedback.
