### ISSUE TITLE
Enable Account and Org in Same Provider

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1382]
Currently a user can only use Org or Account(s) but not both. Users should be able to mix the two.

**Comment by yevgenypats** [comment]
I think it is fine to have limitation on configurations otherwise the config will be very complex and the code. it is a good approach to create `aws-org` and `aws-accounts` configs

**Comment by cqgaurav** [comment]
Closing as unsupported for now. Feel free to reopen if this is needed by you.
