### ISSUE TITLE
S3 Storage Lens

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1383]
### Describe the resource.

S3 Storage lens aggregates metrics about S3 buckets in the account or in the org. This data is able to be dumped on a daily basis into a CSV or parquet file stored in an S3 bucket.

### Use Case

The metrics describe usage and provide drill downs by Region, storage class, bucket, and prefix. In large buckets there are no other ways to understand trends and usage other than listing every object, which is costly ($ and time)... 

### Additional context

If we didn't want to grab S3 Storage Lens we could also grab `NumberOfObjects` and `BucketSizeBytes` on a per bucket basis (note metric data is only available in the region where bucket is located)

**Comment by cqgaurav** [comment]
Blocked by: https://github.com/aws/aws-sdk/issues/259
