### ISSUE TITLE
feat: Shopify Orders use max of 250 rather than default page size of 50

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#13866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the resolver seems to use the default value of 50 orders per request

### Expected Behavior

Limit the number of requests, by making batch size larger. Go up to max of 250

### CloudQuery (redacted) config

n/a

### CloudQuery (redacted) logs

n/a

### CloudQuery version

n/a

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
Shopify plugin has the option to increase page size in the config ([reference](https://www.cloudquery.io/docs/plugins/sources/shopify/overview)) 

> `page_size` (integer, optional. Default: 50): Maximum number of items queried each request. Find an optimum value to balance amount of data fetched and requests timing out. Maximum value 250.

As quoted here, larger page sizes sometimes cause the request to time out. Users can and should experiment with larger page sizes.

**Comment by bbernays** [comment]
Hi @romerocw can you try to remove the quotes around the 250? When you add the quotes it makes it a string while the schema is expecting an integer. So it should be like this:
```
page_size: 250
```

**Comment by romerocw** [comment]
Thanks Ben. I just added page_size: 250 w/out the quotes and it is now running.
