### ISSUE TITLE
feat: Add a Harbor source plugin

### ISSUE THREAD

**Issue by kumaresh0** [cloudquery/cloudquery#13863]
### Describe the plugin

We don't have a source plugin for Harbor registry ( it's an open source registry ) 
https://goharbor.io/

Harbor gives OCI image info and vulnerability scanning details 
https://github.com/goharbor/harbor

### Link to API documentation

https://goharbor.io/docs/2.5.0/working-with-projects/using-api-explorer/

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/harbor. Please sign up there to get a notified when the plugin is available.
