### ISSUE TITLE
research AWS retries, reduce fetch hanging behaviour

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#1391]
### Describe the bug

too high max_retries and max_backoff can cause "hanging" behaviour, while all goroutines "sleep" to wait for retries.

### Expected Behavior

It's better to fail than to hang.

### Steps to Reproduce

the hanging is notoriously difficult to reproduce.

### Provider and CloudQuery version

core: 0.22.10, aws: 0.11.2

**Comment by yevgenypats** [comment]
Per my latest research AWS `failed to get rate limit token` which we should just change the default bucket cost and expose it to the user in any case it is not a good default for them. for CloudQuery the client side throttling doesn't make a lot of sense.
