### ISSUE TITLE
Flaky Integration tests

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#1393]
### Describe the bug

integration tests are flaky. About 50% of commits fail integration tests and only succeed after rerun.

- [x] https://github.com/cloudquery/cloudquery-issues/issues/329 

### Expected Behavior

integration tests shouldn't be flaky.

### Steps to Reproduce

create any PR in this provider. rerun integration tests until they fail.

### Provider and CloudQuery version

...

**Comment by yevgenypats** [comment]
We use mostly unit-tests right now. Closing.
