### ISSUE TITLE
S3 buckets post resolver retruns error on NotFound response

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cloudquery#1394]
### Describe the bug

When some requests of post resolver return NotFound response fetch fails

### Expected Behavior

Fetch should not fail. columns that got not found response should be `null`

### Steps to Reproduce

create s3 bucket without policy and try to fetch this bucket

### Possible Solution

add isNotFoundError checks to requests that can return not found

### Provider and CloudQuery version

cloudquery 0.22.10, aws 0.11.1

**Comment by yevgenypats** [comment]
This is fixed in v1 where we write all ELT errors to logs without trying to randomly split them to cloudquery errors
