### ISSUE TITLE
bug: Inconsistent behavior on Azure rate limiting

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#13944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Support request from [Discord](https://discord.com/channels/872925471417962546/873606591335759872/1153657348842332210)

> I've noticed that when an AZURE sync experience RateLimit issues, I get inconsistent results.
> For example, 
> When tables are `azure_storage_accounts`, `azure_storage_containers` there IS NO RateLimit in the logs and number of resources synced from `azure_storage_containers` is 866 with 0 errors, which is the expected result. I've done multiply syncs with this configuration and the number of resources stays the same.
> When tables are `azure_storage_accounts`, `azure_storage_containers`, `azure_storage_file_shares`, `azure_storage_blob_services`, there IS RateLmit in the logs and number of resources synced from azure_storage_containers is 780 with 20 errors. I've done multiply syncs with this configuration and the number of resources is inconsistent, meaning that the number of resources is sometimes X and sometimes Y, but not the expected 866.

> I'm using Azure v9.3.0 if that matters.

### Expected Behavior

Have consistent behavior

### CloudQuery (redacted) config

Azure v9.3.0

### Steps To Reproduce

In summary if the user adds `azure_storage_file_shares` and `azure_storage_blob_services` tables to the exissting list of `azure_storage_accounts`, `azure_storage_containers` the issue is reproduced.

### CloudQuery (redacted) logs

Not supplied

### CloudQuery version

azure-v9.3.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Closing as stale as I haven't seen this pop up back again, and we're lacking logs to debug this. Please comment if this happens again and we can re-open
