### ISSUE TITLE
feat: Azure source plugin to support Azure Privileged Identity Management (PIM) APIs

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#13969]
### Which problem is this feature request solving?

There is a user request ([discord](https://discord.com/channels/872925471417962546/873606591335759872/1154003643654225970)) to add support for Azure Privileged Identity Management (PIM) resources.
Docs are [here](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/)

### Describe the solution you'd like

Add support

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
This requires usage of the MS Graph SDK:
https://github.com/microsoftgraph/msgraph-sdk-go
https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignmentschedulerequests?view=graph-rest-1.0&tabs=go

Which has a different authentication flow, scopes, etc. (see also https://github.com/microsoftgraph/msgraph-sdk-go/issues/404)

so I'm going to push it back a little for now
