### ISSUE TITLE
AWS::SES::ReceiptRuleSet

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1398]

**Comment by disq** [comment]
Receipt* resources don't have counterparts in [API v2](https://docs.aws.amazon.com/ses/latest/APIReference-V2/index.html), they are only in [v1](https://docs.aws.amazon.com/ses/latest/APIReference/index.html). Closing for now.

If you need this resource fetched using the SES v1 API please reopen this issue (or open a new one).
