### ISSUE TITLE
Support SES

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1401]
- [ ] cloudquery/cloudquery#1400
- [ ] cloudquery/cloudquery#1399
- [ ] cloudquery/cloudquery#1395
- [x] cloudquery/cloudquery#1396
- [x] cloudquery/cloudquery#1397
- [x] cloudquery/cloudquery#1398
- [x] cloudquery/cq-provider-aws#783

**Comment by disq** [comment]
Receipt* resources don't have counterparts in [API v2](https://docs.aws.amazon.com/ses/latest/APIReference-V2/index.html) but they are in [v1](https://docs.aws.amazon.com/ses/latest/APIReference/index.html).
