### ISSUE TITLE
feat: Add Lex bots to AWS source plugin

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#14021]
### Describe the resource

From [AWS documentation](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjPjpjp2sSBAxXrl2oFHUD-B-IQFnoECA0QAw&url=https%3A%2F%2Fdocs.aws.amazon.com%2Flex%2Flatest%2Fdg%2Fprogramming-model.html&usg=AOvVaw2ZhAhXMuMShicpdaJjqrnS&opi=89978449):

A bot is the primary resource type in Amazon lex.

### Use Case

We received a notification from AWS about Lex bots in our accounts and would like to use CloudQuery to look through all of them in our org. 

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/lexmodelbuildingservice/#LexModelBuildingService.GetBots

### Additional Context

Looking through the AWS IAM policy console for Lex, two options show up:

- [Amazon Lex](https://docs.aws.amazon.com/lex/latest/dg/what-is.html) (lex:*)
- [Amazon Lex V2](https://docs.aws.amazon.com/lexv2/latest/dg/what-is.html) (lex:*)

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Completed. Released in `v23.1.0`
