### ISSUE TITLE
feat: Add Backup Gateways to AWS source plugin

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#14022]
### Describe the resource

From [AWS documentation](https://docs.aws.amazon.com/aws-backup/latest/devguide/working-with-gateways.html):

To back up and restore your virtual machines (VMs) using AWS Backup, you must first install a Backup gateway. A gateway is software in the form of an OVF (Open Virtualization Format) template that connects Amazon Web Services Backup to your hypervisor, allowing it to automatically detect your virtual machines, and enables you to back up and restore them.

### Use Case

We would like to use CloudQuery to determine how many backup gateways are in our org since these should be deleted based on our requirements. 

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/backupgateway/#BackupGateway.ListGateways

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
This will be released in the next open-core release.

**Comment by disq** [comment]
Now available in AWS [v23.1.0](https://hub.cloudquery.io/plugins/source/cloudquery/aws/v23.1.0/docs)
