### ISSUE TITLE
feat: Add support for IAM service deletions to AWS source plugin

### ISSUE THREAD

**Issue by pilvikala** [cloudquery/cloudquery#14028]
### Describe the resource

AWS event-based sync supports IAM service's `CreateGroup`, `CreateRole`, and `CreateUser` events.

We should add support for events that update the tables when the original information becomes obsolete:

```
CreateGroup
DeleteGroup
UpdateGroup
DeleteRole
TagRole
UntagRole
UpdateRole
UpdateRoleDescription
DeleteUser
TagUser
UntagUser
UpdateUser
```

We need to discuss how this will work on Snowflake, S3, and other append-only databases.

The first task should be to do a research and come up with a technical proposal.

### Use Case

The problem the AWS event-based sync is solving is to provide an up-to-date information about the state of the resources. However, when the resources are updated, the information gets too old quickly. We received feedback that at this state, it's not really ready for production usage.
We'll start working on covering the IAM service first to complete at least this one use case of getting user information updated.

### Link to API documentation

https://docs.aws.amazon.com/IAM/latest/APIReference/API_Operations.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
`DeleteGroup` - Cannot be completed until delete is implemented in the protocol
`DeleteRole` - Cannot be completed until delete is implemented in the protocol
`DeleteUser` - Cannot be completed until delete is implemented in the protocol
`UpdateGroup` - This causes the ARN to change, so we will have to generate a delete event while syncing the new name. So blocked until delete is implemented in the protocol
`UpdateUser`- This causes the ARN to change, so we will have to generate a delete event while syncing the new name. So blocked until delete is implemented in the protocol

**Comment by bbernays** [comment]
All other events have been implemented in https://github.com/cloudquery/cloudquery-private/pull/197

**Comment by pilvikala** [comment]
This issue was meant to trigger the need for the delete support in the protocol to get it implemented. Quoting my initial comment: "The first task should be to do a research and come up with a technical proposal."
