### ISSUE TITLE
Add Support for AWS::SSM::*

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1409]
- [ ] AWS::SSM::AssociationCompliance
- [ ] AWS::SSM::ManagedInstanceInventory
- [ ] AWS::SSM::PatchCompliance

**Comment by disq** [comment]
About `AWS::SSM::AssociationCompliance`: Looks like [ListComplianceItems](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_ListComplianceItems.html) only supports the `ManagedInstance` resource type, not associations?

**Comment by disq** [comment]
[ListInventoryEntries](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm#ListInventoryEntriesInput) require InstanceId and TypeName which gets a little hairy to query: We don't know if the ID returned from `GetInventory` is a node or an instance ID (not that there could be a difference), and for the `TypeName` we might have to run an API call for each item returned in the `GetInventorySchema` (15 types below), which could get too much.

```
aws ssm get-inventory-schema --region us-east-1 | jq -r .Schemas[].TypeName
AWS:AWSComponent
AWS:Application
AWS:ComplianceItem
AWS:File
AWS:InstanceDetailedInformation
AWS:InstanceInformation
AWS:Network
AWS:PatchCompliance
AWS:PatchSummary
AWS:ResourceGroup
AWS:Service
AWS:Tag
AWS:WindowsRegistry
AWS:WindowsRole
AWS:WindowsUpdate
```
