### ISSUE TITLE
SecretsManager Duplicate Key Violates PK

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1412]
### Describe the bug

Somehow there is a way of having multiple values with the same ARN, when there are duplicate ARNs the DB throws an error and doesn't persist the data

### Expected Behavior

We need to understand how and why an ARN can be duplicated (in a short amount of time)

### Steps to Reproduce

customer reported. No detailed steps

### Provider and CloudQuery version

All

**Comment by yevgenypats** [comment]
I don't think we are able to reproduce it anymore.
And it might be affected by number of things both old destination plugin with logic around what is duplicate and what is not as well as old delete filter which is now replaced by https://www.cloudquery.io/docs/reference/destination-spec.

Closing and will re-open if this is reported again.
