### ISSUE TITLE
Look at using new AWS Cloud Control APIs

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cloudquery#1417]
https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/

Might make life a bit easier

**Comment by yevgenypats** [comment]
We researched this number of times and cloud control is not ready for prime time and might never be as AWS is not keeping up with CloudControl API <->  AWS API, and some prob wont be supported at all. It has big coverage issues, speed issues and so on.
