### ISSUE TITLE
feat: DuckDB Source Plugin

### ISSUE THREAD

**Issue by nicosuave** [cloudquery/cloudquery#14194]
### Which problem is this feature request solving?

Accomodating "Reverse" ELT from DuckDB (specifically a Motherduck instance) -> Postgres

### Describe the solution you'd like

A DuckDB source plugin

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/duckdb. Please sign up there to get a notified when the plugin is available.
