### ISSUE TITLE
Always materialize ARN's when possible

### ISSUE THREAD

**Issue by nick123pig** [cloudquery/cloudquery#1419]
I am using cloudquery for IAM policy analysis, and all policies references ARN's in some way. It would be nice to always have the ARN as a materialized column in cloudquery, rather than having to piece it together myself. Much like "tags" is now a default column on most tables, would it be possible to encourage/enforce all tables to have ARN's?

**Comment by bbernays** [comment]
All AWS resources that have an ARN should be implemented. Please open issues for any resources that you find that is missing an ARN field
