### ISSUE TITLE
feat: Add azure_ad_user to Azure source plugin

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#14294]
### Describe the resource

need data from the graph api for the user https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta 

### Use Case

Need the properties for the user to check for certain checks i.e. lastPasswordChangeDateTime

### Link to API documentation

https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
@code-vise I noticed you opened a few issues with us recently. I'd like to learn more about your use case. Would you mind pinging me via email at michal (at) cloudquery.io?

**Comment by erezrokah** [comment]
Going to close this as done via a community plugin https://hub.cloudquery.io/plugins/source/year-of-the-nimbus/azure-ad/latest/tables/azure_ad_users, if that's not the case please re-open
