### ISSUE TITLE
feat: Add GitHub Actions Workflow Runs and Jobs data to the GitHub Plugin

### ISSUE THREAD

**Issue by jonjozwiak** [cloudquery/cloudquery#14311]
### Which problem is this feature request solving?

I would like to gather WorkflowRuns, run usage, and WorkflowJobs data so that I can get insight into GitHub Actions usage.  

### Describe the solution you'd like

Create new tables github_workflow_runs, github_workflow_run_usage, and github_workflow_jobs to store data from the relevant go-github calls.  

### Pull request (optional)

- [x] I can submit a pull request

**Comment by AshCorr** [comment]
This is something my organisation would find useful too! Are you working on this @jonjozwiak , happy to pick it up if not!

**Comment by jonjozwiak** [comment]
@AshCorr I should have a PR ready early next week for review.

**Comment by erezrokah** [comment]
Released in https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-github-v7.4.0 great contribution @jonjozwiak 🎸
