### ISSUE TITLE
IAM User/Role Permissions boundary

### ISSUE THREAD

**Issue by ywyt738** [cloudquery/cloudquery#1442]
aws provider
Now Permissions boundary is null

**Comment by bbernays** [comment]
Hi @ywyt738 Can you specify the query that is not returning data that you expect to be returning data?

**Comment by ywyt738** [comment]
Hi @bbernays 
```sql
select * from aws_iam_users
select * from aws_iam_roles
```
There is no data in ```permissions_boundary_arn``` and ```permissions_boundary_type``` column.

I see the source code of the aws provider.
```plugins/source/aws/resources/services/iam/roles.go``` and ```plugins/source/aws/resources/services/iam/users.go``` do not contain releated function.

**Comment by bbernays** [comment]
Looking into this now. Thanks for raising the issue!

**Comment by bbernays** [comment]
This has been fixed in the v1 release
