### ISSUE TITLE
feat(gcp): Add support for listing resources in a specific location

### ISSUE THREAD

**Issue by rsatal** [cloudquery/cloudquery#14519]
### Which problem is this feature request solving?

I want to sync the GCP cloud for some specific locations like for AWS cloudquery has `spec.regions`.
I am not getting the option for Azure and GCP

### Describe the solution you'd like

NA

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Im closing this as no-fix for now. In GCP APIs are returning all assets per all region unlike in AWS. you can filter after the data is in postgresql.
