### ISSUE TITLE
bug: source plugin process failed with signal: killed - aws pricing

### ISSUE THREAD

**Issue by ozbillwang** [cloudquery/cloudquery#14552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### related plugin name

- aws pricing

### Current Behavior

About AWS Pricing plugin, the sync command stopped in the middle, even I set `spec.concurrnency` to 5

```
source plugin process failed with signal: killed
```
After did the research, I found this document

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-the-aws-price-list-bulk-api.html#price-bulk-api-quotas

![image](https://github.com/cloudquery/cloudquery/assets/8954908/3aa8757c-7a83-4c63-a691-772ce4b81e09)

It clearly shows me we need set limits on the connections to api call  `AWS Price List Bulk API`

What's the best number I should define? Is the setting related to `spec.concurrency` ? Any other parameters related?
```
kind: source
spec:
  name: "awspricing"
  path: "cloudquery/awspricing"
  version: "v3.0.10"
  tables: ["*"]
  destinations:
    - "postgresql"
  spec:
    # Optional parameters
    # region_codes: []
    # offer_codes: []
    concurrency: 1
    org:
      admin_account:
        # make sure you have created local aws config, reference aws-config-<env> file
        local_profile: cloudquery
      member_role_name: cloudquery-ro
```

How can I understand the relationship between `spec.concurrency` to API's Token bucket size (10) and Refill rate per second (5) ?

Enable debug and see some errors ( `frame too large` )

 ```
2023-10-16T03:42:15Z INF Table exists, auto-migrating module=pg-dest table=awspricing_service_terms
2023-10-16T03:45:51Z INF End sync destinations=["postgresql (v5.0.1)"] module=cli source="aws-pricing (awspricing@v3.0.10)" sync_time=2023-10-16T03:42:05Z
2023-10-16T03:45:51Z INF Sending sync summary to analyticsv1.cloudquery.io:443 module=cli
2023-10-16T03:45:51Z WRN Failed to send sync summary error="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\"" module=cli
2023-10-16T03:45:51Z INF waiting for source plugin to terminate module=cli
```

### Expected Behavior

Get the AWS Pricing tables updates

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "awspricing"
  path: "cloudquery/awspricing"
  version: "v3.0.10"
  tables: ["*"]
  destinations:
    - "postgresql"
  spec:
    # Optional parameters
    # region_codes: []
    # offer_codes: []
    concurrency: 10000 # what number I need change to, 5 ?
```

### CloudQuery (redacted) logs

error log 1
```
source plugin process failed with signal: killed
```

error log 2
```
2023-10-16T03:42:15Z INF Table exists, auto-migrating module=pg-dest table=awspricing_service_terms
2023-10-16T03:45:51Z INF End sync destinations=["postgresql (v5.0.1)"] module=cli source="aws-pricing (awspricing@v3.0.10)" sync_time=2023-10-16T03:42:05Z
2023-10-16T03:45:51Z INF Sending sync summary to analyticsv1.cloudquery.io:443 module=cli
2023-10-16T03:45:51Z WRN Failed to send sync summary error="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: http2: frame too large\"" module=cli
2023-10-16T03:45:51Z INF waiting for source plugin to terminate module=cli
```

### CloudQuery version

cloudquery version 3.13.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by ozbillwang** [comment]
Two updates for this issue. 

1. I adjusted the `spec.concurrency` to 1, still get same issue.
2. my setting is to go through all accounts under AWS Organization (I have updated the source configuration file)

**Comment by bbernays** [comment]
Hi @ozbillwang - The AWS Pricing Plugin doesn't require any sort of authentication or authorization. It uses the price lists that are publicly available at `https://pricing.us-east-1.amazonaws.com`

Can you share the details about the setup of where you are running `cloudquery sync`? Is it in a container? What is the base image On a VM? What is the OS? These details will help us be able to reproduce and fix the issue.

Also I see that you are using postgres `v5.0.1` we identified that `v5.x` had a major performance regression so would strongly urge you to update to `v6.0.4` (which is the latest at the time of writing).

**Comment by ozbillwang** [comment]
I run from a normal account, not master account. I followed the template (https://github.com/cloudquery/iam-for-aws-orgs/blob/main/template.yml) to set the assume role via Cloudformation Stacksets on all accounts. I am fine with this setting to sync data from this Org.

I'd like to get pricing for all accounts under the same AWS Org, similar as the plugin `aws`. That's why I set the `spec.org`. But not sure if this is the proper setting now. 

I will upgrade the backend psql version and have a try

**Comment by ozbillwang** [comment]
still same issue with postgre `v6.0.4`

```
Loading spec(s) from .
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-source-awspricing-v3.0.10/awspricing_linux_amd64.zip
Downloading 100% |
Downloading https://github.com/cloudquery/cloudquery/releases/download/plugins-destination-postgresql-v6.0.4/postgresql_linux_amd64.zip
Downloading 100% |
Starting sync for: aws-pricing (awspricing@v3.0.10) -> [postgresql (v6.0.4)]
\ Syncing resources... (2476/-, 25 resources/s) [3m50s] source plugin process failed with signal: killed
Error: failed to sync v3 source aws-pricing: unexpected error from sync client receive: rpc error: code = Unavailable desc = error reading from server: EOF
```

**Comment by bbernays** [comment]
The AWSPricing plugin doesn't utilize the `org` attribute all of the supported attributes can be found [here](https://www.cloudquery.io/docs/plugins/sources/awspricing/overview)

Can you share any of the logs from `cloudquery.log`? Also any details about the compute resource you are running this on?

**Comment by erezrokah** [comment]
Is this issue still relevant? Do you mind trying with the latest versions? Also what happens if you launch the plugin directly from the `.cq` directory?

**Comment by erezrokah** [comment]
Closing as stale. If still relevant please comment and we'll re-open
