### ISSUE TITLE
Is resource history available?

### ISSUE THREAD

**Issue by K20055612** [cloudquery/cloudquery#1458]
### Is your feature request related to a problem? Please describe.
I haven't seen any history on the resources. Is this intentional, or is history tracked on other tables?

### Describe the solution you'd like
History for resources would be helpful(when it was changed, deleted etc.)

### Describe alternatives you've considered
You could use pgaudit for Postgres, but the primary purpose of cloudquery for me is to keep track of current resources and their history.

**Comment by Chan9390** [comment]
The history feature using timescaleDB was deprecated - https://docs.cloudquery.io/blog/migration-and-history-deprecation

A possible hack (that I currently use) is to save a snapshot of entire DB in .sql or .json format and grepping the required resource over the selected time period.

**Comment by yevgenypats** [comment]
Hi! right now it is quite hard without a work-around as you both suggested. We do work on a new version of CloudQuery which will support both multiple databases and multiple "write" modes - one of them will be append only which will basically provide "history".

**Comment by yevgenypats** [comment]
This should be solved now with `append` in `write_mode` https://www.cloudquery.io/docs/reference/destination-spec#write_mode
