### ISSUE TITLE
feat(source): schema.Table should have a custom data field for source plugins

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#14593]
### Are you positive this feature should be implemented in the SDK?

- [X] I'm positive this is an SDK feature

### Which problem is this feature request solving?

`schema.Table` should allow for a custom data field to be set in the source plugin table definition, which then can be used in docs-generation tools or the resource resolvers (if there's a way to get to schema.Table from the resolver, cloudquery/cloudquery#14592 )

### Describe the solution you'd like

Make it an `any` field

### Pull request (optional)

- [x] I can submit a pull request

**Comment by erezrokah** [comment]
@disq can you give a code example on how the data field will be defined on the table and how will it be displayed to users in the docs?

**Comment by disq** [comment]
I think this goes hand in hand with https://github.com/cloudquery/cloudquery/issues/14592 , some plugins have the same (or very similar) resolvers for a set of tables, but then again if it's just the resolver one can write a resolver generator fn and pass in the data that way. Maybe close this for now as I can't find any reasoning for this to exist.
