### ISSUE TITLE
feat: Move from `[]arrow.Record` to `array.RecordReader`

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#14597]
### Are you positive this feature should be implemented in the SDK?

- [X] I'm positive this is an SDK feature

### Which problem is this feature request solving?

We can move the functions accepting `[]arrow.Record` to `array.RecordReader` and decouple ourselves from the underlying type:
* `[]arrow.Record`: `array.NewRecordReader(sc, records)` where `sc` is `*arrow.Schema`
* `arrow.Table`: `array.NewTableReader(t, -1)` where `-1` stands for `get the largest chunk size` and can be coded instead

### Describe the solution you'd like

Move the signatures to use record readers, so that the logic of what is exactly used is decoupled from the plugins

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
Per the last comment I'll close this a `wontfix`. If we think there's a strong reason to do this please comment and I'll re-open
