### ISSUE TITLE
Improve CI benchmarking by only writing a comment if change is significant

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#14600]
Right now the benchmarking we do in CI reports on every PR, even when no code that changes anything is touched. We can't easily tell when code _should_ be benchmarked, but we can silence the comment if the resulting change is not significant. I'm thinking we don't have to comment if the change is <20% or so, because that's within expected variation for these kinds of tests. A better statistical measure would of course be even better, but I'm not sure we have access to enough information from within the delta plugin.

**Comment by erezrokah** [comment]
We would first need to make the benchmarks more consistent see https://github.com/cloudquery/plugin-sdk/pull/1572#issuecomment-2010197228, I updated the title of the PR accordingly

**Comment by erezrokah** [comment]
OK so apparently only the recent writers benchmarks are noisy we'll silence those (renamed the PR title back)

**Comment by erezrokah** [comment]
Closing as stale/wontfix. I think https://github.com/netlify/delta-action already does this for us, but if not we can re-open this issue. Regardless we might to re-think how we want to measure SDK performance as a whole
