### ISSUE TITLE
feat: Add EFS FileSystemPolicy to AWS source plugin

### ISSUE THREAD

**Issue by mMeijden** [cloudquery/cloudquery#14632]
### Describe the resource

EFS supports File system policies to be configured. These policies are currently not collected by CloudQuery.
https://docs.aws.amazon.com/efs/latest/ug/API_DescribeFileSystemPolicy.html 

Blog post:
https://aws.amazon.com/blogs/aws/new-for-amazon-efs-iam-authorization-and-access-points/ 

Can this be added to the EFS table or as a separate table perhaps?

### Use Case

Our use case is to build a full cloud resource inventory and perform security and compliance analyses on top of that. 
One of the reason we require the file systems is to ensure that they are not overprivileged or public.

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/efs/#EFS.DescribeFileSystemPolicy

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by cychiang** [comment]
I'm working on this at the moment, and it looks nature to me by extending the `filesystems` table with the `filesystem_policy` column.
