### ISSUE TITLE
What should Cloudquery plugins consider as "errors"

### ISSUE THREAD

**Issue by AshCorr** [cloudquery/cloudquery#14652]
### False positive for Errors

We've noticed a few tables from the AWS source plugin throwing seemingly false positives for errors in perfectly normal situations:

1. `aws_s3_bucket_object_lock_configurations`

    An error will be thrown by every S3 bucket that doesn't have Object Lock enabled as the AWS API will return a 404 response code when requesting bucket lock information.
    
2. `aws_lambda_functions`

    Any Lambda that uses a Image runtime will throw 2 errors when it tries to call the `GetRuntimeManagementConfig` and `GetFunctionCodeSigningConfig` AWS APIs, as neither API support image runtime Lambdas.

3. `aws_ecr_repository_lifecycle_policies`

    An error will be thrown by every ECR Repository that doesn't have a lifecycle policy as the AWS API will return a 404 response code when requesting lifecycle policy information.

_this is not an exclusive list_
    
In my opinion, it feels like these should be considered either "warnings" or "info", not "errors", as they're not caused by any underlying api outage/cloudquery misconfiguration/rate limit/etc but instead caused by perfectly normal AWS Resources.

### Impact

Ideally we'd be able to scan our logs for errors and alert us if anything comes up that needs our attention, for example if an API outage caused gaps in our data.

Theres a "table sync finished" log message that gets posted after every table has finished syncing which has a "errors" field indicating the total number of errors encountered. But with how many false positives there are it becomes un-usable

<img width="843" alt="image" src="https://github.com/cloudquery/cloudquery/assets/21217225/11a7e704-ae2e-405a-9f56-829886f4d20a">

We're happy to look at fixing some of these errors ourselves, but wanted to understand what the Cloudquery team considers an "error" to be before we do any work! Maybe some suggestions to plugin developers on what should be considered an error?

**Comment by erezrokah** [comment]
Hi @AshCorr, thanks for raising this issue. Our current approach is to propagate errors by default as it's hard to predict how the AWS (or other APIs) respond. Some will throw 404, some will not error out, etc.

Sometimes we do handle the errors on a case to case basic when it makes sense, for example https://github.com/cloudquery/cloudquery/blob/4e669f9c13f7ed4b7bcdc1e8df5ceacf60917731/plugins/source/aws/resources/services/account/alternate_contacts.go#L45

We're happy to discuss more if you submit a PR per each case

**Comment by bbernays** [comment]
Closing this issue as all examples have been addressed. If you become aware of other examples feel free to open new issues so we can address each one!
