### ISSUE TITLE
feat: Add EC2 default credit specification setting to AWS source plugin

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#14754]
### Describe the resource

Please add EC2 settings to the AWS source plugin. 

This can be found by following these steps:

1. Go to the EC2 console
2. Make sure you're on the **EC2 dashboard** page
3. On the right hand side, under **Account attributes**, select any of the settings listed

 This includes the information below.

- **Default credit specification** (The default credit option for CPU usage of burstable performance instances T2, T3, T3a and T4g. Here yo can modify the specification.)

### Use Case

This is an account level setting for EC2 that will be useful to ensure accounts have the correct settings in place.

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeInstanceCreditSpecifications

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by mnorbury** [comment]
This will be released in the next open-core release.
