### ISSUE TITLE
feat: Add a Solr destination plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#14755]
### Describe the plugin

Support https://solr.apache.org/

### Link to API documentation

https://github.com/stevenferrer/solr-go (not official it seems)

### Pull request (optional)

- [X] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/solr. Please sign up there to get a notified when the plugin is available.
