### ISSUE TITLE
feat: Add EC2 zone group status setting to AWS source plugin

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#14753]
### Describe the resource

Please add EC2 settings to the AWS source plugin. 

This can be found by following these steps:

1. Go to the EC2 console
2. Make sure you're on the **EC2 dashboard** page
3. On the right hand side, under **Account attributes**, select any of the settings listed

 This includes the information below.

- **Zone group status** (local zones, wavelength zones, availability zones and wether they're enabled or disabled)

### Use Case

This is an account level setting for EC2 that will be useful to ensure accounts have the correct settings in place.

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeAvailabilityZones

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
Hi @atqhg23!

Could you please check if [`aws_availability_zones`](https://hub.cloudquery.io/plugins/source/cloudquery/aws/v22.19.2/tables/aws_availability_zones) has the required info you're looking for?
`enabled` & `state` columns, specifically.

**Comment by atqhg23** [comment]
Just took a look, this is great! Thanks for adding this
