### ISSUE TITLE
feat: Add EC2 EBS encryption setting to AWS source plugin

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#14751]
### Describe the resource

Please add the EC2 EBS encryption account status setting to the AWS source plugin. 

This can be found by following these steps:

1. Go to the EC2 console
2. Make sure you're on the **EC2 dashboard** page
3. On the right hand side, under **Account attributes**, select any of the settings listed.

 This includes the information below.

- **EBS encryption** (Set the default encryption status of all new EBS volumes and copies of snapshots created in your account.)

### Use Case

This is an account level setting for EC2 that will be useful to ensure accounts have the correct settings in place.

### Link to API documentation

https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.GetEbsEncryptionByDefault

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
@atqhg23 I noticed you opened a bunch of feature requests lately. I'd like to get in touch to discuss a few details on how you use CQ today and to understand these a bit more. If you're up for it, please ping me at on discord (Pilvikala) or just shoot an email to michal (at) cloudquery.io.
