### ISSUE TITLE
feat: Add a box source plugin

### ISSUE THREAD

**Issue by ibenrodriguez** [cloudquery/cloudquery#14850]
### Describe the plugin

would like to get a list of shared folders from box with access records. 
who has access?
when did they last access?
what ip address did they use to access?
what authentication method was used for access?
what role do they have? read, readwrite, admin, etc...?

### Link to API documentation

https://developer.box.com/reference/

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/ini8labs/box. Please sign up there to get a notified when the plugin is available.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/ini8labs/box. Please sign up there to get a notified when the plugin is available.
