### ISSUE TITLE
bug: wrong region reported(used?)

### ISSUE THREAD

**Issue by stumyp** [cloudquery/cloudquery#14931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I see logs that indicate request made in us-east-1 as one made in ap-northeast-1 or af-south-1.
It looks to me as if the request was made with the cleint configured for that specific region, not the one where the resource is located.
I am confident we do not have objects in these regions. 

### Expected Behavior

Request is made by the client running in the same region as the resource. Logged appropriately.

### CloudQuery (redacted) config

```yml
kind: source
spec:
  destinations:
    - postgresql
  registry: local
  path: /.cq_source/aws
  spec:
    concurrency: 20000
    initialization_concurrency: 50
  tables:
    - aws_elbv1_load_balancers
    - aws_elbv2_load_balancers
    - aws_elbv2_target_groups
    - aws_s3_access_points
    - aws_s3_accounts
    - aws_s3_buckets
    - aws_ec2_regional_configs
    - aws_regions"
  skip_tables:
    - aws_iam_*_last_accessed_details
    - aws_ec2_image_launch_permissions
    - aws_ec2_image_last_launched_times
```

### CloudQuery (redacted) logs

```
2023-10-24T10:00:27Z INF table sync finished client=xxxx:ap-northeast-1 errors=0 module=aws-src resources=1 table=aws_s3_buckets
2023-10-24T10:00:27Z INF table sync finished client=xxxx:ap-northeast-1 errors=1 module=aws-src resources=0 table=aws_s3_bucket_object_lock_configurations
2023-10-24T10:00:27Z ERR table resolver finished with error error="operation error S3: GetObjectLockConfiguration, https response error StatusCode: 404, RequestID: QSKYBXSXXXXXXXXX, HostID: 8xuQpiXXXXXX653jQ5aIO7+Rc5k=, api error ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket" client=xxxx:ap-northeast-1 module=aws-src table=aws_s3_bucket_object_lock_configurations
2023-10-24T10:00:21Z INF top level table resolver started client=xxxx:ap-northeast-1 module=aws-src table=aws_s3_buckets
```

### CloudQuery version

3.23.1

### Additional Context

I've checked the request ID in CloudTrail and found that the request was made in the us-east-1 region, while the resource is also located there.
So far we're seeing it only on `aws_s3_bucket_object_lock_configurations` requests

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
This is a logging issue. In the beginning of a sync we choose a random client (which can have any region) to run `ListBuckets`. After getting those results CQ then runs a `GetLocation` and uses the result of that API call to set the correct region for all other S3 attributes.

Based on the way clients are generated via multiplexing the only way to get the client region to match the resource region is to call `GetBucketLocation` for every single bucket in each region. I am not sure the performance cost of that is worth it.

**Comment by stumyp** [comment]
Hey @bbernays thanks for looking into this.
Based on this log message:


> 2023-10-24T10:00:27Z ERR table resolver finished with error error="operation error S3: GetObjectLockConfiguration, https response error StatusCode: 404, RequestID: QSKYBXSXXXXXXXXX, HostID: 8xuQpiXXXXXX653jQ5aIO7+Rc5k=, api error ObjectLockConfigurationNotFoundError: Object Lock configuration does not exist for this bucket" client=xxxx:ap-northeast-1 module=aws-src table=aws_s3_bucket_object_lock_configurations

The error is happening when CQ is already collecting information about the bucket, in this case `GetObjectLockConfiguration`. Not the `ListBucket` as you suggested. Is it still because of the logging is happening from the same randomly chosen client?

**Comment by bbernays** [comment]
@stumyp Yeah the resolution of a resource will use the same client for all nested resources. As you can see here in the code we override the region based on the `GetBucketLocation` call made in the parent resource: https://github.com/cloudquery/cloudquery/blob/6bc357709a10d5651a8a449d41555bd4f971e554/plugins/source/aws/resources/services/s3/bucket_object_lock_configurations.go#L42-L44C4

**Comment by bbernays** [comment]
Also I just want to point out that a PR was merged last week that properly handled the `ObjectLockConfigurationNotFoundError` error you are seeing. 

https://github.com/cloudquery/cloudquery/pull/14726

So updating to the latest version of the AWS plugin `v22.15.2` should result in that error not appearing in the logs

**Comment by stumyp** [comment]
oh, this is nice, thank you.

**Comment by yevgenypats** [comment]
Closing as solved. please reopen
