### ISSUE TITLE
feat(Azure): Add support for listing resources in a specific location #14519

### ISSUE THREAD

**Issue by rsatal** [cloudquery/cloudquery#14996]
### Which problem is this feature request solving?

I want to sync the Azure cloud for some specific regions or zones like for AWS cloudquery has `spec.regions`.

### Describe the solution you'd like

NA

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Thanks for the issue @rsatal, I'll close this as a duplicate of https://github.com/cloudquery/cloudquery/issues/12794
