### ISSUE TITLE
Throttling: Rate exceeded, status code: 400

### ISSUE THREAD

**Issue by mvaerle** [cloudquery/cloudquery#15]
Hi,

I'm trying to use cloudquery to extract some resources for compliance purposes. I'm fetching IAM data for 23 accounts, so including all policies, users, etc.

After a seemingly random amount of time but always within a couple of minutes, I get the following error:

```
2020/12/21 15:34:19 Throttling: Rate exceeded
	status code: 400, request id: [left this one out]
```

UPDATE:
Just did a bit more research and a workaround is to comment out the accounts in the config.yml and then run fetch in batches of ~3 accounts.

Using cloudquery version 0.4.3

**Comment by sethcenterbar** [comment]
Typically, AWS will work with you to raise the soft limits on your accounts. That's likely the best way to tackle this issue if you need to query all of the accounts at once on a regular basis. I don't believe anything could be done on the cloudquery side other than doing client side throttling.

**Comment by yevgenypats** [comment]
Thanks @mvaerle and @sethcenterbar I believe raising the AWS soft limit might work indeed.
I can also try and add a configurable option to increase the number of retries done by AWS SDK.
Also, I'll add a logging option so you can rerun it and we can see on which retry you get the error. 
As a last resort I guess we will need to implement client side throttling.

**Comment by mvaerle** [comment]
Thanks for the quick reply!

Asking AWS to raise limits might work, but I'm not even sure which limits I'm hitting and by how much. We're never running into these except when using cloudquery. I'm trying to get some insight through cloudtrail but no luck so far, I'll report back if I can find something.

Once there is logging available I'm happy to test and try again. For now I can use the workaround of commenting out accounts and/or contact AWS to raise our limits.

**Comment by yevgenypats** [comment]
@mvaerle I've added `log_level: debug` and `max_retries: 20` to your AWS `config.yml` as specified [here](https://docs.cloudquery.io/aws/tables-reference).

This should show us both what limit is being reached and also if changing `max_retries` to a higher number helps or not?

Those keywords are available at [v0.5.3](https://docs.cloudquery.io/aws/tables-reference)

**Comment by dan-compton** [comment]
1. It's good to gather data on your API usage which can be done with cloudtrail and an ELK stack.  I think there's a one-click cfn link solution out there.

2. If you're using the AWS API I assume it's handling the retry strategy and that may be configurable.  In some cases caching can be enabled.  If not and you're using it often you might add a caching layer or set [up a caching aws proxy](https://github.com/opsee/bezosphere).  If you're rolling your own retries, then use the AWS blog post on retries to implement a good backoff strategy (exponential + jitter).

3. If 2 finally fails you, hit up AWS and they will raise the limit.  Not all limits can be raised.

**Comment by mvaerle** [comment]
@yevgenypats Thanks a lot for the response and the update. I've added both `log_level: debug` and `max_retries: 20` and I can now fetch all iam data from all our accounts without any errors! I assume this is due to the `max_retries` configuration, thanks again.

**Comment by roneli** [comment]
Added max_retries + max_backoff to work with aws sdk v2 https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.2.3
