### ISSUE TITLE
Community provider breadcrumbs are slightly broken on Hub

### ISSUE THREAD

**Issue by ummahusla** [cloudquery/cloudquery#150]
Here is the example from the `Yandex Cloud` community case. We could clearly see that there is a gap between arrows.

https://hub.cloudquery.io/providers/yandex-cloud/yandex/latest

![image](https://user-images.githubusercontent.com/2536096/126059331-92323041-5c7a-424d-a8bd-fd51f3318150.png)

Compared to the `cloudquery` (non-community) case: 

![image](https://user-images.githubusercontent.com/2536096/126059395-068928e2-b309-4c4c-8cae-a2b0de80fec6.png)

**Comment by yevgenypats** [comment]
@ummahusla Thanks! Should be fixed now !https://hub.cloudquery.io/providers/yandex-cloud/yandex/latest

**Comment by ummahusla** [comment]
That was quick haha! Good job.
