### ISSUE TITLE
feat: Add a Google Workspace source plugin

### ISSUE THREAD

**Issue by sulewicz-cb** [cloudquery/cloudquery#15063]
### Describe the plugin

Adding support for Google Workspace would allow reviewing security policies and other security aspects of the integration.

The [admin.googleapis.com](https://developers.google.com/admin-sdk/directory/reference/rest#service:-admin.googleapis.com) is one potential source of information. Additional ones could be [chromepolicy.googleapis.com](https://developers.google.com/chrome/policy) for Chrome Policy Management. There could be more that may be worth integrating.

### Link to API documentation

https://developers.google.com/admin-sdk/directory/reference/rest#service:-admin.googleapis.com

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Jacobojijo** [comment]
Could you assign this to me?

**Comment by erezrokah** [comment]
@Jacobojijo sure think, please see https://www.cloudquery.io/docs/developers/creating-new-plugin/go-source as a reference

**Comment by jsifuentes** [comment]
Hi. I took a stab at publishing a Google Workspace source plugin for CloudQuery. The repository is here: https://github.com/jsifuentes/cq-source-googleworkspace Hope it's helpful for some!

**Comment by yevgenypats** [comment]
Hi @jsifuentes , that looks great! Just a quick question, Is it for the marketplace to be as a paid plugin? If yes, better turn the repo into private and add me as author so I can help review. Also feel free to pick a slot here https://calendly.com/yevgenyp .

**Comment by jsifuentes** [comment]
@yevgenypats My intention is that the plugin remains free and open source. I'm also happy to look into opening a PR to merge into this repo if it will be accepted! :) Let me know

**Comment by yevgenypats** [comment]
Hey @jsifuentes  - sounds great, free and open source is always welcome!  I was just making sure you didn't accidentally want it to be paid and published as free. In that case once you publish the first version please ping us here so we can quickly review and approve so it it will show on CloudQuery hub !

**Comment by jsifuentes** [comment]
@yevgenypats It's submitted to Hub under `jsifuentes/googleworkspace`.

**Comment by erezrokah** [comment]
Hi @jsifuentes the plugin is live https://hub.cloudquery.io/plugins/source/jsifuentes/googleworkspace/v1.0.1, I also opened a PR for the docs https://github.com/jsifuentes/cq-source-googleworkspace/pull/1.

Great work 🙌

**Comment by erezrokah** [comment]
Going to close this as resolved
