### ISSUE TITLE
feat: Add a Duo source plugin

### ISSUE THREAD

**Issue by sulewicz-cb** [cloudquery/cloudquery#15061]
### Describe the plugin

Adding support for [Duo](https://duo.com/) would allow reviewing security policies and other security aspects of the Duo integrations.

### Link to API documentation

https://duo.com/docs/adminapi#overview

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Latour12** [comment]
I'm going to create this plugin, can you please assign it to me?

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/duo. Please sign up there to get a notified when the plugin is available.
