### ISSUE TITLE
feat: Public getters on Plugin class in Java SDK for easier Clojure interop

### ISSUE THREAD

**Issue by spieden** [cloudquery/cloudquery#15065]
### Which problem is this feature request solving?

Extending abstract classes in Clojure can be done either with `proxy` or `gen-class`. The former is lightweight and low ceremony. Here I am making a CloudQuery plugin in Clojure with it: https://github.com/spieden/hello-cq-clojure/blob/fd3a4382c43aae105ae920443673e655e5139705/src/hello_cq/core.clj#L71-L83

The trouble is this creates a proxy class that cannot access protected members. You can accomplish this access with `gen-class` but it has its own drawbacks.

### Describe the solution you'd like

Would it be breaking encapsulation terribly to make public getters for `Plugin.client` and `Plugin.logger`? Given these a Clojure plugin made with `proxy` could use these as intended.

### Pull request (optional)

- [x] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @spieden this doesn't seem like a terrible idea 😄 but a bit hard to know without looking at some code first.
Feel free to submit a PR to https://github.com/cloudquery/plugin-sdk-java

**Comment by spieden** [comment]
Ok so I had this one wrong. Didn't understand the class-level `@Getter` was already adding public getters everywhere! nm
