### ISSUE TITLE
No error when PAT is blank

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1509]
### Describe the Bug

If a user doesn't specify a Personal Access token in the configuration file the provider initialization will continue without an error. 

### Expected Behavior

As long as the Configuration file is the only way of specifying the PAT the configuration function should return an error when none is specified

**Comment by disq** [comment]
I don't think this is the case any more, since the V1 migration: https://github.com/cloudquery/cloudquery/blame/main/plugins/source/github/client/client.go#L52-L54

Feel free to reopen if I missed something.
