### ISSUE TITLE
feat: GCS Destination Templating

### ISSUE THREAD

**Issue by Kirksten3** [cloudquery/cloudquery#15097]
### Which problem is this feature request solving?

Currently with an extract from Postgres -> GCS the data is all landed in a single directory within a bucket. While this isn't necessarily problematic, it's much more convenient to have tables landed in their own directories, and with additional metadata about the export. I imagine this is the same across any file based storage.

### Describe the solution you'd like

It would be really helpful to be able to add some mild templating to `path` strings so that cloudquery can arbitrarily decide where to land data. I'm proposing a structure where the `spec.spec.path` for a gcs destination looks something like: `path/to/file/{source_schema}/{source_table}/{sync_timestamp}`. I realize this probably doesn't work when the source isn't a DB but sync_timestamp would be valuable.

Given this structure if I were to export two tables: `public.actions` and `public.orders` and the sync ran at `2023-11-01 14:52:51` the destination for these files would be something like: `path/to/file/public/actions/20231101145251/*.csv` and `path/to/file/public/orders/20231101145251/*.csv`.

This organization and structure makes it easier to reason about files landed in GCS, and should help to make ingestion into consumers easier too.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by massynmantel** [comment]
> For what it's worth, the S3 destination plugin supports variable templating in the `path` field, as in `path: "path/to/files/{{TABLE}}/dt={{YEAR}}-{{MONTH}}-{{DAY}}/{{UUID}}.parquet"` https://www.cloudquery.io/docs/plugins/destinations/s3/overview . We should be able to do the same for the GCS plugin

Any indication when this will be delivered?

**Comment by erezrokah** [comment]
Hi @massynmantel, we haven't prioritized this issue yet, we'd be happy to accept a contribution though. I marked this issue as `good first issue` to communicate that.
The relevant GCS plugin code is here https://github.com/cloudquery/cloudquery/blob/7c2684039a6d774af466c581d93aae4cda00f412/plugins/destination/gcs/client/write.go#L24 and there's code here https://github.com/cloudquery/cloudquery/blob/7c2684039a6d774af466c581d93aae4cda00f412/plugins/destination/s3/client/write.go#L31 on how to handle replacing path variables

**Comment by shubham-padia** [comment]
I'd like to work on this issue, will follow the approach from S3 destination

**Comment by shubham-padia** [comment]
A question on backwards compatibility, the [current implementation](https://github.com/cloudquery/cloudquery/blob/dbddfa515d9468b4b61f6e4d98030755d0cd6fe4/plugins/destination/gcs/client/write.go#L24) for the gcs destination plugin formats the name as follows by default:

``` golang
name := fmt.Sprintf("%s/%s.%s%s.%s", c.spec.Path, table.Name, c.spec.Format, c.spec.FileSpec.Compression.Extension(), uuid.NewString())
if c.spec.NoRotate {
  name = fmt.Sprintf("%s/%s.%s%s", c.spec.Path, table.Name, c.spec.Format, c.spec.FileSpec.Compression.Extension())
}
```

I'm not sure what the backward compatibility policy for cloudquery is, but we have the following options:

1. Check if the path string has any of the template variables like `{{FORMAT}}`, `{{TABLE}}` and so on. If they do, we follow the behaviour of S3 plugin wherein we replace the template variables and that's it. If there are no such variables, we revert back to the current behaviour in the code block shown above.
2. We introduce a new field called templatePath, which, if present would take precedence over Path. We could then deprecate Path over a major version bump later if we would like to.
3. Technically an option: Break backwards compatibility, but not sure why we might want to do this unless we have history of doing so and users are aware of it. 

My thoughts:
Option 1 would keep the behaviour consistent with other behaviours but it has the downside where the documentation will do a lot of heavy lifting of explaining two different behaviours under the same input key. Option 2 would be easier to manage and deprecate over time if we want to, but it will introduce an input key that is different from the expected from other plugins introducing inconsistency between plugins, which is technically ok, but might not be the best thing from a user point. 

@erezrokah @hermanschaaf Please let me know your thoughts on which approach to follow :)

**Comment by erezrokah** [comment]
Option 1 makes sense to me 👍 We might still need to publish this change as a major version bump in case someone has a template variable in their path but didn't intend for it to be replaced

**Comment by shubham-padia** [comment]
S3 plugin and File plugin are both running [path.Clean](https://pkg.go.dev/path#Clean) in [ReplacePathVariables](https://github.com/cloudquery/cloudquery/blob/9cbabbcc42734e4927925fb3a26932d54f929176/plugins/destination/s3/client/spec/spec.go#L183)

**Question**: Do we want to run [path.Clean](https://pkg.go.dev/path#Clean) for GCS destination plugin? 

Right now, we are not running that in the GCS plugin.

GCS accepts `.` or `..` or `//` and resolves it accordingly. See screenshots below for more details. I'm not sure why they are not allowed in the file or S3 plugins, whether those destinations will give us an error if the path is set to that or whether we don't won't to allow those unclean names in the plugin. Maybe someone with knowledge on either the S3 or the File plugin can help me out here with the original intent of using [path.Clean](https://pkg.go.dev/path#Clean).

<details>
<summary>Path set to `path/path/to/../files`</summary>


Check the `to` directory being not present in the path displayed at the top

![Screenshot 2024-04-11 at 1 20 22 AM](https://github.com/cloudquery/cloudquery/assets/13910561/d632a469-e0c4-4d7e-b821-edabd556def8)


</details>

<details>
<summary>Path set to `//path/to/files`</summary>
Path is displayed at the top of the screenshot

![Screenshot 2024-04-11 at 1 22 09 AM](https://github.com/cloudquery/cloudquery/assets/13910561/5cc0a466-00a7-421c-9289-d44ddf9ef6d5)


</details>

**Comment by erezrokah** [comment]
I think it's ok to use `path.Clean` to keep the logic consistent between plugins and also not depend on GCS normalization of paths.
