### ISSUE TITLE
Add azure monitor activity log resource

### ISSUE THREAD

**Issue by irmatov** [cloudquery/cloudquery#151]
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v53.3.0+incompatible/services/preview/monitor/mgmt/2019-11-01-preview/insights#ActivityLogsClient

Required for implementing CIS policy Section 3.2

**Comment by roneli** [comment]
Issue moved to [cloudquery/cq-provider-azure #46](https://github.com/cloudquery/cq-provider-azure/issues/46) via [**ZenHub**](https://www.zenhub.com/)
