### ISSUE TITLE
ECS Service tags are always empty

### ISSUE THREAD

**Issue by guilhermerocha29** [cloudquery/cloudquery#1513]
### Describe the Bug

In `aws_ecs_cluster_services` table, `tags` are always empty, even though the table is being updated and my services have tags, regardless the amount of tries. It also works fine with the `aws_ecs_task_definitions` table, for example.

### CloudQuery Version

`cloudquery version 0.32.7`

### Steps to Reproduce

```
cloudquery init aws
cloudquery fetch
```

**Comment by bbernays** [comment]
@guilhermerocha29 Thank you very much for opening up this issue. We have opened a PR to fix this and hope to release it early next week
