### ISSUE TITLE
Add GA back to our next.js site

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#1516]

**Comment by erezrokah** [comment]
@yevgenypats can we close this issue? Or add a description of what needs to be done

**Comment by yevgenypats** [comment]
I think we need to add back GA to our website and add a cookie consent :)

**Comment by erezrokah** [comment]
Ah, does GA == Google Analytics? I somehow thought it was about GA/Beta/Alpha :)

**Comment by erezrokah** [comment]
Fixed by https://github.com/cloudquery/cloudquery/pull/3070
