### ISSUE TITLE
transformations: Add a way to run transformations prior to inserting data

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#15176]
We want to enable users to add/change/remove columns on the way in. Now that we support arrow as our data format we might be able to leverage https://arrow.apache.org/datafusion/ to make those kind of transformations without inventing a new language.

**Comment by erezrokah** [comment]
Related to https://github.com/cloudquery/cloudquery/issues/6388

**Comment by erezrokah** [comment]
@marianogappa can we close this issue?

**Comment by marianogappa** [comment]
I'm not too familiar with definition of done. We now have a deployed way to run some transformations prior to inserting data. In principle it can be closed.
