### ISSUE TITLE
feat: Add name to okta plugin.

### ISSUE THREAD

**Issue by stobias123** [cloudquery/cloudquery#15175]
### Which problem is this feature request solving?

Using the okta plugin, and a little surprised that group name isn't a column, but it's part of the `profile` json schema

### Describe the solution you'd like

Would love to be able to obtain meaningful info from this table schema. I.E. 

`select name from okta_groups`

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
Thanks for the suggestion!

We keep all table schema inline with the original API - https://developer.okta.com/docs/reference/api/groups/  and focus on ingestion and one level of flattening for all tables to make it consistent with all plugins. After the data is inside the database it is up to the user to create additional transformation depending on their use case.

As a side note, most database as well as PostgreSQL have JSON operator so it should be possible to relatively easily query that from inside the JSON.

Im closing this as no-fix for now.
