### ISSUE TITLE
bug: AWS | ServiceQuotas API | Not correct passing pagination token in the call.

### ISSUE THREAD

**Issue by mMeijden** [cloudquery/cloudquery#15193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When querying the table `aws_servicequotas_services` this error might appear. This happens in version `v22.15.0` of aws source.

```bash
2023-11-08T19:50:51Z ERR table resolver finished with error error="operation error Service Quotas: ListServices, https response error StatusCode: 400, RequestID: REDACTED, InvalidPaginationTokenException: 
You specified an invalid value for nextToken. 
You must get the value from the response to the previous API call." client=REDACTED:eu-west-1 module=aws-src table=aws_servicequotas_services
```

### Expected Behavior

I would expect the token to be passed correctly to the next API call in case of pagination

### CloudQuery (redacted) config

use `"aws_servicequotas_services"` as table

### CloudQuery (redacted) logs

see above.

### CloudQuery version

3.27.3

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Can you confirm if this error occurs every single sync?

Looking over the code, it seems like the service is returning some type of invalid pagination token or the SDK is handling something incorrectly because we are using the SDKs paginator to handle pagination:

https://github.com/cloudquery/cloudquery/blob/839086e159b7cf2116f9f4513c6dddce567e35c0/plugins/source/aws/resources/services/servicequotas/services.go#L47-L63

**Comment by mMeijden** [comment]
I've seen it for two more accounts, the accounts were crawled via separate containers, but that said, it was more or less around the same time. 

I ran a sync after that again to see if i can give a solid answer on your question, but in the new sync i didn't see it happening. Could have been a small hiccup at the AWS side.

Will report here if i see it again or if i found a way to reproduce it.

**Comment by bbernays** [comment]
I have a feeling that it is on the AWS side of things because we have had other users raise a [similar issue](https://github.com/cloudquery/cloudquery/issues/11706), but have never been able to reproduce it

**Comment by bbernays** [comment]
Closing as stale. If you have more details or are able to reproduce it feel free to reopen the issue
