### ISSUE TITLE
bug: dead link with a developer message

### ISSUE THREAD

**Issue by pilvikala** [cloudquery/cloudquery#15219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I visit https://www.cloudquery.io/integrations/salesforce from Google search results (just google "cloudquery salesforce guide"), I get this error: 
<img width="810" alt="image" src="https://github.com/cloudquery/cloudquery/assets/57617962/fdd0438b-8270-40a4-9f04-c2a4e1f08d4c">

### Expected Behavior

A Hub page with Salesforce plugin details, or at least 404. Not an error message telling me to check the console.

### CloudQuery (redacted) config

n/a

### Steps To Reproduce

1. open  https://www.cloudquery.io/integrations/salesforce

### CloudQuery (redacted) logs

n/a

### CloudQuery version

n/a

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by hermanschaaf** [comment]
@pilvikala I missed adding a redirect for this one. How did you find out about it?

**Comment by yevgenypats** [comment]
This should be solved now
