### ISSUE TITLE
Ambgious Language in Blog post

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#15229]
User reported that we mention: `(You can still stream to Kafka or Google PubSub.)` in this blog post. https://github.com/cloudquery/cloudquery/blob/bd104b97275ffe927fde6a818110ebd90bf33241/website/pages/blog/postgres-cdc-to-any-destination.mdx#L46

CQ currently doesn't support Google PubSub as a destination. We need to clarify or remove what is meant by this line

**Comment by hermanschaaf** [comment]
Fixed the wording to remove the ambiguous comment, closing
