### ISSUE TITLE
feat: Add a azure adaptive_application_controls source plugin

### ISSUE THREAD

**Issue by mayudong200333** [cloudquery/cloudquery#15234]
### Describe the plugin

Gets a list of application control machine groups for the subscription.

### Link to API documentation

https://learn.microsoft.com/ja-jp/rest/api/defenderforcloud/adaptive-application-controls/list?view=rest-defenderforcloud-2020-01-01&tabs=HTTP

### Pull request (optional)

- [X] I can submit a pull request

**Comment by bbernays** [comment]
closed by https://github.com/cloudquery/cloudquery/pull/15236
