### ISSUE TITLE
feat: Add a Google Cloud Pub/Sub destination plugin

### ISSUE THREAD

**Issue by jineshshah36** [cloudquery/cloudquery#15230]
### Describe the plugin

We are hoping to use cloudquery to support a multi-step streaming etl pipeline where we process data in a cloud run container. Ideally, we'd have it triggered via a Pub/Sub event so we could listen to changes with cloudquery and send those changes to a Pub/Sub topic.

### Link to API documentation

None yet

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Tushar-kalsi** [comment]
Hi @yevgenypats  , Can i contribute to build Destination plugin for Google Pub Sub ?

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/google-cloud-pub-sub. Please sign up there to get a notified when the plugin is available.
