### ISSUE TITLE
Rename `provider` to `plugin` in our docs/readmes/guides, etc.

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1526]
We still mention the word `provider` quite a lot.
We should rename `provider` to `plugin` where relevant and update other content as relevant.

For example https://github.com/cloudquery/cloudquery/blob/045e10a58a01908a1900eb710f936198af972c22/website/pages/docs/developers/developing-new-provider.md

**Comment by yevgenypats** [comment]
https://github.com/cloudquery/cloudquery/pull/1837

**Comment by erezrokah** [comment]
Closing as mostly done pending minor fixes
