### ISSUE TITLE
feat: Switch the default scheduler on AWS plugin

### ISSUE THREAD

**Issue by pilvikala** [cloudquery/cloudquery#15384]
### Which problem is this feature request solving?

Customers using AWS plugin with the default `round-robin` scheduler are hitting rate limits on certain api endpoints. 

### Describe the solution you'd like

It appears the `shuffle` scheduler leads to fewer rate-limited requests with AWS plugin. Let's make it the default.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Please note this we'll need to do it in a major version bump (this is a breaking change)

**Comment by erezrokah** [comment]
Done in https://github.com/cloudquery/cloudquery/pull/15386

**Comment by pilvikala** [comment]
@erezrokah what version will this be in?

**Comment by erezrokah** [comment]
> @erezrokah what version will this be in?

https://github.com/cloudquery/cloudquery/pull/15369
