### ISSUE TITLE
feat: Please add a heartbeat to the logs.

### ISSUE THREAD

**Issue by alfredgamulo** [cloudquery/cloudquery#15388]
### Which problem is this feature request solving?

I would like to be given an indication that the CQ process is continuing in a healthy manner by having a periodic log output. In a development environment, I might have log level debug or info however, these logs dump too much resource data into the logs such as CloudWatch Logs. If I switch the log level to warn, then I get no output in a healthy process. As a user, I would like to have positive feedback if I am watching a process that may take hours to complete. 

### Describe the solution you'd like

This could be addressed by a log that indicates which table is being collected by the source module. 
Alternatively, change the Info log so that it doesn't output resource details. 

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
This use case should be covered by the new `--tables-metrics-location` flag, see https://docs.cloudquery.io/docs/reference/cli/cloudquery_sync (example `cloudquery sync ./directory ./aws.yml ./pg.yml --tables-metrics-location metrics.txt). Feedback welcomed
