### ISSUE TITLE
AWS: use `sync.Map` in the `client.ServiceManager`

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#15391]

**Comment by bbernays** [comment]
Do we really want to do this in this large release? Technically I think we can do the refactor in a minor version because nothing user facing would be impacted...

**Comment by candiduslynx** [comment]
We thought about this as a major change as it impacts the access for the core structure in AWS plugin.
I'm OK with moving it out of scope, but a safer bet would be to mark this change breaking, too.

**Comment by bbernays** [comment]
Lets leave this one till after all of the others that are 100% breaking... I am not completely sold on it requiring a major release
