### ISSUE TITLE
Hide global flags under options

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#155]
Currently the main `--help` is a bit cluttered  with all the global flags. It would be nice to hide all the global flags (and usually rare) under `options` similar to 

`kubectl help` and if you want to see all the global flags you would need to do `kubectl options`

**Comment by roneli** [comment]
fixed in #168 and published in [v0.14.2](https://github.com/cloudquery/cloudquery/releases/tag/v0.14.2)
