### ISSUE TITLE
Gitlab as a plugin

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#1552]
### Why do you need this resource or plugin? Please describe.
Gitlab organizations can be sprawling with thousands of projects. Top-down views of subproject configuration can be impossible to gather.

### Describe the solution you'd like
Gitlab as a new plugin, please.

### Additional context
Gitlab API resources https://docs.gitlab.com/ee/api/api_resources.html

**Comment by erezrokah** [comment]
Thanks for opening the issue @Barneyjm, any specific resources that you would like to have first?
https://docs.gitlab.com/ee/api/projects.html?

**Comment by Barneyjm** [comment]
Projects, Releases, Settings would be a great start: 

- https://docs.gitlab.com/ee/api/projects.html
- https://docs.gitlab.com/ee/api/releases/
- https://docs.gitlab.com/ee/api/settings.html

(sorry for the delayed response. fixing my notification preferences)
