### ISSUE TITLE
bug: IAM access analyzer - Unused access findings

### ISSUE THREAD

**Issue by KarthikVenkatraman** [cloudquery/cloudquery#15521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Iam Access analyzer service has recently launched a new analyzer / feature that can report on Unused IAM Roles.
([https://aws.amazon.com/blogs/aws/iam-access-analyzer-updates-find-unused-access-check-policies-before-deployment/](https://aws.amazon.com/blogs/aws/iam-access-analyzer-updates-find-unused-access-check-policies-before-deployment/)). 

Cloudquery currently synchs up the information for this Access Analyzer Findings into the table - 
`AWS_ACCESSANALYZER_ANALYZER_FINDINGS`. However this does not yet capture the findings for analyser type `ACCOUNT_UNUSED_ACCESS` . This is available via the AWS API - https://docs.aws.amazon.com/cli/latest/reference/accessanalyzer/list-findings-v2.html.

Would be very useful if this can be fixed / added.

### Expected Behavior

AWS_ACCESSANALYZER_ANALYZER_FINDINGS table should also capture the findings for Analyzer Type ACCOUNT_UNUSED_ACCESS

### CloudQuery (redacted) config

NA

### CloudQuery (redacted) logs

NA

### CloudQuery version

3.15.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
@KarthikVenkatraman This data will be available as `aws_accessanalyzer_analyzer_findings_v2` in the next major release of the AWS plugin soon.
