### ISSUE TITLE
feat: Add Azure AD resources (users, groups, service principals, apps) to Azure source plugin

### ISSUE THREAD

**Issue by cderamus-heeler** [cloudquery/cloudquery#15524]
### Describe the resource

I'm attempting to inventory and catalog our Azure environments. Great work on the CQ Azure plugin, it's got just about everything one could need. The one thing I'm not seeing is a way to catalog applications, users, service principals, apps and groups. The Azure plugin doesn't appear to have definitions for these. 

I'm opening this up as a new resource, but I think it's a bug because support used to exist in the old Azure driver (ref: https://www.cloudquery.io/blog/inventory-microsoft-azure-with-cloudquery) for these resources and now they've vanished. Based on feedback from @disq he told me to open an issue to investigate. 

### Use Case

I'd like to inventory the identity landscape across my organization's Azure tenants. role assignments and link them back to the correct SP, user, etc.

### Link to API documentation

https://learn.microsoft.com/en-us/rest/api/azure/devops/graph/service-principals/list?view=azure-devops-rest-7.1&tabs=HTTP

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by candiduslynx** [comment]
Citing https://github.com/cloudquery/cloudquery/issues/11814#issuecomment-1868037979
> Created an Azure AD (now known as Microsoft Entra ID) source plugin here:
>
> https://hub.cloudquery.io/plugins/source/year-of-the-nimbus/azure-ad/v1.0.0/docs

Closing as not planned
