### ISSUE TITLE
Azure VM properties needs to have the complete array of networkProfile

### ISSUE THREAD

**Issue by chechau007** [cloudquery/cloudquery#15562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

currently CQ is only taking the 1st element in the networkProfile object i.e networkInterfaces. There are three elements in the array. The third one being networkInterfaceConfigurations which has the subnet Id. 

### Expected Behavior

It should have the complete response (Maxmimum set_gen) mentioned in the link below of Azure Rest APIs so that we can map subnet with instance for Azure.

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list?view=rest-compute-2023-07-01&tabs=HTTP#virtualmachine

### CloudQuery (redacted) config

N/A

### Steps To Reproduce

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

3.14.4

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @chechau007, to confirm. You're referring to this table https://github.com/cloudquery/cloudquery/blob/6aa6e426b4eb792cd62df37fd36d2cc1e06e84ca/plugins/source/azure/resources/services/compute/virtual_machines.go#L15?

**Comment by mnorbury** [comment]
Hi @chechau007, I have been taking a look into this. 

The `azure_compute_virtual_machines` table is populated with a call to the [ListAll](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all?view=rest-compute-2023-09-01&tabs=HTTP) API. As you point out this supports an expanded view if you specify the `$expand` and `$filter` query arguments -  [VirtualMachine_ListAll_MaximumSet_Gen](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all?view=rest-compute-2023-09-01&tabs=HTTP#virtualmachine_listall_maximumset_gen).  The documentation for the `$filter` implies that the you are only allowed to filter by scale sets e.g.  


> 	The system query option to filter VMs returned in the response. Allowed value is 'virtualMachineScaleSet/id' eq /subscriptions/{subId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmssName}'

I suspect the [NetworkProfile](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/list-all?view=rest-compute-2023-09-01&tabs=HTTP#networkprofile) data type is shared between multiple API calls, and returns different fields depending on the API.

If your instances are part of a scale set then we also have the `azure_compute_virtual_machine_scale_sets` and `azure_compute_virtual_machine_scale_set_vms` tables, which contains scale set configurations and instances. These instance do contain further network configuration information - including the subnet that the scale set will use and the instances belong to.

If you are using a standalone VM (i.e. not created by a scale set), then you can always obtain the subnet by joining on the subnet id defined in the properties e.g.

```sql
SELECT
    vm.*,
    COALESCE(
        ni.properties -> 'ipConfigurations' -> 0 -> 'properties' -> 'subnet' ->> 'id',
        'None'
    ) AS subnet_id
FROM
    azure_compute_virtual_machines vm
    LEFT JOIN azure_network_interfaces ni ON COALESCE(
        vm.properties -> 'networkProfile' -> 'networkInterfaces' -> 0 ->> 'id',
        'None'
    ) = ni.id;
```

I hope this helps, let me know if you have any further questions.

**Comment by erezrokah** [comment]
Closing per the comment in https://github.com/cloudquery/cloudquery/issues/15562#issuecomment-1867509923. If this is not resolved please comment and I'll re-open
