### ISSUE TITLE
feat: add tags to the resources identified by config

### ISSUE THREAD

**Issue by michalz-rely** [cloudquery/cloudquery#15596]
### Which problem is this feature request solving?

Currently in the table **aws_config_config_rule_compliance_details** we can see the compliance details and the resource identified compliant/non_compliant. This information is useful, but could be complemented with some context about the resource itself such as tags.

### Describe the solution you'd like

- Extra field containing tags **OR**
- Extended **evaluation_result_identifier** with the information about the tags for the resource **OR**
- Separate table **aws_config_config_resources** containing config recorded resources and their tags

ps. There's no need to query resources individually, AWS config provides a means to get such data directly -  [list-tags-for-resource](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/configservice/list-tags-for-resource.html) so no resource related permissions would be necessary to load the data.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
@michalz-rely - I am unclear about how the `aws_config_config_rule_compliance_details` table relates to the `list-tags-for-resource` API call as that API call only supports `ConfigRule`, `ConfigurationAggregator`, and `AggregatorAuthorization`

```
--resource-arn (string)

The Amazon Resource Name (ARN) that identifies the resource for which to list the tags. Currently, the supported resources are ConfigRule , ConfigurationAggregator and AggregatorAuthorization .
```

**Comment by michalz-rely** [comment]
@bbernays - I think you're right, I thought this will actually list the tags for the resources recorded by AWS Config
