### ISSUE TITLE
feat: finding enrichment support for aws security hub

### ISSUE THREAD

**Issue by michalz-rely** [cloudquery/cloudquery#15598]
### Which problem is this feature request solving?

AWS has announced new findings enrichment - https://aws.amazon.com/about-aws/whats-new/2023/11/new-finding-enrichment-aws-security-hub/

> Now, Security Hub consistently enriches all its findings with resource tags, a new AWS application tag, and account name as the findings are ingested. This new finding enrichment in Security Hub eliminates the need to build data enrichment pipelines or manually enrich metadata of security findings.

### Describe the solution you'd like

Support for mentioned enrichements

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
I believe that this should be released in the `v23.0.0` of the AWS plugin as it is just new fields added to the response for `securityhub:GetFindings`.

If there is something else to this issue please reopen the issue
