### ISSUE TITLE
Feedback for “Creating a New CloudQuery Source Plugin in Go” - directory scaffold example is outdated

### ISSUE THREAD

**Issue by erikkristoferanderson** [cloudquery/cloudquery#15645]
The directory scaffold shown just below where it says "At the time of writing, the scaffold creates a directory structure that looks like this:" is outdated. I would like to open a PR to update this. 

This is on the page https://docs.cloudquery.io/docs/developers/creating-new-plugin/go-source

I also think there are possibilities for other improvments to this part of the documentation, but I don't have fully formed ideas there yet. Id like to work on that as well.

**Comment by erezrokah** [comment]
Thanks @erikkristoferanderson, I've assigned you to the issue. A PR would be great 🎸
