### ISSUE TITLE
SDK Tests: `FindEmptyColumns` doesn't detect empty maps

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#15707]
https://github.com/cloudquery/plugin-sdk/blob/36128dd94c73675428b7380c9f7dccb0e6416758/schema/validators.go#L14

`arr.IsValid(i)` doesn't seem to be enough (or broken) for JSON types.

**Comment by candiduslynx** [comment]
I think it only looks for any values in the record, so it can look past a row with null if there's one with value, too

**Comment by disq** [comment]
The circumstances I verified this was a `map[string]any` column ("tags") with `nil` and `{}` values respectively.
