### ISSUE TITLE
bug: Shopify Plugin doesn't sync fulfillment_status field on shopify_orders table

### ISSUE THREAD

**Issue by konung** [cloudquery/cloudquery#15718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Everything works, but fulfillment_status column is omitted in PostgreSQL destination.  Other columns seem to be there, but I haven't done a full comparison. Just noticed that fulfillment_status is not there, even thou it is in the plugin spec.   I'm guessing the type for fulfillment_status is defined incorrectly. Financial_status works - and it's defined as string, but fulfillment_status is defined as ANY in plugin spec. 

### Expected Behavior

fulfillment_status should be there along with financial_status

### CloudQuery (redacted) config

n/a

### Steps To Reproduce

Just run it and check the final table. 

### CloudQuery (redacted) logs

There is no error produced. The field is just missing.

### CloudQuery version

3.21.1 and 3.29.2

### Additional Context

I thought maybe because I was running an older version of the plugins for shopify and postgresql - 3.1.11 and 6.0.7 respectfully. But I just upgraded to latest cloudquery and latest plugins ( 4.0.1 and 7.1.1) and the fulfillment_status field is still misisng

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
This is fixed in the next plugin release, `v5.0.0` which will be available later today.
