### ISSUE TITLE
bug: Unclear error message when using expired token

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#15850]
## Reproduction steps

(Don't log into CQ for a week or two 😄, then... )

```
cloudquery sync azure-ad.yml
```

Output:
```
Loading spec(s) from azure-ad.yml
Error: failed to get auth token: failed to sign in with custom token: failed to refresh token: 400 Bad Request: {
  "error": {
    "code": 400,
    "message": "TOKEN_EXPIRED",
    "status": "INVALID_ARGUMENT"
  }
}
```

The error message doesn't tell you what failed, and users could be forgiven for thinking it's a problem with the plugin authentication. 

In fact, the solution is to run `cloudquery login`, then `cloudquery sync` again.

## Proposed Solution

Improve the error message for this case, making sure we explain what happened and what the probable solution is (`cloudquery login`)

**Comment by disq** [comment]
This was fixed in https://github.com/cloudquery/cloudquery-api-go/pull/90

**Comment by hermanschaaf** [comment]
@disq  Oh nice, missed that. I'll update my CLI version. Thanks!
