### ISSUE TITLE
Feedback for “Getting started with AWS”

### ISSUE THREAD

**Issue by sxVova** [cloudquery/cloudquery#1594]
curl -L https://github.com/cloudquery/cloudquery/releases/latest/download/cloudquery_linux_x86_64 -o cloudquery
Package status: Not found

**Comment by bbernays** [comment]
@sxVova - Looking into this now. Can you provide a little bit of information about where you were executing the above command (windows, linux or mac), local or cloud instance?

**Comment by erezrokah** [comment]
Thanks for the issue @sxVova and good catch. We missed this when we switched to a monorepo structure
