### ISSUE TITLE
AWS RDS: Subnet groups

### ISSUE THREAD

**Issue by Raphx** [cloudquery/cloudquery#16]
Good day, team at cloudquery.

Currently cloudquery supports fetching a list of RDS clusters. Each cluster comes with a [subnet group field](https://github.com/cloudquery/cloudquery/blob/56b04f64a4769ff999b1735070362d2685e79d9c/providers/aws/rds/clusters.go#L243).

We want to know what possible subnets the RDS instances could be deployed in, and that would require cloudquery to fetch subnet group details by further calling [`DescribeDBSubnetGroups`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBSubnetGroups.html) API.

We should be able to see a list of AWS EC2 subnet IDs that are tied to each RDS cluster subnet group.

**Comment by korsune** [comment]
Added in [v0.5.4](https://github.com/cloudquery/cloudquery/releases/tag/v0.5.4) https://github.com/cloudquery/cloudquery/blob/main/cmd/config.go#L52

**Comment by Raphx** [comment]
Thanks @korsune!
