### ISSUE TITLE
bug:  not all codecommit repos being load in aws

### ISSUE THREAD

**Issue by JohnCalhoun** [cloudquery/cloudquery#16106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

only 10 repositories are being written to destination

### Expected Behavior

all code repositories should be written to destination

### CloudQuery (redacted) config
```
kind: source
spec:
name: aws
path: cloudquery/aws
version: v22.19.2
tables:
- ""
skip_tables:
- aws_cloudtrail_events
destinations:
- s3
concurrency: 10000
deterministic_cq_id: true
spec:
regions:
- us-east-2
- us-east-1
- us-west-2
- eu-west-1
accounts:
- id: *
role_arn:
- id: *
role_arn: *
- id: *
role_arn: *
aws_debug: true
```
### Steps To Reproduce

run in a account with more than 10 repositories

### CloudQuery (redacted) logs

NA

### CloudQuery version

3.10.2

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
@JohnCalhoun - Are you seeing any error messages in the logs?

**Comment by bbernays** [comment]
Closing as stale. If you have more details or are able to reproduce it feel free to reopen the issue
