### ISSUE TITLE
feat: Add support for AWS ECR

### ISSUE THREAD

**Issue by nmeneil** [cloudquery/cloudquery#16120]
### Which problem is this feature request solving?

Having created a custom python plugin, we'd like to store them in ECR. They are custom plugins that would be of no use to the outside world and therefore have no use in being public

### Describe the solution you'd like

Using AWS ECR as a private container store

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by disq** [comment]
Looks like these two lines need some massaging to allow for arbitrary auth credentials (preferably headers too) to be used

https://github.com/cloudquery/plugin-pb-go/blob/main/managedplugin/docker.go#L89-L90
