### ISSUE TITLE
AWS Data Sync or Data Transfer

### ISSUE THREAD

**Issue by mounika-pothula** [cloudquery/cloudquery#16123]
### Describe the plugin

Hi team, we need one source plugin for AWS Data Sync or AWS Data Transfer service.

### Link to API documentation

https://docs.aws.amazon.com/datasync/latest/userguide/API_Reference.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
@mounika-pothula thanks for opening this issue! can you please expand on this? which APIs exactly you are interested in?

**Comment by bbernays** [comment]
We have added support for the following tables:
- `aws_datasync_agents`
- `aws_datasync_azureblob_locations`
- `aws_datasync_efs_locations`
- `aws_datasync_fsxlustre_locations`
- `aws_datasync_fsxontap_locations`
- `aws_datasync_fsxopenzfs_locations`
- `aws_datasync_fsxwindows_locations`
- `aws_datasync_hdfs_locations`
- `aws_datasync_locations`
- `aws_datasync_nfs_locations`
- `aws_datasync_objectstorage_locations`
- `aws_datasync_s3_locations`
- `aws_datasync_smb_locations`


If you are looking for other tables please open a new ticket with the API Calls or resources that you would like to see supported
