### ISSUE TITLE
Add JSON schema to `plugins/source/typeform`

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#16460]
```[tasklist]
### Tasks
- [ ] https://github.com/cloudquery/cloudquery/issues/16505
```

**Comment by VedanthB** [comment]
I would like to work on this. Could you please elaborate a little on what needs to be done here? @candiduslynx

**Comment by candiduslynx** [comment]
Hi @VedanthB!

As the plugin is implemented in Python, it will need an update of the API to support returning the JSON schema from the SDK (see API change: https://github.com/cloudquery/plugin-pb/pull/20).

Once SDK supports returning JSON schema for spec from the plugin, Typeform plugin must utilize this & provide a valid JSON schema for the spec.
