### ISSUE TITLE
feat: show requests per second while sync is running

### ISSUE THREAD

**Issue by dbro** [cloudquery/cloudquery#16507]
### Which problem is this feature request solving?

The current status line shows total resources and resources per second, for example:

\ Syncing resources... (13171/-, 118 resources/s) [3m26s]

This describes the volume of data, but I would like to see the request rate in order to better manage rate limit restrictions enforced by the server.`

### Describe the solution you'd like

I would like to see requests per second, maybe something like 

\ Sync'd 13171 resources (118 /s) from 5345 requests (33 /s) [3m26s]

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
@dbro could you provide a bit more detail on how you expect the displayed request rate helping you in managing the rate limit restrictions enforced by the server? Is this related to a specific plugin?

**Comment by erezrokah** [comment]
Closing this a stale. We've implemented retry logic in almost all plugins to handle rate limits. If this is still an issue please re-open
