### ISSUE TITLE
feat: Add tags for the aws_ssm_parameters table in AWS

### ISSUE THREAD

**Issue by atqhg23** [cloudquery/cloudquery#16541]
### Which problem is this feature request solving?

Tag info is missing for the [aws_ssm_parameters ](https://hub.cloudquery.io/plugins/source/cloudquery/aws/v24.1.0/tables/aws_ssm_parameters)table in AWS

### Describe the solution you'd like

Please add tags for the [aws_ssm_parameters ](https://hub.cloudquery.io/plugins/source/cloudquery/aws/v24.1.0/tables/aws_ssm_parameters)table in AWS

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
This functionality will be available on the hub in the next release (`v24.2.0`)

**Comment by bbernays** [comment]
It is available now: https://hub.cloudquery.io/plugins/source/cloudquery/aws/v24.2.0/docs
