### ISSUE TITLE
feat: SQLite Batching

### ISSUE THREAD

**Issue by hydratim** [cloudquery/cloudquery#16636]
### Which problem is this feature request solving?

SQLite destination plugin is very slow.
@erezrokah suggested that this is likely due to the lack of batching in the SQLite plugin. This tracks, given how much faster the Postgres plugin is with the same data from the same source plugin.

### Describe the solution you'd like

Add batching to the SQLite plugin.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by yevgenypats** [comment]
I would be surprised it's batching. batching in general only helps with remote systems. but curious why would that be slower then local postgres. what source plugin you tested it with?

**Comment by bbernays** [comment]
This blog shows how batching can significantly improve insertion in SQLite:
https://avi.im/blag/2021/fast-sqlite-inserts/
