### ISSUE TITLE
feat: Save GitHub Workflow content as JSON

### ISSUE THREAD

**Issue by akash1810** [cloudquery/cloudquery#16850]
### Which problem is this feature request solving?

The `contents` column in the `github_workflows` table contains the content of a GitHub workflow, as YAML. Postgres[^1] does not have first class support for querying YAML, however it has excellent JSON capabilities.

If there was an additional `contents_as_json` column in the table, querying it would be easier. As JSON is a subset of YAML, the transformation should be minimal.

There's no guarantee the value of `contents` is valid YAML, as it's populated via the [get repository content endpoint](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content). That is, the YAML to JSON conversion could fail. To counter this, we could validate the YAML against a [schema](https://json.schemastore.org/github-workflow.json) first.

Uses cases for querying the contents include:
- How does usage of third-party actions compare to [GitHub's guidance](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)?
- Identifying which actions are in use within an organisation. This can aid configuring an organisational [allow list](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#allowing-select-actions-and-reusable-workflows-to-run).
- Are any (known) deprecated actions in use?

[^1]: An assumption is made that one is using Postgres as a destination, however the use-case is likely to apply to other destinations

### Describe the solution you'd like

A new `content_as_json` column in the `github_workflows` column.

Initial PR - https://github.com/cloudquery/cloudquery/pull/16846.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Thanks for waiting on our respond while we talk this change internally. I commented on the PR in https://github.com/cloudquery/cloudquery/pull/16846#issuecomment-1966659810

**Comment by akash1810** [comment]
Addressed in https://github.com/cloudquery/cloudquery/pull/16846
