### ISSUE TITLE
Why cloudquery sends sync summary to analyticsv1.cloudquery.io:443

### ISSUE THREAD

**Issue by hsravidatta** [cloudquery/cloudquery#16897]
We would like to know, cloudquery sends sync summary to analyticsv1.cloudquery.io:443, this is the question raised by our internal infosec guys that, we agree that cloud query can discover the devices from Azure but it is also connecting to above URL and they are not approving the access to this portal due to security constraints. could you please help us on this? can we disable this ?

**Comment by erezrokah** [comment]
Hi @hsravidatta, see more about the telemetry we collect in https://docs.cloudquery.io/docs/telemetry

**Comment by hsravidatta** [comment]
Thank you very much for quick response. I will check this out by setting to none.

**Comment by erezrokah** [comment]
I'll close this as resolved. Please comment if you have further questions

**Comment by yevgenypats** [comment]
@hsravidatta thanks for the question. Do note that premium tables on azure will require access to our licensing server in any case (as otherwise we can't bill for that)
