### ISSUE TITLE
AWS Redshift: Subnet groups

### ISSUE THREAD

**Issue by Raphx** [cloudquery/cloudquery#17]
Similar to #16, but for Redshift subnet groups, by further calling [`DescribeClusterSubnetGroups`](https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeClusterSubnetGroups.html) after fetching details for Redshift clusters.

It would help for us to know the subnet IDs for each of the Redshift subnet group.

**Comment by korsune** [comment]
Added in [v0.5.4](https://github.com/cloudquery/cloudquery/releases/tag/v0.5.4) https://github.com/cloudquery/cloudquery/blob/main/cmd/config.go#L54
