### ISSUE TITLE
Broken Links in Plugin Contribution Guide

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1701]
[Adding a new Resource](https://github.com/cloudquery/cloudquery/blob/main/plugins/docs/contributing/adding_a_new_resource.md)

**Comment by erezrokah** [comment]
Hi @bbernays can you add the page that linked to the broken link? I couldn't find it

**Comment by bbernays** [comment]
@erezrokah - On [this page](https://github.com/cloudquery/cloudquery/blob/main/plugins/CONTRIBUTING.md#getting-started)

These links are broken:
[Provider Development Environment Setup](https://github.com/cloudquery/cloudquery/blob/main/plugins/docs/contributing/development_environment.md)
[Adding a new Resource](https://github.com/cloudquery/cloudquery/blob/main/plugins/docs/contributing/adding_a_new_resource.md)
