### ISSUE TITLE
feat: Add foreign keys to the tables to find the relationships between the tables in cloudquery

### ISSUE THREAD

**Issue by Prabhanjali** [cloudquery/cloudquery#17015]
### Which problem is this feature request solving?

To find the relationships between the tables in cloudquery

### Describe the solution you'd like

Add relationships between the tables in cloudquery

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @Prabhanjali the relationships are can be found via each plugin docs. For example https://hub.cloudquery.io/plugins/source/cloudquery/alicloud/latest/tables/alicloud_oss_bucket_stats
![image](https://github.com/cloudquery/cloudquery/assets/26760571/38c08861-f15e-48de-89b1-8163a3e502a8)

You can create a JSON version of the docs using the [`tables` command](https://docs.cloudquery.io/docs/reference/cli/cloudquery_tables).

Not all destinations support foreign keys so those will be helpful only for those that do.

**Comment by erezrokah** [comment]
Closing this per my comment
