### ISSUE TITLE
feat(github): Add support to list api-tokens 

### ISSUE THREAD

**Issue by manjunathsc** [cloudquery/cloudquery#17092]
### Which problem is this feature request solving?

I would like to fetch  api-tokens created in a GitHub 

### Describe the solution you'd like

I would like to fetch  api-tokens created in a GitHub 

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by manjunathsc** [comment]
API Tokens - this objects defines an API token created a by a user to allow SW access to github resources.

Use Case
Which tokens and API service integrations are enabled in my environment is an important data point for security audits.

It would be super useful if these resources could be added to github.

**Comment by bbernays** [comment]
@manjunathsc- Is this the information you are looking for: https://docs.github.com/en/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#list-requests-to-access-organization-resources-with-fine-grained-personal-access-tokens

If it is not the information you want can you point to the API that does return the data you are interested in?

**Comment by erezrokah** [comment]
Per https://github.com/cloudquery/cloudquery/issues/17092#issuecomment-2050675390 as it's no clear what to implement I think we can close this as stale, pending further comments on the issue

**Comment by erezrokah** [comment]
Re-opening so @candiduslynx can take another look

**Comment by candiduslynx** [comment]
Currently this [request](https://docs.github.com/en/rest/orgs/personal-access-tokens?apiVersion=2022-11-28#list-fine-grained-personal-access-tokens-with-access-to-organization-resources) isn't implemented in the SDK we use, so closing
