### ISSUE TITLE
Feedback for “Running Plugins Locally”

### ISSUE THREAD

**Issue by duncanmapes** [cloudquery/cloudquery#17093]
What should the reference look like in the case of a JS? I'm having trouble after pulling it down from my NPM package.

**Comment by erezrokah** [comment]
Hi @duncanmapes are you able to share the code for your JS plugin? Usually you could start the gRPC server in a similar way described in https://docs.cloudquery.io/docs/developers/running-locally and the spec configuration should be similar (e.g. `path: "localhost:7777"`).

You can see an example in https://github.com/cloudquery/cloudquery/tree/13749164ae4e8193ee34fbb93eb3a677a6f37f35/plugins/source/airtable

**Comment by duncanmapes** [comment]
Hey @erezrokah, that's what I ended up doing (manually starting the gPRC server).  It just seemed like kind of a hacky way to do it.  It would be nice if it was managed the same way as the Go plugins for example, but its certainly workable as is.

**Comment by erezrokah** [comment]
> It would be nice if it was managed the same way as the Go plugins for example

Go plugins can be built into a binary so the CLI can managed them as a single executable. I hope that explains the differences with JS
