### ISSUE TITLE
provider download

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#171]
Update provider download to use `Short`, `Long` and `Examples` in command (as in all other commands after latest fix).

Update documentation - Add command documentation here - https://docs.cloudquery.io/docs/cli/commands/init/

**Comment by irmatov** [comment]
https://github.com/cloudquery/docs/pull/20

**Comment by irmatov** [comment]
https://github.com/cloudquery/cloudquery/pull/174
