### ISSUE TITLE
Add Support For CockroachDB

### ISSUE THREAD

**Issue by mingfang** [cloudquery/cloudquery#1710]
I would like to use CockroachDB for storage instead of Postgres.
Because CockroachDB wire compatible with Postgres, I was about to use similar database connection URL.
But immediately at startup it failed with this error.
```
Error: could not init state: failed to migrate cloudquery_core tables: try lock failed in line 0: SELECT pg_advisory_lock($1) (details: pq: unknown function: pg_advisory_lock())
```
This is a known issue https://github.com/cockroachdb/cockroach/issues/13546
Ideally Cloudquery add native support for CockroachDB.

**Comment by yevgenypats** [comment]
@mingfang Thanks! Actually we are rolling this next week - we are working on CloudQuery v2 - https://github.com/cloudquery/cloudquery/pull/1463 which separates the plugins from the storage layer as well as remove any non standard PG operations so cockroach will work out-of-the-box in addition to new storage layers coming up such as BigQuery/Snowflake etc...

**Comment by yevgenypats** [comment]
@mingfang This is now out 🥳  with destination plugin `postgresql` version `v1.1.0`

https://github.com/cloudquery/cloudquery/pull/2566

**Comment by mingfang** [comment]
@yevgenypats Just tested and confirmed working. Thank you very much!

**Comment by yevgenypats** [comment]
Amazing, we've added cockroach also to our CI tests but please feel free to let us know if you hit any issues on Cockroach (or PostgreSQL).

**Comment by mingfang** [comment]
Not sure if this is cockroachdb related,  but I'm getting this error with postgres plugin v1.3.3 and tried upgrading my aws plugin from v2.1.0 to v3.0.1...
```
Error: failed to sync source aws: failed to migrate source aws on destination postgresql : failed to call Migrate: rpc error: code = Unknown desc = failed to commit transaction to recreate primary keys: ERROR: transaction committed but schema change aborted with error: (23505): failed to ingest index entries during backfill: duplicate key value violates unique constraint "aws_elasticache_engine_versions_cqpk" (SQLSTATE XXA00)
```
