### ISSUE TITLE
bug: ClickHouse destination uses `DateTime64(3)` for `date64` mapping

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#17204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I also think that we should update the type mapping for `date64` in the ClickHouse plugin.

Currently `DateTime64(3)` (aka ms precision) is used:
https://github.com/cloudquery/cloudquery/blob/aba7a68ef4121240c9dec89b0652e085070f4a85/plugins/destination/clickhouse/typeconv/ch/types/column_type.go#L51-L53

ClickHouse will use `DateTime` instead: https://clickhouse.com/docs/en/sql-reference/formats#data-format-arrow.

I think the behavior between plugin & ClickHouse should be consistent: in Apache Arrow `date64` is still a date, so behavior when the `date64` isn't properly matching the date boundary is UB.

### Expected Behavior

`date64` is mapped to `DateTime` ClickHouse type

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

latest

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
What's the impact of this bug? Is it data corruption? Can you give an example?

**Comment by candiduslynx** [comment]
I don't think there is any corruption, it's just an inconsistency between how ClickHouse treats the Apache Arrow data written directly & our conversions.
