### ISSUE TITLE
Create a Backstage Plugin

### ISSUE THREAD

**Issue by SCKelemen** [cloudquery/cloudquery#1721]
Backstage is increasing in popularity as the defacto developer portal for large companies. Creating a cloudquery plugin for backstage would enhance the experience for searching cloud assets, handling vulnerabilities, and visibility.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/backstage. Please sign up there to get a notified when the plugin is available.
