### ISSUE TITLE
Add Protobuf spec for resources

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#1725]
[Protocol Buffers](https://developers.google.com/protocol-buffers/) are a great tool to describe APIs as well as data.
It'd be great to have a spec for each resource present so that the tooling can be built around CloudQuery data.

**Comment by yevgenypats** [comment]
Closing for now as I don't think we will ever get to this and/or this need more explanation and design documentation on how and what it will mean.
