### ISSUE TITLE
Add Test for Duplicated PK in Test Writer test suite

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#17411]
Add a test to the test suite that has multiple records with the same PK value. This will allow destinations to ensure that they are handling it properly

**Comment by candiduslynx** [comment]
Didn't we use to handle this in the batching? In the sdk

**Comment by erezrokah** [comment]
Since we closed https://github.com/cloudquery/cloudquery/pull/17373 do we still need to add this test? Or maybe lower the priority of the issue? We can move it back to the backlog if needed

**Comment by bbernays** [comment]
While I think #17373 is not an issue. I think we should have a test in the SDK to ensure that the behavior at the destination is what we expect it to be
