### ISSUE TITLE
ci: Update `golangci-lint` config not to use deprecated `run.skip-dirs` option (replaced with `issues.exclude-dirs`)

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#17455]
We can see the following message running `make lint` in out plugin dirs with the latest `golangci-lint`:
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
```

This is not a priority for now, but should be outlined for the future.
```[tasklist]
### Tasks
- [x] CLI
- [x] destination plugins
- [x] source plugins
- [x] plugin-sdk
- [x] codegen
```

**Comment by erezrokah** [comment]
Example line to update https://github.com/cloudquery/cloudquery/blob/a10fb7f5b2535e731d9db620d19bdb53c924ccf2/cli/.golangci.yml#L4

**Comment by erezrokah** [comment]
Will be fixed by https://github.com/cloudquery/filetypes/pull/542 and https://github.com/cloudquery/cloudquery-private/pull/3313
