### ISSUE TITLE
feat: Add tags to compliance transformations

### ISSUE THREAD

**Issue by k-rheinheimer** [cloudquery/cloudquery#17474]
### Which problem is this feature request solving?

Teams use tags to separate resources by team/business unit/environment/etc. If tags are included as fields in the CQ generated tables, they can be included in views created by CQ transformations to allow for further filtering granularity

### Describe the solution you'd like

include tags in CQ tables so that they can be used in compliance transformations

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
For those compliance results that return a resource identifier, why not just a do join between the inventory view on the ARN? This should work out of the box because we already include tags in the resource view

**Comment by k-rheinheimer** [comment]
> For those compliance results that return a resource identifier, why not just a do join between the inventory view on the ARN? This should work out of the box because we already include tags in the resource view

Wouldn't that add an extra dependency on the users to also have run the asset inventory transformation? 

Is this preferable to refactoring the compliance macros to grab tags directly from the aws tables?

**Comment by k-rheinheimer** [comment]
closed for https://github.com/cloudquery/cloudquery/issues/17486
