### ISSUE TITLE
Bug(website): Search links to 404 pages

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1751]
### Describe the Bug

Reported in https://discord.com/channels/872925471417962546/873606591335759872/1016663642952962078
If you search for `database` and click the links they send you to a 404 page:
![image](https://user-images.githubusercontent.com/26760571/188645557-c7c3999f-c1ec-4ba4-b972-63a14d77836a.png)

https://www.cloudquery.io/docs/getting-started/_getting-started-spawn-section#spawn-or-connect-to-a-database

should be https://www.cloudquery.io/docs/getting-started/getting-started-with-aws#spawn-or-connect-to-a-database for example

### Expected Behavior

Search to work

**Comment by MallikharjunaTeja** [comment]
Hi @erezrokah I want to work on this

**Comment by erezrokah** [comment]
Woo thanks @MallikharjunaTeja 🙌  Our search bar is created using a framework called [Nextra](https://nextra.vercel.app/) which is quite new so I'd search for relevant issues in the [GitHub repository](https://github.com/shuding/nextra/issues).

Maybe we can configure the search via https://github.com/cloudquery/cloudquery/blob/5bc205ec7f4a7b2fa8a34793e8d746a43cbb03ed/website/theme.config.tsx#L20.

Also you can run the website version locally by:
1. Forking and cloning the repo.
2. `cd website`
3. `yarn`
4. `yarn dev`

Let me know if you have further questions

**Comment by MallikharjunaTeja** [comment]
@erezrokah i am using windows when i tried to run it on wsl the yarn commands are not working could you please help me with that and if you assign this issue to me it will be useful for my academics

**Comment by erezrokah** [comment]
Hi @MallikharjunaTeja can you share the error you're getting?

**Comment by MallikharjunaTeja** [comment]
when i run npm build command i was getting an error  
![Screenshot (82)](https://user-images.githubusercontent.com/112918796/190900598-a03d11b0-7528-44ee-ad50-8817c316cfc6.png)

then i installed heroku cli but unable to run any command getting  the same error
![Screenshot (83)](https://user-images.githubusercontent.com/112918796/190900663-de34a134-898d-4b92-baa2-5cb9fb43d239.png)

**Comment by cqgaurav** [comment]
Not sure if this helps: seems like the search returns results from this repository [1] which is archived, which result in a 404. eg [2] . Some other examples are returning children links of [3], which I couldn't find a reference for in our repos, maybe it has been removed now. I am assuming somewhere the search index is still referencing routes that no longer exist, and somehow those need to be updated.

[1] https://github.com/cloudquery/docs
[2] https://github.com/cloudquery/docs/blob/main/docs/getting-started/_getting-started-spawn-section.mdx
[3] https://www.cloudquery.io/hub

**Comment by cqgaurav** [comment]
This doesn't seem to be happening anymore (with the documentation still pointing to V0). Any idea what could have fixed it (so if it recurs for V1, we know what to try) ? @erezrokah

**Comment by erezrokah** [comment]
> This doesn't seem to be happening anymore (with the documentation still pointing to V0). Any idea what could have fixed it (so if it recurs for V1, we know what to try) ? @erezrokah

This is great 🚀 Seems to be working on both v0 and v1 docs. I looked at the changes to the Website and I can't see what could have fixed this, but it's already hard to track down because our build was broken/disabled for some time.

I'll close the issue as fixed, and this reproduces again we can't investigate.
