### ISSUE TITLE
feat: `tables` command only return tables specified in config

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#17524]
### Which problem is this feature request solving?

As a user I want to know exactly what tables will be synced by a config.

### Describe the solution you'd like

Right now if I use the `cloudquery tables config.yml` command this will output all of the tables for the plugins included in that command.

My ideal solution would be to expose a CLI flag that specifies whether the CLI should send `tables:[*]` or use the settings specified in the config file to generate the list of tables

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
We weren't able to do this before as docs generation was done in the plugins and didn't expose an option to control the list of tables. With https://github.com/cloudquery/cloudquery/pull/12758 should be not that hard to do

**Comment by erezrokah** [comment]
This is done via https://github.com/cloudquery/cloudquery/pull/17584
