### ISSUE TITLE
bug: AIRTABLE Plugin: sync failed with error message from the log

### ISSUE THREAD

**Issue by shotleybuilder** [cloudquery/cloudquery#17531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Airtable plug-in
From the log:
2024-04-05T08:59:55Z ERR exiting with error error="failed to pull Docker image: Error response from daemon: Head \"https://docker.cloudquery.io/v2/cloudquery/source-airtable/manifests/v2.1.2\": unknown: The server could not parse your request body" module=cli

### Expected Behavior

I'm not sure what to expect since is the first time I've used cloudquery

### CloudQuery (redacted) config

```yaml config
kind: source
# Common source-plugin configuration
spec:
  name: airtable
  registry: docker
  path: docker.cloudquery.io/cloudquery/source-airtable:v2.1.2
  tables:
    # Sync all tables under bases matching the name `base_name_to_sync`
    #- "*__UK__*"
    # Sync all tables matching the name `table_name_to_sync`
    #- "*__*__LRT"
    # Sync all tables matching the name `table_name_to_sync` under bases matching the name `base_name_to_sync`
    - "*__UK__LRT"
  destinations: ["supabase"]
  # airtable-specific configuration
  spec:
    access_token: "redacted" # required
    # endpoint_url: "https://api.airtable.com" # Optional, defaults to `https://api.airtable.com`
    # concurrency: 10000 # Optional, defaults to `10000`

```

### CloudQuery (redacted) logs

```
2024-04-05T08:55:42Z ERR exiting with error error="failed to list Docker images: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.43/images/json?filters=%7B%22reference%22%3A%7B%22docker.cloudquery.io%2Fcloudquery%2Fsource-airtable%3Av2.1.2%22%3Atrue%7D%7D\": dial unix /var/run/docker.sock: connect: permission denied" module=cli
2024-04-05T08:59:55Z INF Loading spec(s) args=["cloudquery-config/airtable.yml","cloudquery-config/postgresql.yml"] module=cli
2024-04-05T08:59:55Z WRN when using the CloudQuery registry, it's recommended to log in via `cloudquery login`. Logging in allows for better rate limits and downloading of premium plugins module=cli
2024-04-05T08:59:55Z ERR exiting with error error="failed to pull Docker image: Error response from daemon: Head \"https://docker.cloudquery.io/v2/cloudquery/source-airtable/manifests/v2.1.2\": unknown: The server could not parse your request body" module=cli
```

### CloudQuery version

cloudquery version 4.3.4

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Hi @shotleybuilder, can you confirm:
1. You have Docker installed and running via `docker --version`
2. The CloudQuery CLI logged in via `cloudquery login`

**Comment by shotleybuilder** [comment]
@erezrokah 
Docker -> Docker version 26.0.0, build 2ae903e
Cloudquery login -> Not sure what behaviour to expect.  I did run `cloudquery login` which opened the web page, I logged in using my github creds and then closed the page.

**Comment by erezrokah** [comment]
> Not sure what behaviour to expect

That's the correct behavior 💯 

Let me try and reproduce the issue and I'll respond here in a bit

**Comment by shotleybuilder** [comment]
@erezrokah okay, thank-you.  I'm going to try and run as a container - I've just generated my API key.

**Comment by erezrokah** [comment]
What is the environment you're running `cloudquery sync` in? Running docker plugins inside Docker won't work out of the box, as the CLI uses docker internally. There are some solutions to running docker inside docker, for example https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker

**Comment by shotleybuilder** [comment]
What is the environment you're running cloudquery sync in? 
Just the terminal on my laptop running Ubuntu 22.04.4 LTS Jammy

**Comment by shotleybuilder** [comment]
Running this cmd:
sudo ./cloudquery sync cloudquery-config/airtable.yml cloudquery-config/postgresql.yml

**Comment by erezrokah** [comment]
Thanks for sharing the information @shotleybuilder, I'm unable to reproduce (running on MacOS).
Any reason you're trying with `sudo`? Maybe drop it?
Can you also try a sanity test and run `docker run ghcr.io/cloudquery/cloudquery:5.13.1`?
That should invoke our CLI via our Docker image

**Comment by shotleybuilder** [comment]
Okay, so there was a problem with my Docker install -> see [here](https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue).  This has fixed 'sudo'.  
`srw-rw---- 1 root docker 0 Apr  3 16:41 /var/run/docker.sock`
`-rw-rw-r-- 1 root docker 295 Mar 20 15:16 /lib/systemd/system/docker.socket`

The result of running:
```
$ docker run ghcr.io/cloudquery/cloudquery:5.13.1
Unable to find image 'ghcr.io/cloudquery/cloudquery:5.13.1' locally
5.13.1: Pulling from cloudquery/cloudquery
4abcf2066143: Already exists 
d9eacfa5a0f3: Pull complete 
b1ca05ac361b: Pull complete 
aa39d93e82aa: Pull complete 
Digest: sha256:dc6b2bb1741903e03611fbb6e0c12c156f1af410863e9ffb36f36e14c47f5d20
Status: Downloaded newer image for ghcr.io/cloudquery/cloudquery:5.13.1
CloudQuery CLI
```

But, I'm still getting the problem Error
```
$ ./cloudquery sync cloudquery-config/airtable.yml cloudquery-config/postgresql.yml
Loading spec(s) from cloudquery-config/airtable.yml, cloudquery-config/postgresql.yml
Error: failed to pull Docker image: Error response from daemon: Head "https://docker.cloudquery.io/v2/cloudquery/source-airtable/manifests/v2.1.2": unknown: The server could not parse your request body
```
Have restarted docker `sudo systemctl restart docker`
Will now try a reboot :)

**Comment by shotleybuilder** [comment]
Okay, so the reboot hasn't worked
```
$ ./cloudquery login
Opened browser at https://accounts.cloudquery.io?returnTo=http://localhost:36651/callback. Waiting for authentication to complete.
Gtk-Message: 13:14:38.906: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Authenticating...
Your current team is set to spongl.
CLI successfully authenticated.
$ ./cloudquery sync cloudquery-config/airtable.yml cloudquery-config/postgresql.yml
Loading spec(s) from cloudquery-config/airtable.yml, cloudquery-config/postgresql.yml
Error: failed to pull Docker image: Error response from daemon: Head "https://docker.cloudquery.io/v2/cloudquery/source-airtable/manifests/v2.1.2": unknown: The server could not parse your request body
$ 
```
Will revert to running as described [here](https://docs.cloudquery.io/docs/deployment/docker)

**Comment by shotleybuilder** [comment]
Wow, this is frustrating, I've pretty much come to the end of my experiment and did not achieve a working sync.  There are errors in the documentation too, which for a beginner is really tough.  Might drop back in when this is matured or someone had blogged about a successful Airtable sync.
Here's about as far as I was able to get:
```
$ sudo systemctl restart docker.socket
$ curl --unix-socket /var/run/docker.sock  http://localhost/_ping; echo
OK
$ docker run --pull=always -v /home/jason/Desktop/cloudquery/cloudquery-config:/config.yml -e CLOUDQUERY_API_KEY==9Yp3pylLVX91M4ej8z9h55b2fv2vAhQZ ghcr.io/cloudquery/cloudquery:latest sync /config.yml
latest: Pulling from cloudquery/cloudquery
Digest: sha256:bcecd4af17ee0ff87fe167ac2c8ef7b852e2df1204bcf43660839e6463c47abc
Status: Image is up to date for ghcr.io/cloudquery/cloudquery:latest
Loading spec(s) from /config.yml
Error: failed to list Docker images: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
I'm going to reinstall Docker but I have to say there were no problems running Airbyte locally yesterday.

**Comment by erezrokah** [comment]
Hi @shotleybuilder sorry you're experiencing this issue. Can I recommend using the CLI directly and not inside a docker container? Especially if you're running from Ubuntu

**Comment by bbernays** [comment]
@shotleybuilder We noticed a typo in our docs we have `-e CLOUDQUERY_API_KEY==api-key` instead of `-e CLOUDQUERY_API_KEY=api-key` . Can you remove the second `=` and retry?

We have also opened a PR to fix this in our docs: https://github.com/cloudquery/cloudquery/pull/17537

**Comment by shotleybuilder** [comment]
@bbernays 
there is another typo `docker run --pull always ` should be `docker run --pull=always`

**Comment by yevgenypats** [comment]
I've opened this issue that should improve experience https://github.com/cloudquery/cloudquery-issues/issues/1479 . Our airtable plugin was written in python mostly serving as an example but all our official plugins are in Go to avoid having docker as a pre-requirement. we will update here once plugin is re-written in Go.

**Comment by erezrokah** [comment]
> Our airtable plugin was written in python

Small correction it's written in JavaScript

**Comment by erezrokah** [comment]
I've also opened https://github.com/cloudquery/cloudquery/issues/17547

**Comment by erezrokah** [comment]
Re-opened as https://github.com/cloudquery/cloudquery/pull/17546 only fix the docs error mentioned in https://github.com/cloudquery/cloudquery/issues/17531#issuecomment-2041030361

**Comment by erezrokah** [comment]
Hi 👋 We published a guide on how to use CloudQuery docker plugins in a containerized environment https://docs.cloudquery.io/docs/advanced-topics/using-cloud-query-docker-registry-plugins-inside-a-containerized-environment
We're also looking to porting the Airtable plugin to a Go binary to simplify deployment, but that might take a bit of time
