### ISSUE TITLE
Doc: Add guide on how to run Docker plugins when running the CLI inside Docker

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#17547]
This has been popping up once in a while and causing quite a bit of friction to our users (see https://github.com/cloudquery/cloudquery/issues/17531).

It's possible (though not recommended) to run Docker inside docker. Which should add a guide for it

**Comment by bbernays** [comment]
Maybe instead of documenting `docker in docker` we should document how to run a docker plugin as a standalone gRPC server. We can show users how they can create a docker-compose to ensure that multiple sources/destinations are all running before running the sync on a separate container

**Comment by erezrokah** [comment]
> We can show users how they can create a docker-compose to ensure that multiple sources/destinations are all running before running the sync on a separate container

That could work to I'll look into it 👍
