### ISSUE TITLE
bug: AWS Foundational Security iam.6 and lambda.1

### ISSUE THREAD

**Issue by k-rheinheimer** [cloudquery/cloudquery#17553]
## iam.6 issue

iam.6 - CQ is reporting we don't have MFA on the root accounts where Security Hub says enabled. The table aws_iam_credential_reports has a column "mfa_active" and they are all set to true. The compliance pack is checking for a column that does not exist in our CQ output

## lambda.1 issue

CQ is reporting the some policies don't restrict public access when security hub says otherwise.
- likely due to lambda function config

**Comment by bbernays** [comment]
Fixed in:
- https://github.com/cloudquery/policies-premium/pull/742
- https://github.com/cloudquery/policies-premium/pull/737
- https://github.com/cloudquery/policies-premium/pull/736
