### ISSUE TITLE
feat: Add Snyk Targets

### ISSUE THREAD

**Issue by komodo472** [cloudquery/cloudquery#17670]
### Which problem is this feature request solving?

Add support for [Snyk Targets](https://apidocs.snyk.io/?&version=2024-04-11#get-/orgs/-org_id-/targets)

### Describe the solution you'd like

Ability to query Snyk targets

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by murarustefaan** [comment]
Implemented in [#2102](https://github.com/cloudquery/cloudquery-private/pull/2102).
