### ISSUE TITLE
feat: Support more Reserved Instances tables

### ISSUE THREAD

**Issue by BenitezDev** [cloudquery/cloudquery#17702]
### Which problem is this feature request solving?

I can't have a full overview of the reserved instances I have in AWS.

At the moment CQ supports aws_ec2_reserved_instances, aws_rds_reserved_instances, and aws_elasticache_reserved_cache_nodes, but there are missing services that can be reserved.

### Describe the solution you'd like

This could be resolved by adding extra tables fetching this APIS:

- aws_elasticache_reserved_cache_nodes -> https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_DescribeReservedCacheNodes.html

- aws_redshift_reserved_nodes -> https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeReservedNodes.html

- aws_opensearch_reserved_instances -> https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_DescribeReservedInstances.html

- aws_elasticsearch_reserved_instances -> https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#ElasticsearchService.DescribeReservedElasticsearchInstancesPagesWithContext

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by murarustefaan** [comment]
Hello @BenitezDev,

First of all, thanks for your interest in Cloudquery!

We implemented the suggested reserved resources tables, with the following names:

* `aws_redshift_reserved_nodes`
* `aws_opensearch_reserved_instances`
* `aws_elasticsearch_reserved_instances`
* `aws_memorydb_reserved_nodes`

These tables will be released, along others, in the next minor version (`v26.5.0`) of the AWS plugin.

For the other 2, elasticache already had a reserved resources table, while for dynamodb the API you linked is the one for changing IAM policies. We were also unable to find any references around reservations of dynamodb instances, seems it's just quotas one can change.
