### ISSUE TITLE
feat: Update CLI docs for addon downloads

### ISSUE THREAD

**Issue by k-rheinheimer** [cloudquery/cloudquery#17772]
### Which problem is this feature request solving?

As an engineer I want the documents page for downloading addons to have more relevant information + an example command:

https://docs.cloudquery.io/docs/reference/cli/cloudquery_addon_download

### Describe the solution you'd like

Modify the command generic example to include the publisher:

> Download an addon to local disk
> cloudquery addon download {publisher}/{addon-type}/{addon-name}@v1.0.0

Add a real example command i.e. 
`cloudquery addon download cloudquery/transformation/aws-compliance-premium@v1.9.0`

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
The docs are auto generated from https://github.com/cloudquery/cloudquery/blob/a4faf755c494239becfdff32b3d143a31bc4ec71/cli/cmd/addon_download.go#L26 FYI, so that's the code to update, then run `make gen` in the `cli` directory

**Comment by k-rheinheimer** [comment]
PR: https://github.com/cloudquery/cloudquery/pull/17774
