### ISSUE TITLE
bug: Github Plugin not returning repo custom properties

### ISSUE THREAD

**Issue by duncanmapes** [cloudquery/cloudquery#17907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

a column is being created in the repo table, but no values are being set

### Expected Behavior

the custom property values on the repo are expected to be set

### CloudQuery (redacted) config

n/a

### CloudQuery (redacted) logs

n/a

### CloudQuery version

v5.18.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
> I wonder if that's only returned on get request rather than list one.

💯  This is correct based on the list vs get schema in https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories vs https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

**Comment by erezrokah** [comment]
Somewhat related to https://github.com/google/go-github/issues/3159 (misaligned between the Go SDK response object and the rest API response schema)
