### ISSUE TITLE
bug: aws_s3_buckets does not specify Server Access log format

### ISSUE THREAD

**Issue by sohil-h** [cloudquery/cloudquery#17905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AWS allows server access logs to be written to any bucket/prefix
This is indicated via logging_target_bucket/logging_target_prefix

### Expected Behavior

AWS now supports 2 formats for logging server access logs
<img width="651" alt="image" src="https://github.com/cloudquery/cloudquery/assets/113948252/67c411ec-f673-40c4-bdd1-28a8b8d30775">
Can we have an indication in the cq table to indicate the format in which logging has been enabled?
Something like logging_format with values in
- [DestinationPrefix][YYYY]-[MM]-[DD]-[hh]-[mm]-[ss]-[UniqueString]
- [DestinationPrefix][SourceAccountId]/​[SourceRegion]/​[SourceBucket]/​[YYYY]/​[MM]/​[DD]/​[YYYY]-[MM]-[DD]-[hh]-[mm]-[ss]-[UniqueString]

### CloudQuery (redacted) config

```  kind: source
  spec:
    ## Required. name of the plugin to use.
    ## This should be unique if you have number of aws plugins.
    name: "${ACCOUNT_ID}"

    ## Required. Must be a specific version starting with v, e.g. v1.2.3
    ## checkout latest versions here https://github.com/cloudquery/cloudquery/releases?q=plugins-source-aws&expanded=true
    version: "v22.12.0"

    ## Optional. Where to search for the plugin. Default: "github". Options: "github", "local", "grpc"
    # registry: "github"

    ## Optional. path for the plugin. Default: "cloudquery/name".
    ## If registry is "github" path should be "repo/name"
    ## If registry is "local", path is path to binary. If "grpc" then it should be address of the plugin (usually useful in debug).
    path: cloudquery/aws

    ## Optional. Default: ["*"] - all tables. We recommend to specify specific tables that you need to sync as this
    ## will reduce the amount of data synced and improve performance.
    ## See all tables: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/README.md
    tables:
      - aws_organizations_accounts
      - aws_s3_accounts
      - aws_s3_buckets
      - aws_rds_certificates
      - aws_rds_cluster_parameter_groups
      - aws_rds_cluster_snapshots
      - aws_rds_clusters
      - aws_rds_db_parameter_groups
      - aws_rds_db_security_groups
      - aws_rds_db_snapshots
      - aws_rds_event_subscriptions
      - aws_rds_instances
      - aws_redshift_clusters
      - aws_redshift_event_subscriptions
      - aws_redshift_subnet_groups
      - aws_regions```

### Steps To Reproduce

_No response_

### CloudQuery (redacted) logs

```N/A```

### CloudQuery version

v22.12.0

### Additional Context

_No response_

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
Hi @sohil-h - It looks like you are using an older version of the AWS plugin. In the latest version of the AWS plugin (`v26.3.0`) we have split the logging configurations into a seperate table where all of the information you are looking for can be found.

More details can be found here:  [aws_s3_bucket_loggings](https://hub.cloudquery.io/plugins/source/cloudquery/aws/latest/docs)

Let me know if this doesn't solve your issue

**Comment by sohil-h** [comment]
@bbernays I see. Thanks a lot!

**Comment by sohil-h** [comment]
It is a bit of a lift for us to upgrade the schema as we have some dependencies on the current one. Is this information present in the version I am on?
