### ISSUE TITLE
Support Azure Kubernetes Service

### ISSUE THREAD

**Issue by kvish** [cloudquery/cloudquery#1791]
### Why do you need this resource or plugin?

Monitoring rbac status of kubernetes cluster

### Describe the solution you'd like

a table consisting of a describe on azure kubernetes cluster.

**Comment by erezrokah** [comment]
Hi @kvish and thank for requesting this resource. I believe we already support it via the [azure_container_managed_clusters table](https://github.com/cloudquery/cloudquery/blob/3523c7e279670079e0d872d89b80c4e6c7f250e3/plugins/source/azure/resources/services/container/managed_clusters.go#L14) and the [enable_rbac](https://github.com/cloudquery/cloudquery/blob/3523c7e279670079e0d872d89b80c4e6c7f250e3/plugins/source/azure/resources/services/container/managed_clusters.go#L104) column.

I'll close the issue as I believe it's already implemented. If I got this wrong and this is not what you asked for, or something is missing from `azure_container_managed_clusters` please comment and I'll re-open.
