### ISSUE TITLE
feat: PostgreSQL destination delete stale requires sequential scan

### ISSUE THREAD

**Issue by kd7lxl** [cloudquery/cloudquery#17913]
### Which problem is this feature request solving?

The postgresql destination plugin deletes stale records like this: https://github.com/cloudquery/cloudquery/blob/f649bed8f631e322862b6bc536e0644ad1368f7b/plugins/destination/postgresql/client/delete.go#L18-L25

The filter on `_cq_source_name` and `_cq_sync_time` requires a sequential scan of the table because these fields aren't indexed:
```sql
explain delete from "gcp_compute_instances" where _cq_source_name = 'foo' and _cq_sync_time < now();
                                  QUERY PLAN
-------------------------------------------------------------------------------
 Delete on gcp_compute_instances  (cost=0.00..20059.78 rows=0 width=0)
   ->  Seq Scan on gcp_compute_instances  (cost=0.00..20059.78 rows=2 width=6)
         Filter: ((_cq_source_name = 'foo'::text) AND (_cq_sync_time < now()))
(3 rows)
```

On tables with several sources, this could be slow. It seems like it could benefit from an index.

### Describe the solution you'd like

Create indexes on `_cq_source_name` and `_cq_sync_time`.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by kd7lxl** [comment]
Just waiting for permission to contribute per https://github.com/cloudquery/cloudquery/blob/85f0d9b82012afa58b6b783b41a01957422b40f0/CONTRIBUTING.md?plain=1#L20

**Comment by erezrokah** [comment]
Hi @kd7lxl, thanks for suggesting a contribution. Maybe you can start with a draft PR to show how the implementation would look like? We'll need to also discuss this internally if we want the SDK schema to tell destinations if they should create indices for columns, or it should be coded in the destination per column

**Comment by kd7lxl** [comment]
The scope of this request is to create an index to directly support the query used in https://github.com/cloudquery/cloudquery/blob/f649bed8f631e322862b6bc536e0644ad1368f7b/plugins/destination/postgresql/client/delete.go#L18-L25

This is not a generic request from the SDK to create indexes, since the SDK or source plugin is not responsible for the design of this `delete` query. The query is defined in `plugins/destination/postgresql/client/delete.go`, so the matching index will created in `plugins/destination/postgresql/client/migrate.go`.

Supporting indexes for other columns via the SDK would be an interesting discussion, but beyond the scope here.
