### ISSUE TITLE
test: Add tests on multiple OS

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1803]
Since we support MacOS, Linux and Windows we should add sanity tests on each OS

**Comment by yevgenypats** [comment]
In that case, maybe we should just run all unit-tests on all OS  as a matrix?

**Comment by erezrokah** [comment]
> In that case, maybe we should just run all unit-tests on all OS as a matrix?

Yeah I'm assuming only the CLI unit tests. I think this means we'll need a separate workflow file as now we run tests the same way for all modules https://github.com/cloudquery/cloudquery/blob/14d2ca6894bdf51597082fbadd1aad7401316e59/.github/workflows/test_unit.yml#L21.

The challenge is setting up docker on MacOS, I'm trying with https://github.com/docker-practice/actions-setup-docker which [seems to time out after 10m](https://github.com/cloudquery/cloudquery/actions/runs/3077855910).
