### ISSUE TITLE
feat: Add list secrets for vault

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#18040]
### Which problem is this feature request solving?

Customers requests to add https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v1 to the [vault](https://hub.cloudquery.io/plugins/source/cloudquery/vault/latest/docs) plugin to be able to see which secrets are available and what are their expiration/renew date (we want only to fetch secret metadata and not the secret itself of course)

### Describe the solution you'd like

-

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
adding some more feedback. Seems there are two versions of the API that we want to support and either support it in a new plugin `vault_v2` or just have more tables in the same plugin starting with `vault_v2`.

in `vault_v1`  to read the metadata one needs to read the secret https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v1#read-secret we just won't store it and only store the metadata while in `vault_v2` there is a special endpoint to read the metadata


https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v1
https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2

**Comment by erezrokah** [comment]
Opened a PR in https://github.com/cloudquery/cloudquery-private/pull/2571/files (internal repo). We don't need a separate plugin as it looks that secrets is the only API that has v1 + v2. The tricky part was the need to recursively list all secrets starting from listing mounts, then going down the path hierarchy. Couldn't find a better way to do it

**Comment by erezrokah** [comment]
Released in https://hub.cloudquery.io/plugins/source/cloudquery/vault/v2.3.0/versions
