### ISSUE TITLE
Integrate with Azure Web App Service Auth settings

### ISSUE THREAD

**Issue by kvish** [cloudquery/cloudquery#1810]
### Why do you need this resource or plugin? Please describe.
 https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/get-auth-settings-v2-without-secrets
 
 USe web app v2 api to get auth settings without secrets

### Describe the solution you'd like

We want to track if auth is enabled on the web app service to ensure least privilege.

**Comment by erezrokah** [comment]
Thanks for the issue @kvish, please let me know if https://github.com/cloudquery/cloudquery/pull/3269 is what you had in mind
