### ISSUE TITLE
bug: ORACLE plugin: no IP address info in oracle_virtualnetwork_ephemeral_public_ips and oracle_virtualnetwork_reserved_public_ips resource table

### ISSUE THREAD

**Issue by gianluca-ava** [cloudquery/cloudquery#18114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

oracle_virtualnetwork_ephemeral_public_ips and oracle_virtualnetwork_reserved_public_ips resource tables don't list the IP address information.

### Expected Behavior

IP address must be listed in oracle_virtualnetwork_ephemeral_public_ips and oracle_virtualnetwork_reserved_public_ips resource tables

### CloudQuery (redacted) config

```kind: source
spec:
  # Source spec section
  name: drcc
  path: "cloudquery/oracle"
  version: "v6.3.0"
  tables: ["*"]
  skip_tables:
    - "oracle_compute_images"
    - "oracle_compute_vnic_attachments"
    - "oracle_virtualnetwork_fast_connect_provider_services"
    - "oracle_networkfirewall_network_firewall_policies"
    - "oracle_networkfirewall_network_firewalls"
    - "oracle_networkfirewall_work_requests"
    - "oracle_networkloadbalancer_work_requests"
  destinations: ["postgresql"] 
  spec:
    concurrency: 500
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v8.0.6"
  spec:
    write_mode: "overwrite-delete-stale"
    connection_string: "postgresql://gamadm:${password}@${host}:${port}/${database}?sslmode=require"
```

### CloudQuery (redacted) logs

> {"level":"info","module":"cli","invocation-id":"52083978-43a3-4800-b06d-7f0ad9aed4a8","client":"xxx","errors":0,"invocation_id":"52083978-43a3-4800-b06d-7f0ad9aed4a8","message":"table` sync finished","module":"oracle-source","resources":0,"table":"oracle_virtualnetwork_ephemeral_public_ips","time":"2024-06-03T12:01:50Z"}

### CloudQuery version

5.20.3

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by savme** [comment]
This is fixed in [v7.0.0](https://hub.cloudquery.io/plugins/source/cloudquery/oracle/v7.0.0)

**Comment by gianluca-ava** [comment]
@savme, I run the v.7.0.0 but I don't see any IP attribute

**Comment by savme** [comment]
@gianluca-ava which tables did you check? Also, do you have data in the `oracle_virtualnetwork_assigned_public_ips` table? Are the IPs you expect to see in the tables assigned to an instance?

**Comment by gianluca-ava** [comment]
@savme, sorry for the delay but I didn't see your question...
I've data in oracle_virtualnetwork_assigned_public_ips but not the ip.
I just found the public IP into oracle_compute_vinics table but I'm not sure it will cover every public ip's

**Comment by savme** [comment]
@gianluca-ava no worries. We made some further changes to the way we handle IPs in [v7.0.4](https://hub.cloudquery.io/plugins/source/cloudquery/oracle/latest/versions#7.0.4-(2024-07-03)). It would be great if you could try syncing using this version (or a newer one) of the plugin and let me know if the data looks correct.

I'll reopen the issue if something is missing.

**Comment by gianluca-ava** [comment]
@savme: thanks, I will run the new version in the next days

**Comment by gianluca-ava** [comment]
@savme: I run the last version but I don't see any change in:
- oracle_virtualnetwork_ephemeral_public_ips
- oracle_virtualnetwork_reserved_public_ips
- oracle_virtualnetwork_assigned_public_ips

**Comment by savme** [comment]
OK, I see, thanks for trying this version! I'm reopening the issue

**Comment by murarustefaan** [comment]
Hey @gianluca-ava, thanks for reporting this again and for your interest in the Oracle plugin.

[v7.2.x](https://hub.cloudquery.io/plugins/source/cloudquery/oracle/latest/versions#7.2.0-(2024-07-30)) added new tables as well as column changes to existing `ips` tables.
Would you mind giving that a try and sharing some feedback with us afterwards?

Closing this issue for now, feel free to reopen if needed.
Thanks!

**Comment by gianluca-ava** [comment]
@murarustefaan: with the late version I see the ip_address attribute on the 3 tables.
