### ISSUE TITLE
EC2 Reserved Instances

### ISSUE THREAD

**Issue by pseymournutanix** [cloudquery/cloudquery#1815]
### Is your feature request related to a problem? Please describe.
I would like to determine reserved EC2 (not Elasticcache) instances and numbers etc.

### Describe the solution you'd like
Details of EC2 reserved instances. If this exists and I have missed it - apologies.

### Describe alternatives you've considered
Using the AWS CLI for example:-
```
aws ec2 describe-reserved-instances
```
Shows the details not sure if this can be tied in with instances etc.

Thanks.

**Comment by hermanschaaf** [comment]
Thanks for reporting this @pseymournutanix! And apologies for the delay in getting back to you, we are hard at work getting a new v2 version ready for release.

It seems that you are right: we are missing information about reserved instances right now. Here is an in-progress PR to add it, currently planned for post-v2. Feel free to comment and/or track progress there: https://github.com/cloudquery/cloudquery/pull/1912
