### ISSUE TITLE
bug: bitbucket plugin misleading installation docs

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#18162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://hub.cloudquery.io/plugins/source/cloudquery/bitbucket/latest/docs tells us to use:
```yaml
  registry: docker
  path: ghcr.io/cloudquery/cq-source-bitbucket:v1.3.0
```

and results in:
> Error: failed to pull Docker image: Error response from daemon: manifest unknown

### Expected Behavior

it should be:
```yaml
  path: cloudquery/bitbucket
  version: v1.3.0
```

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
I believe `docker.cloudquery.io/cloudquery/cq-source-bitbucket:v1.3.0` should also work
