### ISSUE TITLE
bug: `--log-console` is broken on CLI version `v5.20.4`

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#18160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `--log-console` exits with an error `Error All attempts fail:\n#1: failed to copy body to file ...  write /dev/stdout: file already closed`

### Expected Behavior

Not error and CLI command works

### CloudQuery (redacted) config

```yaml
kind: source
spec:
  name: "gcp"
  path: "cloudquery/gcp"
  version: "v14.0.0"
  destinations: ["postgresql"]
  tables: ["*"]
---
kind: destination
spec:
  name: "postgresql"
  path: "cloudquery/postgresql"
  version: "v8.0.4"
  migrate_mode: "forced"
  spec:
    connection_string: "postgresql://postgres:pass@localhost:5432/postgres?sslmode=disable"

```

### Steps To Reproduce

1. `cloudquery plugin install spec.yml --log-console ` 

With the spec.yml above

### CloudQuery (redacted) logs

```
2024-06-06T08:15:06Z INF Loading spec(s) args=["examples/gcp-postgres.yml"] invocation-id=a21036eb-2856-4d1e-8ae7-91fbbd532a31 module=cli
Error: failed to download plugin: failed downloading URL "https://assets.cloudquery.io/cq-cloud-releases/cloudquery/source/gcp/v14.0.0/darwin_arm64". Error All attempts fail:
#1: failed to copy body to file .cq/plugins/source/cloudquery/gcp/v14.0.0/plugin.zip: write /dev/stdout: file already closed
2024-06-06T08:15:07Z ERR exiting with error error="failed to download plugin: failed downloading URL \"https://assets.cloudquery.io/cq-cloud-releases/cloudquery/source/gcp/v14.0.0/darwin_arm64". Error All attempts fail:\n#1: failed to copy body to file .cq/plugins/source/cloudquery/gcp/v14.0.0/plugin.zip: write /dev/stdout: file already closed" invocation-id=a21036eb-2856-4d1e-8ae7-91fbbd532a31 module=cli
```

### CloudQuery version

v5.20.4

### Additional Context

Could be related to https://github.com/cloudquery/plugin-pb-go/pull/332 or https://github.com/cloudquery/plugin-pb-go/pull/330

### Pull request (optional)

- [X] I can submit a pull request

**Comment by disq** [comment]
https://github.com/cloudquery/plugin-pb-go/pull/336
https://github.com/cloudquery/cloudquery/pull/18161
