### ISSUE TITLE
feat(getting-started): Auto select guide based on OS

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1821]
When navigating to https://docs.cloudquery.io/docs/getting-started/getting-started-with-aws (or any other getting started guide), under [download and install](https://docs.cloudquery.io/docs/getting-started/getting-started-with-aws#download-and-install) the selected command is for Linux.

It would be nice to default to the OS relevant guide

**Comment by cqgaurav** [comment]
Perhaps even a copy button for the lazy folks out there

**Comment by yevgenypats** [comment]
I think for starters we can do osx as default :)

**Comment by yevgenypats** [comment]
From quick glance that can be non-trivial because of nextra/next/react so we will have to make sure this component also runs on the client as well which can have other weird effect like late loading (which might not be better then quick loading and just default for osx).

**Comment by erezrokah** [comment]
> From quick glance that can be non-trivial because of nextra/next/react so we will have to make sure this component also runs on the client as well which can have other weird effect like late loading (which might not be better then quick loading and just default for osx).

Yeah, we'll need to see how it can be done in Nextra, or maybe there's a way to do it via Vercel (load a different version of the site based on user agent or something like that)
