### ISSUE TITLE
feat(website): Add copy button to code blocks

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1822]
### Is your feature request related to a problem? Please describe.

Extracted from https://github.com/cloudquery/cloudquery/issues/1821 cc @cqgaurav

### Describe the solution you'd like

It would be nice to be able to copy/paste code blocks from the documentation

### Describe alternatives you've considered

Using the mouse cursor to select the code and then copy it

### Additional context

N/A

**Comment by yevgenypats** [comment]
Should be solved now. It is a nextra feature by just adding `copy` to snippets

https://www.cloudquery.io/docs/quickstart#download-cloudquery-cli
