### ISSUE TITLE
Offline mode doesn't work well even if we provide License

### ISSUE THREAD

**Issue by bshinu51** [cloudquery/cloudquery#18236]
Here I see that plugin-sdk validates the license for offline mode - https://github.com/cloudquery/plugin-sdk/blob/83f5124983e9aae8454c3b2c30bb79ff2a0b9e3e/serve/plugin.go#L194

However even with LICENSE and CLOUDQUERY_API_KEY set it stills talks to api for usage data

```
2024/04/19 08:59:39 [DEBUG] GET https://api.cloudquery.io/teams/<our-team>/usage/cloudquery/source/azure
```

**Comment by erezrokah** [comment]
Closing as stale per lack of response. @bshinu51 if this still happens please provide the information from our [bug reporting template](https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E) so we reproduce it
