### ISSUE TITLE
Include Policies in Release Assets

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1827]
Users should be able to download a specific version of a policy using a `curl` or `wget` command without having to do a git clone

**Comment by erezrokah** [comment]
Users can curl the direct GitHub link e.g `https://raw.githubusercontent.com/cloudquery/cloudquery/main/plugins/source/azure/policies/policy.sql` for a single file, however I can't think of an easy way to download the directory

**Comment by erezrokah** [comment]
This was resolved in https://github.com/cloudquery/cloudquery/pull/1991. Please re-open if we need to discuss this further
