### ISSUE TITLE
feat: complete load balancer resource tables in GCP (gcp_compute_target_https_proxies)

### ISSUE THREAD

**Issue by AviKozokin** [cloudquery/cloudquery#18297]
### Which problem is this feature request solving?

Hi
The list of resource tables specified in the issue https://github.com/cloudquery/cloudquery/issues/13443 specifying GCP tables involved in load balancing in GCP is missing `gcp_compute_target_https_proxies`.
(`gcp_compute_target_http_proxies` are for http only proxies, whereas `gcp_compute_target_ssl_proxies` are for Network Load Balancing)

From google doc reference.

https://cloud.google.com/compute/docs/reference/rest/v1/targetSslProxies
https://cloud.google.com/compute/docs/reference/rest/v1/targetHttpsProxies
https://cloud.google.com/compute/docs/reference/rest/v1/targetHttpProxies

### Describe the solution you'd like

defining the table gcp_compute_target_https_proxies in GCP source

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by murarustefaan** [comment]
Hey @AviKozokin , 

We implemended some more load balancer resource tables as part of our latest v15.9.0 release of the GCP plugin.
https://hub.cloudquery.io/plugins/source/cloudquery/gcp/latest/docs

Let us know of any feedback you might have!
