### ISSUE TITLE
Re-add https://github.com/cloudquery/cq-provider-sdk/pull/453 after cqv2 is released.

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#1833]
Here to make sure I don't forget to do it.

**Comment by yevgenypats** [comment]
@shimonp21 is this still needed?

**Comment by shimonp21** [comment]
It is needed, but not high-priority.
Indeed, we strip timezones if we get a timestamps-with-timezone from upstream.
However, most upstream providers give us timestamps in UTC (which is why it's not high-priority).
I am allergic to timezone-issues, so I would prefer to fix it.
I have an upstanding PR which I will send out for review later.

**Comment by yevgenypats** [comment]
This should be solved by CloudQuery Type System now - https://github.com/cloudquery/plugin-sdk/pull/320
