### ISSUE TITLE
feat: Shopify Shema is fairly old, missing critical new fields and tables

### ISSUE THREAD

**Issue by konung** [cloudquery/cloudquery#18413]
### Which problem is this feature request solving?

I would like to have the ability to specify easily extra tables and/or columns that need to be synced. 

### Describe the solution you'd like

Ability to specify desired tables and columns in the .yml config file for example

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
Hey @konung ! Thanks for reporting this. I'd love to learn more about how you use (or are planning to use) CloudQuery with Shopify. Would you be available for a chat sometime this or next week?

**Comment by konung** [comment]
> Hey @konung ! Thanks for reporting this. I'd love to learn more about how you use (or are planning to use) CloudQuery with Shopify. Would you be available for a chat sometime this or next week?

Hi. 

We are currently evaluating Claude query  against air byte and meltano .

we like the robustness and performance of cloudquery, but it is missing a lot of details for example in Shopify and HubSpot connectors . 

I understand that it might be hard to track all the changes that happen to those apis, so ability to specify additional fields / tables would be the killer feature for us . As for right now while CQ outperforms the other two solutions, it just doesn’t bring all the data

**Comment by maaarcelino** [comment]
Hi @konung, as we haven't heard back from you on this request, I am closing this issue. We are in the process of migrating our Shopify plugin from their REST API to their new GraphQL API and that will bring the table schemas up to date.

If you would like to request that new table resources be added, please reopen this issue with the list of tables.
