### ISSUE TITLE
bug: AWS compliance pack - iam_root_last_used search date comparison

### ISSUE THREAD

**Issue by DanielShepherd-RL** [cloudquery/cloudquery#18420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The date comparison in `macros/iam/iam_root_last_used.sql` is backwards, `<=` instead of `>=`, and it returns results for all users instead of just the root user.

### Expected Behavior

The search should only return results for `root` and the date comparison should hit if the account was used within the last `90 days`.

### CloudQuery (redacted) config

NA

### Steps To Reproduce

Run any of the searches in `macros/iam/iam_root_last_used.sql` against an AWS dataset and it will return incorrect pass/fail statuses and users that aren't root.

### CloudQuery (redacted) logs

NA

### CloudQuery version

5.23.4

### Additional Context

AWS Compliance Premium v1.12.2

```diff
  {% macro athena__iam_root_last_used(framework, check_id) %}
  select
    '{{framework}}' as framework,
    '{{check_id}}' as check_id,
    'Eliminate use of the ''root'' user for administrative and daily tasks' as title,
    SPLIT_PART(arn, ':', 5) as account_id,
    arn as resource_id,
    case 
-    when CAST(password_last_used AS DATE) <= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
+    when CAST(password_last_used AS DATE) >= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
-    when CAST(access_key_1_last_used_date AS DATE) <= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
+    when CAST(access_key_1_last_used_date AS DATE) >= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
-    when CAST(access_key_2_last_used_date AS DATE) <= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
+    when CAST(access_key_2_last_used_date AS DATE) >= (CURRENT_DATE - INTERVAL '90' DAY) then 'fail'
    else 'pass'
    end as status
    from aws_iam_credential_reports
+  where user = '<root_account>'
  {% endmacro %}
```

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by ronsh12** [comment]
Fixed, thanks for reviewing.

**Comment by k-rheinheimer** [comment]
closed with https://github.com/cloudquery/policies-premium/pull/937
