### ISSUE TITLE
bug: GCP recommender (15.5.0) not downloading all the recommenders available on google docs

### ISSUE THREAD

**Issue by pnadiminti** [cloudquery/cloudquery#18556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have used the GCP Source Plugin of Version v15.5.0 to download all the GCP Recommender data advising by Google as shown in the below doc.

https://cloud.google.com/recommender/docs/recommenders

However, we are getting only 2 recommender's data in the table 'gcp_recommendations_projects', i.e., google.compute.address.IdleResourceRecommender, google.compute.image.IdleResourceRecommender

it would be good if you could support all the 'cost' recommenders as per Google doc and along with it in the performance area google.compute.instanceGroupManager.MachineTypeRecommender, google.compute.instance.MachineTypeRecommender, google.cloudfunctions.PerformanceRecommender

### Expected Behavior

It should download all the major recommenders available in the documentation.

### CloudQuery (redacted) config

kind: source
spec:
  name: "gcp"
  path: "cloudquery/gcp"
  version: "v15.5.0"
  tables: 
    # compute engine related tables.
    - gcp_recommendations_projects
  destinations: ["postgresql"]
  spec:
    project_ids: ["test-project"]
    
    service_account_key_json: '${file:service_account.json}'

### Steps To Reproduce

1. Integrate the above GCP configuration.
2. Make sure the service account has an inbuilt GCP Role attached called 'Recommender Viewer'.
3. Make sure you are reachable to database configured.
4. perform cloudquery sync aws.yml postgres.yml
5. Login to the Postgres db and do select * from gcp_recommendations_projects;
6. it will list down all the recommendations.
7. make the following distinct query on the gcp_recommendations_projects table.

SELECT
    distinct((string_to_array(name , '/'))[6]) AS recommendrer_type
FROM
    gcp_recommendations_projects;

### CloudQuery (redacted) logs

Logs Not available.

### CloudQuery version

5.5.5

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by murarustefaan** [comment]
Hey @pnadiminti, would you mind testing with `v15.7.0`? 
We fixed an issue where only global recommendations were synced, rather regional & zonal ones.
