### ISSUE TITLE
Add AWS ELBv2 Attributes

### ISSUE THREAD

**Issue by hobietje** [cloudquery/cloudquery#187]
The AWS ELBv2 Resources do not currently include the attributes.  These include important settings for security compliance, including access logging, WAF, delete protection, etc.

Would love to see these added...

https://docs.aws.amazon.com/cli/latest/reference/elbv2/describe-load-balancer-attributes.html

**Comment by yevgenypats** [comment]
Thanks! This definitely looks useful and should be relatively straight forward. We will prioritize it and add it in the next couple of weeks.

**Comment by hobietje** [comment]
Thanks @yevgenypats.  Apologies for adding issue on this repo btw, should have added it on `cq-provider-aws` instead.
