### ISSUE TITLE
Default Values in Config Are ignored

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#1884]
When a user doesn't set a value we chose default values that differed from the AWS SDK. We either need to get this `default` working or change the documentation to show we are deferring to AWS for the default values (ie 3 retries and 10 s for backoff)

```
	MaxRetries   int       `json:"max_retries,omitempty" default:"10"`
	MaxBackoff   int       `json:"max_backoff,omitempty" default:"30"`
```

**Comment by yevgenypats** [comment]
we should use the `default` library and just use a default function that sets any default.
