### ISSUE TITLE
CLI should exit gracefully if plugin exits with error code

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#1887]
Currently, if the underlying plugin fails during `sync` or `gen`, the CLI outputs that the plugin exited with exit code 1, but doesn't exit itself. This could be an issue in automated environments, where the container would simply keep hanging. We should detect when plugins fail and exit if it is not unrecoverable, similar to how we exit if the plugin is not reachable initially.

**Comment by sdunnedeloitte** [comment]
We're also experiencing this issue. We are running fetches in ephemeral containers driven by Step Functions and the Exit1 is causing the container to fail with an error which is failing our Step Function. It would be great if we could have a little more control over when an Exit 0 or 1 is issued? In a lot of cases we don't mind some level of fetch failure (e.g. an IAM role might not have permission to fetch from a certain region etc.) but we wouldn't consider that a container level failure, more an informational issue. Perhaps adding a flag to cloudquery fetch (e.g. --ignore-minor-errors) could be an easy workaround to fix this issue in automation scenarios?

**Comment by yevgenypats** [comment]
@sdunnedeloitte thanks for reporting!  I think this should be fixed now, and information related errors should never fail the sync information and only write to the logs. If it still happens would love to know the reason so we can handle that.

**Comment by alanjoseuk** [comment]
@yevgenypats Thanks for the update. Could you please confirm the version to which this fix was made? I am using version 0.32.12.

**Comment by hermanschaaf** [comment]
I believe this issue has been fixed through a number of recent changes. I tested the latest version ([v1.0.7](https://github.com/cloudquery/cloudquery/releases/tag/cli-v1.0.7)) and could not reproduce it either by forcing a panic in the source plugin or by ctrl+c'ing the plugin process while a sync was running. In both cases the CLI exited with an appropriate message and error code.

If you are experiencing this issue, please try upgrading to the latest versions of the CLI and plugins. 

I think this was probably the main fix https://github.com/cloudquery/plugin-sdk/pull/257 but there were many other bugfixes over the last couple of weeks that have contributed too.
