### ISSUE TITLE
Add a security policy to the repository

### ISSUE THREAD

**Issue by neilnaveen** [cloudquery/cloudquery#190]
It is recommended to have a security policy https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by bbernays** [comment]
With the GitHub automation tool that @yevgenypats created we can make this file once and distribute to all of our repos

**Comment by yevgenypats** [comment]
This is done now via https://github.com/cloudquery/cloudquery/security/policy

and github org level files https://github.com/cloudquery/.github/blob/main/SECURITY.md
