### ISSUE TITLE
Support for AWS KMS Key Grants

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#1906]
### Why do you need this resource or plugin? Please describe.
To add additional context and awareness of access to AWS KMS Keys.

### Describe the solution you'd like
An ability to query and find active KMS Key Grants on KMS Keys, as this is one possible mechanism for KMS Key Access.

https://docs.aws.amazon.com/kms/latest/developerguide/grants.html

**Comment by disq** [comment]
Looks like `ListGrants`
