### ISSUE TITLE
feat: Support primary keys on Snowflake destination plugin

### ISSUE THREAD

**Issue by Vittitow** [cloudquery/cloudquery#19170]
### Which problem is this feature request solving?

Today, the Snowflake destination plugin does not create primary keys for tables. Which means `write_mode: overwrite-delete-stale` always creates new records instead of upserting on the primary key. Additionally, when using `write_mode: overwrite` duplicate records are created rather than them being overwritten on primary key.

### Describe the solution you'd like

When creating/migrating tables, the snowflake destination plugin should create the proper primary keys on the table like it does for postgres, sqlite etc.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by Vittitow** [comment]
Additionally when using incremental tables and the state backend in snowflake, duplicate key value pairs are created rather than them being updated due to the lack of constraint.

**Comment by bbernays** [comment]
I think that our documentation can be greatly improved with regards to how different write modes are supported for Snowflake, but until Hybrid tables are GA, there is no reason to set Primary Keys for Snowflake tables as they are documented to not be enforced. We also might even be able to support writing to a temp table then doing a merge to handle in place updates.

https://docs.snowflake.com/en/sql-reference/constraints-overview

**Comment by Vittitow** [comment]
We just spent a significant amount of time and resources migrating all of our cloudquery syncs from postgres to snowflake to find out that the write modes work differently and now all of our data is bad. Now we're going to have to spend even more time and resources migrating back to postgres... To say the documentation could be significantly improved is an understatement.

**Comment by bbernays** [comment]
@Vittitow - We have fixed this issue by properly handling updates in `overwrite` and `overwrite-delete-stale` in `v4.3.0` of the snowflake destination plugin

**Comment by Vittitow** [comment]
> @Vittitow - We have fixed this issue by properly handling updates in `overwrite` and `overwrite-delete-stale` in `v4.3.0` of the snowflake destination plugin

Thank you for the quick turnaround. Does this also handle setKey on incremental tables as well so the key value pairs won't be duplicated? If unsure we'll test either way.

**Comment by Vittitow** [comment]
@bbernays fyi the push to hub failed https://github.com/cloudquery/cloudquery/actions/runs/10924144967/job/30322475643

**Comment by bbernays** [comment]
We are looking into the deployment now. As for the `Incremental` `setkeys` looking into that as well. In the meantime you can actually continue to use your Postgres DB as a state backend while storing data in Snowflake [here is an example](https://docs.cloudquery.io/docs/advanced-topics/managing-incremental-tables)

**Comment by bbernays** [comment]
The new version is available on the hub now: https://hub.cloudquery.io/plugins/destination/cloudquery/snowflake/v4.3.0/docs

**Comment by bbernays** [comment]
@Vittitow - The `SetKey` should also be fixed in that values should not be duplicated, but I will test it out and verify that before closing this issue

**Comment by Vittitow** [comment]
@bbernays I've tested successfully locally for overwrite, overwrite-delete-stale and incremental tables. All looks good to me. Will follow up if we run into issues once we get our pipeline updated to use the new version. Thank you again for the quick resolution.
