### ISSUE TITLE
Bug(v2): Plugin output interleaved with CLI output

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#1920]
### Describe the Bug

```
curl -L https://github.com/cloudquery/cloudquery/releases/download/cli/v0.33.1-pre.0/cloudquery_darwin_arm64 -o cloudquery
chmod a+x cloudquery
./cloudquery gen source azure@v0.14.0-pre.0
./cloudquery sync "."
```

See video:

https://user-images.githubusercontent.com/26760571/191495062-7ee8b907-e585-4487-9630-95aa4e44a80c.mov

### Expected Behavior

Maybe dump plugin output to a file?

### CloudQuery Version

`cloudquery version 0.33.1-pre.0`

**Comment by yevgenypats** [comment]
Seems it's my debug output that I forgot to remove. pushing a fix right now.
