### ISSUE TITLE
Support for Okta groups and applications

### ISSUE THREAD

**Issue by flyingh0rse** [cloudquery/cloudquery#1923]
### Is your feature request related to a problem? Please describe.

I'm using Okta as an SSO for accessing into AWS. Cloudquery only provides one table `okta_users` - https://github.com/cloudquery/cloudquery/blob/main/plugins/source/okta/docs/tables/okta_users.md. Theres currently no support for Okta groups & applications that I can utilize.

### Describe the solution you'd like

The solution would include new tables to gather information about:
- okta groups
- okta applications

These tables will have the cq_id of the users present in `okta_users` table using which I can correlate Okta.

### Describe alternatives you've considered

I tried using Steampipe's capabilities and it is working fine to fetch data - https://hub.steampipe.io/plugins/turbot/okta/tables. However, I am querying two different places - steampipe and then cloudquery using a python script for correlation. I have implemented CQ for most of my projects after reading the blog post https://badshah.io/cloudquery-vs-steampipe/ so having new okta tables will help get and correlate data from single place.

**Comment by disq** [comment]
This was released in okta v1.3.0 https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-okta-v1.3.0
