### ISSUE TITLE
feat: When syncing, I should be notified if my plugins are out of date

### ISSUE THREAD

**Issue by jsifuentes** [cloudquery/cloudquery#19286]
### Which problem is this feature request solving?

As I've gone on and off with giving attention to how I use CloudQuery, I've noticed that I am never really aware when I am using a version of a source plugin that may be significantly out of date.

### Describe the solution you'd like

When using `cloudquery sync`, the versions of the plugins I am using from the cloudquery registry should be version checked against the registry to see if I am out of date, and I should be alerted with a warning at the beginning of the sync process.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by marianogappa** [comment]
@jsifuentes thank you for raising this issue! A fix for it has been merged https://github.com/cloudquery/cloudquery/pull/19376 and it has just been released: https://github.com/cloudquery/cloudquery/releases/tag/cli-v6.9.0
