### ISSUE TITLE
Case Studies Page is opening in new tab when clicked 

### ISSUE THREAD

**Issue by adam-cobb532** [cloudquery/cloudquery#19561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on 'Case Studies' in the Resources drop-down nav, it opens the page in a new tab - this behaviour is a hangover from when the 'Case Studies' were located on the Docs website.

### Expected Behavior

The page should open in the current tab.

### CloudQuery (redacted) config

N/A

### Steps To Reproduce

Click on the 'Case Studies' link in the Resources drop-down menu

### CloudQuery (redacted) logs

N/A

### CloudQuery version

N/A

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Fixed by https://github.com/cloudquery/frontend/pull/1632
