### ISSUE TITLE
AWS Systems Manager Review and Capabilities Support

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#1983]
### Why do you need this resource or plugin? Please describe.
Currently, CloudQuery supports the following SSM resources in tables: aws_ssm_documents, aws_ssm_instance_compliance_items, aws_ssm_instances, aws_ssm_parameter_policies, and aws_ssm_parameters

### Describe the solution you'd like
Would be good to review Systems Manager capabilities, the coverage, and validate the list of resources we need to cover for better coverage (or at least a prioritized list) of Systems Manager's capabilities.

**Comment by cqgaurav** [comment]
Closing this as done in the previous iteration, please reopen if needed
