### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by naga-8790** [cloudquery/cloudquery#19973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CloudQuery (redacted) config

# Example Config
<redacted-config-content>

### CloudQuery (redacted) logs

<trimmed-log-content>

### CloudQuery version

CloudQuery version: <version>

### Pull request (optional)

- [X] I can submit a pull request

**Comment by bbernays** [comment]
Closing as it is an empty issue
