### ISSUE TITLE
Region in GCP Resource View

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2021]
GCP APIs return the region in which a resource is located in the form: `https://www.googleapis.com/compute/v1/projects/${PROJECT_ID}/regions/${REGION_NAME}`. This means that users cannot aggregate or group on a regional basis as inherently the grouping will be project + region… Here is the same query but parses the region out from the entire url: https://gist.github.com/bbernays/67be1c9aa2cc4410c1308f880a543ba0

Should CloudQuery adopt this more transformed version of the query or stick with the default values that GCP APIs are returning?

**Comment by erezrokah** [comment]
Closing as stale. If relevant the policies team can re-open when they add this transformation
