### ISSUE TITLE
v1: JSON columns should document their structure when possible

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2023]
With the move to v2, we now have many JSON columns that were relational tables before. With this move however, we have lost some documentation around the available fields in these columns. In many cases, we technically have access to this information, because the JSON column is inferred from an underlying Go struct. We should add the necessary metadata to help users understand the contents of these columns, and help document when changes to them are made.

**Comment by erezrokah** [comment]
Great point, we could do this based on the struct or even based on the fetched object.
Probably there's a way to generate a JSON schema from a struct/instance

**Comment by yevgenypats** [comment]
I would say this is a low priority as anyone writing queries anyway does it with real data, so would push this forward until this becomes a more requested feature as this can also become quite complex.

**Comment by erezrokah** [comment]
Closing as done, `cloudquery tables --format json` command will now also print `type_schema` where applicable for JSON columns (for plugins released on July 25 or after). `type_schema` is a valid JSON string representing the JSON data type
