### ISSUE TITLE
Bug(v2): ARNs were removed on several AWS tables

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2029]
We should add ARNs back to these tables, or investigate why they were removed and make appropriate fixes:

- `aws_autoscaling_group_scaling_policies`
- `aws_backup_vault_recovery_points`
- `aws_ecs_task_definitions`
- `aws_elasticbeanstalk_environments`
- `aws_fsx_backups`
- `aws_lambda_function_aliases`
- `aws_resourcegroups_resource_groups`
- `aws_xray_sampling_rules`

**Comment by cqgaurav** [comment]
+1 to investigating why these were removed, even if we then decide that the issue is unrelated to the launch

**Comment by hermanschaaf** [comment]
- [x] `aws_autoscaling_group_scaling_policies`: renamed `policy_arn` -> `arn`
- [x] `aws_backup_vault_recovery_points`: renamed `recovery_point_arn` -> `arn`
- [x] `aws_ecs_task_definitions`: renamed `task_definition_arn` -> `arn`
- [x] `aws_elasticbeanstalk_environments`: renamed `environment_arn` -> `arn`
- [x] `aws_fsx_backups`: the `ResourceARN` field was previously named `arn`, but that refers to the resource, not the backup, so we should keep it `resource_arn` and have no `arn` field for backups.
- [x] `aws_lambda_function_aliases`: renamed `alias_arn` -> `arn`
- [x] `aws_resourcegroups_resource_groups`: renamed `group_arn` -> `arn`
- [x] `aws_xray_sampling_rules`: extracted `arn` from `SamplingRule.RuleARN`

FIxed in https://github.com/cloudquery/cloudquery/pull/2099
