### ISSUE TITLE
Nit: Change PR Template

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2030]
The PR template is mostly boilerplate and it's usually bigger then the summary which makes it a bit harder to read when getting the notification in slack. Can we just do something simple as 

```
### Sumary
```

or even better just empty PR template given if someone is contributing he read the contribution guide so no need to link to the contribution guide from every PR (as it's also linked in the GitHub interface on the right side when you open a PR)

**Comment by erezrokah** [comment]
> or even better just empty PR template given if someone is contributing he read the contribution guide so no need to link to the contribution guide from every PR (as it's also linked in the GitHub interface on the right side when you open a PR)

I see the PR template as a summary of the contributing guide with common gotchas, for example I'm sure most contributors will forget to sync docs/run the linter.

I do think we can shorten it, or maybe put some stuff in comments

**Comment by yevgenypats** [comment]
Yeah maybe let's shorten + move to comments. If linters will fail the github action will fail so I think it will be pretty obvious for the reviewrs to see why it fails and also to read the `CONTRIBUTING.md`. Anyway, it is just a nit as Im using a lot the slack github channel for notifications and the boilerplate a lot of time takes more then the summary and either cut off or makes it hard to read.

**Comment by erezrokah** [comment]
> Anyway, it is just a nit as Im using a lot the slack github channel for notifications and the boilerplate a lot of time takes more then the summary and either cut off or makes it hard to read.

Got it, maybe we can also do something about this in the Slack integration
