### ISSUE TITLE
Add documentation regarding AWS IAM Credential Report limitation where applicable for credential report-dependent tables

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#2073]
### Is your feature request related to a problem? Please describe.
AWS only permits generating a credential report as often as once every 4 hours.  Thus, information pulled using AWS Credential Reports can be as old as up to 4 hours depending on when the credential report was generated and may not be up to date as when a CloudQuery user runs cloudquery fetch.

To clarify for cloudquery users, we'd like to add additional information to provide clarity surrounding credential report related information;

### Describe the solution you'd like
Add documentation where appropriate for AWS IAM Credential Report-related resources so cloudquery users are aware of the limitations of Credential Reports and Credential Report information as the data may not match what the Cloudquery user may expect.

### Describe alternatives you've considered
The impending new version of cq will have fixes for certain IAM tables since the new version will introduce credential reports as its own table, separate from other IAM tables such as IAM users.

### Additional context

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html

**Comment by bbernays** [comment]
I agree that we should document this. I think we need to figure out how to document any edge cases for specific resources.

**Comment by bbernays** [comment]
After thinking about it some more, I am not so sure that we need to document this as we are not documenting all of the behaviors of the Cloud Provider... When the credential report was being used as the ListUser call then 100% we should have documented that, but now that the CredentialReport is fully standalone I don't think there is a need to document the 4 hour behavior
