### ISSUE TITLE
Can't get the disable-delete flag to work with fetch

### ISSUE THREAD

**Issue by savvyspoon** [cloudquery/cloudquery#208]
When I try to run the flag disable delete flag or -d  with the fetch command it shows as not a valid option.  This would be a super helpful flag for long term retention of history

cmd/fetch.go

**Comment by roneli** [comment]
Can you tell me what CloudQuery version you are running + the provider version? only the latest versions support this flag.

Just a quick not currently, disable-delete will remove stale data that was fetched previously and didn't return on the new fetch.

**Comment by savvyspoon** [comment]
I'm using 0.15.3

**Comment by savvyspoon** [comment]
CQ 0.15.3  AWS  latest

**Comment by roneli** [comment]
> CQ 0.15.3 AWS latest

Flag is exposed from CQ v0.15.4

**Comment by savvyspoon** [comment]
That did the trick. Sorry, i didnt see the update. Thanks
