### ISSUE TITLE
Chore: Use latest only for CLI releases

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2082]
I think found a hack to use the native interface in github so latest  will show only for CLI releases 
I just released postgresql but the latest is still shown as test  - https://github.com/cloudquery/cloudquery/releases 
Seems that the latest  tag is decided purly based on the tag. If we keep all plugins with 0.x.y  and use for CLI 1.x.y  CLI should always have the latest tag.  

If that's true/makes sense maybe we want to consider that?

**Comment by erezrokah** [comment]
> Seems that the latest tag is decided purly based on the tag. If we keep all plugins with 0.x.y and use for CLI 1.x.y CLI should always have the latest tag.
> 
> If that's true/makes sense maybe we want to consider that?

We should verify it is true first. I think also `latest` doesn't include draft/pre-releases (which is good) so it's not only about the tag. And even with the tags, I think it's based on the timestamp and not the naming:
![image](https://user-images.githubusercontent.com/26760571/192715527-736ad311-d443-4ef5-9cf4-000ac546605b.png)

https://stackoverflow.com/questions/22822586/swap-latest-release-on-github

I'm not sure GitHub takes the trouble of parsing tags and sorting based on SemVer as not everyone uses the same convention for tags.

But we should verify

**Comment by yevgenypats** [comment]
This is solved now via static link/redirect on vercel - https://www.cloudquery.io/docs/quickstart#download-cloudquery-cli
