### ISSUE TITLE
AWS provider - Is not importing ECS information or ECR images

### ISSUE THREAD

**Issue by melaraj2** [cloudquery/cloudquery#21]
I have the generated config for AWS, and I see that ECS and ECR are configured, but after running fetch, no data is in the database for those two services.

**Comment by korsune** [comment]
@melaraj2 I've released a bugfix in [v0.6.1](https://github.com/cloudquery/cloudquery/releases/tag/v0.6.1) which should fix the ECS data. The ECR data is not yet supported (apart from the table creation) - Is this something that you need?

**Comment by melaraj2** [comment]
It would be nice to have the ECR.  We do scan on push, so to query the database to find images that have vulnerabilities would be great!

**Comment by korsune** [comment]
Got it. I'll add the ECR. Just making sure I understand the full picture - you want the `ImageScanFindingsSummary` result from the Rest API to be available in the sql tables right ?

**Comment by melaraj2** [comment]
That would be important as well as the push dates.

**Comment by korsune** [comment]
Added ECRs - let me know if all works as expected on your end:)  https://github.com/cloudquery/cloudquery/releases/tag/v0.6.2
