### ISSUE TITLE
chore: Bring lint docs per plugin back after new CI changes

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2138]
Follow-up
https://github.com/cloudquery/cloudquery/pull/2093

**Comment by erezrokah** [comment]
And probably add codegen diff tests

**Comment by erezrokah** [comment]
And caching due to https://github.com/cloudquery/cloudquery/pull/2140

**Comment by erezrokah** [comment]
I'll close this and open separate issues so we can tag blocking/non blocking ones
