### ISSUE TITLE
GCP Org/Folder Support

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2144]
In V0 users were able to grab projects based on Org or Folder structure. In V1 we only support grabbing projects via `GetProjectsV1`

- We need to enable users to use the `Filter` field to be able to do server side filtering
- Support Org/Folder because `Filter` can only filter on the parent but does not support nested folders

**Comment by cqgaurav** [comment]
@bbernays closing as the Status says done, could you please reopen and specify the scope of remaining work if there is something remaining ?

**Comment by bbernays** [comment]
The following PRs fully implemented the required functionality:
[Org/Folder](https://github.com/cloudquery/cloudquery/pull/2991)
[Server Side Filtering](https://github.com/cloudquery/cloudquery/pull/3170)
