### ISSUE TITLE
Imported Grafana AWS Inventory Dashboard Doesn't Work

### ISSUE THREAD

**Issue by markmishaevcx** [cloudquery/cloudquery#2183]
### Describe the Bug
Hi,
I'm following this tutorial to import AWS cloud inventory dashboard:
https://www.cloudquery.io/blog/open-source-cloud-asset-inventory-with-cloudquery-and-grafana

And importing this dashboard:
https://github.com/cloudquery/dashboards/blob/main/dashboards/aws/aws_asset_inventory.json

After importing the dashboard fails to render with the following error:

Error updating options: e.replace is not a function

### Expected Behavior
Dashboards is rendering as shown in the tutorial
What should have happened?
-->

### CloudQuery Version
cloudquery version 0.32.12

### Grafana Version
8.2.2

**Comment by yevgenypats** [comment]
Hi @markmishaevcx ! We are in the middle of rolling out a complete new version for CloudQuery - https://v1.cloudquery.io/blog/cloudquery-v1-release 

We will take care of this shortly after. Thanks for reporting!
