### ISSUE TITLE
Bug(CLI): CLI doesn't work on Windows

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2206]
This is basically the same bug as https://github.com/cloudquery/cloudquery/pull/1894.

Detected via https://github.com/cloudquery/cloudquery/pull/2204.

I believe the bug is now in the code that was moved to the SDK via https://github.com/cloudquery/plugin-sdk/pull/208, specifically the path in the zip is in-correct on Windows:
https://github.com/cloudquery/plugin-sdk/blob/11b75eb17b7cee0dfb2d56e48597f01840f01c5c/clients/download.go#L54

**Comment by yevgenypats** [comment]
Seems we had another issue. looks like it is still mostly on the SDK side so Im not sure if we will be able not to have cross platform tests on the SDK - https://github.com/cloudquery/plugin-sdk/pull/246

**Comment by erezrokah** [comment]
Better described in https://github.com/cloudquery/plugin-sdk/issues/245

**Comment by erezrokah** [comment]
> Seems we had another issue. looks like it is still mostly on the SDK side so Im not sure if we will be able not to have cross platform tests on the SDK - [cloudquery/plugin-sdk#246](https://github.com/cloudquery/plugin-sdk/pull/246)

After fixing the download issue, the tests experienced the same issue @amanenk had (hanging on Windows)
