### ISSUE TITLE
Bug(CLI): No progress bar when downloading plugins

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2221]
### Describe the Bug

Related to https://github.com/cloudquery/plugin-sdk/issues/222.

The CLI doesn't show progress when downloading plugins and creates the impression is just hangs for a bit before starting (depending on your internet speed).

This could be achieved by passing a writer here https://github.com/cloudquery/cloudquery/blob/1af9ec438770ff660ed1141c6e43b5b02426a01a/cli/cmd/sync.go#L69

### Expected Behavior

Show progress bar when downloading plugins

### CloudQuery Version

v1-pre-release

### Steps to Reproduce

Try the v1 pre-release with any big plugin like AWS.

**Comment by amanenk** [comment]
It seems that the issue is already solved: 
![image](https://user-images.githubusercontent.com/20381690/194028783-a9936131-3213-40f7-8c3c-16fcb1c1a377.png)

**Comment by erezrokah** [comment]
Fixed in https://github.com/cloudquery/plugin-sdk/pull/238
