### ISSUE TITLE
Feature request: Equinix Metal

### ISSUE THREAD

**Issue by vielmetti** [cloudquery/cloudquery#224]
Hi, we have an API for Equinix Metal at https://metal.equinix.com/developers/api/ and I'd love to have a conversation about getting CloudQuery running to query our infrastructure.

**Comment by candiduslynx** [comment]
Go SDK: https://github.com/equinix-labs/metal-go

**Comment by yevgenypats** [comment]
Hi @vielmetti - if still relevant and you are interesting in developing and selling via our hub/marketplace (https://hub.cloudquery.io) reach out here - https://docs.cloudquery.io/register-for-marketplace
