### ISSUE TITLE
Feature Request: Historical records

### ISSUE THREAD

**Issue by somerska** [cloudquery/cloudquery#228]
It would be significantly more useful/powerful if I can see how resources are trending. This feature request is for CQ to not delete records when fetch is ran (or at least allow for a flag to control the behavior) and also to include a column for a date time field on the table(s).   Please thumb up if you would like to see this feature in CloudQuery.

**Comment by roneli** [comment]
History support added from v0.17.0! Check out how to configure [here](https://docs.cloudquery.io/docs/cli/history/configuration)
