### ISSUE TITLE
Add AWS ECS Services Structure

### ISSUE THREAD

**Issue by melaraj2** [cloudquery/cloudquery#23]
For compliance purposes, it's important to pull down all of the AWS ECS Services and details. Mainly you need to get the list of services for each cluster API - (API ECS list-services).  Then the service's details for each API (ECS describe-services).

The most important items for services details are:
networkConfiguration section 
including SecurityGroup Id,
subnets

loadbalancers section:
target ARN (You also need a structure for target groups.  This is the link between a service and the load balancer it uses.)

With the information above, you can run a query to find which service is exposed privately, or publically with what security group rules.

**Comment by korsune** [comment]
@melaraj2 Thanks for creating this! I've added ECS details in [v0.6.7](https://github.com/cloudquery/cloudquery/releases/tag/v0.6.7). I'd appreciate if you can test it and if you can also share the SQL query so the community can re-use it.

**Comment by melaraj2** [comment]
It is almost there.  We are missing the target group which attaches to load balancer.

A service is associated with a large group and a target group is associated with a load balancer.  I couldn't find that association.

**Comment by korsune** [comment]
column `target_group_arn` exists in `aws_ecs_service_load_balancers` do you mean the target group itself is missing?

**Comment by melaraj2** [comment]
Correct.  You need the target group's detailed information which will include a link to elbv2.

**Comment by yevgenypats** [comment]
so do you mean you want to add another table to `elbv2` which will have output from `DescribeTargetGroups` ? this way you will be able to join?

**Comment by korsune** [comment]
@melaraj2 I've added `aws_elbv2_target_groups` and `aws_elbv2_target_group_load_balancer_arns` in [v0.6.8](https://github.com/cloudquery/cloudquery/releases/tag/v0.6.8). Let me know if this works?

**Comment by melaraj2** [comment]
I see the new tables, and that would work, but they did not fill in with any data.

**Comment by korsune** [comment]
I think you might need to delete `config.yml` and re-run `./cloudquery gen config aws`

**Comment by korsune** [comment]
Closing this issue as I think it is solved. If not let me know and I'll re-open.

**Comment by dan-compton** [comment]
Does this include NLBs and ALB as well?  The practical data here is important as well. I'd be highly interested not just in the state of the UCS service and task groups but also placement constraints as well as specific cloud watch metrics though I'm not sure if you're pulling those yet.

Here's two true life use cases. The first involves a discovery regarding your ECS cluster. All ACS clusters have been provisioned in an identical way and therefore clusters are not utilized equally across environments. Specific clusters are dedicated to k streams jobs which must have special constraints around deployment to ensure that they are able to rebuild their state stores following failure or redeploy. A company wants to consolidate its infrastructure and do so through the analysis of these clusters and the combination of them with placement constraints and other details in mind.
