### ISSUE TITLE
AWS AppStream Resources

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#2302]
### Why do you need this resource or plugin? Please describe.
AppStream is a broad service with many different parts. Bolded likely most important?

https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/

- DescribeAppBlocks 
- DescribeApplicationFleetAssociations 
- **DescribeApplications** 
- DescribeDirectoryConfigs 
- DescribeEntitlements   
- **DescribeFleets** 
- DescribeImageBuilders 
- DescribeImagePermissions 
- **DescribeImages** 
- DescribeSessions 
- **DescribeStacks**   
- DescribeUsageReportSubscriptions 
- DescribeUserStackAssociations 
- **DescribeUsers**

[DescribeAppBlocks](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeAppBlocks)	
[DescribeApplicationFleetAssociations](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeApplicationFleetAssociations)	
[DescribeApplications](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeApplications)	
[DescribeDirectoryConfigs](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeDirectoryConfigs)	
[DescribeEntitlements](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeEntitlements)	
[DescribeFleets](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeFleets)	
[DescribeImageBuilders](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeImageBuilders)	
[DescribeImagePermissions](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeImagePermissions)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeImagePermissionsPagesWithContext) )
[DescribeImages](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeImages)	( [Paginator](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeImagesPagesWithContext) )
[DescribeSessions](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeSessions)	
[DescribeStacks](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeStacks)	
[DescribeUsageReportSubscriptions](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeUsageReportSubscriptions)	
[DescribeUserStackAssociations](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeUserStackAssociations)	
[DescribeUsers](https://docs.aws.amazon.com/sdk-for-go/api/service/appstream/#AppStream.DescribeUsers)

### Describe the solution you'd like
Tables for each bolded resource above (extra <3 for all of them)

**Comment by shimonp21** [comment]
@Barneyjm The appstream resources have been released in AWS plugin version `v4.7.0`. You can find the list of tables here: https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/docs/tables.

All described api-calls above were implemented, except `imagePermissions` (Let us know if this repreesents a siginifcant drawback).
