### ISSUE TITLE
Chore: Ensure consistent documentation around version parameter being required now (v1)

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2317]
In v1, `version` is now a required config parameter, and `latest` is not allowed. I think I have fixed many instances where the documentation around this was not consistent with the CLI, but we should check that there are no more discrepancies.

**Comment by yevgenypats** [comment]
Also gave it a quick look. seems solved. If any inconsistencies will come up we will just fix as we go.
