### ISSUE TITLE
CLI: Improve formatting of error output

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2382]
Currently, if the CLI encounters an error in the configuration (or something else) it can output some messages that are not very human-friendly. For example:

```
cloudquery sync cq
Loading spec(s) from cq
Starting sync for:  heroku -> [postgresql]
| Syncing resources... (0/-, 0 resources/hr) [0s] Error: failed to sync source heroku: failed to fetch resources: failed to sync source heroku: failed to fetch resources from stream: rpc error: code = Unknown desc = failed to sync resources: table heroku_add_on_webhook_events cannot be both included and skipped
```

The relevant part for the user in this case is the very last bit: `heroku_add_on_webhook_events cannot be both included and skipped`.

I'm not sure what a reasonable fix will look like here, but maybe a start would be output only the final part of the error to the terminal, and write the rest to the logs:

```
cloudquery sync cq
Loading spec(s) from cq
Starting sync for:  heroku -> [postgresql]
| Syncing resources... (0/-, 0 resources/hr) [0s] 
Error: table heroku_add_on_webhook_events cannot be both included and skipped
```

**Comment by yevgenypats** [comment]
Closing as I think we shouldn't format go errors but a better approach will be having a future validation layer where we can print warnings/errors on each line instead of wrapping/unwrapping/splitting errors - https://github.com/cloudquery/plugin-sdk/pull/272
