### ISSUE TITLE
Mysql driver

### ISSUE THREAD

**Issue by chalkan3** [cloudquery/cloudquery#24]
Error: Error 1059: Identifier name 'accepter_option_allow_egress_from_local_classic_link_to_remote_vpc' is too long

**Comment by korsune** [comment]
@chalkan3 can you please share which MySQL version you are using?

**Comment by korsune** [comment]
I believe this was fixed in (v0.6.6)[https://github.com/cloudquery/cloudquery/releases/tag/v0.6.6]
