### ISSUE TITLE
nothing output to logs

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#2413]
### Describe the Bug
run cq sync
cloudquery.log is created but produces no logging

### Expected Behavior
cloudquery.log is written to while a cq sync is in progress

### CloudQuery Version
cloudquery version 1.0.2
sourcve: aws v1.0.1
destination: postgres v.1.0.0

### Debug Output
n/a

### Steps to Reproduce
run a sync as such:
./cloudquery sync aws-frsq.yml postgres.yml

### References
same issue reported here yesterday:
https://discord.com/channels/872925471417962546/873606591335759872/1026612519550320651

**Comment by amanenk** [comment]
fixed in #2389
