### ISSUE TITLE
poor performance when talking to Postgres over a network

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#2462]
### Describe the Bug
poor performance when talking to Postgres over a network

a very rough, non-scientific, observation/benchmark

CQ running on an m5xl 4 cores, 16 gb memory, 40 gb gp2 ebs
Postgres dockerized locally
pull approx. 700k resources over 10 AWS accounts
time: ~15 minutes

CQ running on the same m5xl 4 cores, 16 gb memory, 40 gb gp2 ebs
Postgres on a t2.small in the SAME REGION and SAME AZ as the ec2 instance where CQ is running
same CQ configs, pull approx. 700k resources over 10 AWS accounts
time: ~30 minutes

CQ running on the same m5xl 4 cores, 16 gb memory, 40 gb gp2 ebs
Postgres on a t2.small in the SAME REGION and DIFFERENT AZ as the ec2 instance where CQ is running
same CQ configs, pull approx. 700k resources over 10 AWS accounts
time: ~45 minutes

CQ running on the same m5xl 4 cores, 16 gb memory, 40 gb gp2 ebs
Postgres on a t2.small in the DIFFERENT REGION as the ec2 instance where CQ is running. (us-east-1 <--> us-west-1)
same CQ configs, pull approx. 700k resources over 10 AWS accounts
time: "forget it, you'll be there forever" :)

### Expected Behavior
in big quotes :)
good/decent performance when pointed at a Postgres over a network, any case where Postgres is not "local"

### CloudQuery Version
CQ=1.0.2
psql plugin = 1.0.0
aws plugin = 1.0.1

### Steps to Reproduce

Also please share any other necessary configuration files
-->

**Comment by bbernays** [comment]
@jimr6007 - Thank you very much for reporting this. We have been able to reproduce the issue and are working towards a fix!

**Comment by shimonp21** [comment]
Hi @jimr6007 - just updating that we are still reopening and investigating this - seems like the issue still persists.

**Comment by yevgenypats** [comment]
Just an update on the fix Im working on. 

Apparently [pgx](https://github.com/jackc/pgx) uses prepared statements by default which causes slow down as it does additional work around understanding the type of the remote schema. Changing the pgx to simple protocol (without prepared statements) solves this issue. However it will require some changes to the postgresql destination to specify type of each column. This is all possible as we are aware of types per column so Im working on a fix.

**Comment by yevgenypats** [comment]
This should be solved starting https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-postgresql-v1.3.3 . sorry for the late update (seems PR wasn't linked to the issue)
