### ISSUE TITLE
Store Array of Enums as []Text rather than JSONB

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2484]
### Describe the Bug

When an API returns a list of custom strings CQ codegen does not understand if the type is a struct or a string and therefore always stores the value in a JSONB field.

``` go
type CustomType string

// Enum values for ExtendedKeyUsageName
const (
	ExtendedKeyUsageNameTlsWebServerAuthentication CustomType = "TLS_WEB_SERVER_AUTHENTICATION"
	ExtendedKeyUsageNameTlsWebClientAuthentication CustomType = "TLS_WEB_CLIENT_AUTHENTICATION"
	ExtendedKeyUsageNameCodeSigning                CustomType = "CODE_SIGNING"
	ExtendedKeyUsageNameEmailProtection            CustomType = "EMAIL_PROTECTION"
)
type Response struct {
    ArrayCustomType []CustomType
}
```

### Expected Behavior

The above example should be stored in an `[]Text` field rather than a JSONB

**Comment by disq** [comment]
Maybe something is missing here: https://github.com/cloudquery/plugin-sdk/blob/main/codegen/transformers.go#L60-L66
