### ISSUE TITLE
Store Custom Type as Text Rather than JSONB

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2485]
### Describe the Bug

When an API returns a custom string CQ codegen does not understand if the type is a struct or a string and therefore always stores the value in a JSONB field.
```
type CustomType string

// Enum values for ExtendedKeyUsageName
const (
	ExtendedKeyUsageNameTlsWebServerAuthentication CustomType = "TLS_WEB_SERVER_AUTHENTICATION"
	ExtendedKeyUsageNameTlsWebClientAuthentication CustomType = "TLS_WEB_CLIENT_AUTHENTICATION"
	ExtendedKeyUsageNameCodeSigning                CustomType = "CODE_SIGNING"
	ExtendedKeyUsageNameEmailProtection            CustomType = "EMAIL_PROTECTION"
)
type Response struct {
    StringValue CustomType
}
```

### Expected Behavior

The above example should be stored in an `Text` field rather than a `JSONB`

**Comment by disq** [comment]
@bbernays I don't seem to have it with `reflect`: https://go.dev/play/p/aGUvIVAnVWH

**Comment by bbernays** [comment]
@disq - Thank you for looking into it!
