### ISSUE TITLE
Remove the use of github.com/bxcodec/faker

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2492]
Right now we use **heavly** github.com/bxcodec/faker in alot of our mock tests and in some of the new tests we use our own https://github.com/cloudquery/plugin-sdk/blob/main/faker/faker.go. 

We should move all of the mock tests to our own faker or at the very least disallow new code with `github.com/bxcodec/faker`.

Most of `github.com/bxcodec/faker` capabilities are mainly around generating random types of data like credit card and so on which we don't really need but the biggest issue is that this library wasn't built for production use and it is sharing all options across all objects instance which can cause race conditions and mock tests to fail because it is accessing maps concurrently.

https://github.com/bxcodec/faker/blob/master/faker.go#L243

This might also be a blocker to turn our mock tests into parallel with `t.Parallel` https://github.com/cloudquery/plugin-sdk/blob/main/plugins/source_testing.go#L30

**Comment by bbernays** [comment]
A couple of questions:
1. Do we have any examples of the mock tests failing because of this library?
2. How much time or costs could be saved by running these tests in parallel?

**Comment by erezrokah** [comment]
> 1\. Do we have any examples of the mock tests failing because of this library?

I experienced a couple. `bxcodec/faker` doesn't handle circular structs very well, and also inserts random data which makes it harder to test.


> 2\. How much time or costs could be saved by running these tests in parallel?

By default `go test` runs in parallel, so basically we've seen failures with `bxcodec/faker` just by running `go test` on the mock tests.

**Comment by erezrokah** [comment]
This is listed as `fast follow` for v1 [here](https://www.notion.so/cloudquery/v2-Created-ed27199b013c4f6b82131afdcd6087fc#7c4573e7365441c6b780fd84f71dce54) (internal link)

**Comment by yevgenypats** [comment]
I don't think they are running in parallel by default - https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently

**Comment by erezrokah** [comment]
> I don't think they are running in parallel by default - https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently

Ah good point. I did see `bxcodec/faker` fail on map write concurrency errors regardless, so probably due to:
![image](https://user-images.githubusercontent.com/26760571/195082052-cff31578-e126-4fe8-a268-64803bd50f47.png)
