### ISSUE TITLE
Add schema to postgresql destination plugin

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2532]
Right now the postgresql destination plugin is writing to the default schema in the connection. The plugin should use a schema configurable by the user with `public` being the default.

**Comment by bbernays** [comment]
Couldn't a user specify the schema in the connection url?

**Comment by yevgenypats** [comment]
Yeah you are right. looks like it's possible to use `search_path` though I recall we had some issues with that and might be better to specify this explicitly and also create all queries in the destination plugin with schema defined by the user.

https://github.com/jackc/pgx/issues/1013

But will close for now until someone will bring this up.
