### ISSUE TITLE
Policy download: Tagging requires lightweight tags

### ISSUE THREAD

**Issue by michelvocks** [cloudquery/cloudquery#256]
### Policy download requires lightweight tags

Git supports two kinds of tags: lightweight and annotated tags. `policy download` currently only works with lightweight tags.

### Expected Behavior

Support annotated tags.

**Comment by disq** [comment]
```
go run main.go policy describe aws
Downloading Policy cloudquery-policies/aws
failed to load policy: failed to checkout repository tag: failed to checkout tag (v0.0.2): object not found
```

First time running a policy. After `policy run aws` it doesn’t need to fetch and works. Or is this a different bug?

**Comment by roneli** [comment]
Should be fixed in policy v3 using go-getter under the hood
