### ISSUE TITLE
chore: Stop auto-labeling issues

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2571]
I think we don't have that much issues and better if we can label them manually (or at least based on some convention) - because I wasn't able to drop labels (or maybe this was fixed)

**Comment by disq** [comment]
Can't drop labels either, something about an invalid token.

**Comment by yevgenypats** [comment]
cc @erezrokah if you can take a look please

**Comment by erezrokah** [comment]
Yes, this doesn't work that good. We can drop it
