### ISSUE TITLE
feat(aws): New resource elasticache

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#2580]
### Why do you need this resource or plugin? Please describe.

Requested by partner https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticache

**Comment by bbernays** [comment]
We already support, are there any other resources that are needed?
```
elasticache.Clusters(),
elasticache.EngineVersions(),
elasticache.GlobalReplicationGroups(),
elasticache.ParameterGroups(),
elasticache.ReplicationGroups(),
elasticache.ReservedCacheNodes(),
elasticache.ReservedCacheNodesOfferings(),
elasticache.ServiceUpdates(),
elasticache.Snapshots(),
elasticache.SubnetGroups(),
elasticache.UserGroups(),
\elasticache.Users(),
```

**Comment by hermanschaaf** [comment]
I'm going to close this issue as we already support all the main resources for elasticache. They were added relatively recently, as part of https://github.com/cloudquery/cloudquery/issues/1368 & https://github.com/cloudquery/cloudquery/pull/1327

If there's a specific resource needed, let's open a new ticket for that.
