### ISSUE TITLE
Adding new config fields break backwards-compatibility between the CLI and plugins

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#2612]
# Summary

When we add a new general source/destination config option that applies to all plugins, such as the recent addition of `table_concurrency` and `resource_concurrency` (https://github.com/cloudquery/plugin-sdk/pull/268), we break backwards-compatibility between the CLI and previous versions of plugins. So if users upgrade the CLI, they will be forced to also upgrade all plugins to at least use the same SDK version, or otherwise it won't work. 

The error users will get relates to the field not being recognized by older versions of the plugins: 

```
rpc error: code = InvalidArgument desc = failed to decode spec: json: unknown field "table_concurrency"
```

This happens even if we include default values for the new config options and/or they are not made to be required.

# Explanation

This situation arises because we have two (or more) versions of the plugin-sdk running at the same time, all communicating with one another.

For the sake of simplicity, let's use an example where the CLI is using version 1.0.1, and the source plugin is using the previous version, v1.0.0:

 - CLI (plugin-sdk v1.0.1)
 - Source (plugin-sdk v1.0.0)

The CLI will read yaml config and convert it to JSON. This JSON includes the new fields that were added in v1.0.1 (perhaps using default values). This JSON spec will now be sent to the source plugin, which is not aware of the new fields. At this point the source plugin will return an error indicating that it found an unrecognized field in the config: https://github.com/cloudquery/plugin-sdk/blob/main/internal/servers/source.go#L61-L68 . The sync will not be able to proceed, and the user will be forced to upgrade their plugin.

# Workarounds

The only workaround to the current situation is for users to upgrade the versions of their plugins to be at least as high as the version used by the CLI. 

# Implications

This implies that any additional config option we add right now is a breaking change. Ideally, we want to be able to add config options and have them ignored by older versions of the plugins (maybe with a warning).

# Possible Solutions

Can we remove the `dec.DisallowUnknownFields()` check when parsing the JSON? Maybe we should, but this will mean we are unable to warn users if their configs are incorrect. I'm opening this issue to discuss this and other potential solutions.

**Comment by erezrokah** [comment]
Great catch @hermanschaaf 👍 

> Can we remove the `dec.DisallowUnknownFields()` check when parsing the JSON? Maybe we should, but this will mean we are unable to warn users if their configs are incorrect. I'm opening this issue to discuss this and other potential solutions.

Can we parse to unknown fields into a stub interface and then iterate on it?

**Comment by yevgenypats** [comment]
I think this will be the solution eventually - https://github.com/cloudquery/plugin-sdk/pull/272 and yes removing `DisallowUnknownFields` as otherwise it's not possible to keepbackward compat nicely. same as protobuf is doing.

**Comment by erezrokah** [comment]
Maybe we need to discuss this more, but I'm thinking we should never have:
- CLI (plugin-sdk v1.0.1)
- Source (plugin-sdk v1.0.0)
as we should always first release the plugins with SDK `v1.0.1` and then the CLI with SDK `v1.0.1`.
Then the SDK can handle backwards compatibility with older versions.

Otherwise we can get into this 🐰 🕳️ with other SDK features too.

Another option is to have the CLI not import the SDK, and consume it via calls the plugin client (which seems 🙃 especially with things like parsing configurations).

**Comment by hermanschaaf** [comment]
@erezrokah Ah, it's not about the order in which we release them. I agree, we should always first release the plugins and then the CLI.

The issue here, however, is that users are likely to update their CLI without updating all the versions of plugins in their config files. If they use a newer CLI version with older plugin versions, it will break. Another issue is that it's hard to tell from a CLI version which versions of plugins you should be using.

**Comment by erezrokah** [comment]
> The issue here, however, is that users are likely to update their CLI without updating all the versions of plugins in their config files. If they use a newer CLI version with older plugin versions, it will break. Another issue is that it's hard to tell from a CLI version which versions of plugins you should be using.

💯 Got it thanks for the explanation. I think this can happen with any SDK feature that is "shared" between plugins and CLI, but it's off topic for this issue, so we can visit in another discussion.

**Comment by yevgenypats** [comment]
Closing this as this is solved now. We can add a follow-up for validation warnings.
