### ISSUE TITLE
Fix CQ deployment scripts broken with the V1 release

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#2617]

**Comment by erezrokah** [comment]
Related PR https://github.com/cloudquery/helm-charts/pull/117. We should work on top of it to fix the Helm charts, specifically https://github.com/cloudquery/helm-charts/blob/f63128e22c1bd7d60ae66f6979cd6eebfd9b32ae/charts/cloudquery/templates/cronjob.yaml#L35

**Comment by erezrokah** [comment]
Helm charts repo is up to date.

We need to follow up in:
https://github.com/cloudquery/terraform-aws-cloudquery
https://github.com/cloudquery/terraform-gcp-cloudquery
https://github.com/cloudquery/terraform-azure-cloudquery

**Comment by erezrokah** [comment]
This is done and all repos use CloudQuery v1 now (for Azure this is an initial release)
