### ISSUE TITLE
Support for AWS Service quota

### ISSUE THREAD

**Issue by vivek-siva** [cloudquery/cloudquery#2630]
any plans for bringing in aws service quota data - i don't see the table data for service quota here - https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/docs/tables

**Comment by bbernays** [comment]
Hi @vivek-siva Thank you for opening this issue! We have an issue open for this: https://github.com/cloudquery/cloudquery/issues/1407

 I would encourage you to upvote that issue so we can see the community interest (as that drive much of our prioritization)... I also would encourage you to try and expand on the use case for the data to give us more context.

**Comment by bbernays** [comment]
@vivek-siva - Just wanted to give you a heads up that we have opened a PR for adding support for AWS Service quota
