### ISSUE TITLE
Document Error Handling Conventions

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#2631]
What types of errors should CloudQuery plugins handle vs returning to the user. At a high level this should be documented either for all plugins or for each plugin if there are any specific edge cases

**Comment by yevgenypats** [comment]
We should always return all errors to the user and then let the user decide what is important with what is not as we really can't know and it's infinite amount of work to develop error classifier and ignore logics

**Comment by bbernays** [comment]
When a user runs CQ in a CI environment and it returns errors, how are users supposed to be able to identify actionable errors and filter out errors that are non-actionable or expected/normal?

**Comment by cqgaurav** [comment]
This could be just linked from our contribution guide.

**Comment by yevgenypats** [comment]
Closing as not sure what the it the action item here. Errors which are non-recoverable should return to the user and return `-1` exit code while recoverable errors should be logged. Each plugin defines what is recoverable and what not on it's own. For example auth errors are usually non-recoverable or incorrect configuration.
