### ISSUE TITLE
Bug(release): Some plugins don't have their version embedded correctly

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2642]
### Describe the Bug

In order for `<plugin> --version` command to work we need to embed the correct version via Go Releaser.
Go Releaser expects it to be under `resources/plugin.Version`:
https://github.com/cloudquery/cloudquery/blob/7b2c4aac79ca356efb41244c9ee3d8306c600dd2/plugins/.goreleaser.yaml#L12
That requires plugins to follow a specific directory and package convention.
Some don't like `k8s,okta,terraform`. We should fix it

### Expected Behavior

`<plugin> --version` should work for all plugins

**Comment by erezrokah** [comment]
This is completed

**Comment by yevgenypats** [comment]
Is it completed to destination plugins as well?

**Comment by erezrokah** [comment]
Ah no, good catch, I'll re-open and fix thos

**Comment by erezrokah** [comment]
I somehow thought we did this for destinations plugins when we introduced them 🙃

**Comment by erezrokah** [comment]
Follow up in https://github.com/cloudquery/cloudquery/pull/2946 and https://github.com/cloudquery/cloudquery/pull/2947
