### ISSUE TITLE
Queries for AWS IMDSv2

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#2646]
### Is your feature request related to a problem? Please describe.
Additional CloudQuery for AWS IMDSv2 queries.

### Describe the solution you'd like
Queries for Lightsail IMDSv2 and AMI IMDSv2

### Additional context
CQ was updated for support for both Lightsail IMDSv2 and AMI IMDSv2, this is to finish queries for IMDSv2

**Comment by bbernays** [comment]
@jsonpr Can we close this?

**Comment by jsonpr** [comment]
Yeah, thanks @bbernays - Go ahead and close this issue.  

Unrelated - your GitHub profile bbernays name is set to "First Last".  Unsure if that's intentional or not.
