### ISSUE TITLE
Logging standards

### ISSUE THREAD

**Issue by dan-compton** [cloudquery/cloudquery#27]
From what I've gathered in my first skim, it seems like the logging standards haven't been completely defined yet but their central theme is around the zap.logger and it's type rappers and tricks to provide zero alloc and efficient logging.  

However I think that the real slow down within this code will be related to round trip time for specific queries, optimization of queries to third party platforms, and ultimately rate limiting and dealing with API errors and graceful way.

As I continue to make contributions to this code base would it be frowned upon if I deviated from the strict yet performance zap.logger in favor of the only slightly less performant zap sugared logger?

**Comment by yevgenypats** [comment]
@dan-compton Thanks for the issue. You are correct that the bottleneck is the network and database. On the other-hand in addition to performance the current strict zap logger also gives the ability for external tools/monitoring to process the log easily as it's in json format which would be more challenging  in a "free text" logging.

**Comment by yevgenypats** [comment]
Closing as stale for now.
