### ISSUE TITLE
chore(ci): Detect when column types change and ensure we release it as a breaking change

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2769]
When we change a column type we should release it as a breaking change if it can't be migrated.
Since it's easy to miss by reviewers (🤚 me in https://github.com/cloudquery/cloudquery/pull/2763).

We should find a way to test for such changes, and alert developers.

### Possible solutions
1. Do it in our testing framework
2. Detect it via changes to the table doc files

**Comment by bbernays** [comment]
I think we should also try to detect when a column gets renamed or deleted

**Comment by disq** [comment]
Related #3557

**Comment by erezrokah** [comment]
I think we can close this in favor of https://github.com/cloudquery/cloudquery/issues/3557

**Comment by hermanschaaf** [comment]
An automated change recently removed a field, so I think we do need some check that ensures it's at least marked as a breaking change: [https://github.com/cloudquery/cloudquery/commit/e6b1e3b10b96c6a5ceb28389efc91da4d9aca590#diff-da3e874014b83b329fa368f[…]2445c406a63fa2c93fc02f1b6L28](https://github.com/cloudquery/cloudquery/commit/e6b1e3b10b96c6a5ceb28389efc91da4d9aca590#diff-da3e874014b83b329fa368f4009df201d465e882445c406a63fa2c93fc02f1b6L28)

**Comment by erezrokah** [comment]
This is done via https://github.com/cloudquery/cloudquery/pull/5377. If https://github.com/cloudquery/cloudquery/pull/5377 works well for automated PRs we can consider enforcing it for manual PRs too (though I think the summary in https://github.com/cloudquery/cloudquery/pull/5347 should be enough)
