### ISSUE TITLE
Executing A Single Query Within a Policy

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#279]
### Is your feature request related to a problem? Please describe.

In order to figure out how to execute a single query in a policy I had to go through the code line by line and add in debug statements.

### Describe the solution you'd like

I think a few things would improve this:

1. Add tests to ensure that the subpath functionality is preserved and working as expected
2. Add documentation in the readme of how to call a policy with a subpath
3. Add documentation within the command how to run a policy with a subpath

**Comment by roneli** [comment]
This is possible in policy v3.

**Comment by roneli** [comment]
@bbernays reopen if I am wrong
