### ISSUE TITLE
bug(website): The Cloudflare plugin is missing the the list of sources

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#2817]
https://www.cloudquery.io/docs/plugins/sources
![image](https://user-images.githubusercontent.com/26760571/195652273-171d845b-adad-4e1a-9ee6-3d3463a6c2d0.png)

We should add the Cloudflare plugin to that list

**Comment by cychiang** [comment]
Please take a look #3185 and I'm not sure about the status of the `Cloudflare` plugin. Should be `Preview` or `GA`?

**Comment by cychiang** [comment]
Hi @erezrokah maybe we can close this issue? Because #3185 is merged 👍

**Comment by erezrokah** [comment]
Great catch! I'll close it.

FYI if you write in the PR description `fixes #2817` for example the issue will be auto closed when the PR is merged
