### ISSUE TITLE
116 Broken links on the cq website

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#2838]
Following a demo feedback, I ran Dr link check on cloudquery.io, and found 116 broken links. Might need to find atleast the issues with depth 2 and fix them. Also check if any existing monitoring should have been able to catch these.

I didn't pay for the premium version myself so might have to run the linkchecker again to actually investigate again, but I looked into a few and they looked legit

![Image](https://user-images.githubusercontent.com/113518845/195816187-325e82e9-05a8-435e-aba0-b1eb43bfc5ed.png)

**Comment by erezrokah** [comment]
Thanks for opening the issue @cqgaurav. We have automation that checks for broken links once per day, and also if someone changes the Website **AND** adds a `check_broken_links` label. It shows 149 broken links:
https://github.com/cloudquery/cloudquery/actions/runs/3255603006/jobs/5345086543

I got it to 0 broken links a whole back with the move from v0 to v1 we need another pass at it.

The reason we do it only for labeled PRs is that it can take a bit of time to run the checker. Maybe now we have less links on the site, so we can run it on every PR that changes the Website, I'll take a look.

The reason we also run it periodically is to catch broken external links (for example we linked to an external site that's not in our control, and that site changed its structure).
