### ISSUE TITLE
Redshift support

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#2844]
Create a standalone destination plugin for Redshift

**Comment by cqgaurav** [comment]
From Ben: AWS has provided functionality to redshift can directly query s3. We should perhaps document how this can be done.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/redshift. Please sign up there to get a notified when the plugin is available.
