### ISSUE TITLE
Feedback for “Overview”

### ISSUE THREAD

**Issue by alphasecio** [cloudquery/cloudquery#2906]
Comparison links are broken:
https://www.cloudquery.io/docs/cq_vs_others/aws_config
https://www.cloudquery.io/docs/cq_vs_others/google_cloud_asset_inventory
https://www.cloudquery.io/docs/cq_vs_others/cspms
https://www.cloudquery.io/docs/cq_vs_others/steampipe

**Comment by yevgenypats** [comment]
Thanks for spotting this! opened a PR to fix this.
