### ISSUE TITLE
Allow `cloudquery init` to append configs for new providers

### ISSUE THREAD

**Issue by ukmadlz** [cloudquery/cloudquery#292]
### Is your feature request related to a problem? Please describe.
Currently to add a new provider to an existing `config.hcl` you need to manually add the provider config block

### Describe the solution you'd like
If running `cloudquery init [new provider]` check if config already contains said provider, and if not appends the relevant config block to the `config.hcl` in the same way running `cloudquery init aws gcp okta` will append them in sequence for a new `config.hcl` file

**Comment by shimonp21** [comment]
Also linking a related documentation issue for the GCP provider: https://github.com/cloudquery/cq-provider-gcp/issues/104

**Comment by bbernays** [comment]
Instead of appending we have decided to just support multiple config files

**Comment by yevgenypats** [comment]
In V2 we use `gen` to output new files and we use new file for very source or destination plugin.
