### ISSUE TITLE
Policy block improvment

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#294]
### Is your feature request related to a problem? Please describe.
Currently the policy block looks like the following:

```
policy "remote_policy_1" {
  type = "remote"
  source = "https://github.com/cloudquery-policies/aws-cis-1.2.0.git"
  sub_path = ""
  version = "v0.0.5"
}
```
The `type` + `source` are redundant arguments imo and can be simplified both from configuration standpoint and both from documentation standpoint.

Currently `type` can be: `remote`, `local`, `hub`.

I believe `hub` and `remote` are the same and there is no reason to distinguish between them. The hub just serve as a discovery site and the policies are stored on github.

For local I think this can be solved by doing something like this: `file:///username/home/mypolicy`

**Comment by bbernays** [comment]
Right now only remote SVCs are supported... what if instead of `https://` we used `git://` and then `https://` could be used for any file stored at the remote location

**Comment by yevgenypats** [comment]
This is completely redone / taken care of in policy v3
