### ISSUE TITLE
Query Enhancements

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#297]
### Is your feature request related to a problem? Please describe.

Support configuration checks at the config level rather than just the Policy level in order to add more granularity. This way a user can at least run a subset of checks without having to upgrade

**Comment by yevgenypats** [comment]
We migrated to pure sql https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/policies so this shouldn't be relevant anymore.
