### ISSUE TITLE
`cloudquery init azure` fails with 404

### ISSUE THREAD

**Issue by Threpio** [cloudquery/cloudquery#298]
### Describe the Bug

Upon a clean download on my local mac m1 and when trying to run `cloudquery init azure` I get the following error message: 

```
 ✘ tan@MacBook-Pro-tilhrende-Theo  ~  cloudquery init azure
Initializing CloudQuery Providers...

❌ Failed to initialize provider: plugin cloudquery/azure@v0.3.7 failed to download: got 404 http code instead expected 200.
```

![Screenshot 2021-11-23 at 09 32 47](https://user-images.githubusercontent.com/49570057/142996686-03e086b5-2c73-4dee-b270-0ff2344e32f2.png)

### Expected Behavior

The CLI tool downloads the necessary azure packages for it to work. 
To not receive an error message and to be able to use Cloudquery to run Azure setup.

### CloudQuery Version

```
 ✘ tan@MacBook-Pro-tilhrende-Theo  ~  cloudquery version
Version: 0.16.1
Commit: 8f8550a92685eab9b49ea99efe1e185ee15b73c6
Date: 2021-11-23 10:05:17.22914 +0100 CET m=+0.033652085
```
### Debug Output

No additional logs was shown when this command was run: 

![Screenshot 2021-11-23 at 10 07 24](https://user-images.githubusercontent.com/49570057/142996811-4344fe17-de4d-4f2f-8b06-264039b2f5c4.png)

### Steps to Reproduce

```
brew install cloudquery/tap/cloudquery
brew upgrade cloudquery
cloudquery init azure 
```

### References

**Comment by roneli** [comment]
Hi @Threpio thanks for reporting this issue! We tagged a new version the [cq-provider-azure](https://github.com/cloudquery/cq-provider-azure/releases/tag/v0.3.8) to support ARM OS. 

Feel free to close this issue if you don't have any other errors :)

**Comment by Threpio** [comment]
@roneli Thanks and sure :)
