### ISSUE TITLE
[K8s] Add Support for Kubernetes Secrets 

### ISSUE THREAD

**Issue by SCKelemen** [cloudquery/cloudquery#2981]
Kubernetes Secrets is a core function of Kubernetes. It would be useful to be able to gather insights and visibility from kubernetes secrets.

As this feature is part of the Kubernetes Core, it should probably be included in the core plugin service. 
- [Kubernetes Secrets](https://kubernetes.io/docs/concepts/configuration/secret/)
- [Secret Definition](https://pkg.go.dev/k8s.io/api/core/v1#Secret)
- [SecretList Definition](https://pkg.go.dev/k8s.io/api/core/v1#SecretList)

**Comment by erezrokah** [comment]
Closing as fixed https://github.com/cloudquery/cloudquery/pull/3183. @SCKelemen please comment if anything needs to be added on top of that PR
