### ISSUE TITLE
ARN is incorrectly pluralized for EC2 instances

### ISSUE THREAD

**Issue by nick123pig** [cloudquery/cloudquery#2986]
### Describe the Bug
The resolveInstanceArn function for ec2 instance is incorrect. It's pluralizing `instance` as `instances`

### Expected Behavior
ARN should be `arn:aws:ec2:us-west-2:123456:instance/i-01234` instead of `arn:aws:ec2:us-west-2:123456:instances/i-01234`

### CloudQuery Version
1.2.0

**Comment by bbernays** [comment]
@nick123pig - Thank you for opening this issue!

**Comment by bbernays** [comment]
Feel free open a PR, I can definitely close mine!

**Comment by nick123pig** [comment]
nope - it's exactly the same as yours!
