### ISSUE TITLE
Add AWS ECR Repository

### ISSUE THREAD

**Issue by rsclarke-vgw** [cloudquery/cloudquery#30]
Currently ECR images are fetched by first calling `DescribeRepository` in order to set the appropriate input arguments for `DescribeImages`.  However the repository structure itself contains details such as tag immutability, image scanning config and encryption is not persisted to the database for querying.

For example, one could query which ECR repositories allow mutable images.

**Comment by yevgenypats** [comment]
@rsclarke-vgw Thanks for posting this! This should be solved in https://github.com/cloudquery/cloudquery/releases/tag/v0.7.7
