### ISSUE TITLE
AWS Choosing Multiplexer 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#3006]
In the AWS contributor guide ensure it is properly explained how to choose the name of the service on which to multiplex (service name must be in the `partition_service_region.json` file)

Also document how to debug: plugin compiles, able to run a sync on that new table, but resolver is never actually invoked

**Comment by yevgenypats** [comment]
I think for aws side we also need to panic if we use a service that doesn't exist and/or use constants

**Comment by bbernays** [comment]
I don't think it will be that simple, as a service can exist in a single region/partition

**Comment by yevgenypats** [comment]
Yes, but if it doesn't exist at all it should panic as this happened to me as well multiple times where I had a typo and/or use constants instead of strings
