### ISSUE TITLE
Run Migration without a sync

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#3077]
Users that run syncs in parallel need a way to be able to run a migration as a one off command because otherwise when syncs are done in parallel the initial migration will fail

**Comment by hermanschaaf** [comment]
I'd like to suggest the following interface:

 - add a `migrate` command that only runs the migration, nothing else
 - add a `--skip-migration` flag to `sync` to override the default behavior of performing a migration first

This will still require some synchronization on the user-side, however. For example, you would need an orchestrator that first runs `cloudquery migrate`, waits for it to complete, and then runs all the instances of `cloudquery sync --skip-migration` in parallel.

**Comment by erezrokah** [comment]
Is there a way to lock the DB during the migration? Then we won't need an additional command (I vaguely remember we talked about this problem before)

**Comment by bbernays** [comment]
I agree with @erezrokah that the best way to solve the underlying issue of coordinating a parallelized sync is to run the migration as a single transaction

**Comment by hermanschaaf** [comment]
We discussed this further on a call, just summarizing the outcome here:
 - we will start by adding the `migrate` command and `--skip-migration` option
 - transactions may also work, but can also lead to some unforeseen bugs/complexities, and not every destination will support that kind of function.

A typical workflow might involve running many cloudquery workers in parallel. When it's time to upgrade, a separate worker can be started to run the migration. As long as the workers are still running the old version, it shouldn't cause any issues, as migrations are backwards-compatible. Once the migration is finished, the workers can then also be upgraded.

We're not saying we definitely won't explore transactions in the future, but for this case it seems less risky to give users a bit more control over when migrations run.
