### ISSUE TITLE
Implement CIS benchmark policy for Kubernetes

### ISSUE THREAD

**Issue by SCKelemen** [cloudquery/cloudquery#3112]
CIS has a benchmark for Kubernetes which can be implemented as a Policy in the Kubernetes plugin
https://www.cisecurity.org/benchmark/kubernetes

PR: #4716

**Comment by SCKelemen** [comment]
Queries
- [5.3.2 Ensure that all Namespaces have Network Policies defined]
- [Namespaces should have a default network policy to deny all egress traffic]
- [Namespaces should have a default network policy to deny all ingress traffic]
- [Network policies should not have a default policy to allow all egress traffic]
- [Network policies should not have a default policy to allow all ingress traffic]
- [5.7.2 Ensure that the seccomp profile is set to docker/default in your Pod definitions]
- [Seccomp profile is set to docker/default in CronJob definition]
- [Seccomp profile is set to docker/default in DaemonSet definition]
- [Seccomp profile is set to docker/default in Deployment definition]
- [Seccomp profile is set to docker/default in Job definition]
- [Seccomp profile is set to docker/default in your Pods]
- [Seccomp profile is set to docker/default in Pod security policy]
- [Seccomp profile is set to docker/default in your Replication Controller definition]
- [Seccomp profile is set to docker/default in your StatefulSet definition]
- [5.7.4 The default namespace should not be used]
- [ConfigMap definition should not use default namespace]uld not use default namespace]
- [DaemonSet definition should not use default namespace]ould not use default namespace]
- [Ingress definition should not use default namespace]
- [Job definition should not use default namespace]
- [Pods should not use default namespace]
- [ReplicaSet definition should not use default namespace]
- [ReplicationController definition should not use default namespace]
- [RoleBinding definition should not use default namespace]
- [Role definition should not use default namespace]
- [Secret definition should not use default namespace]
- [ServiceAccount definition should not use default namespace]
- [Services should not use default namespace]
- [StatefulSet definition should not use default namespace]
- [5.1.6 Ensure that Service Account Tokens are only mounted where necessary]
- [5.2.1 Minimize the admission of privileged containers]
- [5.2.2 Minimize the admission of containers wishing to share the host process ID namespace]
- [5.2.3 Minimize the admission of containers wishing to share the host IPC namespace]
- [5.2.4 Minimize the admission of containers wishing to share the host network namespace]
- [5.2.5 Minimize the admission of containers with allowPrivilegeEscalation]
- [5.2.6 Minimize the admission of ro]

**Comment by jsonpr** [comment]
Closing this old issue.
