### ISSUE TITLE
chore(ci): Consider greeting users on first interaction with the repo

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3161]
Example https://github.com/tj-actions/changed-files/issues/702#issuecomment-1285802990

Action to use https://github.com/actions/first-interaction

**Comment by cychiang** [comment]
Hi @erezrokah I create a draft PR to add a workflow for greetings. However, I think it would be good to discuss a bit on what messages we would like to send out to users. 

Please take a look on #3175

**Comment by erezrokah** [comment]
Fixed in https://github.com/cloudquery/cloudquery/pull/3175 thanks @cychiang 🚀
