### ISSUE TITLE
When fetch doesn't run policy message is not clear enough.

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#317]
### Is your feature request related to a problem? Please describe.
Currently if I just run policy without running fetch it will give the following error:

```
Cloning Policy cloudquery-policies/aws
❌policy "cloudquery-policies-aws" -  error: aws/cis-v1.20/cis-v1.20/aws_log_metric_filter_and_al…  

📋 cloudquery-policies-aws Results:

❌ Policy failed to run
Error: aws/cis-v1.20/cis-v1.20/aws_log_metric_filter_and_alarm/aws_log_metric_filter_and_alarm_query: ERROR: relation "aws_cloudtrail_trails" does not exist (SQLSTATE 42P01)
```

A new user who is not familiar with what is fetch or how cloudquery works internally won't know how to resolve it. We need a way to check if fetch was run and if not, not run the policy and give the user an error and a next step.

```
You should first run `cloudquery fetch`
docs: https://docs.cloudquery.io/......
```

**Comment by yevgenypats** [comment]
@bbernays makes sense @roneli wdyt ?

**Comment by roneli** [comment]
FetchSummary storage is important yes.
