### ISSUE TITLE
Bug: subpolicy either doesn't work or message is misleading.

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#318]
### Is your feature request related to a problem? Please describe.
Currently running  the following: `cloudquery policy run aws --sub-path cis-v1.2.0`

```
ep@MacBook-Pro-8 stuff % cloudquery policy run aws --sub-path cis-v1.2.0
Starting policies run...

Cloning Policy cloudquery-policies/aws
❌policy "cloudquery-policies-aws" -  error: selected policy/query i…  

📋 cloudquery-policies-aws Results:

❌ Policy failed to run
Error: selected policy/query is not found

Finished policies run...
```

what does it mean `select policy/query` not found? maybe policy or query? Also suggest to add the name that it looked for.
But the path does exist as far as I can tell https://github.com/cloudquery-policies/aws/blob/main/policy.hcl#L9

**Comment by bbernays** [comment]
In case others come across this: make sure you are starting the selector from the root policy in the file.
for example in this case the proper selector is: aws/cis-v1.2.0

so this example will work:
```cloudquery policy run aws --sub-path aws/cis-v1.2.0```

**Comment by roneli** [comment]
subpath as an argument is going to be removed when #322 is merged. 

`cloudquery policy run aws aws/cis-v1.2.0` this will be used instead
