### ISSUE TITLE
poor performance on aws_ecs_task_definitions

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#3184]
### Describe the Bug
across 50 accounts and over 3 million resources a full sync usually takes 6 to 7 hours, not too bad

but as I watch compute resource usage on my k8s pod and RDS instance while a sync is in progress I see both the pod and the rds instance working super hard for the first 30 minutes or so and then usage drops to a trickle for the remaining hours.

manual testing and watching logs and which tables are growing shows me that cq is slowed down dramatically by aws_ecs_task_definitions

for "reasons" :) -- we have one account with over 500k ecs task defintions

### Expected Behavior
cq and the aws source plugin processes ecs task definitions faster than it does now

### CloudQuery Version
cli: 1.3.6
aws source: 3.5.0
postgres destination: 1.3.9

### Debug Output
I can get logs while in progress if you like, just let me know please

### Steps to Reproduce

run cq sync with aws source on an acocunt with an unusually large number of ecs task definitions

Also please share any other necessary configuration files
-->

**Comment by erezrokah** [comment]
Thanks for the issue @jimr6007 👍 While we investigate this issue, do you mind confirming that syncing only with the `aws_ecs_task_definitions` table takes a long time?

What I'm trying to understand if we're slow on this specific resource, or if there's another issue related handling resources in general.

To sync only `aws_ecs_task_definitions` you could use a similar config to:

```yaml
kind: source
spec:
  name: aws
  path: cloudquery/aws
  version: "v3.5.2" # latest version of aws plugin
  tables: ["aws_ecs_task_definitions"]
  destinations: ["postgresql"]
```

If syncing only `aws_ecs_task_definitions` is indeed very slow, a possible solution could be to separate the configurations to speed up the bulk of the sync

**Comment by erezrokah** [comment]
Closing this per @bbernays comment and my suggestion to split the configs. @jimr6007 please comment if still relevant and I'll re-open
