### ISSUE TITLE
total_resources count in log is always zero for every resource

### ISSUE THREAD

**Issue by thegoldenmeow** [cloudquery/cloudquery#3201]
### Describe the Bug
The log output from sync always has total_resources count as 0 against each resource and does not reflect the actual number (in both key value and json log formats)

### Expected Behavior
total_resources count should reflect the actual resources synced

### CloudQuery Version
cloudquery version 1.3.7

### Debug Output
INF fetch table finished duration=676.800416 module=cli subscription_id=**** table=azure_search_services total_resources=0

### Steps to Reproduce

```
cloudquery sync source.yaml destination.yaml --log-format --json
```

**Comment by BenitezDev** [comment]
This problem also occurs with aws and gcp

```
{"level":"info","module":"cli","duration":123,"message":"fetch table finished","project_id":"xxxxxx","table":"gcp_iam_roles","total_resources":0,"time":"x"}
{"level":"info","module":"cli","account_id":"xxxxxxx","duration":123,"message":"fetch table finished","region":"xxxx","table":"aws_ec2_vpcs","total_resources":0,"time":"x"}
```

**Comment by erezrokah** [comment]
Thanks for reporting the issue @thegoldenmeow and @BenitezDev, a PR to fix this is under review https://github.com/cloudquery/plugin-sdk/pull/316

**Comment by yevgenypats** [comment]
Closing as should be solved in https://github.com/cloudquery/cloudquery/releases/tag/cli-v1.5.1. and https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-gcp-v2.4.0 

If this is not solved, please re-open
