### ISSUE TITLE
chore(ci): Monitor binaries sizes with `goweight`

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3241]
Low priority, we could use a tool like https://github.com/jondot/goweight and run it in CI to detect when a PR increases the size of our binaries significantly

**Comment by MukulKolpe** [comment]
Hey @erezrokah, can I work on this issue?

**Comment by erezrokah** [comment]
Sure thing @MukulKolpe that would be great 🚀 

I would recommend trying to add it to our test plugin first via a new job here:
https://github.com/cloudquery/cloudquery/blob/3523c7e279670079e0d872d89b80c4e6c7f250e3/.github/workflows/source_test.yml#L50

If it provides valuable information we can add it to other plugins, WDYT?

**Comment by erezrokah** [comment]
Closing as won't fix for now
