### ISSUE TITLE
RDS tables duplicated to Neptune tables

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#3262]
### Describe the Bug
RDS clusters, parameter groups, snapshots are all duplicated as Neptune clusters, PGs and snapshots

### Expected Behavior
all RDS clusters are not neptune clusters, but all neptune clusters are RDS clusters

### CloudQuery Version
plugins-destination-postgresql-v1.3.7/postgresql_linux_amd64.zip
plugins-source-aws-v3.4.1/aws_linux_amd64.zip
cli-v1.3.4

**Comment by Barneyjm** [comment]
i guess this is an AWS "bug" actually: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/neptune/describe-db-clusters.html

DocumentDB and Neptune both return RDS stuff apparently. 

Can we add engine filters on the CQ process to ensure they're only returning the appropriate resource type?

**Comment by Barneyjm** [comment]
https://github.com/aws/aws-cli/issues/5859#issuecomment-760366515

**Comment by Barneyjm** [comment]
might have to modify RDS's collection process too -- we'd get duplicates in RDS tables too for any Neptune/DocumentDB cluster. 

filter for each engine type in RDS? https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-instances.html

seems less than ideal but until AWS "fixes" their API, i don't think there's another way

**Comment by Barneyjm** [comment]
this affects pre-v1 CQ too by the way 
```
select * from aws_rds_clusters where engine = 'docdb'
```

**Comment by Barneyjm** [comment]
> I don't think that DocumentDB endpoints actually supports filtering on the engine as it is not one of the documented fields: https://docs.aws.amazon.com/documentdb/latest/developerguide/API_DescribeDBInstances.html

I think it does since clearly it's just a wrapper on the RDS APIs but it's (shockingly /s) not documented (please excuse the python. same API though): 

```
Python 3.10.3 (v3.10.3:a342a49189, Mar 16 2022, 09:34:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> print(boto3.__version__)
1.20.51
>>> docdb = boto3.client('docdb')
>>> docdb.describe_db_clusters(Filters=[{'Name':'engine', 'Values':['docdb']}])
>>> len(docdb.describe_db_clusters(Filters=[{'Name':'engine', 'Values':['docdb']}])['DBClusters'])
2 #i made two test clusters
>>> db = docdb.describe_db_clusters(Filters=[{'Name':'engine', 'Values':['docdb']}])['DBClusters'][0]
>>> db['DBClusterIdentifier'], db['Engine'], db['EngineVersion']
('my_example_docdb', 'docdb', '4.0.0')
>>> 
>>> rds = boto3.client('rds')
>>> db = rds.describe_db_clusters(Filters=[{'Name':'engine', 'Values':['docdb']}])['DBClusters'][0]
>>> db['DBClusterIdentifier'], db['DBClusters'][0]['Engine'], db['DBClusters'][0]['EngineVersion']
('my_example_docdb', 'docdb', '4.0.0')
```
two different clients, same response. Thanks AWS

**Comment by bbernays** [comment]
Thank you for doing that validation!  I have opened a pr to fix this. 

I don't think that we should do any filtering on the RDS resources though. This is an implementation by AWS that I don't think we should correct as it would mean any new versions of RDS or Aurora would require a code change. I am alright with Neptune + DocDB needing that though

**Comment by Barneyjm** [comment]
sweet. i'm a little concerned that not amending RDS will result in duplicate data but i agree that it's intended functionality by AWS though. 

should DocDB and Neptune just be views built on top of the RDS table?

**Comment by bbernays** [comment]
I was thinking that might be an option as well, although would require some added capabilities to CloudQuery in order to manage those views.

 In Neptune there are some tables/APIs that are unique to Neptune and that do not support filtering, so not everything would be a view

**Comment by jsonpr** [comment]
Agreed that filtering should be done on DocDB and Neptune.  @Barneyjm - I'm surprised that it's the same response for different clients.  Even the AWS page states "For certain management features such as cluster and instance lifecycle management, Amazon DocumentDB leverages operational technology that is shared with Amazon RDS and Amazon Neptune."

* For DocDB (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/docdb/describe-db-clusters.html), filterName=engine,Values=docdb
* For Neptune (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/neptune/describe-db-clusters.html), filterName=engine,Values=neptune.

For RDS, another option is to filter out docdb and neptune to return RDS + Aurora so we don't have to rely on filtering based off knowledge of all versions of RDS and Aurora.  It's a safer bet that neptune and docdb will only have those engine values given AWS documentation on those resources as well.

This is definitely worth an internal cloudquery conversation for best path forward - whether we leave RDS as is, whether we create a new view, and how we potentially structure DocDB and Neptune.
