### ISSUE TITLE
Resource Types > Security Groups

### ISSUE THREAD

**Issue by dikuesan1** [cloudquery/cloudquery#3270]
Hello,

Is it possible??

I am trying to fetch resources that are using particular security groups. For example, I am trying to fetch Lambdas using the default security group. I also want to query the Lambda ARN, the Security group name (default) instead of the SG id and also tags that are tied to the lambda resource. 

or

I discovered it's possible to pull all ENIs that are attached to the default security group (see query below), However, the description column is helpful but lets say I want to pull the ARN of the resource that is tied to the ENI that is tied to the default SG. How can this be done? Please help :(

```sql
SELECT account_id,region, arn, description, groups, tags
FROM aws_ec2_network_interfaces 
where groups @> '[{"GroupName": "default"}]'
limit 10
```

**Comment by Barneyjm** [comment]
Something similar was asked for EC2s. Answer here: https://discord.com/channels/872925471417962546/1016576453988601946/1016762731036151808
