### ISSUE TITLE
Tags Columns in V1 aren't unified

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#3280]
### Describe the Bug
Some tables have tags as `list(dict)` and others are just type `dict`. ideally this would be unified as type `dict` for all tables. 

### Expected Behavior
`{"my_tag": "my_value"}` is best. Looks like the resolver looks like this in this situation: 
```
return resource.Set(c.Name, client.TagsToMap(output.Tags))
```

`[{"Key":"my_tag", "Value":"my_value"}]` is very clunky.

### CloudQuery Version
v1.3.4

### List of tables afflicted
source query: 
```
SELECT distinct cq_table, jsonb_typeof(tags) from aws_resources 
group by cq_table, tags
```

| cq_table | tag_type |
| -------- | -------- |
| aws_acm_certificates | array |
| aws_autoscaling_groups | array |
| aws_codebuild_projects | array |
| aws_dax_clusters | array |
| aws_ec2_customer_gateways | array |
| aws_ec2_ebs_snapshots | array |
| aws_ec2_ebs_volumes | array |
| aws_ec2_flow_logs | array |
| aws_ec2_hosts | array |
| aws_ec2_images | array |
| aws_ec2_instances | array |
| aws_ec2_key_pairs | array |
| aws_ec2_nat_gateways | array |
| aws_ec2_network_interfaces | array |
| aws_ec2_security_groups | array |
| aws_ec2_subnets | array |
| aws_ec2_vpc_endpoints | array |
| aws_ec2_vpc_endpoint_service_configurations | array |
| aws_ec2_vpc_peering_connections | array |
| aws_ec2_vpcs | array |
| aws_ec2_vpn_gateways | array |
| aws_efs_filesystems | array |
| aws_organizations_accounts | array |

**Comment by bbernays** [comment]
Beyond just fixing the highlighted columns, can we add a unit test to verify that any `tag` column has the correct structure? I don't think this is the first issue we have seen with this

@disq @yevgenypats @hermanschaaf

**Comment by disq** [comment]
@bbernays yes but how? `schema.PathResolver("Tags")` is valid on the resources that already have `Tags` as `map[string]string` (or `map[string]*string` or `map[string]interface{}`) I think best way is to tweak codegen a little. See the PR.

**Comment by bbernays** [comment]
I was thinking we could have some type of plugin specific tests:

https://github.com/cloudquery/cloudquery/blob/a35b8e89d625287a9b9406ff18cfac78ffdb1241/plugins/source/aws/client/testing.go#L40-L53
