### ISSUE TITLE
Feature Request: fetch all/multiple GCP Projects

### ISSUE THREAD

**Issue by thraxil** [cloudquery/cloudquery#33]
We structure our GCP setup by heavily using Projects to organize things. Currently we have about 120 separate projects.

Since cloudquery's config has `project_id`, I would need to generate a config with 120 stanzas to allow it to fetch all of our data. Obviously I can hack that together using the output from `gcloud projects list` and some scripting, but it would be much nicer if there were a clean way to just tell cloudquery to fetch fetch all of them or some subset of them.

I'm happy to contribute this kind of functionality, but I wanted to first make sure that it would be the kind of contribution that you'd be willing to take and what kind of preferences you had for how it should be configured.

Eg, an obvious approach would be to add a `projects_filter` field to the config that would (if present) replace `project_id` field and tell cloudquery to fetch data for all the projects that match it. Either some kind of regex/glob matching or handling the same filter syntax that `gcloud projects list --filter=....` accepts.

The other part of that functionality would also be to add a `gcp_project` resource since GCP projects have their own metadata (eg we use tags on projects to organize things per team/customer/etc) and I would probably want to be able to query that metadata the same as with compute/storage/etc resources.

**Comment by yevgenypats** [comment]
Hi @thraxil Thanks for posting this and describing this in detail!

We've changed the GCP [config](https://docs.cloudquery.io/gcp/tables-reference) `yaml` so you can specify list of `project_ids` in [v0.8.0](https://github.com/cloudquery/cloudquery/releases/tag/v0.8.0).

I'll be happy if you can test it and let me know if it works as expected.

Regarding Project resource - sure we'll add this shortly as well.

**Comment by thraxil** [comment]
@yevgenypats that's an improvement, but still means that someone with multiple projects would need to gather that list of project ids first. We have projects being created and deleted on a daily basis, so that would be really annoying to maintain. I'm really looking to be able to just do `projects: *`, `projects: myorg-prod-*`, or `projects_filter: "labels.environment: prod"` or similar.

**Comment by yevgenypats** [comment]
@thraxil Got it. I've added a a `project_filter` keyword which behaves like `--filter` and by default behaviour which will source all accessible projects if none specified. Let me know if that works better?

https://docs.cloudquery.io/gcp/tables-reference
