### ISSUE TITLE
Output is being cut instead of wraparound/new line

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#333]
### Describe the Bug

Running something like the following:
```
ep@macbook-pro-73 aws % cloudquery policy run
Starting policies run...

❌policy "cis" -  error: failed to load policy: failed to parse policy file: "pci_dss_v3.2.1/polic…  

📋 cis Results:

❌ Policy failed to run
Error: failed to load policy: failed to parse policy file: "pci_dss_v3.2.1/policy.hcl:103,27-68: Invalid function argument; Invalid value for \"path\" parameter: stat queries/ec2/public_ingress_on_port_22.sql: no such file or directory., and 1 other diagnostic(s)"

Finished policies run...

ep@macbook-pro-73 aws % 
```

**Comment by bbernays** [comment]
Information is being truncated when we try to [update the progress bar](https://github.com/cloudquery/cloudquery/blob/5e109611970046c6cac0a196ebf1b164e7f2fe4b/pkg/ui/console/client.go#L540)

The [progress bar library](https://github.com/vbauerster/mpb/blob/9873d129c59f5eda83a5ce419b75f070abd0df09/bar.go#L431-L465) automatically truncates everything beyond the width of the terminal window:


I am not sure it is that serious of an issue for us to pursue this any further as the full text of the error is printed out in the `Results` section. @yevgenypats thoughts?

**Comment by yevgenypats** [comment]
Running sql directly now and not part of cq cli now - https://github.com/cloudquery/cq-provider-aws/tree/main/policies
