### ISSUE TITLE
PCI DSS Policy formatting is weird

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#334]
### Describe the Bug
Running
```
cloudquery policy run cloudquery-policies/aws aws/pci_dss_v3.2.1

ep@macbook-pro-73 aws % cloudquery policy run cloudquery-policies/aws aws/pci_dss_v3.2.1 
Starting policies run...

Downloading Policy cloudquery-policies/aws
✓ policy "cloudquery-policies-aws" -  evaluating -                1s   Finished Queries: 82/82

📋 cloudquery-policies-aws Results:

⚠️ Policy finished with warnings

	✓   autoscaling_groups_elb_check              Auto Scaling groups associated with a load balancer should use health checks                                                   passed

	❌  1                                         CloudTrail logs should be encrypted at rest using AWS KMS keys                                                                 failed

```

Produces the Following output

**Comment by bbernays** [comment]
@yevgenypats- The output for PCI DSS is now consistent across all policies. If we want to print out the the full path of the policy (Not just the query name) then it will require more changes.

**Comment by yevgenypats** [comment]
> @yevgenypats- The output for PCI DSS is now consistent across all policies. If we want to print out the the full path of the policy (Not just the query name) then it will require more changes.

I was mainly referring to the huge space 
```
❌  1                                         CloudTrail
```
I guess maybe we need to think about a better way to show/format in general. Prob not high priority but still.

**Comment by bbernays** [comment]
This issue was occurring because one query had a long name. We define the size of the name column based on the largest column
