### ISSUE TITLE
Validate Consistent Data Structure Across Resources

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#3347]
Within a source plugin there can be fields that all (or most) resources have that require transformations in order to expose a consistent experience. The field can be added in multiple ways or can be there by default. For example in the AWS provider `Tags` is a field that sometimes is included in the Get Resource call or sometimes it is a standalone call (see RDS)... We need a way of ensuring that all resources that have a specific field name always have the same structure.

This could be done at one of the following places:
1. Unit test
2. Integration test

I don't think it can be done at Codegen as we cannot ensure that custom resolvers format the data correctly

**Comment by yevgenypats** [comment]
Tagged it as `aws` and `testing` as seems to me this should be aws specific logic that we want to add to unit test

**Comment by bbernays** [comment]
I was trying to keep it generic as the ability to validate specific fields in a source table is something that I think could be useful across all plugins.

**Comment by yevgenypats** [comment]
Ok got it. misunderstood.

**Comment by disq** [comment]
This came into attention with https://github.com/cloudquery/cloudquery/issues/3280 as moving the tag resolver into codegen doesn't help in the case of custom resolvers.

**Comment by erezrokah** [comment]
Going to close this as non actionable at the moment. We've added some structure testing to tags specifically https://github.com/cloudquery/cloudquery/blob/6342e0251db735ffbcb4e133456463410d9f9725/plugins/source/aws/client/testing.go#L90 but still missing more validation https://github.com/cloudquery/cloudquery/blob/6342e0251db735ffbcb4e133456463410d9f9725/plugins/source/aws/client/testing.go#L100

If you think this is still relevant please open an actionable suggestion/RFC to fix the issue
