### ISSUE TITLE
feat(website): Don't process Markdown files as MDX files

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#3358]
This is blocked by https://github.com/shuding/nextra/issues/709

Our build framework parses Markdown files as MDX files, which causes memory issues and often fails, limiting our ability to add new markdown files to our Website.

cc @cqgaurav

We should consider contributing to Nextra to be able to configure this (assuming it's not too much work), then use that configuration in our build process.

**Comment by yevgenypats** [comment]
I'll be closing this as we move our plugin configuration to our own registry so documentation in nextra/docs should be kept pretty light as it will only be used for our CLI/managed version

**Comment by erezrokah** [comment]
💯 Also https://github.com/shuding/nextra/issues/709 was resolved a while back so it solved the original issue we had too
