### ISSUE TITLE
AWS: Some ARNs are invalid

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#3466]
### Describe the Bug
As described in the "Resource Issues" section of https://github.com/cloudquery/cloudquery/issues/3067 , some resources that don't have ARNs in the AWS side have a made-up `arn` column instead of using composite keys:

- aws_ec2_instance_statuses
- aws_ec2_instance_types
- aws_ec2_vpc_endpoint_service_configurations

Possibly more.

### Expected Behavior
ARNs should match with the AWS format and availability.

### CloudQuery Version
`plugins-source-aws-v3.8.0`

### References
https://github.com/cloudquery/cloudquery/issues/3067

**Comment by candiduslynx** [comment]
Should be addressed via #3210, too.
As [mentioned](https://github.com/cloudquery/cloudquery/issues/3210#issuecomment-1339697196) there:
1. We have a description [here](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
2. We have a reference with all (supposedly generated) ARN formats in [Service Authorization Reference](https://docs.aws.amazon.com/service-authorization/latest/reference/)
3. We could utilize the info from [gen source](https://github.com/aws/aws-sdk-go-v2/tree/main/codegen/sdk-codegen/aws-models)
