### ISSUE TITLE
Support rbac-authentication in k8s.

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#3467]
### Is your feature request related to a problem? Please describe.
Currently, k8s only supports authentication via config-file.
It can be useful to also support rbac-authentication (i.e. running in a pod, without a kubeconfig file).

**Comment by cychiang** [comment]
It sounds like it will be a different scenario. By looking at the [code](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/k8s/client/client.go#L64) for handling k8s client. It supports multiple context so the CQ can retrieve data from different k8s cluster. 

So when implementing the rbac for CQ and it needs to bind the role to a service account and assign the account to a pod. So I guess by supporting this then users are only be able to retrieve the usage of current cluster? 

If CQ wants to support getting data from multiple k8s cluster then one possible way in AWS is to setup a EKS cluster with OIDC and IRSA then assign permissions for accessing other EKS cluster then bind the IAM role with service account so CQ can use that service account to generate context for other EKS cluster. 

Maybe it's too complicate in the early stage but would like to discuss a little bit to see whether I'm capable to help with this task or not.

**Comment by shimonp21** [comment]
Also adding @yevgenypats to this discussion.

**Comment by candiduslynx** [comment]
I suppose it was implemented in #7296
