### ISSUE TITLE
MySQL identifier too long

### ISSUE THREAD

**Issue by zscholl** [cloudquery/cloudquery#35]
👋 When running cloudquery against AWS resources using MySQL I get the below error
```
Error 1059: Identifier name 'fk_aws_redshift_cluster_parameter_group_statuses_cluster_parameter_status_list' is too long
```

MySQL has a 64 character limit on column names and it looks like that is not adjustable: https://dev.mysql.com/doc/refman/5.7/en/identifier-length.html

Maybe column names should be truncated depending on providers? Or as a configuration option?

**Comment by yevgenypats** [comment]
@zscholl Hi! I pushed a fix to [v0.8.5](https://github.com/cloudquery/cloudquery/releases/tag/v0.8.5). I think this is second time this bug surface so it's good time to add basic system tests. I'll add those tomorrow and it should catch those kinds of issues before release/merge.

**Comment by zscholl** [comment]
Wow thanks! 😄 

Yeah some basic validation tests that create the tables for each supported database would be a great addition 👍

**Comment by zscholl** [comment]
Tested the fix and it works, thank you!
