### ISSUE TITLE
Lambda Debugging Improvements

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#355]
### Is your feature request related to a problem? Please describe.
When debugging CQ running on lambda we need better diagnostics information being logged
### Describe the solution you'd like
Fields/Params to log:
1. All items in [cfg](https://github.com/cloudquery/cloudquery/blob/f9e9ba5fcd65a39034170adb420426d9a70ec5d8/deploy/lambda.go#L16)
2. All `CQ_*` environment variables
3. Version of cloudquery being executed
4. Event input

**Comment by yevgenypats** [comment]
Lambda not supported anymore. closing.
