### ISSUE TITLE
bug: gcp_compute_addresses migration failed to drop column id

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#3564]
Reported by d0uble3l on Discord:

```
Error: failed to migrate source gcp on destination postgresql : failed to call Migrate: rpc error: code = Unknown desc = failed to drop column id on table gcp_compute_addresses: ERROR: cannot drop column id of table gcp_compute_addresses because other objects depend on it (SQLSTATE 2BP01) 
```

**Comment by disq** [comment]
If there's a view drop won't work. In the past we ran a query to check if there were any dependent views and warned the user before forcing the drop/alter ((nostalgia link)[https://github.com/cloudquery/cloudquery/commit/bb93967803a28dfc1fccc0fb45af207d76208b2d#diff-51f8c1b2c2b3859a7998a22ac3f61c4c5ce929429f92642fea9c1015aac82b4aR263])

**Comment by hermanschaaf** [comment]
Thanks for the context @disq! It looks like this was caused (in this instance) by running CloudQuery v1 against a database created with a v0 version. There are many breaking changes between v0 and v1, so this is not expected to work: in this case the best advice is to drop the old database and create a new one using v1.
