### ISSUE TITLE
Anonymized stats: track when sync ends

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#3566]
Right now we only send stats when the sync completes, but it would be useful for us to also track when the sync starts, so that we can get a sense of how often syncs are started but not completed (which could be an indication of issues with the plugin or documentation around it).

**Comment by erezrokah** [comment]
We should probably hook into Cobra and track all commands start/exit with flags and exit code

**Comment by hermanschaaf** [comment]
I think we should reframe this ticket, and rather than log whenever a sync starts, we should make sure we log whenever the sync ends (regardless of when it's from a panic, ctrl+c, etc)

**Comment by hermanschaaf** [comment]
Will be closed by https://github.com/cloudquery/cloudquery/pull/7756

**Comment by erezrokah** [comment]
Can we release https://github.com/cloudquery/cloudquery/pull/7756? Looks like it's approved
