### ISSUE TITLE
AWS: UnauthorizedOperation - fatal

### ISSUE THREAD

**Issue by hitesh50** [cloudquery/cloudquery#36]
AWS response "UnauthorizedOperation: You are not authorized to perform this operation" doesn't seem to be handled properly.   Cloudquery abruptly stops when it gets such response message

2021/01/16 17:39:57 UnauthorizedOperation: You are not authorized to perform this operation.
        status code: 403, request id: d001de6e-cb48-446e-a402-8fc8c67ff275

**Comment by yevgenypats** [comment]
@hitesh50 Thanks for reporting. We pushed a fixed to [v0.8.6](https://github.com/cloudquery/cloudquery/releases/tag/v0.8.6). Let me know if this is resolved.

**Comment by hitesh50** [comment]
Resolved - Thanks
