### ISSUE TITLE
Detect FaaS

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#366]
### Describe the Bug
The env variable `AWS_EXECUTION_ENV` is actually set when using AWS ECS Fargate and EC2 as well as Lambda

### Expected Behavior
Only find FaaS environments

### References

- [Source-1](https://stackoverflow.com/questions/54177061/is-it-possible-to-detect-fargate-without-trying-the-metadata-api)
- [Source-2](https://github.com/jeshan/fargate-environment-variables)

**Comment by disq** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

Do you think we should remove `AWS_EXECUTION_ENV` check (there are other env vars anyway) or check for `AWS_Lambda_` prefix?

**Comment by bbernays** [comment]
I think probably the `AWS_LAMBDA_FUNCTION_NAME` is enough
