### ISSUE TITLE
AWS: UnsupportedOperationException 

### ISSUE THREAD

**Issue by hitesh50** [cloudquery/cloudquery#37]
Looks like another exception need to be handled, for continued processing

UnsupportedOperationException: arn:aws:kms:us-east-2:XXXXXX:key/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx origin is EXTERNAL which is not valid for this operation.

**Comment by yevgenypats** [comment]
@hitesh50 can you please share your `config.yml` and the command you are running? I'll try to reproduce it

**Comment by hitesh50** [comment]
I am running "./cloudquery fetch" command

Here is the config.yml file....
providers:
  - name: aws
    accounts: # Optional. if you want to assume role to multiple account and fetch data from them
      - role_arn: arn:aws:iam::111111111000:role/AWS_Role
#    regions: # Optional. if commented out assumes all regions
#      - us-east-1
#      - us-west-2
#    log_level: debug
    max_retries: 5 
    resources: # You can comment resources your are not interested in for faster fetching.
      - name: autoscaling.launch_configurations
      - name: cloudtrail.trails
      - name: directconnect.gateways
      - name: ec2.customer_gateways
      - name: ec2.flow_logs
      - name: ec2.images
      - name: ec2.instances
      - name: ec2.internet_gateways
      - name: ec2.nat_gateways
      - name: ec2.network_acls
      - name: ec2.route_tables
      - name: ec2.security_groups
      - name: ec2.subnets
      - name: ec2.vpc_peering_connections
      - name: ec2.vpcs
      - name: ecs.clusters
      - name: ecr.images
      - name: efs.filesystems
      - name: elasticbeanstalk.environments
      - name: elbv2.load_balancers
      - name: emr.clusters
      - name: fsx.backups
      - name: iam.groups
      - name: iam.password_policies
      - name: iam.policies
      - name: iam.roles
      - name: iam.users
      - name: kms.keys
      - name: rds.certificates
      - name: rds.clusters
      - name: rds.db_subnet_groups
      - name: redshift.clusters
      - name: redshift.cluster_subnet_groups
      - name: s3.buckets

**Comment by yevgenypats** [comment]
@hitesh50 Good catch. This is related to some nuances in AWS SDK, we now check if it is an EXTERNAL key before calling the unsupported API. This should be fixed in  [v0.8.7](https://github.com/cloudquery/cloudquery/releases/tag/v0.8.7) (it is currently building)

**Comment by hitesh50** [comment]
@yevgenypats - Thanks for your help resolving this
