### ISSUE TITLE
Flaky crash: `failed to create new OS thread`

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#3722]
### Describe the Bug
```
~/projects/cqtmp % cloudquery sync .
Loading spec(s) from .
Starting sync for:  aws -> [postgresql]
/ Syncing resources... (29977/-, 1186 resources/s) [54s] runtime: failed to create new OS thread
runtime: failed to create new OS thread
failed to terminate source client:  source plugin process exited with status exit status 1
Error: failed to sync source aws: failed to fetch resources from stream: rpc error: code = Unavailable desc = error reading from server: EOF
```

### CloudQuery Version
```
cloudquery version 1.5.3
aws: 4.3.0
postgresql: 1.6.1
```

**Comment by candiduslynx** [comment]
https://pkg.go.dev/runtime/debug#SetMaxThreads
According to the description we either need to increase this amount OR take a look at scheduling mechanisms (limit the amount of active resolvers/API calls running).

**Comment by candiduslynx** [comment]
Tried to add an option to tune goroutines per thread (https://github.com/cloudquery/plugin-sdk/pull/400), but for now this seems too flaky to be able to make something of it.
