### ISSUE TITLE
AWS Service Quotas should have tags

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#3723]
[API Reference](https://docs.aws.amazon.com/servicequotas/2019-06-24/apireference/API_ListTagsForResource.html#API_ListTagsForResource_RequestSyntax) suggests that quotas should also have tags.

**Comment by bbernays** [comment]
CloudQuery cannot grab tags for each resource in its current form as a each quota needs to be fetched individually. As of Nov 2022 there are ~30,000 quotas that would need to be fetched, which would take A LONG time. The number of resources will continue to grow as AWS adds more regions and makes more quotas configurable
