### ISSUE TITLE
Discussion: Should we write nulls into JSON columns that are expected to be arrays?

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#3724]
There are cases where JSON columns are expected to be arrays, and our policy queries then use `JSONB_ARRAY_ELEMENTS` to extract the elements. However, if the returned value from AWS is null, we write `null` into the column, rather than an empty array. When this happens, `JSONB_ARRAY_ELEMENTS` fails. We could, instead, choose to write an empty array in such cases. This would make policy queries simpler, as we wouldn't need to have a switch case on null instances. I'm not sure whether we should do this from a philosophical standpoint though.

See this ticket for additional context: https://github.com/cloudquery/cloudquery/pull/3565#issue-1435794670

**Comment by disq** [comment]
I think they should be valid json object. But can we tell if they're supposed to be arrays or objects? We could do `NOT NULL DEFAULT '[]'` on the dest side and accomodate/skip on insertion but then would it fail if we're expecting `{}` instead (on some cases)?

**Comment by yevgenypats** [comment]
If we want to have defaults then we either need to take care of that on the resolver side or have some kind of default on sdk side, not on destination as it's not db agnostic and will create infinite amount of work. 

but seems to me that we know where are those special columns where we dont want null (so it's not really default) but we want to have a default if not null so maybe we can just do that on the resolver side with `PathNotNullResolver`?

**Comment by disq** [comment]
`PathNotNullResolver` could just look at the cq type, but since cq types don't have a default empty value... maybe call it `PathDefaultResolver` and give it a default in the call... as in `func PathDefaultResolver(path string, default interface{}) ColumnResolver` and if the value is null, have the given `default` casted to the `valuetype` and set into resource?

**Comment by shimonp21** [comment]
Closing for now after https://github.com/cloudquery/plugin-sdk/pull/430.
Let's reopen to discuss again if we run into issues related to nested fields (which https://github.com/cloudquery/plugin-sdk/pull/430 doesn't fix).
