### ISSUE TITLE
Improve policy output

### ISSUE THREAD

**Issue by roneli** [cloudquery/cloudquery#380]
Improve policy output to be more consistent, allow users to define what defines a success/failure in the check, what is the identifier etc' allow to add failure description allowing reader to understand what is problematic and how to fix.

This feature will built above policy v3 #369 refactor,

**Comment by bbernays** [comment]
Related enhancement: https://github.com/cloudquery/cq-provider-gcp/issues/189

**Comment by yevgenypats** [comment]
Running policy directly now - https://github.com/cloudquery/cq-provider-aws/tree/main/policies
