### ISSUE TITLE
UI mode in non-terminal

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#392]
### Is your feature request related to a problem? Please describe.
as reported by a user in discord in scenarios where cloudquery runs in CI or in docker the output is defaulted to logger // non-human output. It would be nice to have a way for a human readable output even for non-terminals and not fallback to logger.

**Comment by erezrokah** [comment]
Should be resolved in [v2](https://github.com/cloudquery/cloudquery/pull/1463)
