### ISSUE TITLE
Optionally, store policy run results in a DB

### ISSUE THREAD

**Issue by paul-e-allen** [cloudquery/cloudquery#393]
### Is your feature request related to a problem? Please describe.

Having to handle JSON files containing detailed `policy run` results is surprising given that CQ is all about shoving configuration into an RDMS.

### Describe the solution you'd like
It would be awesome to be able to use SQL tools and queries to report on `policy run` results.

### Describe alternatives you've considered
Many/most BI tools _can_ ingest JSON directly, so that pathway could help solve the problem.

**Comment by TinLe** [comment]
I would like to make sure that the ability to generate JSON output from policy run continued to be supported.  This can be configured in config.hcl.  Perhaps by default the results are stored in DB, but optionally also generated as JSON file.

**Comment by shimonp21** [comment]
A recent change in how policies work changed the default to insert policy results into the postgres database (`aws_policy_results` / `gcp_policy_results` / ...).

You can find more details here https://docs.cloudquery.io/docs/policies.

output in csv format is also supported (see details in the link above).
