### ISSUE TITLE
bug: ResourceExhausted on GetMetrics RPC call

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#3962]
Error reported by `mosca` on [Discord](https://discord.com/channels/872925471417962546/873606591335759872/threads/1039578140453896192):

```
failed to get metrics for source gcp: failed to call GetMetrics: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9383267 vs. 4194304)" module=cli
```

Version information:

```
cloudquery version 2.0.3

name: gcp
path: cloudquery/gcp
version: "v2.4.6" 

name: postgresql
path: cloudquery/postgresql
version: "v1.6.6"
```

**Comment by hermanschaaf** [comment]
They reported running against 200+ projects in GCP, so it may be that the [`SourceMetrics` map](https://github.com/cloudquery/plugin-sdk/blob/c66be4bb440990327c6e1aa82e5ffdd76659bd07/plugins/source_metrics.go#L9) is simply getting too big. If this is the case, we'll have to split it up before sending it over GRPC.

**Comment by candiduslynx** [comment]
IMO it' just this: https://pkg.go.dev/google.golang.org/grpc#MaxCallRecvMsgSize

**Comment by hermanschaaf** [comment]
@candiduslynx Good call, that looks like a great short-term solution. That said, if the issue really is that the map is getting too big (and not some memory allocation/corruption issue), it's probably only a temporary solution, since it's just a matter of time until we get a large enough number of accounts and clients to exceed the limits again.

**Comment by yevgenypats** [comment]
Yeah we need a way to make sure a message is capped so we need to make it a streaming call that streams metric per table per client

**Comment by jimr6007** [comment]
I have the same issue with AWS plugin, cli 2.0.7, aws source plugin 4.11.3

roughly 50 accounts, and 3 to 4 millions total resources if I tell it to pull all the things but...
I am excluding ecs* and ecr* which is like two thirds of that huge resource count

Error: failed to get metrics for source aws: failed to call GetMetrics: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (36300400 vs. 4194304)

**Comment by hermanschaaf** [comment]
This was fixed by https://github.com/cloudquery/plugin-sdk/pull/396, which was released for official source plugins in these versions:
 - aws [v4.14.0](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-aws-v4.14.0)
 - azure [v1.4.3](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-azure-v1.4.3)
 - gcp [v2.4.14](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-gcp-v2.4.14)

(The latest versions of other official plugins will all also have this fix soon)
 
Upgrading the plugins to these versions should resolve the `GetMetrics ResourceExhausted ` error. Please let me know / re-open the issue if that is not the case!
