### ISSUE TITLE
Add Severity level to checks

### ISSUE THREAD

**Issue by roneli** [cloudquery/cloudquery#398]
Add Severity level to checks, default to HIGH, but can CRITICAL, MEDIUM, LOW.

**Comment by paul-e-allen** [comment]
I second this. Users need a way to prioritize the policy checks that fail.

**Comment by yevgenypats** [comment]
Thanks for the info everyone!

Our policies now are pure SQL so should be relatively easy to add any severity level (or any other metadata) and I think it will be up to the user to define severity as it's really company/use-case specific.

https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/policies_v1
Adding severity here - https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies_v1/create_aws_policy_results.sql
