### ISSUE TITLE
Fetch AWS VPCs and subnets

### ISSUE THREAD

**Issue by Raphx** [cloudquery/cloudquery#4]
Hi, great work on cloudquery!

I'm looking to add a new feature to fetch VPCs and subnets detail as well, is there any work in progress on this one?

I would like to contribute, it would help for my use case.

**Comment by yevgenypats** [comment]
Hi @Raphx , thanks for the issue. I think there is some work in progress and we will push this in the next few days. What can help us is If you describe your use-case so we can test it. Also, once we release it any testing and additional feedback is appreciated.

**Comment by Raphx** [comment]
Thanks for the follow up @yevgenypats. Our use case is very much network-related, most of it is showing relationships between different networking subnets, what I imagine we would need is:

- A list of VPCs and subnets within it, i.e. details for VPC, details for subnet, and association of subnet to the VPC via `VpcId` on each subnet.
- For each VPC, a list of assigned CIDR block for it, i.e. the `CidrBlockAssociations` info for each of the VPC.

Hope this helps. :)

**Comment by yevgenypats** [comment]
Hi @Raphx we added support for [VPCs](https://app.gitbook.com/@cloudquery/s/cloudquery/aws/tables-reference/ec2/vpcs) and [subnets](https://app.gitbook.com/@cloudquery/s/cloudquery/aws/tables-reference/ec2/subnets). Can you please test this and confirm that it works as intended or other feature/tweaks are needed ?

**Comment by Raphx** [comment]
Yes, just what I needed, full details for VPCs and subnets! Great work mates 🎉

**Comment by yevgenypats** [comment]
Awesome. Please feel free to open any issue/feature-request/bugs all feedback is welcome.
