### ISSUE TITLE
bug: Deadlock when running sync

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#4070]
We have received some user reports of a deadlock occurring sometimes when cloudquery is run against many accounts / projects. 

```
      cli: version 1.5     

      path: cloudquery/aws
      version: v4.7.2

      path: cloudquery/postgresql
      version: v1.6.4
```

Discord thread here: https://discord.com/channels/872925471417962546/873606591335759872/threads/1039578413675057213

**Comment by bbernays** [comment]
@hermanschaaf - Have we ever seen this with the GCP plugin or always AWS?

**Comment by hermanschaaf** [comment]
We haven't had any reports of deadlock since https://github.com/cloudquery/plugin-sdk/pull/395 was released, so let's close this and open as a new issue if new reports of deadlock surface.
