### ISSUE TITLE
Command line flags not working to set driver and dsn

### ISSUE THREAD

**Issue by mvaerle** [cloudquery/cloudquery#41]
I'm trying to use command line flags to specify the driver and dsn, but it doesn't look like it's getting picked up. Or maybe I'm doing it wrong. When using environment variables it does work!

This doesn't work, data is still being put in the sqlite database:
`cloudquery fetch --driver postgresql --dsn postgresql://localhost:5432/cloudquery`

while this does work:
`CQ_DRIVER=postgresql CQ_DSN=postgresql://localhost:5432/cloudquery cloudquery fetch`

**Comment by yevgenypats** [comment]
@mvaerle I'm trying to reproduce it. Are you using latest version?

**Comment by mvaerle** [comment]
My bad, upgrading from 0.8.5 to 0.8.7 fixed the issue
