### ISSUE TITLE
Confusing update check failed

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#410]
### Describe the Bug
When running cloudquery vanilla with `--enable-console-log` with any provider you will see the following:

```
WRN update check failed error="open .cq/last-update-check: no such file or directory"
```

What does this message say? why update check failed ? if it's failed why it's a warning?

Example - https://github.com/cloudquery-policies/azure/runs/4816948497?check_suite_focus=true#step:6:8

**Comment by irmatov** [comment]
Reproducible if .cq directory does not exist yet.

**Comment by irmatov** [comment]
Answering question:

Q: What does this message say?
A: Apparently, update check mechanism encountered an error.

Q: why update check failed?
A: there is no .cq directory yet, so this is why it failed (it should've saved that last-update-check file, but .cq dir does not exists).

Q: If it's failed why it's a warning?
A: CQ could be running in some restricted environment, where .cq/last-update-check is not writable for example. (docker container etc). Updates could be handled in some other way (periodic docker build etc). So strictly speaking this is not an error that prevents normal operation, I think.
