### ISSUE TITLE
Constraint error triggering on second fetch call using postgresql

### ISSUE THREAD

**Issue by mvaerle** [cloudquery/cloudquery#42]
When using postgres as a driver and running fetch for the second time I'm getting a constraint error from cloudquery. 

I'm running:
`CQ_DRIVER=postgresql CQ_DSN=postgresql://localhost:5432/cloudquery cloudquery fetch`

The first time it runs nicely, the second time I get the following error:

```
Error: ERROR: constraint "fk_aws_redshift_cluster_parameter_group_statuses_cluster_parame" for relation "aws_redshift_cluster_parameter_statuses" already exists (SQLSTATE 42710)
```

**Comment by yevgenypats** [comment]
I wasn't able to reproduce this one. Can you try and test if it also happens when you start with a clean PostgreSQL database?

**Comment by mvaerle** [comment]
My bad, upgrading from 0.8.5 to 0.8.7 fixed the issue
