### ISSUE TITLE
Scope Policy runs by AWS account, Azure subscription, GCP project

### ISSUE THREAD

**Issue by paul-e-allen** [cloudquery/cloudquery#420]
### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like
When running CQ policies, it would be useful to be able to scope those runs to AWS account, Azure subscription, GCP project, etc. At present, Policy queries apply against all the data CQ has collected and there is no way to inject scoping. 

A use case would be that a central team is managing CQ data fetch and policy runs, but that each AWS account has different owners. In this situation you to want easily generate policy results against subsets of the CQ database so that those results can be sent to account owners separately.

### Describe alternatives you've considered

One could add a `target_aws_account` table in the DB with a single row containing the target account id, and modify Policy queries to  join to that table, restricting query scope. Then do `policy run` one account at a time, updating `target_aws_account` before each targeted `policy run`.

**Comment by yevgenypats** [comment]
We run now sql policies directly with `psql` - https://github.com/cloudquery/cq-provider-aws/tree/main/policies
and storing all the result in one table which should be easy to use with  regular sql to scope and filter by account, framework and so on.

Some example for filterable Grafana dashboards as well - https://github.com/cloudquery/cq-provider-aws/tree/main/dashboards

Closing this as answered. Feel free to reopen if this is incorrect.
