### ISSUE TITLE
Kubernetes Ingress

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#4208]
### Why do you need this resource or plugin? Please describe.
Currently, CloudQuery K8s does not support Kubernetes Ingress.  

### Describe the solution you'd like
Resource support for K8s Ingress.

### Additional context
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by cychiang** [comment]
Looks like this issue has been resolved by https://github.com/cloudquery/cloudquery/pull/4495 
I can see that there is a table for [ingress](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/k8s/resources/services/networking/ingresses.go#L12)

**Comment by jsonpr** [comment]
Thanks, @cychiang for the comment!  Yes, we (CloudQuery) just did a large K8s update - the one you linked in your comment.

I'll close this issue for now.
