### ISSUE TITLE
Fetch Summary violation on multiple providers

### ISSUE THREAD

**Issue by roneli** [cloudquery/cloudquery#423]
### Describe the Bug
If running two providers (two aws provider blocks) you receive 
failed to save fetch summary err="ERROR: duplicate key value violates unique constraint \"fetches_pk\" (SQLSTATE 23505)"

### Expected Behavior
Summary saved for each block

### CloudQuery Version
v0.19.1

### Steps to Reproduce
```
cloudquery fetch
```

Add the following providers to config.hcl

```
provider "aws" {
  configuration {
    aws_debug = false
  }
  // list of resources to fetch
  resources = [
    "lambda.runtimes"
  ]
  // enables partial fetching, allowing for any failures to not stop full resource pull
  enable_partial_fetch = true
}


provider "aws" {
  alias = "aws-2"
  configuration {
    aws_debug = false
  }
  // list of resources to fetch
  resources = [
    "lambda.runtimes"
  ]
  // enables partial fetching, allowing for any failures to not stop full resource pull
  enable_partial_fetch = true
}
```

**Comment by disq** [comment]
Another issue: If provider fails to configure for some reason (bad credentials or something else), finish_time is recorded as time.Zero and error count is also 0. maybe create `fs` and defer the save just before the `for` loop? or the defer func can check if finish_time.IsZero() and set it maybe? or just always set finish_time in the defer?
