### ISSUE TITLE
Validate command for Specs

### ISSUE THREAD

**Issue by RyPeck** [cloudquery/cloudquery#4340]
It would be helpful to have a `validate` sub-command for spec files when configuring the `tables` to sync and avoid accidentally specifying child tables.

**Comment by erezrokah** [comment]
Hi @RyPeck, thanks for opening the issue 🚀 

Can you provide a bit more information on what would be the expected input and output of such a command.
For example:
1. Input: `cloudquery validate <specs-files-or-directories>`
2. Output: A list of errors with the specs or a success message

Is that correct?

If so, won't running `sync` will already fail is the specs are incorrect?
If it doesn't fail when you expect it to fail, can you share your configuration?

**Comment by erezrokah** [comment]
Closing this issue as stale per my comment. @RyPeck please comment if still relevant and I'll re-open
