### ISSUE TITLE
Athena view for resources

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#4383]
### Is your feature request related to a problem? Please describe.
may I ask for some help converting this to a Athena/Presto view:
https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/views/resources.sql

### Describe the solution you'd like

convert this Postgres SQL to Athena/Presto SQL
https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/views/resources.sql

**Comment by bbernays** [comment]
@jimr6007 - Very interested in this request! How are you getting data into Athena/Presto in the first place though?

**Comment by timoguin** [comment]
I'd love to have this too!

**Comment by hermanschaaf** [comment]
Hey @jimr6007 and @timoguin, I just wanted to let you know that we are looking into this! 

As a first step, I've opened this related ticket to document how to load CloudQuery data into AWS Athena: https://github.com/cloudquery/cloudquery/pull/5943

While working on that ticket, like you, I was able to query the data from Athena by setting up a Glue Crawler. It seems to work! However, I found that the crawler gets the schema wrong for many tables, causing queries to fail or return incorrect results. It doesn't seem like there's any particular problem with our CSV output, and it even happens for small files with < 1000 rows, so I'm reaching out to AWS to see what we can do about this. If it doesn't work out, we may need to add support for Parquet as an output format to CloudQuery first, so Glue doesn't need to infer the schema in the first place :)

**Comment by timoguin** [comment]
> Hey @jimr6007 and @timoguin, I just wanted to let you know that we are looking into this! 
> 
> As a first step, I've opened this related ticket to document how to load CloudQuery data into AWS Athena: https://github.com/cloudquery/cloudquery/pull/5943
> 
> While working on that ticket, like you, I was able to query the data from Athena by setting up a Glue Crawler. It seems to work! However, I found that the crawler gets the schema wrong for many tables, causing queries to fail or return incorrect results. It doesn't seem like there's any particular problem with our CSV output, and it even happens for small files with < 1000 rows, so I'm reaching out to AWS to see what we can do about this. If it doesn't work out, we may need to add support for Parquet as an output format to CloudQuery first, so Glue doesn't need to infer the schema in the first place :)

Awesome! I've been watching the output pretty intently!

Parquet would most certainly be the "righter" way, but great work on everything so far!

**Comment by timoguin** [comment]
Oh and I forgot to mention, Glue Crawlers are certainly not a requirement. Particularly if the schema is already known, it can be defined manually in Athena by using Apache Hive DDL to create the tables.

**Comment by hermanschaaf** [comment]
Hi @timoguin and @jimr6007! 👋  We've been slowly chipping away at this problem, and it is now very feasible to load all your infrastructure data into S3 and query it from Athena. We've also been able to iron out the schema issues we were seeing with the initial CSV version. Here is a how-to guide describing how to do it with the new S3 (JSON) plugin and a glue crawler: https://www.cloudquery.io/how-to-guides/how-to-load-infrastructure-data-into-athena

Converting the resources view to Athena syntax like @jimr6007 requested should now not be too difficult, I will give it a shot 😄

**Comment by peterfigueiredo** [comment]
Me too! Very interested on this honestly.

**Comment by sfanous** [comment]
@hermanschaaf @peterfigueiredo 

I believe the following query should get it done. I wrote it but haven't fully tested it yet

```sql
with aws_tables as (
    select table_name
    from information_schema.columns
    where table_name like 'aws_%s'
        and column_name = 'account_id'
    intersect
    select table_name
    from information_schema.columns
    where table_name like 'aws_%s'
        and column_name = 'arn'
),

select_statements as (
    select concat('select _cq_id, _cq_source_name, _cq_sync_time, ',
        '''',
        table_name,
        '''',
        ' as _cq_table, account_id, ',
        case
            when
                exists (
                    select 1
                    from
                        information_schema.columns
                    where
                        information_schema.columns.column_name = 'region'
                        and information_schema.columns.table_name = aws_tables.table_name
                ) then 'region'
            else concat('''', 'unavailable', '''')
        end,
        ' as region, arn, ',
        case
            when
                exists (
                    select 1
                    from
                        information_schema.columns
                    where
                        information_schema.columns.column_name = 'tags'
                        and information_schema.columns.table_name = aws_tables.table_name
                ) then 'json_format(tags)'
            else concat('''', '{}', '''')
        end,
        ' as tags from ',
        table_name
    ) as select_statement
    from aws_tables
)

select concat('create view aws_resources as (',
    array_join(array_agg(select_statement), ' union all '),
    ');') as create_view_statement
from select_statements;
```

Couple of important caveats to note

1. This query will just create the `create view` statement. It will not create the actual View. You'll need to copy the output of this query and execute it yourself.
I would have loved to set this up as an [Athena Prepared Statement](https://docs.aws.amazon.com/athena/latest/ug/querying-with-prepared-statements.html) but unfortunately Athena doesn't support `create view` in prepared statements.

2. The tags in the View are of type `varcher` and not `JSON`. This is again an Athena limitation which uses Hive and Hive in turn doesn't support `JSON` datatype. [These are the only dataypes supported by Athena.](https://docs.aws.amazon.com/athena/latest/ug/data-types.html). What this means is that if you want to process the `tags` column as JSON in your queries you'll need to use `json_parse(tags)` to convert the varchar back to JSON.

I'll try to setup a S3 destination and test this out in the coming days but feel free to let me know if it works for you or not.

**Comment by sfanous** [comment]
There was a small issue in my query as `tags` is already a `varchar`. I have fixed the query, tested it and confirms that the View works as expected.

**Comment by peterfigueiredo** [comment]
@sfanous thanks a lot for the amazing work. 
I tried running your query but the create_view_statement output is empty (but it runs successfully).
In the query, where do we specify the database to run the query into? That is most likely the problem I think information_schema is missing.
![query](https://user-images.githubusercontent.com/37262279/218415319-9718d7db-8d0d-465f-b188-e780787a6956.png)

**Comment by hermanschaaf** [comment]
Thanks for sharing that @sfanous, looks great! 

So I think we have two solutions now, you can use the one the fits your needs:
 - @sfanous 's [query](https://github.com/cloudquery/cloudquery/issues/4383#issuecomment-1427110428) can be run, and the output copy-pasted to create the view. 
 - if you want to automate the process (or run it on a schedule), another option is to use the script that I wrote here: https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/views/athena, which will create the view for you based on your information_schema. It can be run either as a standalone binary or as a Lambda function, and you should be able to set this up to run after every CloudQuery sync.
 
@sfanous If you want to open a PR to add your query to the `plugins/source/aws/views/athena` directory along with a note in the Readme, I'd be happy to include it!

**Comment by sfanous** [comment]
> Thanks for sharing that @sfanous, looks great!
> 
> So I think we have two solutions now, you can use the one the fits your needs:
> 
> * @sfanous 's [query](https://github.com/cloudquery/cloudquery/issues/4383#issuecomment-1427110428) can be run, and the output copy-pasted to create the view.
> * if you want to automate the process (or run it on a schedule), another option is to use the script that I wrote here: https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/views/athena, which will create the view for you based on your information_schema. It can be run either as a standalone binary or as a Lambda function, and you should be able to set this up to run after every CloudQuery sync.
> 
> @sfanous If you want to open a PR to add your query to the `plugins/source/aws/views/athena` directory along with a note in the Readme, I'd be happy to include it!

https://github.com/cloudquery/cloudquery/pull/7990

Tried to fit it into the existing Readme as best as I could.
