### ISSUE TITLE
AWS IAM Users created in the last 4 hours might not be picked up.

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cloudquery#44]
AWS IAM Users are loaded via GetCredentialReport. Credential reports can only be generated every 4 hours, so resources might not be picked up if you created a user within the last 4 hours.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html

**Comment by yevgenypats** [comment]
@James-Quigley Thanks for pointing this out (I wasn't aware of this)! I guess the right approach here would be to use the AWS SDK API directly (Though the credentials report contains some information that is not exposed via the API, maybe we can merge both and get the best of both worlds). What do you think?

**Comment by James-Quigley** [comment]
Agreed! Should likely load users/policies/groups etc directly via their respective apis and merge info with credential report to get that extra data

**Comment by yevgenypats** [comment]
Awesome. I'll add this today/tomorrow.

**Comment by mvaerle** [comment]
Instead of implementing separate calls it might be worthwhile to look at the get-account-authorization-details call that I used here (https://github.com/cloudquery/cloudquery/pull/45). I don't think it contains the password related information from the credentials report, but users, groups, roles and policies are in there.

**Comment by yevgenypats** [comment]
@mvaerle It's possible but just like you said it won't contain `password_enabled`, `password_last_used`, `password_last_changed`, `password_next_rotation`, `mfa_active` which are used for example in a CIS benchmark policy. so I guess we can either use the `get-account-authorization-details` or the standard api (I need to test that `get-account-authroization-details` is not missing anything) and merge it with the report so we will have additional information that is available. I guess this is the best we can do here.

**Comment by dan-compton** [comment]
Sorry, I'm back and probably out of the loop, but I might have related knowledge. 

I seemed to remember that IAM-related actions are relatively expensive and that short-term gap may not be possible to work around without either using [cloudtrail](https://docs.aws.amazon.com/IAM/latest/UserGuide/cloudtrail-integration.html) to get the API call, [tagging](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags_users.html), or STS). 

I worked at a monitoring company wherein I implemented a cloudformation template that installed a "bastion instance" as well as roles and permissions for resource monitoring (like instana).  Importantly, this setup let the bastion instance communicate both with our infrastructure and with the customers.   Our use of cross-account access also let us intervene, store only short-lived tokens aquired via STS, and allow the customer to own the security context (if they uninstall our cloudformation template, we don't have access).

 Here's the [cloudformation](https://github.com/opsee/spanx/blob/master/roler/role-cf.json.tmpl#L18-L34) role that gets installed which allows the bastion instance (health checker) to perform necessary actions on customer infra and ship checks back to us in addition to letting us intervene by manually grabbing creds through STS. 


We ended up centralizing the storage of these short-lived access tokens in a service called Spanx which was essentially an STS credentials cache.  The implementation of the custom credentials provider is [here](https://github.com/opsee/spanx/blob/master/spanxcreds/spanx_provider.go) and plainly performs the task of fetching short-lived credentials for cross-account access from the cache base[d on known session timeout window.](https://github.com/opsee/spanx/blob/master/spanxcreds/spanx_provider.go#L31-L39).

Pretty simple example in test; https://github.com/opsee/spanx/blob/master/spanxcreds/spanx_provider_test.go#L11-L28.

**Comment by dan-compton** [comment]
Is it the case that you have no control over resource creation nor cheap way of being notified?

**Comment by yevgenypats** [comment]
Solved with https://github.com/cloudquery/cq-provider-aws/pull/21
