### ISSUE TITLE
chore(website): Don't hard code Nextra internal CSS classes

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#4549]
At the moment we hard code Nextra internal CSS classes in the Website:
https://github.com/cloudquery/cloudquery/blob/edbc2f7de73d71b658803716bd136f9a162ddc79/website/components/pages/home.tsx#L61

This makes updating Nextra very difficult as there's no guarantee the class names won't change (either by name or style).

> This is somehow blocked by https://github.com/shuding/nextra/issues/332 that should allow us to re-use components instead of creating our own and hard coding the classes

**Comment by yevgenypats** [comment]
Closing as stale. especially as we move towards our own next.js website
