### ISSUE TITLE
Add MongoDB as a supported destination 

### ISSUE THREAD

**Issue by misczak** [cloudquery/cloudquery#4610]
### Why do you need this resource or plugin? Please describe.
We have been building views in Postgres to support requests from our cloud and security team members. Some of these views require us to write complex joins and pull out atomic elements from JSON arrays to satisfy the conditional logic. Supporting MongoDB would simplify the data model and make it easier to create reports and views, therefore enhancing the value of cloudquery to our teams. 

### Describe the solution you'd like
A destination plugin that allows results to be sent to a MongoDB database, either a self-managed one or one on the Atlas managed service. The latter might require support for Atlas' SRV connection strings to help streamline connectivity. 

### Additional context
MongoDB Atlas support would be especially useful, as it has a built-in Charts feature that would make it even easier to visualize the current state of our cloud footprint.

**Comment by erezrokah** [comment]
Thanks for the issue @misczak, in case someone wants to pick this up, visit https://www.cloudquery.io/docs/developers/creating-new-plugin to get started

**Comment by yevgenypats** [comment]
This is available now: https://www.cloudquery.io/docs/plugins/destinations/mongodb/overview
