### ISSUE TITLE
Target data fetches to a subset of accounts or resource types

### ISSUE THREAD

**Issue by paul-e-allen** [cloudquery/cloudquery#462]
### Is your feature request related to a problem? Please describe.
n/a

### Describe the solution you'd like
Since data fetching can be time-consuming if there are a lot of AWS accounts, Azure subscriptions, etc. configured in `config.hcl`, it would be nice to be able to target a fetch to a subset of the accounts configured. 

Another targeting dimension might be the resource type. E.g., refresh the data for all accounts, but just for the `ec2.vpcs` resource type.

### Describe alternatives you've considered
You could use a secondary `config.hcl` that contains configuration for just the target account(s) or resource types.

**Comment by roneli** [comment]
lets say we have the following config:
```
provider "azure" {
  resources = ["*"]
}

provider "aws" {
  configuration {
    aws_debug = false
  }
  // list of resources to fetch
  resources = [
    "s3.buckets"
  ]
  // enables partial fetching, allowing for any failures to not stop full resource pull
  enable_partial_fetch = true
  // Limit provider to fetch only 5 resources at a given time
  max_parallel_resource_fetch_limit = 5
}


provider "aws" {
  alias = "aws-2"
  configuration {
    aws_debug = false
  }
  // list of resources to fetch
  resources = [
    "*"
  ]
  // enables partial fetching, allowing for any failures to not stop full resource pull
  enable_partial_fetch = true
}
```

Would adding a keyword to fetch i.e `cq fetch azure aws-2` be helpful? Where this would run aws-2 block and azure provider blocks only.

 I am trying to think how to substitute resources via command line that will make it simpler to give it more granular control.

**Comment by paul-e-allen** [comment]
Yes, that seems like a reasonable solution.

**Comment by paul-e-allen** [comment]
I've been thinking a little more about that possible solution. As I look forward to support for AWS Organizations and Org-aware configuration for the AWS provider, I'm not sure the alias idea would work well. It _could_ still work, but it would destroy the utility of the Org-aware provider configuration (where we just provide a role in the master account, and name a role to assume in linked accounts) because you would end up having to list out every account that you might want to target directly (with an alias).

Still, the alias approach is better than nothing.

**Comment by roneli** [comment]
Hi @paul-e-allen we release this feature in v0.20.2, see examples in #468, you can close this issue if this feature solves this for you.

**Comment by paul-e-allen** [comment]
I've finally had a chance to try out this new feature. I like it! Thanks!
