### ISSUE TITLE
Documentation Issue in K8s

### ISSUE THREAD

**Issue by SCKelemen** [cloudquery/cloudquery#4685]
Some fields in the K8s pods table is prefixed with `spec_` in the database, but this prefix is not reflected in the docs:
https://github.com/cloudquery/cloudquery/blob/main/plugins/source/k8s/docs/tables/k8s_core_service_accounts.md

![Screenshot 2022-11-15 at 18 28 48](https://user-images.githubusercontent.com/4325375/201986586-65bd970b-f520-491d-a164-564bcf5aaa3b.png)

K8s 2.4.0
psql 1.7.11
cli 2.0.17

**Comment by erezrokah** [comment]
Hi @SCKelemen can you verify the link to the docs you mentioned, the link to pods is https://github.com/cloudquery/cloudquery/blob/main/plugins/source/k8s/docs/tables/k8s_core_pods.md which does have the `spec` prefix

**Comment by erezrokah** [comment]
Closing as stale per @shimonp21. This should be fixed in later versions of the k8s plugin
