### ISSUE TITLE
refactor(aws): Remove 10 different types of creating ARNs

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#4689]
We need to remove all functional "dry" components creating `arn` as it makes the code hard to maintain and error prone. We only want to use `arn.ARN` without any wrapper as we prefer "KISS" over "DRY" especially when all the functional component dont really make the code shorter but rather creating a maze of functional components that create a string.

**Comment by disq** [comment]
Remove 10.... but keep the rest? 😂 

`client.ARN` has 24 usages
`client.AccountGlobalARN` and `client.PartitionGlobalARN` has 3 each
`client.RegionGlobalARN` seems to have 17

So it's to remove 44 method calls and replace them with `arn.ARN`, also remove `client.makeARN`
