### ISSUE TITLE
Default AWS CIS policy does not work with Postgres

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cloudquery#47]
The policy generated by `cloudquery gen policy aws_cis` is not compatible with postgres in several ways:

1. boolean values in postgres queries should be `false` instead of 0
2. Date types don't need to be converted
3. Comparing against 30 days ago e.g. can be done like: `(now() - '30 days'::interval)`
4. The VIEW that gets created fails because "column 'id' specified more than once
5. The root account hardware MFA check fails due to invalid group by
6. The filter patterns that use the view aren't valid for postgres

Maybe the `cloudquery gen` command could take in the same `--driver` flag and based on that it could switch which policy file it outputs?

**Comment by yevgenypats** [comment]
@James-Quigley Thanks for bringing this up. I'm actually working on putting the policy outside of this repository and adding the `--driver` flag just as you suggested. It's in the works but this specific feature will take a few weeks. Hopefully after that it will be very easy to add new policies.

**Comment by yevgenypats** [comment]
This should be solved now with https://github.com/cloudquery/cloudquery/releases/tag/v0.11.2 as we support only PostgreSQL (out of relational databases, Neo4j still experimentally supported)
