### ISSUE TITLE
Migrate only the tables specified in config

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#4715]
Currently migrations are performed for all tables supported by the source plugin. I believe it would make sense to limit these only to the tables specified in the config. 

This would have these advantages:
 - only tables specified in the config will be created, no others
 - faster migrations for configs that select specific tables
 - no chance of a migration for a skipped table affecting the outcome of a sync
 - fine-grained control over which tables to migrate at any time

**Comment by bbernays** [comment]
I am simultaneously very weary and excited about this because it opens up the possibility of having multiple versions of the same provider in a single postgres database

**Comment by hermanschaaf** [comment]
@bbernays Oh, I hadn't thought of that 😬 Good point! Should be fine though...
