### ISSUE TITLE
Write errors don't show up in summary

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#4717]
### Describe the Bug
An error like this (originating from the destination plugin):
```
2022-11-16T10:44:47Z ERR failed to execute batch with pgerror error="ERROR: null value in column \"id\" of relation \"digitalocean_space_cors\" violates not-null constraint (SQLSTATE 23502)" module=pg-dest
```

Should show up to the user in the summary - but in this case the summary did not show this error (the `2` is from fetch-permissions-denied...)

```
~/projects/cqdo % cloudquery sync .
Loading spec(s) from .
Starting migration for: digitalocean -> [postgresql]
Migration completed successfully.
Starting sync for:  digitalocean -> [postgresql]
Sync completed successfully. Resources: 499, Errors: 2, Panics: 0, Time: 5s
~/projects/cqdo % vim cloudquery.log
```

The database is empty (because the entire batch failed...)

### CloudQuery Version
```
cloudquery version 2.0.18
digitalocean version 2.2.21
postgres plugin version 1.7.11
```

**Comment by erezrokah** [comment]
I moved this to the next sprint (6) and unassigned @yevgenypats so we can re-assign someone when we start working on this

**Comment by shimonp21** [comment]
Closing - this behavior was fixed.
Right now - write errors cause a CLI crash, so no chance of them going unnoticed
