### ISSUE TITLE
Expose stats related to the sync

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#4718]
It is currently quite hard to determine which tables take the longest to sync or fetch the most data. For the purposes of fine-tuning performance, this would be useful information, since it would allow users to decide whether they would rather skip certain tables if they take long but don't contain information they are necessarily interested in.

I'm unsure what the best way to expose this would be, but I will propose something simple to start with here. We can also consider other proposals, or start simple and build on the foundations into the future.

The simplest way I can think of is to write an INFO log message when a table finishes syncing, stating how many resources were fetched and how long it took (and maybe, down the line, also how many API calls were made?). The downside of this is that if your sync is still running, you can't easily tell which resources are still being fetched. To remedy this, maybe we can also output an INFO message every minute with some stats about the tables that are in-progress.

Some other options considered:
 - show the current table(s) being synced as part of the CLI output? This list might be too long.
 - a prometheus endpoint? We don't have a long-running server right now.

**Comment by erezrokah** [comment]
Adding https://github.com/cloudquery/cq-provider-sdk/pull/237/files for context (not saying we should take that approach). In v0 we had a heartbeat mechanism that periodically logged fetch/sync stats.
We added it mostly to see what resources are stuck/mostly stuck/hanging.

**Comment by amanenk** [comment]
We could make additional stats as a flag that shows top 3 longest to fetch tables with time during fetch.
Also. it could give a list of longest resources to fetch in the end, but user would need to wait until the ending of the fetch.

We had a table to store metadata about fetches. If we had something like this we could do a tool that could list old fetches and create reports based on fetches data.

**Comment by erezrokah** [comment]
Hi @edomaur, thanks for adding your comment. Can you share which log message is missing with the new update? An example for what you were using will be great

**Comment by edomaur** [comment]
hi @erezrokah. I don't have the exact description, but what I fetched from the logs was the final status of the sync that is printed by the cli tool, which tells the quantity of resources, errors, panics and total duration of the run.

**Comment by erezrokah** [comment]
Hi @edomaur 👋 
We're currently working on a standardized approach to collecting telemetry via OpenTelemetry, see [here](https://github.com/cloudquery/plugin-sdk/pull/1097).

We're hoping to have an initial version of plugins and CLI ready by the end of next week.
Once we have docs ready, I'll link them in this issue. Sorry for the log changes, and I hope we can get something working for you soon

**Comment by erezrokah** [comment]
The docs for OpenTelemetry are up, see https://www.cloudquery.io/docs/advanced-topics/monitoring#opentelemetry-preview and https://www.cloudquery.io/docs/reference/source-spec#otel_endpoint-preview

**Comment by erezrokah** [comment]
I'm going to close this with the initial release version of OpenTelemetry released. If there's anything else that needs to be expoed, please open a dedicated issue with the metrics you'd like to have
