### ISSUE TITLE
Error while executing psql policy.sql for AWS policies

### ISSUE THREAD

**Issue by gtsopour** [cloudquery/cloudquery#4731]
### Describe the Bug
When executing 
psql ${DSN} -f policy.sql

"Executing check Cloudfront.3"
psql:queries/cloudfront/viewer_policy_https.sql:15: ERROR:  cannot extract elements from a scalar

**Comment by bbernays** [comment]
@gtsopour Thank you for opening this issue! I have been able to replicate it on our environment... working on a fix now
