### ISSUE TITLE
VMWare

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#4799]
Rest API: https://developer.vmware.com/apis/vsphere-automation/latest/
Not sure if they have a go sdk, some other sdks are here : https://developer.vmware.com/sdks

**Comment by candiduslynx** [comment]
I wonder if this [example](https://github.com/vmware/go-vcloud-director/blob/main/samples/discover/discover.go) might be of any use.

**Comment by yevgenypats** [comment]
Closing for now until someone will reopen/request.
