### ISSUE TITLE
Request for query command to optionally return output in a machine readable format e.g. json/yaml

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cloudquery#48]
For anyone looking to utilize the policy packs programmatically or in CI, it would be useful to be able to have the output from the `query` command be in format more easily parsed, such as json or yaml.

**Comment by yevgenypats** [comment]
I think it should be possible via `--output` flag for `query` command. It output to a json file. Let me know if this works as expected?

**Comment by James-Quigley** [comment]
Ah missed that in the command help. That does work, however it isn't quite properly formatted json. Its a bunch of individual json objects. Perhaps they should be in a list?

**Comment by James-Quigley** [comment]
Writing up a fix for this. Will submit a PR soon
