### ISSUE TITLE
Destination Plugin Request: Elasticsearch

### ISSUE THREAD

**Issue by cloudmatt** [cloudquery/cloudquery#4800]
### Why do you need this resource or plugin? Please describe.

Elasticsearch is a popular log/metric aggregation backend in the security/ops world (Elastic Stack being a very popular OSS 'SIEM' solution) and having the ability to output CloudQuery's data directly into Elasticsearch could help teams have a single pane of glass and build dashboards in tools they may be more familiar with. Plus, speaking for myself here, learning SQL syntax to parse nested json objects is quite difficult; with Elasticsearch it's a lot easier to deal with some of these large JSON objects easier.

Also, as datasets grow overtime it becomes much more difficult, both operationally and cost-wise, to scale a SQL database whereas Elasticsearch supports scaling, sharding, and replicating much more natively.

I will caveat this whole request with this: Elasticsearch is quite known for massive breaking changes between versions so supporting this _could_ become burdensome overtime but I still believe the ability to output to Elasticsearch would be something hugely impactful to users.

### Describe the solution you'd like

Be able to output to elasticsearch supporting the following configurable options, this isn't an exhaustive list and I'm sure more would come up if this was taken on but a quick list:

1. Passwordless and Username/PW based authentication
2. TLS and non-TLS connections
3. Ability to specify an [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html)
4. Support for self-hosted and Elastic Cloud [both are quite popular and unfortunately use different libraries/sdks iirc]
5. Ability to set an index name

**Comment by hermanschaaf** [comment]
Thanks for the feature request @cloudmatt! A new Elasticsearch destination is now available as preview 🚀  https://www.cloudquery.io/docs/plugins/destinations/elasticsearch/overview 

It was tested against Elasticsearch 8.6.0, and older versions may not work perfectly, but if an issue is raised for a specific version we should be able to add support.

**Comment by erezrokah** [comment]
Closing this as resolved, please comment if I got this wrong
