### ISSUE TITLE
Google directory

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#4839]
I am descoping this to mostly Google Drive. One of the usecase we should be able to identify is which files are available to users outside the organization.

SDK Location: https://pkg.go.dev/google.golang.org/api/drive/v3
We should be able to use Permissions.List method to retrieve a list of permissions for each file

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/google-directory. Please sign up there to get a notified when the plugin is available.
