### ISSUE TITLE
Running "go test" shouldn't ask for github credentials

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#485]
### Describe the Bug
Running
```
go test ./...
```

or 
```
go test ./pkg/policy/...
```

Will prompt the user for github credentials (repeatedly...)

```
Username for 'https://github.com': shimonp21@gmail.com
Password for 'https://shimonp21@gmail.com@github.com':
Username for 'https://github.com': shimonp21@gmail.com
Password for 'https://shimonp21@gmail.com@github.com':
```

### Expected Behavior
Tests should run without prompting the user.

### CloudQuery Version
Version: development
Commit: development
Date: 2022-02-11 15:16:23.83513 +0200 IST m=+0.061006738

### Steps to Reproduce
```
go test ./...
```

**Comment by roneli** [comment]
This requires to remove the use of the git executable in go-getter.

**Comment by yevgenypats** [comment]
Removed policy command as we use `psql` directly
