### ISSUE TITLE
AWS Region Order Matters - causes failures for non-opt-in regions

### ISSUE THREAD

**Issue by RyPeck** [cloudquery/cloudquery#4869]
### Describe the Bug

Unexpected AWS auth issues when a region is provided in configuration.

### Expected Behavior

The provided order of AWS Regions shouldn't affect a sync.

CQ should skip regions (perhaps with an INFO message) that we haven't opt-in to.

### CloudQuery Version
`cloudquery version 2.0.19`

### Debug Output
<skip - easily reproduce>

### Steps to Reproduce

1. Create an AWS Sync file just the table `aws_regions` and a list of regions like so - 
```
  spec:
    regions:
      - af-south-1
      - us-east-1
```

2. Run sync and observe Error `2022-11-21T15:33:22Z ERR exiting with error error="failed to sync source aws: failed to fetch resources from stream: rpc error: code = Unknown desc = failed to sync resources: failed to create execution client for source plugin aws: no enabled accounts instantiated" module=cli`

3. Switch order of regions - Run sync and observe success.

### Additional Context
The `af-south-1` account is not opted into in my test account.

You can observe the same failure running `aws --region <region>  ec2 describe-regions` against a region you haven't opted into.

### References
https://docs.aws.amazon.com/general/latest/gr/rande-manage.html

**Comment by bbernays** [comment]
@RyPeck - Thank you for raising this issue! We have looked into it and found that this issue was because we were making a `DescribeRegions` call to the first region in the region list. The open PR changes it so that CloudQuery will loop through all of the provided regions until it finds a region that is valid
