### ISSUE TITLE
plugin: File destination plugin

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#4983]
File destination plugin should support number of formats as well as number of storage backends where those files can be saved.

This is mostly useful for data-lakes and data-warehouses

**Comment by erezrokah** [comment]
Hi @yevgenypats can we close this issue? Is there anything missing from the newly released destinations?

**Comment by yevgenypats** [comment]
Closing as it is now part of s3, gcs, azure blobstorage
