### ISSUE TITLE
Ensure Support for HTTP Proxy

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#499]
### Is your feature request related to a problem? Please describe.

Many organizations require all traffic to go through specific proxies, we need to ensure that users are able to direct their traffic to these proxies

### Describe the solution you'd like

- Users should be able to define proxy settings via environment variables as well as the config.hcl
- Providers need to respect these settings as well

**Comment by gs5741** [comment]
Thanks for getting this opened @bbernays

**Comment by gs5741** [comment]
@bbernays - I think if we can export environment variables onto the VM/Lambda that would be great. Today we export variables like HTTP_PROXY=http://proxy.abc.com:9090 and use that to route internet traffic via proxy for example to connect to iam.amazonaws.com as it's not exposed via PrivateLink in AWS
