### ISSUE TITLE
Inaccessible types for gorm query

### ISSUE THREAD

**Issue by rsclarke-vgw** [cloudquery/cloudquery#5]
Providers define their resource types under internal packages rather than being exported making them inaccessible to use in querying with gorm.

Using cloudquery as a library it would make sense to expose these types in order to reuse gorm for querying.

**Comment by korsune** [comment]
Hi @rsclarke-vgw thanks for the issue. I think we can expose those types indeed. can you please provide a bit more information regarding the use-case? i.e why using gorm for querying instead of using SQL?

**Comment by rsclarke-vgw** [comment]
Unless there's intent to swap out or replace gorm, it just seems to make sense to me that anyone using cloudquery as a library can fully use the gorm querying capabilities.

**Comment by korsune** [comment]
Done. Let me know if this works as expected.
