### ISSUE TITLE
Add configuration to allow if stale data should be automatically deleted or not

### ISSUE THREAD

**Issue by axelmukwena** [cloudquery/cloudquery#506]
### Is your feature request related to a problem? Please describe.

Keeping stale data shouldn't only be accessible through TimescaleDB if you do not entirely need the TimescaleDB extension and its functionalities.

### Describe the solution you'd like

Though the `history` configuration is only available with TimescaleDB, it should be fairly accessible to set if stale data should be automatically deleted or not, when working with a regular PostgresDB. This will allow a user to decide if stale data will be overwritten or rows will be incrementally appended.

Perhaps a global setting or limited at provider level configuration.

```
// Somewhere in the config.hcl file

...
keep_stale_data = true
...
```

Also, perhaps disallow using having `history` and `keep_stale_data == true` at the same time.

**Comment by yevgenypats** [comment]
Hi! This should be solved now with `write_mode` - https://www.cloudquery.io/docs/reference/destination-spec#write_mode
