### ISSUE TITLE
chore: Move iam-for-aws-org to utilities

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#5063]
Right now we have one repository for one file here -  https://github.com/cloudquery/iam-for-aws-orgs. We should move this into utilities under `plugins/source/aws/utilities` (or `aux`) and close the old repo as it is not discoverable and we want to limit number of repos as we moved to monorepo.

**Comment by bbernays** [comment]
This was in a standalone repo because the template is used in a tutorial... And the instructions on the tutorial began with cloning that repo...
https://www.cloudquery.io/blog/deploying-cloudquery-into-aws-org

**Comment by yevgenypats** [comment]
Can we update the tutorial? and move it from the repo to the monorepo?

**Comment by yevgenypats** [comment]
Closing as stale
