### ISSUE TITLE
Document TimescaleDB Version Requirements

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#507]
### Describe the Bug

Currently if you try and bring up Cloudquery with History enabled on a timescaledb running `1.7.5` you get an error saying:
```
ERROR: relation "timescaledb_information.hypertables" does not exist (SQLSTATE 42P01)
```

Our documentation only says that the Postgres version needs to be higher than version 12... never specifies the version of TSDB

### Expected Behavior

Our documentation should clearly layout what versions of PG is supported as well as the corresponding versions of TSDB

Ideally our runtime version checks should also flag unsupported configurations (ie pg12 and TSDB  1.7.5)

**Comment by disq** [comment]
`SELECT extversion FROM pg_catalog.pg_extension WHERE extname='timescaledb';`
