### ISSUE TITLE
Improve Policy Snapshot Testing

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#511]
### Describe the solution you'd like

- [ ] For each test output/log the result (pass/fail) and contents of `description` file (if it exists)
- [ ] Enable a "fail fast" toggle
- [ ] Upon a failure output exactly which test and contents of `description` file (if it exists)
- [ ] Generate a "coverage" output. For each control in the policy specify how many test cases were ran and whether if there was at least a single positive and negative test for it

**Comment by yevgenypats** [comment]
We don't have a policy command any more. executing sql directly - https://github.com/cloudquery/cq-provider-aws/tree/main/policies
