### ISSUE TITLE
Azure DNS resources (zones and records)

### ISSUE THREAD

**Issue by S0obi** [cloudquery/cloudquery#5126]
### Why do you need this resource ? Please describe.

Add Azure DNS ressource support:
* Azure DNS zones
* Azure DNS records (A, MX, TXT, etc...)

### Additional context

- [Azure DNS documentation](https://learn.microsoft.com/en-us/azure/dns/)
- [Azure DNS Terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dns_zone)

**Comment by S0obi** [comment]
@erezrokah, thanks for taking this one. Don't hesitate if you need tests :)

**Comment by erezrokah** [comment]
I think this is the relevant Go code https://github.com/Azure/azure-sdk-for-go/tree/028cadc86c4bab0dcd7ecfaed23aa55c9d4e02b4/sdk/resourcemanager/dns/armdns.

I marked this issue as blocked while we migrate to the new Azure SDK via https://github.com/cloudquery/cloudquery/pull/5350

**Comment by S0obi** [comment]
Hello @erezrokah, I just noticed that [azure_dns_zones](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_dns_zones.md) just appeared in the doc. Seems like we can close this issue now.

**Comment by erezrokah** [comment]
Thanks for following up @S0obi! This was added in Azure v2 of the plugin, but I forgot to resolve the issue, sorry for not updating sooner
