### ISSUE TITLE
Add Custom ID to each table to be set by user in provider's configuration

### ISSUE THREAD

**Issue by axelmukwena** [cloudquery/cloudquery#517]
### Is your feature request related to a problem? Please describe.

Scenario: You're using one database for multiple users. While some providers have an ID to identify the user (e.g AWS `account_id`), other providers such as digital ocean don't have an account ID across all tables. Thus, it's impossible to visualize data for a specific user only.

### Describe the solution you'd like

Have an *optional* `custom_user_id` string column in all the tables. It can be set through each provider's configuration:

```hcl
provider "azure" {
  configuration {
    //  Optional
    custom_user_id = < YOUR_CUSTOM_USER_ID >
  }
  resources = ["*"]
  enable_partial_fetch = true
}
```

So that:

```sql
SELECT * FROM history.azure_authorization_role_assignments WHERE custom_user_id = '64827249869'
SELECT * FROM history.azure_authorization_role_assignments WHERE custom_user_id = 'username'
```

### Describe alternatives you've considered

- Running multiple databases for each user. Not financially sane at large scale.

**Comment by yevgenypats** [comment]
This is solved in v1 with `name` which will be available in each row under `_source_name`

**Comment by RyPeck** [comment]
@yevgenypats you are referring to https://www.cloudquery.io/docs/reference/source-spec#name right?

**Comment by yevgenypats** [comment]
@RyPeck exactly
