### ISSUE TITLE
Add option to disable spinner from sync operation

### ISSUE THREAD

**Issue by Vimao** [cloudquery/cloudquery#5179]
Current implementation is great for interactive terminal, but results in excessive login when CQ is started for example in EKS. 

Example:

![image](https://user-images.githubusercontent.com/47415312/204770607-a2c54027-cd9e-4036-a108-05e39dcc8ce9.png)

Please allow a quiet mode of operation that would not render any messages other than those from specified log level

**Comment by erezrokah** [comment]
Hi @Vimao and thank you for opening the issue. Can you try with the `--log-console` flag? That is, run `cloudquery sync --log-console`. That should work better when running in non interactive environment.

You could also use `cloudquery sync --log-console > /dev/null 2>&1` to silence the output.

See more log flags here https://www.cloudquery.io/docs/reference/cli/cloudquery#options.

Please let me know if that works for you.

**Comment by Vimao** [comment]
Hello @erezrokah .

Thanks for the tip, it works! I could've checked the --log-console output before posting. Sorry for the unneeded issue then!

**Comment by erezrokah** [comment]
Thanks for the follow up @Vimao, glad to see it's working for you.
We've discussed detecting non interactive environments in the past and setting that flag automatically, so it's definitely a possible gotcha, and not an unneeded issue 😄 
Eventually we decided to let the user chose as auto detection can have a lot of edge cases and can be confusing.
