### ISSUE TITLE
Policy Execution Prerequisites

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#519]
### Is your feature request related to a problem? Please describe.

Most policies work based on looking for any and all data that matches a query. If a user runs fetch with a subset of resources that don't fully satisfy all of the tables needed by a policy/check then the policy will be marked as compliant even though it doesn't really have enough information to make that determination.

### Describe the solution you'd like

We can use the "live query" functionality to ensure all of the resources that are needed for a check have been fetched "recently" by checking the fetch summary

### Describe alternatives you've considered

Hard code a list of resources and corresponding provider versions that are necessary

**Comment by yevgenypats** [comment]
Migrated to pure sql - https://github.com/cloudquery/cloudquery/tree/main/plugins/source/aws/policies
