### ISSUE TITLE
Store Fetch ID in cq_metadata

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#520]
### Is your feature request related to a problem? Please describe.

To understand how data was added to the db it is important to be able to correlate a row with a specific column fetch.

### Describe the solution you'd like

store fetch_id in cq_metadata

**Comment by disq** [comment]
SDK has provisions for this in the cqMeta column definition, but we don't set this in execution?

**Comment by disq** [comment]
It still needs corresponding metadata to be set somewhere, which is missing.

**Comment by bbernays** [comment]
Unfortunately it looks like a bigger task than just injecting the `cq_fetch_id` field.

The metadata comes from the [extraFields](https://github.com/cloudquery/cq-provider-sdk/blob/20ae1b872b4e67018976fc2f821bd5826099789f/provider/execution/execution.go#L48) in `TableExecutor`. Which is also used to inject other PKs (like `cq_fetch_date`)

**Comment by disq** [comment]
yes the problem seems to be adding any other extraField also requires the column to be present in the table.
