### ISSUE TITLE
Verify handling of null bytes in strings in snowflake

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#5255]
If a destination doesn't support null-bytes in strings, it can cause empty tables... All details here: https://github.com/cloudquery/cloudquery/pull/5249

**Comment by shimonp21** [comment]
blocked on https://github.com/cloudquery/cloudquery/issues/5248

**Comment by erezrokah** [comment]
https://github.com/cloudquery/cloudquery/issues/5248 is merged is this issue unblocked?

**Comment by shimonp21** [comment]
https://github.com/cloudquery/plugin-sdk/pull/532 is the PR to add the test for this. Will discuss this with YP.
