### ISSUE TITLE
Review behaviour of NULLs in JSON fields

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#5256]
Same as https://github.com/cloudquery/cloudquery/pull/5249, but for json's (postgresql likely doesn't like nulls in jsons either..)

**Comment by shimonp21** [comment]
Wow, this is confusing!

Let's say we start with a golang map that is `schema.TypeJson` 
`map[string]string{"k": "v\x00"}`.  (map["k"] in hex is `56 00`) 

We then json-marshal it into bytes (for `schema.JSON`), to become:
```
{  "  k  "  :  "  v  \\  u  0  0  0  0  "  }  
7b 22 6b 22 3a 22 56 5c 75 30 30 30 30 22 7d
```

(These bytes pass through one more marshalling-umarshalling, but it does not affect outcome...)

We then pass those bytes to postgres, who throws `ERROR: unsupported Unicode escape sequence (SQLSTATE 22P05)"`

A simple stripping approach as in #5249 won't work here, because stripping
```
\\ u  0  0  0  0
5c 75 00 00 00 00
```

From the marshaled-json-bytes can actually be wrong in some cases (for example, when the original string was, instead of `56 00`:)

```
v  \\ \\ u  0  0  0  0
76 5c 5c 75 30 30 30 30
```

**Comment by shimonp21** [comment]
One very ugly hack we could do is:

- Strip `5c 75 30 30 30 30` that are not preceded by one more `5c`.

I am not sure if there are edge-cases where this could screw something up

**Comment by shimonp21** [comment]
Another possible approach (just brainstorming):

- unmarshal into a `map[string]string`, strip `00` nulls from the resulting golang `string`s, and marshal back into a json.
  Performance of this is ugly though (although we do so much marshalling-unmarshalling already :) )

**Comment by shimonp21** [comment]
One more edge-case:

```
\\ \0
5c 00

=> Marshaling =>

\\ \\ \\ u  0  0  0  0
5c 5c 5c 75 30 30 30 30
```

**Comment by yevgenypats** [comment]
I think this is solved now and we do validation on the SDK side with `unmarshal/marshal`

**Comment by shimonp21** [comment]
Reopening: I believe we don't actually do the validation on SDK side (we probably need to do it on postgresql side and not SDK side).

Currently this causes a crash:
https://github.com/cloudquery/cloudquery/issues/7647

**Comment by shimonp21** [comment]
Should be fixed in https://github.com/cloudquery/cloudquery/pull/7801.
Will add tests and close this issue.

**Comment by erezrokah** [comment]
Closing as resolved
