### ISSUE TITLE
Snapshot Testing- Destroys DB

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#526]
### Is your feature request related to a problem? Please describe.
Right now snapshot testing is a destructive action in that it will modify data and schemas in a way that is backwards incompatible

### Describe the solution you'd like

Rather than ensuring we are making changes or structuring data in a way that won't conflict/ damage existing databases we should do all of our restoration into a throwaway schema

### Describe alternatives you've considered
1. Warning customers about the risk and suggesting that they run it against a temp local db

2. Structure data so that it is easily findable and unique from any other data (cq_id always starts with `test_`)

**Comment by yevgenypats** [comment]
Running policy with sql is external now to cloudquery cli.
