### ISSUE TITLE
AWS plugin missing Launch Templates

### ISSUE THREAD

**Issue by Rumbles** [cloudquery/cloudquery#5261]
### Why do you need this resource or plugin? Please describe.
Launch configurations are deprecated and launch templates are the new way to do things, but I see no way to scrape this info with cloudquery, previously we collected info on launch configurations, but now we have switched to launch templates there is no scaling group info in our db

### Describe the solution you'd like
Collect the autoscaling group info for launch templates

### Additional context
No

**Comment by candiduslynx** [comment]
Hello!
We already have a `launch_template` field in [`aws_autoscaling_groups`](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/aws_autoscaling_groups.md) table.
Does it contain the info you're looking for?

**Comment by Rumbles** [comment]
Hi, thanks! I had added that to our resources and asked the reporter to let me know if that doesn't solve the issue, closing :)
