### ISSUE TITLE
Needs Mock + Discussion: Move recipes up in the main page instead of focusing on data integration

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#5271]
The current homepage starts with a big data integration banner, while [the SEO analysis](https://docs.google.com/document/d/13BSIhE0jBLG89byxr0HtPHzHNvyAF4_STpDqMCqRR7U/edit#heading=h.894vu17bmf0s) shows that data integration isn't a primary search term when people are looking for tools like us. They are usually searching for recipes/usecases, and then arrive at us.

Moving the recipes slightyl up, makes it easy for new exploring developers to understanding what this tool is about.

However, this needs some mocking and then alignment on acceptable designs before we make any changes there.

**Comment by hermanschaaf** [comment]
@cqgaurav Could you expand on what this means?

**Comment by cqgaurav** [comment]
Updated, let me know if this description makes sense. This is in "Needs product input" state, to ensure we have a discusision on it.

**Comment by yevgenypats** [comment]
Closing as low priority
