### ISSUE TITLE
Reduce log noise

### ISSUE THREAD

**Issue by gavinclarkeuk** [cloudquery/cloudquery#5273]
### Is your feature request related to a problem? Please describe.

The Info level logging seems incredibly noisy, especially on certain resources. We are just using the AWS plugin, but we see ~170k logs per sync. These are almost entirely made up of "Table resolver started/finished" and "Fetch table finished" logs.

If these logged just once for each table that would be ok, but depending on the table they can log multiple times. the worst offender by far is the `aws_ecr_repository_image_scan_findings` table - which is responsible for a whopping ~120k of the logs we're seeing.

### Describe the solution you'd like

Either consolidate the generic "Table resolver started/finished" and "Fetch table finished" info logs into a single log statement for each table, or reduce the logs to debug level (turned off by default).

**Comment by bbernays** [comment]
@gavinclarkeuk Thank you for raising this issue! We are going to review what we can do to make logging more useful and less verbose... in the meantime you can reduce the verbosity by using the `--log-level` flag: 

`cloudquery sync config.yml --log-level=error`

**Comment by shimonp21** [comment]
We removed logging of relational tables - so the number of log-lines will no longer depend on number of resources (but only on number of tables).
The number of log-lines remaining are: {numRegions} X {numAccounts} X {numRootTables}.
This change should reduce the noise by 80% - so closing this issue.

Versions with this change are:
```
aws: 7.3.2
gcp: 3.2.0
azure: to-be-released.
```

Feel free to reopen if the logs are still too spammy...
