### ISSUE TITLE
Remove brew install command from the main page and move it behind a OS aware download CTA.

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#5287]
Why: Showing the brew install command on the main page, gives the impression that we are mac only or mac first tool.

Why not: additional friction.

Tradeoff: i believe a big download or try CTA should outweigh risking higher bounce rates for non mac os devs

**Comment by erezrokah** [comment]
Maybe we can add analytics on how many people actually copy past that command?

**Comment by yevgenypats** [comment]
Done now
