### ISSUE TITLE
Quickstart page should include more information after start syncing section

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#5289]
Right now the quickstart ends at start syncing, but doens't tell the developer what to expect in the output. Here are few suggestions.

- [] include an example for how it would work with AWS and postgres, and show basic queries and how to connect to postgres.
- [] How to query what columns are in there ?
- [] Remove the OS specific pages under the top level quickstart. This is confusing since our quickstart points to Linux as the next link, but there is no logical connection from Mac quickstart to linux. We could instead lead to core concepts as the logical next step ffor users coming to site.
- [] we could also pointers to the following pages

Dashboards link
Policies
Batch queries
Running in a container/cloud
How to read logs
Troubleshooting links
Running as ci-cd pipeline

![Image](https://user-images.githubusercontent.com/113518845/205062869-849c6556-0476-4ad6-a5b3-5466f912c0b2.png)

**Comment by erezrokah** [comment]
Closing as we have a syncs section https://www.cloudquery.io/docs/core-concepts/syncs
