### ISSUE TITLE
Azure Load Balancers

### ISSUE THREAD

**Issue by AlecR** [cloudquery/cloudquery#5293]
### Why do you need this resource or plugin? Please describe.

We'd like to be able to scan Azure load balancers to ensure they're properly configured. Some criteria we'd like to be able to check for is whether the load balancers are configured to only accept HTTPS requests and if they have backend services attached to them)

### Describe the solution you'd like

A new database table that lists all of the azure load balancers for a given Azure account

### Additional context

https://azure.microsoft.com/en-us/products/load-balancer/

**Comment by erezrokah** [comment]
Relevant Azure SDK code is https://github.com/Azure/azure-sdk-for-go/blob/028cadc86c4bab0dcd7ecfaed23aa55c9d4e02b4/sdk/resourcemanager/network/armnetwork/loadbalancers_client.go

I marked this issue as blocked while we migrate to the new Azure SDK via https://github.com/cloudquery/cloudquery/pull/5350

**Comment by erezrokah** [comment]
Closed by https://github.com/cloudquery/cloudquery/pull/5350 and released in v2 of the Azure plugin, see https://www.cloudquery.io/docs/plugins/sources/azure/tables and https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_network_load_balancers.md
