### ISSUE TITLE
Debugging File-backed Variables Error

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#539]
### Describe the Issue
Customers use file backed variables as ways of integrating with other systems like vault. When using a filebacked variable for DSN it is nearly impossible to debug the issue as the value is always redacted.

### Possible solution

Expose a flag that would remove any redaction on local logs so that users can debug issues

**Comment by erezrokah** [comment]
Should be resolved in [v2](https://github.com/cloudquery/cloudquery/pull/1463)
