### ISSUE TITLE
Azure Table Storage

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#5425]
Why do you need this resource or plugin? Please describe.
We'd like to be able to scan Azure Tables under Storage to ensure they're properly configured. Some criteria we'd like to be able to check for is that table service does not allow full read, write or delete ACL permissions.

Describe the solution you'd like
A new database table that lists all of the azure table segmented under an Storage Account for a given Azure account

Additional context
https://azure.microsoft.com/en-us/products/storage/tables

**Comment by erezrokah** [comment]
Closed by https://github.com/cloudquery/cloudquery/pull/5350 and released in v2 of the Azure plugin, see https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_storage_tables.md
