### ISSUE TITLE
Feature Request: Keeping History

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cloudquery#55]
In the current implementation, CloudQuery wipes tables for each selected resource during execution. This prevents tracking the state of an object throughout history. 

One potential solution would be to include a time stamp column on each resource that is the same for all resources tracked in a given execution of CloudQuery. You could then query by all resources from a given snapshot, or query a single resource over time. 

Then it would be great to include options such as only keeping _x_ versions of a resource, or only keeping resources less than _y_ hours old. 

If primary keys are set on resource ID, they might need to be shifted to be a joint key of resource ID and time stamp. This would mean that you couldn't have two instance of CloudQuery fetch running in the same timestamp, but that likely isn't an issue

**Comment by dan-compton** [comment]
> In the current implementation, CloudQuery wipes tables for each selected resource during execution.   This prevents tracking the state of an object throughout history.

Effectively this is equivalent to out-of-order, parallal, causal A/B integration test execution and maybe a desired outcome.  You have some number of tests that must be executed by a user prior to the experiments conclusion which happens within some time window t_T.  

I do not know if there is a threshold outcome for the completion of the execution (some minimal number of resources which must be modified or if there is a time limit and how if ever that will tend towards a live stream.  That almost sounds on its face like a problem for kstreams and ksql if it weren't for the overhead of fragmentation.  I wouldn't want to be in the business of managing individual tables and joins for an innumerable number of resource types.  I would think storing the immutable state entity which is a pointer to a prior immutable state entity {resources and ops and temporal data} (or resource primitive) primitive and the operational data would be enough.

Not an expert on that though (the query aspect).  This delta lake concept seems reasonable: https://databricks.com/blog/2020/05/27/modernizing-risk-management-part-1-streaming-data-ingestion-rapid-model-development-and-monte-carlo-simulations-at-scale.html.   You could get time-windowed joins and alternate universes if you fed it with kafka and changed causality.

**Comment by dan-compton** [comment]
Or https://www.confluent.io/blog/real-time-analytics-with-kafka-and-pinot/

**Comment by Rackme** [comment]
I used this little workaround for now If needed, cloning the DB for each version.
```
str_date_postgres=$(date '+%Y_%m_%d')
docker-compose exec postgres psql -U postgres -c "CREATE DATABASE dump_$str_date_postgres WITH TEMPLATE postgres;"
# Prepare new postegre database (to avoid duplicates)
docker-compose exec postgres dropdb -U postgres postgres
docker-compose exec postgres createdb -U postgres postgres
```
But of course I have to specify each dump date I want to search in.

**Comment by igrant-2ndWatch** [comment]
Historical transactional data is typically where a Data Warehouse would come in handy if you have a sound data model. A Data Lake would be useful if you need ingest raw (unstructured) data and will transform it for various consumption. You may even have a Data Lake feed into a Data Warehouse!

This strategy is recommended as it provides flexibility and performance.

* Flexibility in that you can model the data in whatever way you see fit on the other end of the ETL. Additionally, the app DB is free to make whatever changes necessary for local improvement.
* Performance in that the app DB remains "small". Also, with the above flexibility in layered modeling you can structure data based on each use case thus minimizing query time.

An ETL process -- much like the snapshot dump you are doing here -- would of course automate this workflow for you, but it is a warehouse/lake that would allow you to run analytics across the historical data. Even if a warehouse/lake is inaccessible or you wish to keep it within a relational DB, I would still recommend an ETL like you have over expanding the tool to handle multiple use cases.

**Comment by roneli** [comment]
History support added from v0.17.0! Check out how to configure [here ](https://docs.cloudquery.io/docs/cli/history/configuration)
