### ISSUE TITLE
Aurora Serverless Timeout Backoff

### ISSUE THREAD

**Issue by jasonscalia** [cloudquery/cloudquery#551]
### Describe the Bug
This bug should apply to all providers, but when configuring cloudquery with an Aurora Serverless - Postgresqsl RDS DB, you'll encounter the following error when initiating a cloudquery run:

$kubectl logs -f jobs/cloudquery-cron
8:20PM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
8:20PM INF ❌ Failed to initialize client. Error: validate: failed to connect to `host=<removed> user=cloudquery database=cloudquery`: dial error (timeout: dial tcp 10.0.21.120:5432: i/o timeout)
validate: failed to connect to `host=<removed> user=cloudquery database=cloudquery`: dial error (timeout: dial tcp 10.0.21.120:5432: i/o timeout)

This is most likely due to the serverless cluster being allowed to scale down to 0 active workers and cloudquery timing out or exhausting retries before the database comes back online.

If you re-deploy a Cloudquery job after receiving the failure, it will continue as normal.

### Expected Behavior
Cloudquery should make X # of attempts to connect to the DB before failure and should connect without issue.

### CloudQuery Version
0.21.5

### Steps to Reproduce

1. Configure Aurora Postgresql compatible RDS backend for CQ in AWS
2. Allow the cluster to scale down to 0 after 5 mins of inactivity
3. Run kubectl create job --from=cronjob/cloudquery-cron cloudquery-cron
4. Error appears
5. Run kubectl create job --from=cronjob/cloudquery-cron cloudquery-cron2 and it will work as expected

**Comment by shimonp21** [comment]
Hey, thanks for this bug report, Jason! We are looking into this, and should have an update for you really soon.

**Comment by shimonp21** [comment]
Alright, so after discussing with the team, the solution we came up with is "configurable timeouts and retries".
Keeping in mind we don't want to change the default behaviour (where a short timeout can be fitting), we would like users to be able to configure in their `config.hcl` files longer timeouts and more retries.

A config.hcl block with configurable timeouts might look like:

```
cloudquery {
  ...

  provider "aws" {
    ...
  }

  connection {
    dsn = "postgres://postgres:pass@localhost:5432/postgres?sslmode=disable"
    timeout_seconds = 20 # optional (default = whatever_we_have_today)
    retries =  3 # optional (default = 1) 
  }
}
```

This solution will likely require changes in both [cloudquery-core](https://github.com/cloudquery/cloudquery) and [cq-provider-sdk](https://github.com/cloudquery/cq-provider-sdk).

**Comment by yevgenypats** [comment]
So alot was changed since this issue :)  including no more HCL, multi-database support and much more - https://www.cloudquery.io/blog/cloudquery-v1-release

Retry logic done right can be extremely complex and very difficult to do right. See pgx discussion (the library we use underneath) - https://github.com/jackc/pgx/issues/701. 

Right now the best thing would be probably to to make sure it has one node before running.

The only thing I believe we can implement is not a retry but rather a `wait_for_pg` which will just wait for X seconds  when connecting to the postgres on start.

**Comment by yevgenypats** [comment]
Im closing this now as seems like in AWS Aurora serverles V2 it scales back to 1 but if it's a high priority please re-open.
