### ISSUE TITLE
New Source Plugin: Azure DevOps

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#5511]

**Comment by erezrokah** [comment]
Marked this as `good first issue`. If someone wants to contribute https://github.com/cloudquery/cloudquery/blob/fee3b2e1df69f61e4bdfb5b0e599fb442a75f16f/plugins/source/azuredevops/codegen/recipes/core.go is a good example how to scaffold resources

**Comment by bbernays** [comment]
I am going to close this because it seems like we now have a [azuredevops source plugin](https://github.com/cloudquery/cloudquery/pull/5558). 

If we are missing specific resources I suggest we open new issues for those resources

@erezrokah @jsonpr

**Comment by erezrokah** [comment]
👍 We haven't added it to the Website though, but we can if someone requests it

**Comment by bbernays** [comment]
I have created a new issue for [that work](https://github.com/cloudquery/cloudquery/issues/6585)...
