### ISSUE TITLE
Add Azure Resource_skus and add its table also

### ISSUE THREAD

**Issue by Prateek-Rajpal** [cloudquery/cloudquery#5521]
### Why do you need this resource or plugin? Please describe.
I need to scan all the available compute resource_skus in azure cloud
### Describe the solution you'd like
check this golang armcompute package for resource skus client: 
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute#ResourceSKUsClient
### Additional context
See this website to see the sample data :
https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list?tabs=Go

**Comment by erezrokah** [comment]
Thanks for the issue @Prateek-Rajpal, I'm marking this as blocked until we migrate to the new Azure SDK via https://github.com/cloudquery/cloudquery/pull/5350

**Comment by erezrokah** [comment]
Resolved by https://github.com/cloudquery/cloudquery/pull/5629

**Comment by Prateek-Rajpal** [comment]
Thankyou for solving this.
But now I am not getting any data in skus table . Also compute services tables are not getting any resources.
So I think there is some problem in compute services, like fetchSkus() function is not getting called.

**Comment by erezrokah** [comment]
The [last comment](https://github.com/cloudquery/cloudquery/issues/5521#issuecomment-1352916908) is related to https://github.com/cloudquery/cloudquery/issues/5683, so closing this issue. Please comment and I'll re-open if that's not the case
