### ISSUE TITLE
Log entry does not contain table name

### ISSUE THREAD

**Issue by kvish** [cloudquery/cloudquery#5525]
### Describe the Bug

`{"level":"warn","module":"cli","account_id":"610540955272","error":"operation error Lambda: GetFunction, https response error StatusCode: 403, RequestID: 6f2b87ec-209d-432c-b34e-4182c35d0aad, api error AccessDeniedException: User: arn:aws:sts::610540955272:assumed-role/secureframe-scan/aws-go-sdk-1670483822164965073 is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:us-east-1:610540955272:function:SecureframeAgentStack-aws-ProviderframeworkonTimeo-IQNCfyLHQEvN because no identity-based policy allows the lambda:GetFunction action","message":"Failed to get function","module":"aws-src","region":"us-east-1","time":"2022-12-08T07:17:02Z"}`

warn log for Lambda does not include a table name. This warn entry should have a table entry of aws_lambda_functions

### Expected Behavior

warn log for Lambda does not include a table name. This warn entry should have a table entry of aws_lambda_functions

### Steps to Reproduce

Sync with insufficient permissions to describe lambda functions

**Comment by erezrokah** [comment]
Thanks for the issue @kvish, I believe we should propagate this as an error and implemented a fix in https://github.com/cloudquery/cloudquery/issues/5525.
