### ISSUE TITLE
azure_resources view not getting created

### ISSUE THREAD

**Issue by vineetbadola** [cloudquery/cloudquery#5536]
Hi

I am trying to setup Cloudquery with my Azure account so that i can view the dashboard in Grafana

I can see that all 108 tables are getting created and populated in the posgress database.but my grafana dashboard is not showing any data
After debugging looks like the  view azure_resources is not getting created 

I am using below grafana dashboard id 16569
https://grafana.com/grafana/dashboards/16569-azure-asset-inventory/

Kindly help me to proceed

regards
vineet

**Comment by erezrokah** [comment]
Thanks @vineetbadola, linking the [Discord thread](https://discord.com/channels/872925471417962546/1051153174867742720/1051154231320662038) and proposed solution to create the view via https://github.com/cloudquery/cloudquery/tree/2ce06fc3f47e8842ba5a1c7b44a87c49564a24ca/plugins/source/azure/dashboards#installation

**Comment by erezrokah** [comment]
Going to close this as stale per the suggested solution. If still relevant please comment and I'll re-open
