### ISSUE TITLE
web app configurations table

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#5542]
### Why do you need this resource or plugin? Please describe.
We'd like to be able to Ensures the latest HTTP version is enabled for App Services. Some criteria we'd like to be able to check for Enabling HTTP2.0 ensures that the App Service

### Describe the solution you'd like
Need HTTP20Enabled filed for check the latest HTTP version is enabled for App Services.

**Comment by erezrokah** [comment]
Hi @code-vise and thank you for requesting this resource. To confirm, this relates to the Azure source plugin?

**Comment by code-vise** [comment]
Yeah this relates to Azure plugin. Do you need cloudsploit plugin link or Azure Rest Api docs?

**Comment by erezrokah** [comment]
> Yeah this relates to Azure plugin. Do you need cloudsploit plugin link or Azure Rest Api docs?

Yes please that would be helpful

**Comment by code-vise** [comment]
This is cloudsploit plugin link: https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/appservice/http20Enabled.js

**Comment by erezrokah** [comment]
I believe this is fix by https://github.com/cloudquery/cloudquery/pull/5350 and released in v2 of the Azure plugin. See https://www.cloudquery.io/docs/plugins/sources/azure/tables and https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_appservice_web_apps.md

You'll need to get the Web Apps, then look into `properties->siteConfig->http20Enabled`.

I'll close the issue, but if this doesn't work for you, comment and I'll re-open
