### ISSUE TITLE
Add a '--no-log-colors' to disable colorization for '--enable-console-log'

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#560]
### Is your feature request related to a problem? Please describe.
Colorized logs can get mangled when going through uesrs' systems.

### Describe the solution you'd like
A `--no-log-colors` flag that disables colors of logs outputted to stdout. The flag should have no impact if `--enable-console-log` is not specified.

**Comment by roneli** [comment]
Wip #559

**Comment by roneli** [comment]
Added in #559
