### ISSUE TITLE
Policy Tests broken

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#562]
### Describe the Bug

We run a `cq policy run ` for every pr in all of our policy repos. We used to run it as a sanity check to ensure that no sql syntax errors would block customers. Now that we enforce a fetch prior to running a policy that test stops before it ever even executes the policy

### Expected Behavior

SQL policies should run

### CloudQuery Version

0.22.0

### Additional Context

We have a few options:
1. run a fetch prior to execution
2. Pin cq version to <0.22
3. Insert a record to make it look like fetch occurred
4. expose an override flag to disable fetch check

**Comment by shimonp21** [comment]
Discussed with Ron, chosen solution is overriding the 'fetch check' with a flag
