### ISSUE TITLE
Enable All Organization Features

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#5621]
### Why do you need this resource or plugin? Please describe.
We'd like to be able to Ensures all Organization features are enabled. Some criteria we'd like to be able to check for not all Organization features are enabled.

### Describe the solution you'd like
Need FeatureSet field for check the all Organization features are not enabled.

**Comment by erezrokah** [comment]
Hi @code-vise, do you mind linking to the API docs that have the `FeatureSet` field so we can confirm we're syncing the correct data?
