### ISSUE TITLE
 azure_web_app web_configs aren't included in the CQ model, need to query the latest TLS for azure web app

### ISSUE THREAD

**Issue by LoluPapi** [cloudquery/cloudquery#5625]
### Why do you need this resource or plugin? Please describe.

We'd like to be able to ensure that all web apps are using the latest version of TLS. Some criteria we'd like to be able to check if the web app is using the latest TLS 1.2 version. It seems we can search this criteria because azure_web_app web_configs arent included in the CQ model

### Describe the solution you'd like
Need  to be able to check if App Services is using the latest TLS

**Comment by yevgenypats** [comment]
Hi! Checkout this table https://github.com/cloudquery/cloudquery/blob/main/plugins/source/azure/docs/tables/azure_appservice_web_apps.md

it should be available in the `properties` column. 

Full response documentation available here: https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list

**Comment by yevgenypats** [comment]
Closing. Please re-open if incorrect or still missing info.
