### ISSUE TITLE
Contributing to BigQuery Destination

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#5706]
### Describe the Bug

Currently PR tests fail if PR is from a fork for BigQuery destination. 

### Expected Behavior

Possible solutions:
- Document how to properly run tests and open prs
- The parts of the test that require access to the actual resource should be in a seperate test workflow from the build, lint and unit tests.

**Comment by erezrokah** [comment]
Similar to https://github.com/cloudquery/cloudquery/issues/5265 (which I closed). I tend to spend the effort in support this, only when we'll have someone that doesn't belong to our team open a PR for BigQuery/Snowflake.

**Comment by erezrokah** [comment]
Closing as won't fix for now. If someone tries to contribute we can validate the CI manually
