### ISSUE TITLE
Please add the following tables for aws cloud.

### ISSUE THREAD

**Issue by xi3007-prajpal** [cloudquery/cloudquery#5788]
### Why do you need this resource or plugin? Please describe.
Please add the following tables for aws:
    1. aws_elasticsearch_instance_types
    2. aws_elasticsearch_versions
    3. aws_managed_prometheus_workspaces
As,I want to use these resources in my project.

### Describe the solution you'd like
You can use the following apis and functions:
- For Elasticsearch instance types : 
https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#ElasticsearchService.ListElasticsearchInstanceTypes 
- For ElasticsearchVersions: 
https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#ElasticsearchService.ListElasticsearchVersions
- For ManagedPrometheus:
https://docs.aws.amazon.com/sdk-for-go/api/service/prometheusservice/#PrometheusService.ListWorkspaces

**Comment by candiduslynx** [comment]
Will do Managed Prometheus in a separate PR

**Comment by candiduslynx** [comment]
Hi @xi3007-prajpal!
I've implemented the required resources, however, the `instance_types` is not a separate resource but a column in `aws_elasticsearch_versions` table.
