### ISSUE TITLE
error when trying to use environmental variables. -  Error: parse "DSN redacted": invalid port ":&tbi-=8" after host

### ISSUE THREAD

**Issue by MichaelTay0** [cloudquery/cloudquery#586]
### Describe the Bug

Using environmental variables. 

```
connection {
    dsn = "host=${DB_HOST} user=postgres password=${DB_PASSWORD} database=postgres port=5432 sslmode=disable"
  }
```
receiving the following error ... 

90m10:20PM[0m INF ❌ Failed to initialize client. Error: parse "DSN redacted": invalid port ":&tbi-=8" after host

### Debug Output

90m10:20PM[0m INF ❌ Failed to initialize client. Error: parse "DSN redacted": invalid port ":&tbi-=8" after host

### Additional Context

I have has also tried the following (this is running in a docker container  - stored the password as an env var 

`export CQ_VAR_DSN="postgres://postgres:${PGPASSWORD}@cloud-sql-proxy:5432/postgres?sslmode=disable"
`

```
  connection {
    dsn = "${DSN}"
  }
```

### References

https://github.com/cloudquery/cloudquery/discussions/585
https://github.com/cloudquery/cloudquery/issues/216

**Comment by spangenberg** [comment]
Hi @MichaelTay0,

can you please give me a little bit more information on how you run cloudquery in your first and second example?
I was not able to replicate this issue myself, also can you report which version you're using.

This example seems to work for me.

I put this in my config:
```hcl
  connection {
    dsn = "postgres://postgres:${DB_PASSWORD}@${DB_HOST}:5432/postgres?sslmode=disable"
  }
```

And execute with:
```bash
CQ_VAR_DB_HOST=localhost CQ_VAR_DB_PASSWORD=pass cloudquery fetch
```

Best,
Daniel

**Comment by MichaelTay0** [comment]
In this example, I am running from my mac.

I think It worked, but after I fetch, I then try to run a policy pack 

> Configuration Error Diagnostics:
❌ Unknown variable; There is no variable named "DB_PASSWORD". [./config.hcl:11,34-45]
❌ Unknown variable; There is no variable named "DB_HOST". [./config.hcl:11,49-56]
❌ Unsuitable value type; Unsuitable value: value must be known [./config.hcl:11,12-32]

Is is safe to say I have to export the env vars everytime I issue a `cloudquery <command> `Would I have to do the following on the policy run also? 

`CQ_VAR_DB_HOST=$TAYO_HOST CQ_VAR_DB_PASSWORD=$TAYO_PASSWORD cloudquery policy run gcp//cis_v1.2.0  --output-dir results/`
