### ISSUE TITLE
Receiving Fetch Error - EOF

### ISSUE THREAD

**Issue by MichaelTay0** [cloudquery/cloudquery#592]
### Describe the Bug

{"level":"error","alias":"gcp","provider":"gcp","version":"v0.6.10","error":"rpc error: code = Unavailable desc = error reading from server: EOF","time":"2022-04-21T14:01:41Z","message":"received provider fetch error"}

### CloudQuery Version

Latest
### Debug Output

{"level":"error","alias":"gcp","provider":"gcp","version":"v0.6.10","error":"rpc error: code = Unavailable desc = error reading from server: EOF","time":"2022-04-21T14:01:41Z","message":"received provider fetch error"}

**Comment by spangenberg** [comment]
Hi @MichaelTay0,

can you please add more details, like the complete output of the fetch run?
You can also redact fields you don't want anyone to see.
If you want you can also use our [Discord](https://cloudquery.io/discord) to discuss the issue you're facing.

Best,
Daniel

**Comment by MichaelTay0** [comment]
Thanks for responding, 
Unfortunately, I am not comfortable sharing the `cloudquery.log` file in a public repo.
What additional details would you need? 

We seem to be receiving the error 
`{"level":"error","alias":"gcp","provider":"gcp","version":"v0.6.10","error":"rpc error: code = Unavailable desc = error reading from server: EOF","time":"2022-04-22T16:31:56Z","message":"received provider fetch error"}
`
at the end of our very long fetch 

Our GCP organization is pretty large ~700ish projects

**Comment by spangenberg** [comment]
I can understand that you're not comfortable sharing in public.
Can you please send the log directly to me, so the team and I can take a look?
Please send it to `daniel@cloudquery.io`, if you prefer you can also encrypt the log with our public key that you can find here: https://keybase.io/cloudquery

**Comment by spangenberg** [comment]
I'll be closing this ticket for the moment since we haven't heard back from you within a week.
If you are still encountering this issue, please comment on it and we will reopen it.
