### ISSUE TITLE
Feature: AWS VPC Peering Connections

### ISSUE THREAD

**Issue by Raphx** [cloudquery/cloudquery#6]
Hi, I would like to have the relevant data to visualise relationships between different VPC in a peering connection setup. This would require cloudquery to fetch details for VPC peering connections.

The details that I would need are the ones as documented [in this page](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcPeeringConnection.html).

**Comment by yevgenypats** [comment]
Hi @Raphx Thanks for the issue. We added the resource, Let me know if this works as accepted.

Release: https://github.com/cloudquery/cloudquery/releases/tag/v0.3.3 
Commit: https://github.com/cloudquery/cloudquery/commit/8a6dbc1210fd451b0ef8c3f870076004aa1e898c
Documentation: https://docs.cloudquery.io/aws/tables-reference/ec2/vpc_peering_connections

**Comment by Raphx** [comment]
Awesome, great work!
