### ISSUE TITLE
Encrypted credentials

### ISSUE THREAD

**Issue by ab2386** [cloudquery/cloudquery#60]
Hi, 

Do you have in the roadmap to encrypt the credentials?. I just configured cloudquery to use with Azure and is a risk to put the credential in plain text on the env variables.

Thanks, 
Alonso

**Comment by James-Quigley** [comment]
Not sure what you mean. Storing secrets in an environment variable on your system is a fairly standard practice. It's one of the ways you can authenticate with the Azure SDK, AWS SDK etc. 

And who would do the encrypting? If you encrypt a file with your azure credentials, how are you going to pass the encryption key to cloudquery? You'd have the same issue.

**Comment by yevgenypats** [comment]
@ab2386 can you please elaborate on this? To add to what James said it is a standard practice to put creds an in environment variables.

As an additional security/defense-in-depth measure you can:
1) Create a profile with read-only permissions
2) You can use something like vault in connection with cloudquery (https://www.vaultproject.io/)

**Comment by ab2386** [comment]
Hi, 

Probably i didn't express my question very well. English is not my first language.

I was testing cloudquery to see if we can use it in production but we can not have credentials in plane text anywhere, not in a config file or in a env variable. For our in house apps we are allowed to use hashed passwords that the app can process or use a vault like cyberark. I know hashed password is not the best security but at least is not so easy to read.

I'll look into vaultproject to see how I can make it work with cloudquery

Thanks,
Alonso

**Comment by yevgenypats** [comment]
@ab2386 got it. I'll look into this if we can write a documentation/guide on how to use [hashicorp vault](https://www.vaultproject.io) with cloudquery. It's pretty much the same idea as cyberark vault. If you will be able to use it I'd love to hear how you did it so I can write some guide on this.

**Comment by yevgenypats** [comment]
Closing as unclear
