### ISSUE TITLE
DSN Parsing

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#600]
### Describe the Bug
`postgres://cloudquery:yMLh4SV0j#gPP>T@cluster-id.us-east-2.rds.amazonaws.com:5432/postgres`

This is a valid password for Postgres. CQ Parsing fails to recognize the characters in the password and outputs the following error:

```
parse "DSN redacted": invalid port ":yMLh4SV0j" after host
```

### Expected Behavior

Should parse DSN cleanly

### CloudQuery Version
```
Version: 0.22.3
Commit: d9170a5140a2a8b0bc151fc15502607be103e070
Date: 2022-04-12T09:17:49Z
```

**Comment by disq** [comment]
Couple snags:
- xo/dburl seems to [call](https://github.com/xo/dburl/blob/master/dburl.go#L258) `url.Parse`, which cuts off the fragment part (`#` - which is part of the password)
- Even if removing `#` from the password, unescaped `>` results in another net/url error: "invalid userinfo". Escaping it as `%3E` seems to work.

In conclusion, this seems to work:
```
postgres://cloudquery:yMLh4SV0j%23gPP%3ET@cluster-id.us-east-2.rds.amazonaws.com:5432/postgres
```
(verified with `result.User.Password()`)

**Comment by bbernays** [comment]
Is there anyway we could escape the characters within CQ? Or do we just have to tell users certain characters are not supported?

**Comment by disq** [comment]
We can’t change how URLs work, but maybe walk back the dsn-as-url feature since so many people have trouble with it.
