### ISSUE TITLE
chore(github): Move impl from interfaces + mocks to embedding the GitHub client

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#6010]
1. Embed the GitHub client
2. Override `BaseUrl` for tests
3. Optional: prepend `UserAgent` with `cloudquery-source-github/<ver>`

**Comment by erezrokah** [comment]
Hi @candiduslynx I unassigned you as we deprioritized this issue

**Comment by erezrokah** [comment]
I'm going to close this as `wontfix` for now. If you think the refactoring is worth the effort please comment and I'll re-open
