### ISSUE TITLE
Sorting for How To Guides

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6019]
How to guides should not be sorted by post date, but instead should be alphabetically sorted...

**Comment by erezrokah** [comment]
> How to guides should not be sorted by post date, but instead should be alphabetically sorted...

Are they not sorted alphabetically already? https://www.cloudquery.io/how-to-guides

**Comment by bbernays** [comment]
Hadn't looked, but it does appear they are... In that case should we remove the dates from the guides?

**Comment by erezrokah** [comment]
> In that case should we remove the dates from the guides?

Yes, I believe @hermanschaaf already did that in https://github.com/cloudquery/cloudquery/pull/5943/commits/cab6cca4d68d4f67a428e36f18a8bf47665dd6a1, and that's the reason they are sorted alphabetically.

I'll close the issue. Please comment if there's further action to be done
