### ISSUE TITLE
Building process of providers removes pre-release status from pre-releases.

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#603]
### Describe the Bug
After build, pre-releases lose their "pre-release" status and become regular releases.

### Expected Behavior
Shouldn't happen!!

### Steps to Reproduce
Create pre-release and wait 10 minutes for the build (you know the build finished when there are assets other than source_code.zip

**Comment by erezrokah** [comment]
This was resolved by https://github.com/cloudquery/.github/pull/66, specifically https://github.com/cloudquery/.github/pull/66/files#diff-a871a95715e1cf2f40ca47f4aa75e9504e89c008078aae6eb7242fc825ca66acR65 and https://github.com/cloudquery/cloudquery/pull/660/files
