### ISSUE TITLE
[Research] How to setup Cq with GCP/other clouds and k8s (aspects: authentication)

### ISSUE THREAD

**Issue by cqgaurav** [cloudquery/cloudquery#6080]
@yevgeny could you expand here on what is needed ?

**Comment by erezrokah** [comment]
We would like to document (for starts) how to extract K8s relevant data using the GCP plugin

**Comment by erezrokah** [comment]
We should document that in order to get K8S data from cloud providers like AWS, GCP, Azure one should use the K8s plugin

**Comment by yevgenypats** [comment]
Closing as stale
