### ISSUE TITLE
Policy HCL Changes:

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#609]
-  [x] For providers that need to have more context around the results of a policy result we will enable a policy to declare columns that all checks must return. For example required (ie project_id, region, account), 
- [x] Declare the field is the `PK/ID` (for future decorator)
-  [ ] All SQL queries should have the following fields outputs should have the following:
    - `CQ_ID` (suggested)
    - `Status` (suggested)
    - `Reason` (suggested)
    - `Remediation` (suggested)
-  [ ] For output on a specific  Can add:
    - `Reason`
    - `Remediation`

**Comment by roneli** [comment]
Currently `remediation` wasn't added, and also `cq_id` isn't required or validated based on #664
