### ISSUE TITLE
DSN in config should be optional

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#612]
### Describe the Bug

`dsn` in config.hcl should be optional (as long as `--dsn` is specified) but it doesn't seem to be, if `connection` block is specified.

### Expected Behavior

`config.hcl` without `dsn` should work as long as DSN is specified with `--dsn` cli param.

### CloudQuery Version

`v0.22.10`

### Steps to Reproduce

- Remove DSN from config, but keep an empty `connection` block.
- Run cq fetch with --dsn param.

**Comment by bbernays** [comment]
@disq @roneli Is this still an issue with the refactor?

**Comment by disq** [comment]
config is mostly untouched so I'm guessing yes.
