### ISSUE TITLE
Add SQL Server as a supported destination

### ISSUE THREAD

**Issue by rafaelrodrigues3092** [cloudquery/cloudquery#6145]
### Is your feature request related to a problem? Please describe.
We have existing client and application environment details hosted in SQL Server.
We would like to tie Azure infrastructure to these environments.

### Describe the solution you'd like
Have SQL Server as a supported destination

### Describe alternatives you've considered
Currently using Postgres. We have been thinking of setting an ETL job to load data from PG to SQL Server.

### Additional context
SQL Server is one of the most widely used RDBMS

**Comment by candiduslynx** [comment]
Hi @rafaelrodrigues3092!
We've just merged the SQL Server destination that works both with local/dedicated SQL server as well as Azure SQL Server.
We'll be releasing tomorrow, so you can check it out soon.

**Comment by rafaelrodrigues3092** [comment]
This is awesome!
Thank you for the quick turnaround!
I will give it a try once it's out.
Thanks again!

**Comment by candiduslynx** [comment]
@rafaelrodrigues3092, the plugin is [released](https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-mssql-v1.0.0)!
https://www.cloudquery.io/docs/plugins/destinations/mssql/overview

**Comment by rafaelrodrigues3092** [comment]
@candiduslynx 
I was able to test it out. I did a single run from Azure (single subscription) -> MSSQL
At first glance, it seems to be working fine. I did notice some Primary Key Violations in the log.

Let me know if you want me to add them here, or can create a separate ticket with all my (potential) findings once I have a little more time to do a more thorough check.

Thanks again for this!

**Comment by candiduslynx** [comment]
@rafaelrodrigues3092 Please create a separate ticket for us to review. Thanks!

**Comment by candiduslynx** [comment]
> I will try to set up an Azure AD authentication scenario.

One tricky thing is that you'll need to set up application ID for this, too. And don't forget to set `auth_mode` to `azure`.

**Comment by rafaelrodrigues3092** [comment]
> > I will try to set up an Azure AD authentication scenario.
> 
> One tricky thing is that you'll need to set up application ID for this, too. And don't forget to set `auth_mode` to `azure`.

@candiduslynx I think this is the case - but just to double check -  does this mean that the Service Principal used to collect the infrastructure resources on the target Azure Subscriptions (as described here https://www.cloudquery.io/docs/plugins/sources/azure/overview#creating-a-service-principal) is also the entity used to authenticate with the database server?

**Comment by rafaelrodrigues3092** [comment]
@candiduslynx I was able to successfully authenticate to Azure SQL Managed Instance with AD.
I am in the process of doing a more thorough test on a larger scale. I will open another ticket with my findings and reference it here.
