### ISSUE TITLE
Custom fields for TLS, Java, Php and .Net

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#6151]
### Why do you need this resource or plugin? Please describe.
We'd like to be able to ensures that all web apps are using the latest version of TLS, Java, php .Net versions. Some criteria we'd like to be able to check that all web apps are using the latest version of TLS, Java, php and .Net.

### Describe the solution you'd like
We need TLS, java, php and .Net version fields for check the latest versions.

### Additional context
This is cloudsploit referenced api.
https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list-configurations#siteconfigresourcecollection
There are cloudsploit plugin links for TLS, Java, Php and .Net:
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/appservice/tlsVersionCheck.js
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/appservice/javaVersion.js
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/appservice/netFrameworkVersion.js
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/appservice/phpVersion.js

**Comment by candiduslynx** [comment]
The child table for `azure_appservice_web_apps` with the [list configs](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appservice/armappservice/v2#WebAppsClient.NewListConfigurationsPager) call should cover it.

**Comment by yevgenypats** [comment]
Hi @code-vise Thanks for opening this! Can you please check if this not already available in `azure_appservice_web_apps` table under `properties.siteConfig`. As seems that per the Azure API https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list It returns the site config as well https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list#site (under `properties.siteConfig`). Azure documentation sometimes is not accurate so in that case we might need to add another table.

**Comment by yevgenypats** [comment]
Closing. Please reopen if this issue is not solved.

**Comment by code-vise** [comment]
> Hi @code-vise Thanks for opening this! Can you please check if this not already available in `azure_appservice_web_apps` table under `properties.siteConfig`. As seems that per the Azure API https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list It returns the site config as well https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list#site (under `properties.siteConfig`). Azure documentation sometimes is not accurate so in that case we might need to add another table.

So the list API does not return correct response. For instance, if you create a webapp with java runtime, list API return javaVersion: null but list-configurations return correct response.

**Comment by erezrokah** [comment]
Re-opening so we can verify this issue

**Comment by disq** [comment]
The data should be in `azure_appservice_web_app_configurations`, which was covered in #9109 and released in 5.2.0 (#9112).

**Comment by erezrokah** [comment]
Thanks @disq, I'll close this issue then, @code-vise please comment (again) if needed
