### ISSUE TITLE
Create policy pack for GCP

### ISSUE THREAD

**Issue by ccojocar** [cloudquery/cloudquery#62]
It would be useful to have a policy pack for GCP similar with AWS CIS. Some of the findings from GCP Security Command Center can be helpful for a start: https://cloud.google.com/security-command-center/docs/concepts-vulnerabilities-findings.

**Comment by yevgenypats** [comment]
GCP CIS Version - is available here - https://hub.cloudquery.io/policies/cloudquery/gcp-cis-1.2.0/latest
