### ISSUE TITLE
Bug(postgres): When recreating primary key(s) constraint, `not null` is not removed from old PK(s) 

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#6248]
Related to https://github.com/cloudquery/cloudquery/issues/6246

When we recreate primary keys during migration, we set new primary keys columns to `not null`:
https://github.com/cloudquery/cloudquery/blob/efca4a7c8092f306a41583e2d5debf80875b64ae/plugins/destination/postgresql/client/migrate.go#L128

However we don't remove `not null` enforcement on previous primary keys.
Since we also don't delete renamed columns, when we try to insert new data to the table, the old column is populated with `NULL` and the insert fails.

### Proposed solution(s)

- Solution 1 - Look for all `not null` columns and remove the enforcement when recreating primary keys
- Solution 2 - If after the migration the table has `not null` columns that are not part of the new schema, fail the migration

**Comment by candiduslynx** [comment]
Solution 3: if the new schema isn't the subset of the schema after migration (there might be extra columns, but the constraints and PK are the same) – fail the migration

**Comment by erezrokah** [comment]
> there might be extra columns, but the constraints and PK are the same

Aren't extra columns OK? The sync will work and add the missing data no?

**Comment by candiduslynx** [comment]
Yes, extra columns in the resulting schema ore OK.
Basically, we want to check that the resulting schema contains all and every:
* column from the new schema
* constraint from the new schema
* the PK is exactly the same (including constraints)

**Comment by erezrokah** [comment]
I might be misunderstanding, but we're already creating any missing column/constraint/primary key here:
https://github.com/cloudquery/cloudquery/blob/efca4a7c8092f306a41583e2d5debf80875b64ae/plugins/destination/postgresql/client/migrate.go#L81
so I'm not sure how something will be missing.

The issue describes a use cases where the auto migration succeeds, but the DB is in a state that any future sync fails.

**Comment by candiduslynx** [comment]
Basically, my proposal is extension of solution 2 with more general rules. However, we can just implement the 2nd solution for a quick fix.
