### ISSUE TITLE
Provide a docker image for cloudquery tool

### ISSUE THREAD

**Issue by ccojocar** [cloudquery/cloudquery#63]
It would be useful to have an official docker image which can be used to run the cloudquery tool. This will allow to execute the tool either using Kubernetes or cloud run service.

**Comment by yevgenypats** [comment]
We've added an official [docker](https://github.com/orgs/cloudquery/packages/container/package/cloudquery) image. And initial support/documentation to run cloudquery inside a docker https://docs.cloudquery.io/quick-start#download-and-install
