### ISSUE TITLE
feat(docs): Write a guide on how to use renovate to auto update plugins

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#6335]
With the help of a user on our Discord we got a nice renovate config to use, see https://discord.com/channels/872925471417962546/974029056070795284/1058757584942800937

Could be worth writing a How To Guide for it.

**Comment by cloudmatt** [comment]
👋🏻 - since I went through the pains of figuring it out, I'd be glad to contribute my lessons learned to some sort of how-to guid e. Is there a particular repo I could open a PR against and add a doc? Or post some markdown as a comment here?

**Comment by yevgenypats** [comment]
Both will work. If you want to contribute to an how-to guide this would be awesome. Basically just add your how to here - https://github.com/cloudquery/cloudquery/tree/main/website/pages/how-to-guides and we will review the PR. 🙏

**Comment by cloudmatt** [comment]
Done - PR is https://github.com/cloudquery/cloudquery/pull/6435

**Comment by erezrokah** [comment]
This is shipped 🚀  https://www.cloudquery.io/how-to-guides/update-plugins-using-renovate
