### ISSUE TITLE
bug: BigQuery migrations fail on new columns

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6364]
Migration error reported by user on Discord:

```
Error: failed to migrate source aws on destination bigquery : failed to call Migrate: rpc error: code = Unknown desc = googleapi: Error 400: Provided Schema does not match Table aws_backup_vault_recovery_points. Field composite_member_identifier is missing in new schema, invalid
```

It seems like `composite_member_identifier` was newly added a week or two ago, but this shouldn't be a breaking change.

**Comment by disq** [comment]
`aws_backup_vault_recovery_points` wasn't added a week or two ago it was there since CQ v0 times.

**Comment by hermanschaaf** [comment]
Oh sorry, my mistake when typing the ticket: `composite_member_identifier` was added to `aws_backup_vault_recovery_points` a week or two ago.
