### ISSUE TITLE
Postgres migration doesn't recreate composite PK if only the column order was changed

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#6375]
Consider the following conditions:
* there's some source plugin with 2 versions, `A` & `B`
* between these 2 versions there's a table `T` with PK `(X, Y)` for `A` and `(Y, X)` for `B`. Nothing else changed (even the column types are the same)

Now, if we have 2 users:
1. Started using version `A`, then migrated to `B`
2. Started using version `B`

These 2 users will have different composite PK column order:
1. Has the PK from version `A`, namely `(X, Y)`, as postgres destination doesn't recreate the Pk if the only thing that differs is the columns order
2. Has the PK from version `B`, namely `(Y, X)`

Composite PK column order has a huge impact on the queries execution, so recreation in such situation should be considered.

cc: @erezrokah @yevgenypats

**Comment by erezrokah** [comment]
To add more context, we consider PK order changes as a breaking change, so under a major version bump. Regardless we could look into a graceful migration if possible

**Comment by candiduslynx** [comment]
connected to #6043

**Comment by yevgenypats** [comment]
I think right now it is too early to deal with that and it is over optimization even though PKs have impact on performance execution. I don't think we should deal with that and we shouldn't consider column and/or order change a breaking change and also no need to act upon that in our postgresql destination.

**Comment by yevgenypats** [comment]
Closing this as we already have https://github.com/cloudquery/cloudquery/issues/6043 https://github.com/cloudquery/cloudquery/issues/6600

we can reopen this in the future when someone will complain about this. (closing this keeping our number of issues small helps focus on the highest priority issues)
