### ISSUE TITLE
Bug(Neo4j): Neo4j Syncs append data into certain tables

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#6377]
Multiple syncs for Neo4j append data instead of expected behavior of overwriting data.

Reference tables:
* aws_iam_user_attached_policies
* aws_iam_role_policies
* aws_iam_user_access_keys

Verified across postgresql and multiple syncs.

**Comment by bbernays** [comment]
This occurs for any resource that doesn't have a PK defined
