### ISSUE TITLE
Gitlab SaaS support

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#6426]
Currently, the gitlab source supports self-hosted according to the documentation. It actually works fine with the SaaS option, only problem is it pulls ALL of gitlab which, while reveals interesting information about gitlab, probably isn't ideal behavior. 

SaaS support could work by pre-filtering API calls to gitlab.com (bolded is preferred): 
1. **first call /namespaces, grab the IDs of each namespace from the response, then call /groups/:namespaceid:/projects**
2. /projects?visibility=private would only return a given user's namespace projects. However if a user didn't have private projects, they'd still need to run visibility=public and they'd end up grabbing everything from gitlab again. 
3. /users/:userid:/projects returns information about a users _owned_ projects, which is not always the case

Alternatively, we could just live with grabbing all of Gitlab.com and filter post-fetch, but that doesn't seem scalable as gitlab grows its public presence and doesn't seem like a "good api citizen" thing to do to Gitlab.

### Additional context
spoke briefly with ben about this in discord.

found some issues recently closed, though i don't think the solution helps in this namespace-wide data gathering capability: https://gitlab.com/gitlab-org/gitlab/-/issues/16149

https://docs.gitlab.com/ee/api/namespaces.html

**Comment by bbernays** [comment]
I agree that for the SaaS the default option should not be to grab ALL projects! Unfortunately GitLab has said that [they do not intend](https://gitlab.com/gitlab-org/gitlab/-/issues/16149) to support getting all projects in a namespace. So I think the only path is to list all groups and then use the `List All Projects for a specific group (including sub groups)` functionality to be able to get a list of projects...

https://gitlab.com/gitlab-org/gitlab-foss/-/issues/50325

**Comment by erezrokah** [comment]
Hi 👋 I think using the minimal access level parameter should work fine for groups and projects, WDYT?
See https://github.com/cloudquery/cloudquery/pull/6852/files#diff-f69312ad749c9c487bade22fc946ff945885bae4e1e8f30bf9c4e353dbcebd30R48
