### ISSUE TITLE
Store Policy Output in Database

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#643]
### Background

Policy output is currently just piped to stdout or a file on the local filesystem. This means that each organization needs to implement their own method for normalizing and storing the data. This data is valuable for the organization as it can provide details on what needs to be fixed as well as high level trends on how the organization's cloud security posture is evolving over time.

### The solution:

Rather than returning the data directly to the user we will also store the data in the same database for customers to be able to query using their existing BI tools.

Implementation will occur in 3 distinct phases: 

- [x] #644
- [x] #645
- [x] #646

**Comment by yevgenypats** [comment]
This is already done in by executing the sql directly - https://github.com/cloudquery/cq-provider-aws/tree/main/policies
