### ISSUE TITLE
Provide a configuration option to generate AWS IAM credential reports before syncing data

### ISSUE THREAD

**Issue by AlecR** [cloudquery/cloudquery#6443]
### Is your feature request related to a problem? Please describe.

AWS IAM credential reports provide useful information about the IAM users in an org, but currently they must be manually generated by a user before CloudQuery can pull the most up to date information

### Describe the solution you'd like

Provide a configuration option which, when enabled, calls the API to generate credential reports before syncing the `aws_iam_credential_reports` table. 

### Additional context

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html
https://docs.aws.amazon.com/IAM/latest/APIReference/API_GenerateCredentialReport.html

**Comment by bbernays** [comment]
Can you provide more information about why users have to manually generate the credentials report? Are users seeing errors? Looking at the code, CQ always try to generate a report...

https://github.com/cloudquery/cloudquery/blob/499f421fa96b2d3c63f0679b32e00f98cc0da4b3/plugins/source/aws/resources/services/iam/credential_reports_fetch.go#L23-L31

**Comment by AlecR** [comment]
Thanks for sharing that snippet @bbernays. I was unaware that these reports are already being pulled as part of fetching that data. After digging into the logs from a few runs it appears that this is actually a permissions issue preventing the new reports from syncing. Closing this ticket as it is not an issue with the Cloudquery code.
