### ISSUE TITLE
CloudQuery Policy Selector

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#647]
### Describe the Bug
CloudQuery does not respect a selector when the same policy is also defined in the config.hcl

config.hcl:
``` 
policy "aws" {
    source = "aws"
}
```

`cloudquery policy run aws//cis_v1.2.0`

This will run the entire AWS policy instead of just the cis_v1.2.0

### Expected Behavior

When a selector is passed it should override any policies defined in config.hcl

**Comment by bbernays** [comment]
@roneli - I think this was fixed and merged correct?

**Comment by roneli** [comment]
Correct closing this issue.
