### ISSUE TITLE
CDK or CloudFormation

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#648]
### Is your feature request related to a problem? Please describe.

Currently we support [terraform](https://github.com/cloudquery/terraform-aws-cloudquery) for deployment of CloudQuery on EKS + [helm](https://github.com/cloudquery/helm-charts). As part of our work to improve onboarding experience around production deployment we might want to checkout CloudFormation (or CDK) to deploy it in AWS as it has better native experience and no need to manage state file. 

### Additional context

References:
 https://github.com/aws-quickstart/quickstart-hashicorp-vault
https://github.com/aws-quickstart/quickstart-eks-hashicorp-vault

**Comment by bbernays** [comment]
What is the action item for this issue? Are we trying to release a CloudFormation/CDK template as a quickstart?

**Comment by cqgaurav** [comment]
We decided that we aren't going to support anything apart from our terraform based deployments for now. We might think about supporting something like this as part of managed version.
