### ISSUE TITLE
Prisma 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6582]
### Why do you need this resource or plugin? Please describe.

https://prisma.pan.dev/api/cloud/cspm/alerts

### Additional context

Go SDK can be found here: https://pkg.go.dev/github.com/paloaltonetworks/prisma-cloud-go

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/prisma. Please sign up there to get a notified when the plugin is available.
