### ISSUE TITLE
feat: Add Postgres state backend

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6665]
Postgres would make a good addition alongside the local backend we currently support for storing cursor state of incremental tables. The ability to store state remotely is especially useful in distributed or containerized environments.

This backend would need to be added to the plugin-sdk: https://github.com/cloudquery/plugin-sdk/tree/main/internal/backends

**Comment by yevgenypats** [comment]
I'll await for a bit more usage and experience with the backend cursor but if indeed it gains traction and users ask for more backends (not only local-file) we will have to have another grpc client/server I think as it can  grow up pretty quickly.

**Comment by erezrokah** [comment]
Thanks @RyPeck I opened an issue to update the docs in https://github.com/cloudquery/cloudquery/issues/12791
