### ISSUE TITLE
feat: Add S3 state backend

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6666]
S3 would make a good addition alongside the local backend we currently support for storing cursor state of incremental tables. The ability to store state remotely is especially useful in distributed or containerized environments.

This backend would need to be added to the plugin-sdk: https://github.com/cloudquery/plugin-sdk/tree/main/internal/backends

**Comment by erezrokah** [comment]
Closing stale, S3 is supported as a backend
