### ISSUE TITLE
Feedback for “Support”

### ISSUE THREAD

**Issue by peterfigueiredo** [cloudquery/cloudquery#6676]
Hi CloudQuery Support,

Just to mention that your Discord link is broken.

I am having issues configuring the destination plugin for S3 and don't know how I can reach you.

What is the best way?

Best,
Peter

**Comment by hermanschaaf** [comment]
Hi @peterfigueiredo, Discord would be the best place for live support - does the link posted by the GitHub bot above not work for you? (It seems to work for me) Or if you found another link somewhere that was broken, please let us know where so we can fix it :)

It could be that Discord is blocked on your network, in which case I'd be happy to try and help here on GitHub issues as well.

**Comment by yevgenypats** [comment]
Closing as I think this all works. Please re-open or if there is a broken link somewhere 🙏 . Thank you!
