### ISSUE TITLE
feat: Add support for parquet format to file destination plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6708]
Currently the file destination plugin supports JSON and CSV outputs. Parquet would make a fine addition to the collection, as it offers better compression, has a schema, and is more performant to query.

**Comment by erezrokah** [comment]
I marked this `good first issue` as we're open to a contribution. The implementation should start by adding the support to https://github.com/cloudquery/filetypes

**Comment by hermanschaaf** [comment]
Completed in:
 - https://github.com/cloudquery/cloudquery/pull/7731
 - https://github.com/cloudquery/cloudquery/pull/7729
 - https://github.com/cloudquery/cloudquery/pull/7726
 - https://github.com/cloudquery/cloudquery/pull/7612
