### ISSUE TITLE
feat: Hashicorp Vault source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6738]
https://developer.hashicorp.com/vault/api-docs/libraries

Requested by a user on Discord https://discord.com/channels/872925471417962546/974029056070795284/1062778093875499058

At a high level, the vault resources are broken down into 3 areas:

- [system](https://developer.hashicorp.com/vault/api-docs/system) resources e.g. policies, mount points, audit etc
- [auth](https://developer.hashicorp.com/vault/api-docs/auth) resources e.g. roles, groups, certificate etc (implementation specific)
- [secret engines](https://developer.hashicorp.com/vault/api-docs/secret) resources e.g. credentials, tokens, roles (implementation specific)

**Comment by mnorbury** [comment]
`sys` resources added in [release-v1.0.0](https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-vault-v1.0.0)

**Comment by erezrokah** [comment]
Closing as resolved via https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-vault-v1.0.0
