### ISSUE TITLE
Make metrics more atomic

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#6761]
Metrics should be accessed atomically as well as updated.

Currently, there are some useful metrics that we provide for plugins.
However, the metrics collection or updates might not be atomic in the code.

We need to ensure the metrics collection to be atomic in the codebase (i.e., use [sync.Uint64](https://pkg.go.dev/sync/atomic#Uint64) and other proper types for the values and ensure proper isolation).

**Comment by yevgenypats** [comment]
Closing as we are removing in-house metrics and will be moving to open-telemtry.
