### ISSUE TITLE
Missing CSV Headers 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6783]
### Describe the Bug

When using the CSV format for blob storage destinations (s3, gcs, azureblob) CQ doesn't have any way of specifying the headers. There is no way to correlate data to a specific version to infer the headers as we do not persist the source version of the plugin

This will take 4 Seperate PRs to complete:
- [x] #6794
- [x] #6795
- [x] #6796
- [x] #6797

**Comment by erezrokah** [comment]
Closing this as resolved. If I got this wrong please re-open
