### ISSUE TITLE
bash completion trouble

### ISSUE THREAD

**Issue by PascalBourdier** [cloudquery/cloudquery#683]
### Describe the Bug
cloudquery installation makes troubles in bash completion

### Expected Behavior
```
. /opt/homebrew/etc/bash_completion
```

### CloudQuery Version
Version: 0.23.0
Commit: 3581f3d8db2fec131b1478fa75935cbc6e572e91
Date: 2022-05-10T12:16:00Z

### Debug Output
NA

### Steps to Reproduce
```
brew install cloudquery
. /opt/homebrew/etc/bash_completion
-bash: Anonymous: command not found
```

### Additional Context
```
head -3 /opt/homebrew/etc/bash_completion.d/cloudquery
Anonymous telemetry collection and crash reporting enabled. Run with --no-telemetry to disable, or check docs at https://docs.cloudquery.io/docs/cli/telemetry
# bash completion for cloudquery                           -*- shell-script -*-

```

### References
bug introduced by: https://github.com/cloudquery/cloudquery/blob/34184260b5cf066ed18c95cc2dfa9b10a89270d4/cmd/command.go#L85

**Comment by bbernays** [comment]
@PascalBourdier Thank you for bringing this up we have opened a pr that to fix this issue. If this doesn't fix your issue please re open the issue!
