### ISSUE TITLE
Support Remote Config in Google Cloud Storage

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#686]
### Is your feature request related to a problem? Please describe.

Currently we only support S3 for remote config.

### Describe the solution you'd like

Enable a user to store a config in Google Cloud Storage

**Comment by yevgenypats** [comment]
We don't want to support natively various storage layers for configs at the CLI level but rather this should be done with external tools or scripts as this will bloat the CLI with unlimited set of libraries which will make maintains hard and increase CLI size in an unnecessary ways even for users that don't use any of those storage for configs.
