### ISSUE TITLE
Support `NotResource` Attribute for provider

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#687]
### Is your feature request related to a problem? Please describe.
Right now a user can either hard code a list of all resources they want to fetch or use the `*` to get all resources. There is no way to explicitly deny a set of resources

### Describe the solution you'd like

Add an HCL attribute `not_resource`  which takes a list of resources that are not fetched

**Comment by disq** [comment]
We have `ignore_resources` in drift side so maybe a similar keyword? But the syntax is different for drift (it's `resource_type:<tags, identifier or *>`) so this one wouldn't be the same syntax.

**Comment by bbernays** [comment]
maybe `skip_resources`? I am thinking that it takes an array like `resources`
