### ISSUE TITLE
feat(alicloud): Add support for CMS resources

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#6930]
At the time of writing, the [alicloud plugin](https://www.cloudquery.io/docs/plugins/sources/alicloud/overview) supports Billing, OSS and ECS. In the [original ticket](https://github.com/cloudquery/cloudquery/issues/6416), @ishmouse also requested support for CMS. CMS supports the following resources, which we should add support for:

- [x] [ALIYUN::CMS::Contact](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-contact)
- [x] [ALIYUN::CMS::ContactGroup](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-contactgroup)
- [x] [ALIYUN::CMS::DynamicTagGroup](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-dynamictaggroup)
- [x] [ALIYUN::CMS::EventRule](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-eventrule)
- [x] [ALIYUN::CMS::EventRuleTargets](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-eventruletargets)
- [x] [ALIYUN::CMS::GroupMetricRule](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-groupmetricrule)
- [x] [ALIYUN::CMS::MetricRuleTargets](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-metricruletargets)
- [x] [ALIYUN::CMS::MetricRuleTemplate](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-metricruletemplate)
- [x] [ALIYUN::CMS::MonitoringAgentProcess](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-monitoringagentprocess)
- [x] [ALIYUN::CMS::MonitorGroup](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-monitorgroup)
- [x] [ALIYUN::CMS::MonitorGroupInstances](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-monitorgroupinstances)
- [x] [ALIYUN::CMS::SiteMonitor](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-sitemonitor)
- [ ] [ALIYUN::CMS::ResourceMetricRule](https://www.alibabacloud.com/help/en/resource-orchestration-service/latest/aliyun-cms-resourcemetricrule)

**Comment by blesniewski** [comment]
Yes
