### ISSUE TITLE
Microsoft SQL Server destination escapes `&` symbol in data

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#7001]
### Describe the Bug
> I am using the Azure source plugin. In the tags column I am seeing issues with unicode characters
`{"BillTo":"P\u0026T"}` instead of `{"BillTo":"P&T"}`. This works properly with Postgres destination.

### Expected Behavior
The data should be stored as `{"BillTo":"P&T"}`.

### CloudQuery Version
| Component | Version |
| --- | --- |
| `cloudquery` | `v2.2.0` |
| `azure` | `v3.4.0`|
| `mssql` |  `v1.0.0` |

### References
See #6984 for originally reported issue.

**Comment by candiduslynx** [comment]
Hi @rafaelrodrigues3092!
The v2 is out, could you please retest? You'll need to drop the database, as it is a major bump.

**Comment by rafaelrodrigues3092** [comment]
> Hi @rafaelrodrigues3092! The v2 is [out](https://github.com/cloudquery/cloudquery/releases/tag/plugins-destination-mssql-v2.0.0), could you please retest? You'll need to drop the database, as it is a major bump.

Thank you for the super fast turnaround on this @candiduslynx 
I should be able to test it out by end of day (EST time zone).
When I started testing the v1, I also upgraded to the Azure source plugin to v3.4.0 which introduced some performance issues on my environment. I am currently running a sync with Postgres to ensure I have a proper baseline for comparison with the MSSQL plugin (it could take up to 4 hours)

**Comment by rafaelrodrigues3092** [comment]
@candiduslynx  confirmed. Special characters are properly escaped.
Thank you!
