### ISSUE TITLE
No such host and too many open files

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#707]
### Describe the Bug

Right now we see a lot of errors that show either "no such host" or too many open-files.

Both errors are prob related (https://github.com/golang/go/issues/18588) and we already have a partial fix in place where we try to increase ulimits if we have the permissions.

We need to improve this further and calculate and the concurrent goroutines limit no more then the max ulimit specified. We should also print this information as info showing what is the concurrency limit we are running with.

**Comment by roneli** [comment]
Fixed in https://github.com/cloudquery/cq-provider-sdk/pull/256

**Comment by yevgenypats** [comment]
Closing for now as we don't set ulimit anymore as part of cloudquery. we will leave it to the user and will just add it to troubleshooting guide.
