### ISSUE TITLE
Add primary key violation check to test destination

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#7175]

**Comment by erezrokah** [comment]
Hi @candiduslynx, can you explain what's the purpose of adding this check?
Don't we need to run syncs on real data to catch PK key violations? How would adding it to the test destination help catch violations?

**Comment by candiduslynx** [comment]
@erezrokah the idea is to be able to sync from real source plugin to the test destination in order to see the pk violations.
