### ISSUE TITLE
account-aliases names 

### ISSUE THREAD

**Issue by shivabasu** [cloudquery/cloudquery#720]
Support running a query with AWS account aliases number and Azure subscription name. ( instead of AWS account number or subscription number )

 It will be easy to run queries against the alias name instead of AWS account number, Azure subscription number.

**Comment by bbernays** [comment]
Thank you for this request! We will definitely look into how we can expose better ways of querying data!

In the meantime for AWS accounts, as long as you are fetching the `iam.accounts` resource you can extract the alias by using the following sub query:
```sql
SELECT ACCOUNT_ID
FROM AWS_ACCOUNTS
WHERE ALIASES[1] =  'alias-name'
```


For example if you wanted to find all s3 buckets in account with alias `company-account-a` you would run this query:
```sql
SELECT ALIAS.NAME,
	AWS_S3_BUCKETS.*
FROM AWS_S3_BUCKETS
JOIN
	(SELECT ALIASES[1] AS NAME,
			ACCOUNT_ID ACCOUNT_ID
		FROM AWS_ACCOUNTS
		WHERE ALIASES[1] = 'company-account-a') ALIAS ON AWS_S3_BUCKETS.ACCOUNT_ID = ALIAS.ACCOUNT_ID
```

**Comment by erezrokah** [comment]
Hi @shivabasu and sorry for responding late regarding Azure.
It seems we retrieve the subscription name for Azure along side with the id, so the following query should work:

```sql
SELECT * FROM AZURE_SUBSCRIPTION_SUBSCRIPTIONS
WHERE DISPLAY_NAME = '<name>'
```
 
 Please let me know if that is what you were looking for

**Comment by erezrokah** [comment]
Closing as answered, @shivabasu please let us know if you have any other questions or we need to re-open the issue
