### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by Tymek** [cloudquery/cloudquery#7217]
One of contributors is trying to promote this project in an aggressive way.

<img width="961" alt="image" src="https://user-images.githubusercontent.com/2625371/214870823-e3794180-0cc5-444f-b082-360b755671c2.png">

**Comment by yevgenypats** [comment]
Hey @Tymek This is me :) Im the founder, if we opened an issue in one of your repositories and it's not relevant Im sorry. I opened this only in projects that I think it's relevant, so I wouldn't consider this spam, I don't have other way of reaching out to maintainers other then a GitHub issue to relevant projects. Again sorry if I opened this in a non-relevant projects you are part off. Feel free to reach out to me directly as well.

**Comment by yevgenypats** [comment]
Closing. Feel free to re-open or reach out to me directly.
