### ISSUE TITLE
`azure_compute_skus` primary key violations

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#7245]
See #7183 for more details.

**Comment by erezrokah** [comment]
Re-opened this issue to investigate https://github.com/cloudquery/cloudquery/pull/7267#issuecomment-1407597896

**Comment by candiduslynx** [comment]
It seems that there are several problems:
1. `kind` isn't always filled in
2. `family`, `name` are, but don't provide proper uniqueness

We need to update the PK to include the value hash, as proposed in #7202 for AWS RDS enggine versions
