### ISSUE TITLE
Investigate Incremental Tables for AWS Plugin

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#7286]
### Is your feature request related to a problem? Please describe.

Some tables that might benefit from 

`aws_inspector2_findings`
`aws_inspector_findings`
`aws_config_*_compliances`
`aws_docdb_events`
`aws_ec2_ebs_snapshots`
`aws_ec2_instances`
`aws_ec2_instance_statuses`
`aws_ecr_repository_image_scan_findings`
`aws_glue_job_runs`

**Comment by skhreshefsharvit** [comment]
any plans on doing this?

**Comment by DylanKeyer** [comment]
+1

**Comment by bbernays** [comment]
@DylanKeyer and @skhreshefsharvit - I will be working on this issue. Are there any specific tables that you would particularly be interested in seeing support Incremental syncs?

**Comment by bbernays** [comment]
Update:
- As of aws plugin `v24.1.0` `aws_inspector2_findings` now supports incremental sync
- The following tables cannot be converted into  `aws_ec2_ebs_snapshots`,`aws_ec2_instances`, `aws_ec2_instance_statuses` into incremental tables as their is no API filtering capability that is suitable. 
- `aws_ec2_instances` is able to be synced using the Event-based syncing capabilities
- `aws_ec2_ebs_snapshots` and `aws_ec2_instance_statuses` can both be supported in the future via event-based syncing
- None of the IAM APIs are suitable for incremental sync, but most IAM resources are already supported via the event-based sync. If there are any resources that are missing please let us know

**Comment by erezrokah** [comment]
Closing as done. Please comment if you have additional requests
