### ISSUE TITLE
Test --cq-dir behavior

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#7292]
We should test that when `--cq-dir` is set, it is respected by the plugin download process. This is an important feature for running multiple cloudquery instances in parallel from the same directory.

**Comment by erezrokah** [comment]
We use it in our existing tests https://github.com/cloudquery/cloudquery/blob/b7a81763d61b6eaec6cad81636647afe85ac4cd9/cli/cmd/sync_test.go#L22 so maybe it would be easy to add an assertion there
