### ISSUE TITLE
Resources With No (guaranteed) Unique Fields

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#7293]
### Is your feature request related to a problem? Please describe.

Identify and implement a better way to handle PKs for resources that are NOT user defined and that have no clear unique ids (or set of fields that guarantee uniqueness) 

This is a continuation of [this conversation](https://github.com/cloudquery/cloudquery/pull/7202#discussion_r1088643448)

**Comment by erezrokah** [comment]
I think the action item here could be to do one of the following (in the SDK) if there are not PKs:
1. Use all columns as PKs
2. Add a new column `_cq_item_hash`, make that the PK and hash the entire content of the item

**Comment by erezrokah** [comment]
Thought of another option. If the resource is a relation we can make it a column of the parent, similar to https://github.com/cloudquery/cloudquery/pull/12408#discussion_r1267911498

**Comment by erezrokah** [comment]
OK so we haven't seen many of these cases so I'm not sure we need a generic approach (or can have since we would need to verify the fields we use for uniqueness manually anyways). Closing for now as `wontfix`. If you think we still need this comment and I'll re-open
