### ISSUE TITLE
fix(website): Hide deprecated blogs

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#7332]
Nextra has a feature of hiding pages, while keeping the links (avoiding 404s).
We should try and use it to hide deprecated blog posts:
https://nextra.site/docs/docs-theme/page-configuration#hidden-routes

I tried it but couldn't get it to work, so I'm probably missing something and will need to debug it further.
Maybe it only hides it in the sidebar:
![image](https://user-images.githubusercontent.com/26760571/215425818-d349d651-9045-4139-a6c2-888c443f3e80.png)

**Comment by yevgenypats** [comment]
Closing as we are not using nextra anymore
