### ISSUE TITLE
Possible improvements to `cloudquery` commands

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#751]
Opening a top level issues to log ideas I have when I use the `clouduqery` CLI.

- [x] When running `cloudquery fetch` before running `cloudquery init` we get an error `Failed to read file; The file "./config.hcl" could not be read: no such file or directory. Hint: Try cloudquery init <provider>`. We could also prompt the user (if we detect a non CI environment) to run the `init` for them, e.g. `would you like to run init now?` or something similar
- [x]  When running `cloudquery init <provider>` with an existing config file, the command fails with `Error: Config file ./config.hcl already exists`. We could also prompt the user (if we detect a non CI environment) to override the existing config. In CI environments we can fail, and also add `--force` flag to always override without prompting

**Comment by yevgenypats** [comment]
init,gen were removed.
