### ISSUE TITLE
GitHub Rate Limiting

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#7523]
### Describe the Bug

If you run CloudQuery on a GitHub Action for a small org like CloudQuery, you will get throttled.

For just syncing the following tables: `github_repositories*`

### Expected Behavior

There should be a ratelimiting mechanism within the plugin to protect against rate limit errors

**Comment by erezrokah** [comment]
This was improved by https://github.com/cloudquery/cloudquery/pull/8078 and https://github.com/cloudquery/cloudquery/pull/8074. Regarding the 5000 per hour rate limit there isn't much we can do so I'm closing the issue. We can re-visit of we get more users reports
