### ISSUE TITLE
Add no-color flag for logs and output

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#762]
### Is your feature request related to a problem? Please describe.
Right now even if we use `--enable-console-log` in various environments we will see things like that: `[31merror=[0m` in the logs.

### Describe the solution you'd like
1) Explicit flag to disable colors
2) maybe auto detect.
3) are colors are at all necessary as part of cloud query **logs**? can we remove it all together? This might remove the chicken and egg of detecting, disabling etc. we can still keep them in the UI mode but not sure I would do that in the logs mode. Might make sense in the logs mode to use tools on top that parse and colorize, etc...

**Comment by roneli** [comment]
There is a log colour detector, this is becaue ui.ColorizedOutput gets also sent to the logger, there is another function called ColorizedNoLogOutput that doesn't save to the log.

**Comment by bbernays** [comment]
does the `--disable-log-color` flag not do this?
