### ISSUE TITLE
Is it possible to get docker image layer and base image used in k8s cluster information with current kubernetes plugin 

### ISSUE THREAD

**Issue by mjzet** [cloudquery/cloudquery#7634]
We are using cloudquery version [2.0.26], and k8s plugin version "v3.0.1.
Is it possible to get information related to base docker image used for a container image of  pod/sts etc along with docker layers constituting the container image.

**Comment by erezrokah** [comment]
Hi @mjzet 👋 Do you mean the Docker image referenced from https://www.cloudquery.io/docs/advanced-topics/docker?

If so see related file here:
https://github.com/cloudquery/cloudquery/blob/db53d6da57428748a26911a9843668ae8d32117c/cli/Dockerfile.goreleaser

We use GoReleaser to publish to the Docker registry here:
https://github.com/cloudquery/cloudquery/blob/db53d6da57428748a26911a9843668ae8d32117c/cli/.goreleaser.yaml#L13

**Comment by erezrokah** [comment]
Hi @mjzet as @hermanschaaf pointed out to me, you might be asking about based images of pods used in k8s.
Can you confirm? If so we'll need to see how to extract that data

**Comment by mjzet** [comment]
@erezrokah  I mean, I am already running cloudquery in a pod where I am trying to sync tables from my kubernetes cluster context to postgres sql db. I need one layer down information as in, in a pod, the image that we are using:

1. What is the base image of the pod image used.
2. What all docker layers are present in the container image of pod.

Thanks!

**Comment by erezrokah** [comment]
Thanks for clarifying @mjzet!

So there's the `spec_containers` column which is a JSON array of containers each have an `Image` field.
Is it correct that you'd like to unwrap that into the layers that formed the image?

That might be out of scope for CloudQuery (unless we have a Docker source plugin...).
I found this tool https://github.com/wagoodman/dive, would that work for you (by post processing CloudQuery data)?

**Comment by mjzet** [comment]
@erezrokah  DO you already have Docker source plugin already ?

**Comment by erezrokah** [comment]
We don't have one yet. I think it will require some thinking to support your use case, as it's not simply syncing all of the docker registry. There's some logic there to unwrap image layers that we probably wouldn't want to re-implement.

I'll bring this up with the rest of the team to see what they think too

**Comment by mjzet** [comment]
@erezrokah  Sure, Thanks for the information.

**Comment by erezrokah** [comment]
Hi @mjzet, we discussed this internally and we feel this is currently out of scope for CloudQuery. We might re-visit this as a separate source plugin in the future, so users can correlate data between multiple plugins.
Our recommendation is to use a separate post processing job to read the image and do the analysis.

Please let me know if that make sense.

**Comment by yevgenypats** [comment]
Also, adding another question. @mjzet  Do you have currently a tool you use to extract layers and info from docker images? This will help us also better understand the use-case end-to-end.

**Comment by erezrokah** [comment]
Closing this as answered. If you have any concerns or questions please comment
