### ISSUE TITLE
Sonatype Nexus Source Plugin

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7640]
Customer requested source plugin for Sonatype Nexus (storage repository)

https://www.sonatype.com/products/repository-oss-download

**Comment by yevgenypats** [comment]
@pilvikala can you add it as coming soon plugin and we will be able to close it.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/sonatype-nexus. Please sign up there to get a notified when the plugin is available.
