### ISSUE TITLE
sync with s3 or file destination does not get all resources

### ISSUE THREAD

**Issue by jimr6007** [cloudquery/cloudquery#7645]
### Describe the Bug

been running sync with Postgres destination for months now, works great
that gives me 281 elbv2_load_balancers
great...

try it with file or S3 destination and I only get 10

the sync to file or s3 completes without error, no errors while sync in progress

### Expected Behavior

sync to destination file or s3 should yield the same or pretty close to the same number of resources as a sync to destination postgres

### CloudQuery Version
2.3.6
latest versions of AWS source and S# destination plugins

### Debug Output

n/a

### Steps to Reproduce

run a sync with AWS source and file or s3 destination

Also please share any other necessary configuration files
-->

**Comment by jimr6007** [comment]
sorry guys, user error...

**Comment by yevgenypats** [comment]
No worries. Thanks for reporting back 🙏

**Comment by yevgenypats** [comment]
Can you share the user-error just in case, for future users if they hit the same snag?
