### ISSUE TITLE
unsupported Unicode escape sequence

### ISSUE THREAD

**Issue by nicolascavedale** [cloudquery/cloudquery#7647]
### Describe the Bug

I have recently upgraded Cloudquery to the latest version (docker image), and some things have changed since the version I was in (e.g. separate source and dest yml files, sync instead of fetch). I made all the necessary changes for this new version and config seems to be ok, but when I run the sync command, it actually runs for a few minutes but at some point fails with the following error:

Error: failed to sync v1 source accounts-resources: failed to write for accounts-resources (aws@v13.0.0) -> postgresql (v2.0.8): failed to CloseAndRecv client: rpc error: code = Internal desc = Context done: context canceled and failed to wait for plugin: failed to execute batch with pgerror: severity: ERROR, code: 22P05, message: unsupported Unicode escape sequence, detail :\u0000 cannot be converted to text., hint: , position: 0, internal_position: 0, internal_query: , where: JSON data, line 1: {"AthenaError":{"ErrorCategory":2,"ErrorMessage":..., schema_name: , table_name: , column_name: , data_type_name: , constraint_name: , file: jsonfuncs.c, line: 615, routine: json_ereport_error: ERROR: unsupported Unicode escape sequence (SQLSTATE 22P05)

Is there any configuration I may have overlooked? I couldn't find anything in the documentation about this.

Any help will be appreciated!

Thanks!

**Comment by nicolascavedale** [comment]
As you can see in the error message, the plugins versions are (aws@v13.0.0) and postgresql (v2.0.8).
I'm running this on ECS/Fargate (AWS).

**Comment by shimonp21** [comment]
@nicolascavedale Thank you for reporting this!
From my first look, this is a bug in the CloudQuery code, so no configuration issues on your side.
I will keep you posted on how the investigation/fix goes.

**Comment by shimonp21** [comment]
@nicolascavedale Hello, and sorry for the delay.
I managed to reproduce and fix this bug - I believe upgrading to `postgresql` plugin version `v2.0.10` Should fix the bug you are seeing.
Please let us know!

**Comment by nicolascavedale** [comment]
Thank you @shimonp21 !! I will do another test and let you know the results...

**Comment by erezrokah** [comment]
Thanks for the report @nicolascavedale and the fix @shimonp21. I'll close this as resolved, if the issue still exists please comment and I'll re-open @nicolascavedale 👍

**Comment by nicolascavedale** [comment]
Worked great! I only had to increase the size of the container (cpu/mem) because I kept getting some EOF errors.

**Comment by erezrokah** [comment]
Thanks for confirming @nicolascavedale! Great fix @shimonp21 🚀
