### ISSUE TITLE
AWS IAM User Signing Certificates

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7694]
https://docs.aws.amazon.com/cli/latest/reference/iam/list-signing-certificates.html

**Comment by bbernays** [comment]
@jsonpr- Is there any security reason why we should consider **not** storing the `CertificateBody`?

**Comment by jsonpr** [comment]
@bbernays Good question.  the `CertificateBody` corresponds with the public key so in theory, it should not be sensitive information.  

It should be ok - I could see some customers asking for it to be redacted.  For now, let's leave it in and if customers request to take it out, we can revisit that question.
