### ISSUE TITLE
Change of Json format in tags column, table aws_ec2_instances after AWS plugin 9.1.1

### ISSUE THREAD

**Issue by cloudguy11** [cloudquery/cloudquery#7715]
### Describe the Bug
AWS Plugins later than circa version 9.1.1 change the Json format in the tags column of table aws_ec2_instances. This introduces an incompatible change,  and the json format change is also not present in other plugins like Azure source plugin.

Examples:

aws_ec2_instances, column tags format until 9.1.1 is  {"KEY" : "VALUE"}, example: 

{"Name": "My_name_value", "Product": "my_product_value", "Customer": "my_customer_value"}

In AWS plugin versions >= 10.x.x, the json format is:

[ {"Key": "my_key_value", "Value" : "my_value"} , ...] , example:

[{"Key": "Customer", "Value": "my_customer_value"}, {"Key": "Product", "Value": "my_product_value"}, {"Key": "Name", "Value": "My_name_value"}]

That new json format, has several disadvantages:
1. New JSON format is much more difficult to query with PostGres SQL queries.
2. Incompatible and different from the format of other source plugins like Azure, which stick to the preferable old KEY:Value format.
3. Not backwards compatible with existing Apache Superset and Grafana Dashboards and reports.

Therefore, potentially an unintended, und undesirable format change.
I suggest to switch back to the previous json format of the aws_ec2_instances tags string.

### Expected Behavior

In the aws_ec2_instance table the "tag" column should be in the format:
 {"Key_name" : "value", "Key_name2", "value2"} 

instead of

[ {"Key": "Key_name", "Value" : "value"} , {"Key": "Key_name2", "Value" : "value2"}] 

### CloudQuery Version
Affects versions after AWS Plugin 9.1.1, e.g.  AWS Source plugins 10.x.x an above.

### Steps to Reproduce

1. Sync AWS ressources using AWS Plugin version <= 9.1.1 into PostGres. Check Json format of table aws_ec2_instances, column "tags".
2. Repeat the same with AWS Plugin version > 10.x.x. Observe change in JSON format of table aws_ec2_instances, column tags and compare format also to azure_compute_virtual_machines, columns 'tags'

**Comment by bbernays** [comment]
@cloudguy11 can you check the latest release? I think it might have been fixed in https://github.com/cloudquery/cloudquery/pull/7621

**Comment by cloudguy11** [comment]
Thanks. V13.1.0 solved the issue.
