### ISSUE TITLE
Unexpected errors when running policies

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#772]
### Describe the Bug
User experienced errors when running policies.
![image](https://user-images.githubusercontent.com/37939765/170024053-c418b17c-6b1b-4e3a-be3d-013f0a8acfa1.png)

The errors were fixed when by adding super weird blocks to `config.hcl`:

```
policy "aws" {
  source = "aws"
}

policy "gcp" {
  source = "gcp"
}
```

It may be related to https://github.com/cloudquery/cloudquery/issues/771.
Also, I really think the option of embedding policies in `config.hcl` is not good - it doesn't follow the "single-source-of-truth" paradigm. i.e. I believe policies should always be separate from `cloudquery`'s config. 

### CloudQuery Version
cloudquery version 0.23.2

**Comment by bbernays** [comment]
@shimonp21 Can we close this issue?

**Comment by shimonp21** [comment]
It's a duplicate of https://github.com/cloudquery/cq-provider-sdk/issues/312.
