### ISSUE TITLE
CLI link to telemetry documentation results in 404

### ISSUE THREAD

**Issue by bdmorin** [cloudquery/cloudquery#7829]
### Describe the Bug

When exploring how to configure cloudquery, the link to describe how to work with telemetry options results in a 404.
<img width="1279" alt="CleanShot 2023-02-08 at 16 16 20@2x" src="https://user-images.githubusercontent.com/476219/217663735-19736f03-a100-4080-bbe5-025c1aa36140.png">

https://docs.cloudquery.io/docs/cli/telemetry results in a 404.
<img width="691" alt="CleanShot 2023-02-08 at 16 18 02@2x" src="https://user-images.githubusercontent.com/476219/217663949-91e44d67-0981-48c6-82a2-74e39c49d9cd.png">

### Expected Behavior

I assume the CLI link should point to this page:
https://www.cloudquery.io/docs/telemetry

### CloudQuery Version

```
~> cloudquery version
Version: 0.22.1-hotfix
Commit: fba843dea84c68cfd144aca7ce13321cffccfb3b
Date: 2023-02-08T19:53:19Z
```

### Debug Output

The debug output command in the github template does not appear to work.

`cloudquery --log-console --log-level debug`

I've tried many iterations of the debug command, none of them worked.
```
> cloudquery version --log-console --log-level debug
Error: unknown flag: --log-console
Usage:
cloudquery version

Additional help topics:
```

**Comment by bbernays** [comment]
Hi @bdmorin - Thank you for opening this issue! The version you are using is a hotfix for a super old version of CloudQuery that we released today for a user. 

I think you have have actually raised a bigger issue in that our brew `brew install cloudquery` is currently pointing towards the latest release rather than the highest version. If you run `brew install cloudquery@2` you will get the latest version

**Comment by bbernays** [comment]
@bdmorin just wanted to let you know that we have updated the brew tap so if you run `brew remove cloudquery` and then reinstall it you should get the latest version `v2,.3.8`

**Comment by yevgenypats** [comment]
Thanks for reporting everyone. Closing. This was a glitch in our release process. Fixed now with https://github.com/cloudquery/cloudquery/releases/tag/cli-v2.3.8
