### ISSUE TITLE
AWS Account AZs

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7910]
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-availability-zones.html

**Comment by bbernays** [comment]
Is this different than [`aws_regions`](https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/docs/tables/aws_regions.md)?

**Comment by jsonpr** [comment]
Good catch!, edited for AZs.

**Comment by jsonpr** [comment]
Thanks, edited to cover AZs
