### ISSUE TITLE
AWS Transit Gateway Route Table Routes

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7913]
https://docs.aws.amazon.com/cli/latest/reference/ec2/search-transit-gateway-routes.html

**Comment by bbernays** [comment]
@jsonpr - We already support [TGW Route Tables](https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_transit_gateway_route_tables)... Is this resource different or is it still needed?

**Comment by jsonpr** [comment]
Hey @bbernays this issue is for Route Table Routes and not just the route table.  The actual routes which are currently not included in TGW Route Tables.

**Comment by bbernays** [comment]
There is no read-only way to get all routes for a TGW Route Table. The method linked in this issue (`search-transit-gateway-routes`) has no pagination or sort options, which means that we cannot even guarantee that we will get the same subset of routes for each request. The other method (`export-transit-gateway-routes`) exports the data to a user defined S3 bucket and returns the full path to the object.

**Comment by erezrokah** [comment]
Going to close this as `wontfix` for now. We can re-open if someone requests it again and research a solution
