### ISSUE TITLE
AWS RDS Resources: Backtracks, Events, more

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7916]
- [ ] RDS BackTracks https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusterBacktracks.html
- [ ] Events: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeEvents.html
- [ ] Option Group (and Option Group Options): https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeOptionGroups.html
- [x] Reserved Instances: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeReservedDBInstances.html

**Comment by Hokwang** [comment]
I need `reserved instances`.

**Comment by bbernays** [comment]
@Hokwang - Thanks for the comment. I have opened a separate issue to track that request: #8261

**Comment by hermanschaaf** [comment]
I've opened https://github.com/cloudquery/cloudquery/pull/8671 to add RDS Backtracks, Events and Option Groups
