### ISSUE TITLE
AWS EC2 Resources

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#7926]
- [x] Launch Templates, Launch Template Versions https://github.com/cloudquery/cloudquery/pull/8675
- [x] Spot Fleet, Spot Instances https://github.com/cloudquery/cloudquery/pull/8679
- [x] DHCP Options https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DhcpOptions.html https://github.com/cloudquery/cloudquery/pull/8678
- [x] Image Launch Permissions https://github.com/cloudquery/cloudquery/pull/8689

**Comment by blurayne** [comment]
+ Launch Template Version ;)

**Comment by erezrokah** [comment]
> also i noticed images are just from one specific account. unfortunately i cannot read from the other account that shares the images as workaround. some kind of additional filtering for those plugins would be cool (source config file?)

Hi @blurayne thanks for commenting! Do you mind opening a new issue for this? Please provide an example configuration and expected result vs actual result if possible as that would make it easier to understand your use case

**Comment by disq** [comment]
Launch templates were implemented in https://github.com/cloudquery/cloudquery/pull/8675

**Comment by disq** [comment]
Image Launch Attributes would mean calling https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImageAttribute.html but the problem is if we want other types of attributes we need to multiply the calls to fetch each set of attributes separately:

> Valid Values: description | kernel | ramdisk | launchPermission | productCodes | blockDeviceMapping | sriovNetSupport | bootMode | tpmSupport | uefiData | lastLaunchedTime | imdsSupport

**Comment by jsoncow** [comment]
I'm ok leaving it as only launchPermissions for now to finish this issue.  

Description, sriovNetSupport, imdsSupport, bootMode, tmpSupport, productCodes, kernel, ramdisk are all included in aws_ec2_images.  (Also blockDeviceMapping)

That leaves uefiData and lastLaunchedTime as the other attributes we currently don't have.   We can leave it as is and if there's a future feature request for these other attributes, we can revisit them.

**Comment by jsonpr** [comment]
I'm ok leaving it as only launchPermissions for now to finish this issue.

Description, sriovNetSupport, imdsSupport, bootMode, tmpSupport, productCodes, kernel, ramdisk are all included in aws_ec2_images. (Also blockDeviceMapping)

That leaves uefiData and lastLaunchedTime as the other attributes we currently don't have. We can leave it as is and if there's a future feature request for these other attributes, we can revisit them.

**Comment by erezrokah** [comment]
I think this is done, great work @disq. I updated the issue description with the relevant PRs. If something is missing please comment and I'll re-open
