### ISSUE TITLE
The allignmnet of the output table is not correct. 

### ISSUE THREAD

**Issue by manish199014** [cloudquery/cloudquery#797]
### Describe the Bug
The output of the policy "aws//foundational_security/iam/IAM.5" is not correctly aligned. 

### Query Output
Marked in the red block are AWS account ID and similarly the value of the other rows are misplaced. 

![image](https://user-images.githubusercontent.com/14213944/170623010-de6b50f7-6bfb-4e26-8175-e95fc9de8f9f.png)

### CloudQuery Version

0.24.1

**Comment by bbernays** [comment]
@manish199014 - Thank you for your bug report. We have found the issue and working on releasing a fix soon

**Comment by erezrokah** [comment]
Thanks for reporting @manish199014 and for the fix @bbernays.
The fix for this issue is released in https://github.com/cloudquery/cloudquery/releases/tag/v0.24.7
