### ISSUE TITLE
Feature Request: Support BigQuery as database

### ISSUE THREAD

**Issue by portenez** [cloudquery/cloudquery#80]
Story

> As report builder
I want to  use [Google's BigQuery](https://cloud.google.com/bigquery) 
So that I can benefit of `BigQuery`'s capabilities

Why use BigQuery

- Setting up BigQuery is very simple (automated or through the gcp console)
- BigQuery can be easily integrated with [Google Data Studio](https://datastudio.google.com/u/0/) which can be used to create interactive reports.
- BigQuery supports an on-demand pricing model very useful for prototyping.
- BigQuery on-demand model allows for one  [free 1TB per month](https://cloud.google.com/bigquery/pricing#on_demand_pricing)

**Comment by yevgenypats** [comment]
Hey @portenez , Thanks for the issue. I've a couple follow-up question - DataStudio is useful indeed but it also works with PostgreSQL. Any reason not to use Postgres? BigQuery has some limitations on relations and updating of configurations (a lot of times it is used in kinda append only mode which I'm not sure is the case here)

**Comment by portenez** [comment]
Hi, thanks for replying. Basically, it's just `BigQuery` comes with a decent free tier. Whether Postgres doesn't quite have a free tier. (or is it?). But yeah, in general, `Postgres` works well in general.

**Comment by yevgenypats** [comment]
Got it. I guess if it's a matter of price it might be easier to find a free managed Postgres provider (I think Heroku has one https://elements.heroku.com/addons/heroku-postgresql).

**Comment by portenez** [comment]
Thank you for the convo 🙏🏽 . It all makes sense.

Some comments and questions for my ref... and then we can close this ticket (If the `cloudquery` teams thinks it's not valuable at the moment).

## Comments

- BigQuery's `append-only` operating-mode it's a feature (as it is an analytics db), but I do understand if it goes against the current philosophies of the `cloudquery` project
- There's another ticket logged #55 , asking to keep track of historical data. If a timestamp is appended to each crawl, then the `append-nature` of `cloudquery` becomes a non-issue.

## Questions

> BigQuery has some limitations on relations 

Is this something that the cloudquery team has encountered before? If so.. It'll be useful to know some concrete issues with these limitations. We don't have to go into great details, but a link would be great.

**Comment by yevgenypats** [comment]
Thanks for the follow-up.

Regarding append only mode we are implementing something like this ATM so bigquery and also a bit stronger then just append only so we should have this feature soon.

Hopefully this answers the comments.

Regarding the relation question - For example if you have `ec2_instance` and `ec2_ips` and other one-to-many tables. you can easily join on those and also add smarter constraints like `cascade` so when you remove an instance from the database all the related one-to-many data is also removed and your data stays consistent.

**Comment by portenez** [comment]
Thanks. I got it. I'm good with closing the ticket.
