### ISSUE TITLE
Feature Request: Add support for GCR repositories and images

### ISSUE THREAD

**Issue by portenez** [cloudquery/cloudquery#81]
Can cloudquery support GCR just like it supports ECR?

> As a gcp and aws user
I want to have data about both ecr(aws) and gcr(gcp)
so that I can analyze container patterns in both was and gcp

Cloudquery currently supports  ECR(aws docker registry) images, however it does not support GCR (GCP). 

as ref. cloudquery currently creates the following ecr related tables.

1. aws_ecr_image_tags
1. aws_ecr_image_severity_counts
1. aws_ecr_repositories
1. aws_ecr_images

**Comment by roneli** [comment]
closing, resources have already been added to AWS provider :)
