### ISSUE TITLE
Sync log table

### ISSUE THREAD

**Issue by michalz-rely** [cloudquery/cloudquery#8146]
### Is your feature request related to a problem? Please describe.
CQ does not provide a native broken sync handling mechanism. It would be beneficial creating a sync log table

### Describe the solution you'd like
A table storing sync_time(_cq_sync_time) | start(timestamp) | heartbeat(timestamp) | finish(timestamp)

### Describe alternatives you've considered
Reading CQ log file and looking for the sync_time, manually inserting it to the DB

### Additional context
If the sync job is made in a append mode and CQ is writing to postgres, _cq_sync_time is used for querying point in time data. The problem starts, if for any reason sync job get distracted. Another sync job might be necessary to complete a snapshot, but the data from a disrupted sync job would still be in the inconsistent state in the db, so we might end up with duplicated entries for that day, from bot incomplete sync, and complete sync.

It would be great to have some simple solution that could identify if the previous sync job has succeeded successfully. If not, to try make another sync, and if succeed delete rows containing _cq_sync_time of the job which has not completed.

**Comment by erezrokah** [comment]
Closing this issue in favor of https://github.com/cloudquery/cloudquery/issues/8690. While not completely identical solutions, I think the use case is the same, so we can discuss on a the same issue
