### ISSUE TITLE
feat: CloudWatch source plugin

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8163]
Users are interested to use CloudQuery to sync CloudWatch (mostly to S3 destination) and then join the data with other CQ and billing/cost data with Athena.

**Comment by bbernays** [comment]
When you say cloudwatch what do you mean? Logs, Metrics, RUM?

**Comment by yevgenypats** [comment]
Pasting link from discord - https://discord.com/channels/872925471417962546/1075592785798905866/1075818516655120394

**Comment by pilvikala** [comment]
The aws_alpha_cloudwatch_metrics and aws_alpha_cloudwatch_metric_statistics are supported in the AWS plugin now.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/cloudwatch. Please sign up there to get a notified when the plugin is available.
