### ISSUE TITLE
bug(website): Light mode code snippets are hard to read

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#8227]
Example:
![image](https://user-images.githubusercontent.com/26760571/219949617-59b0de20-541a-41a1-9698-89c2f4b05fe2.png)

In https://www.cloudquery.io/docs/plugins/sources/aws/overview

**Comment by nagaajay4** [comment]
Can you please assign me the issue I am interested @erezrokah.

**Comment by hermanschaaf** [comment]
Thanks @nagaajay4 - I assigned the issue to you, let us know how you get on 😃

**Comment by erezrokah** [comment]
Thanks @nagaajay4, we're using Nextra as our build framework. See about it's syntax highlighting feature here https://nextra.site/docs/guide/syntax-highlighting
