### ISSUE TITLE
Test with v10 postgres instead of v11

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#828]
aurora DB is 10.8, and a lot of users use it. We need to test that we don't break compatibility with it.

**Comment by erezrokah** [comment]
Relevant `cloudquery` repo workflows are here:
https://github.com/cloudquery/.github/blob/affdca8a853ba90a3854b2dfc0fc7d60d6c839b0/workflows/repo-specific/cloudquery/test.yml#L19
https://github.com/cloudquery/.github/blob/affdca8a853ba90a3854b2dfc0fc7d60d6c839b0/workflows/repo-specific/cloudquery/sanity.yml#L19
https://github.com/cloudquery/.github/blob/affdca8a853ba90a3854b2dfc0fc7d60d6c839b0/workflows/repo-specific/cloudquery/policy_test.yml#L18

Also, we should update the required status checks here:
https://github.com/cloudquery/.github/blob/affdca8a853ba90a3854b2dfc0fc7d60d6c839b0/repo-settings/cloudquery/config.yaml#L11
