### ISSUE TITLE
S3 Source

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8320]
Source to sync json,csv,parquet from an S3.

Specific use-case: (AWS Config snapshots)

Requested by user on discord

**Comment by erezrokah** [comment]
For those watching this issue, we have a new [`file` source plugin](https://www.cloudquery.io/docs/plugins/sources/file/overview) that can source local `parquet` files (e.g. [AWS Cost and Usage reports](https://www.cloudquery.io/docs/core-concepts/dashboards#cost-optimization)).

If supporting sourcing `parquet` files directly from S3 is something you're interested in, comment on this issue with your use case.

**Comment by fosk06** [comment]
The use case i would need is this one : read files(csv,parquet) from S3 bucket and move them to destination ( databases, warehouses etc)

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/s3-bucket. Please sign up there to get a notified when the plugin is available.
