### ISSUE TITLE
Need signedIdentifiers field

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#8339]
### Why do you need this resource or plugin? Please describe.
Some criteria we'd like to be able to check the queue ACL does not contain full access permissions.

### Describe the solution you'd like
Need signedIdentifiers field for getQueueAcl check the queue ACL does not contain full access permissions.

### Additional context
This is cloudsploit referenced api:
https://docs.microsoft.com/en-us/azure/storage/queues/storage-quickstart-queues-portal

This is cloudsploit plugin link: https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/queueservice/queueServiceAllAccessAcl.js

**Comment by erezrokah** [comment]
Hi @code-vise, do you mind linking to the REST API/Go lang SDK code that has this information? I could not find a method to get the queue access policy in https://learn.microsoft.com/en-us/rest/api/storagerp/queue-services/list?tabs=HTTP

**Comment by code-vise** [comment]
sure, here it is https://www.npmjs.com/package/@azure/storage-queue. 
We would like to ensure that queues do not allow full write, delete, or read ACL permissions. And we need Queue Service table for this.

**Comment by erezrokah** [comment]
Good catch @RyPeck, it's not blocked, but I think we will need to use another API to get this information so might take a bit more effort. I'll schedule this for our next iteration to take a look

**Comment by RyPeck** [comment]
@erezrokah looking to see the same thing for storage tables as well. With #5425 completed we saw tables get populated - but not the ACLs pulled in.

**Comment by RyPeck** [comment]
@erezrokah should I create a separate issue for tables?

**Comment by erezrokah** [comment]
Yes, please do @RyPeck, that should help us with prioritization 🙌
