### ISSUE TITLE
feat(azure): Remove `azure_azuredata_sql_server_registrations` table

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#8343]
Context in https://github.com/Azure/azure-sdk-for-go/issues/19789#issuecomment-1438803340

That `azuredata` API is deprecated and we should only use `azurearcdata` (source - Azure support).

Code to delete https://github.com/cloudquery/cloudquery/tree/7c1dc40bc07a2b8211ca2e884748e45ffc7a6f0b/plugins/source/azure/resources/services/azuredata

**Comment by pat-nel87** [comment]
@erezrokah Please assign this to me, I'll gladly take care of this.

**Comment by erezrokah** [comment]
Resolved by https://github.com/cloudquery/cloudquery/pull/8419, great work @pat-nel87 🎸
