### ISSUE TITLE
Support Local Provider Plugin

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#840]
Users should be able to execute a plugin they have locally without first downloading it. This will enable users to use private providers

**Comment by OneCricketeer** [comment]
Watching. Also seems to be related to #738 

Might be worth gather inspiration from Terraform that will read from directories like `~/.terraform.d/plugins/${PROVIDER_NAMESPACE}/${VERSION}/${OS_ARCH}`

**Comment by erezrokah** [comment]
Should be resolved in [v2](https://github.com/cloudquery/cloudquery/pull/1463)

**Comment by yevgenypats** [comment]
Closing as solved in v1 via `registry: local` - https://www.cloudquery.io/docs/reference/source-spec#registry and specifying `path` to local plugin
