### ISSUE TITLE
Connecting Relation Tables to Parent Table

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#8415]
### Describe the Bug

Currently if a relation table adds a new resource for an existing parent object, the nested resource will have a `_cq_parent_id` that is randomly generated and points to nothing

### Expected Behavior

Users should always be able to join a record in a relation table to the parent record.

### Steps to Reproduce
1. create lambda function
2. sync `aws_lambda_functions` and `aws_lambda_function_alias`
3. Create alias resource for function created in step 1
4. Sync same tables as in step 2
5. Try and join the alias resource to the function using the `_cq_parent_id`
Also please share any other necessary configuration files

**Comment by candiduslynx** [comment]
Decided approach: deterministic `_cq_id`:
1. Implement deterministic PK hash:
  - hash all PK fields in the order they're defined
  - if the field is map, it's hash should also be deterministic
  See [maps.Keys](https://pkg.go.dev/golang.org/x/exp/maps#Keys) & [slices.Sort](https://pkg.go.dev/golang.org/x/exp/slices#Sort) doc.
    ```go
    keys := maps.Keys(field)
    slices.Sort(keys)
    for _, key := range keys {
      ...
    }
    ```
  - if there's no PK apart from `_cq_id`, hash the whole resource (excluding fields prefixed `_cq_`) in the same order the fields are defined
2. As the `_cq_id` becomes deterministic, we should always overwrite `_cq_parent_id`

**Comment by disq** [comment]
I don't think definition order is important for our use case? Why not hash keys after sorting, so that order never matters and is consistent even if the order changes (as fields are sometimes moved from `transformers` to overrides they change order but the hash shouldn't really really care about it -- as this is not for indexing etc. purposes)

**Comment by candiduslynx** [comment]
Updated to sort keys first

**Comment by bbernays** [comment]
I think [this library](https://github.com/mitchellh/hashstructure) will dit everything we need in terms of the ensuring the hash is deterministic even for maps and slices

**Comment by candiduslynx** [comment]
> I think [this library](https://github.com/mitchellh/hashstructure) will dit everything we need in terms of the ensuring the hash is deterministic even for maps and slices

We need to address the fact that we sometimes skip fields, too.
So, we should hash each column value and then, possibly, use uuid5 hash (SHA-1 hashing) to construct the final `_cq_id` value.

**Comment by bbernays** [comment]
Why couldn't we call something like this (assuming that we validate the library handles map/slice ordering):

```go
pks := table.PrimaryKeys()
if len(pks) == 0 {
    hash, err := hashstructure.Hash(entireItem, hashstructure.FormatV2, nil)
    if err != nil {
        panic(err)
    }
} else {
    hash, err := hashstructure.Hash(pks, hashstructure.FormatV2, nil)
    if err != nil {
        panic(err)
    }
}
```

**Comment by candiduslynx** [comment]
`table.PrimaryKeys()` returns only column names.
so, the code would look something like
```go
names := table.PrimaryKeys()
if len(names) == 0 {
  names = table.Columns.Names() // TODO: filter out internal columns, like _cq_id
}

slices.Sort(names)
var value []any
for _, name := range names {
  value := append(value, resource.Get(name))
}
return hashstructure.Hash(value, hashstructure.FormatV2, nil)
```

**Comment by disq** [comment]
Need to strip any name that has the `_cq_` prefix as well. `funk` might have a helper method for it.

**Comment by erezrokah** [comment]
Related PR at https://github.com/cloudquery/plugin-sdk/pull/712

**Comment by bbernays** [comment]
This was an issue only in Postgres where CQ wasn't updating the cq_id/parent_id for relation resources
