### ISSUE TITLE
New Source Plugin: Amplitude

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8423]
Sync [Amplitude](https://amplitude.com/) data and APIs.

There is an experimental go SDK - https://github.com/amplitude/experiment-go-server.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/amplitude. Please sign up there to get a notified when the plugin is available.
