### ISSUE TITLE
New Source Plugin: Amazon ads

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8424]
Sync [Amazon Ads API](https://advertising.amazon.com/about-api).

Info: Seems like no Go SDK but should be possible to write a small SDK

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/amazon-ads. Please sign up there to get a notified when the plugin is available.
