### ISSUE TITLE
New Source Plugin: Bing Ads

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8425]
Sync Bing Ads API.

Also, reached out the MSFT team for maintenance - https://github.com/BingAds/BingAds-Python-SDK/issues/234

[https://learn.microsoft.com/en-us/advertising/guides/\?view\=bingads-13](https://learn.microsoft.com/en-us/advertising/guides/%5C?view%5C=bingads-13)

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/bing-ads. Please sign up there to get a notified when the plugin is available.
