### ISSUE TITLE
Delete "plugin_directory" and "policy_directory" configuration options

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#843]
### Describe the Bug
Currently, the `plugin_directory` and `policy_directory` configurations are "no-op", i.e. they do absolutely nothing.
Both plugins and policies are always downloaded and run from `.cq` directory, regardless of any `plugin_directory` or `policy_directory` values.

**My strong belief is that rather than fixing this feature, we need to disable it completely:**

1. `.cq` is an idiomatic name for a CLI's internal cache directory. `.[product]` is used as a convention in a myriad of products (e.g. `.git`, `.vscode`, `.terraform`...). It is a very good default behaviou.
2. Currently, `cloudquery init [provider]` creates a `config.hcl` file with:
   ```
   plugin_directory = "./cq/providers"
   policy_directory = "./cq/policies"
   ```
   This is the very strongest argument for deleting this feature instead of fixing it. The moment we fix it, users who run with our configs will suddenly see new created directories named `cq` (no dot). i.e., instead of seeing it and thinking, "ah, this is some sort of internal cloudquery cache", they will think "hmmm, why does this product create so many directories on my computer".
   The fact that until now all our configs included this unreasonable default, means that fixing the bug will change the current reasonable default (`.cq`) to a much less reasonable one (`cq`). **I believe we must avoid this**. 
3. Cloudquery config is already quite long and complex. It shouldn't be overloaded by default with features of very niche use-case (I deduce it is of very niche use-case because, although it is included in every config created by `cloudquery init`, customers never complained about the fact it doesn't work.

### CloudQuery Version
```
Version: 0.24.8
Commit: 5927c7a0a489a999c17e1db75d51b986c105975f
Date: 2022-06-02T16:10:04Z
```

### Steps to Reproduce
`config.hcl`: 
```
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "aws" {
    version = "latest"
  }
  
  connection {
    username = "postgres"
    password = "pass"
    host     = "localhost"
    port     = 5432
    database = "postgres"
    sslmode  = "disable"
  }
}

// All Provider Configurations

provider "aws" {
  configuration {
    aws_debug = false
  }

   resources = ["*"]
}
```

bash:
```
cloudquery fetch
cloudquery policy run aws
```

Both the aws provider and policy will be downloaded into the `.cq` directory. A cq directory will not be created. Neither will it be filled with providers/policies, even if it already existed.

### Additional Context
- I think it will be best to remove it before `config.hcl` is moved to a `yaml` format, as it will reduce the need to convert features that don't work.

**Comment by bbernays** [comment]
I believe we have some users that are not running the latest version of the core. Do you know what version this broke? If we were to remove this we have to think about those users that care the most about stability. Is there anyway we could detect these scenarios and help users avoid errors?

**Comment by bbernays** [comment]
But I agree we should work to reduce the complexity of the config.hcl

**Comment by yevgenypats** [comment]
This is a good question and worth checking when it broke, if it's for long time (codename 3-6 months) Im fine with removing this completely for now as it means no one is using and it is less code to support then fixing it and pushing new behaviour to the user or supporting more code that we have to test and fix.

**Comment by shimonp21** [comment]
Exact same behaviour in cloudquery from 2022-02-07 (4 months ago). (core v0.20.2, aws-provider 0.10.4).

For completeness the config-hcl I used:
```
cloudquery {
  plugin_directory = "./cq/providers"
  policy_directory = "./cq/policies"

  provider "aws" {
    version = "v0.10.4"
  }

  connection {
    dsn = "postgres://postgres:pass@localhost:5432/postgres?sslmode=disable"
  }
}

// All Provider Configurations

provider "aws" {
  configuration {
    aws_debug = false
  }

   resources = ["*"]
}
```

**Comment by yevgenypats** [comment]
Im good with deleting this feature as it's not used/working.

**Comment by shimonp21** [comment]
Looking at the code, a full cleanup without breaking backward-compatibility is not easy (requires writing a bunch of custom code).
In https://github.com/cloudquery/cloudquery/blob/b1c82dac06d8497a57eded1918a0a642e6f65476/pkg/config/config_parser.go#L121, we use `DecodeBody`, and it will fail if `Cloudquery.PluginDirectory`  and `Cloudquery.PolicyDirectory` are removed.

I don't want to break backward compatibility over this.
I also don't want to write a bunch of custom parsing code for this deprecation.

#855 excludes it from any new `cloudquery init` configs. It also adds a comment stating that these fields are deprecated in the `config.hcl` and not actually used.

Next time we break backward compatibility (i.e. move to YAML), we can cleanup the code some more.
