### ISSUE TITLE
New Source Plugin: Mailchimp

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cloudquery#8430]
Sync [Mailchimp API](https://mailchimp.com/developer/marketing/api/).

Related Issue: https://github.com/mailchimp/mc-magento2/issues/1646

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/mailchimp. Please sign up there to get a notified when the plugin is available.
