### ISSUE TITLE
deploy on Serverless compute

### ISSUE THREAD

**Issue by amirbtb** [cloudquery/cloudquery#8496]
### Is your feature request related to a problem? Please describe.
We run a very light Cloud DataPlatform on GCP using only serverless products ; it allows us to have very small bills. I see in the [deployment section of CloudQuery documentation](https://www.cloudquery.io/docs/deployment/overview) that you suggest 2 solutions to run CloudQuery : 
- "locally"
- "a remote non-ephemeral environment [...] on Kubernetes (EKS or GKE)" (+ "a managed PostgreSQL").

In our DataPlatform, we can't afford the cost of GKE or a managed database. We rely on FaaS & CaaS + frameworks for the heavy lifting  : 
- Google Cloud Functions & Cloud Run + [Goblet](https://github.com/goblet/goblet) on GCP
- AWS Lambda + [Chalice](https://github.com/aws/chalice) on AWS
- Azure Functions on Azure (I don't know if there is a FaaS/CaaS heavy lifting framework for Azure)

To store the data, we also rely on services that are "*cheap*" : 
- We store manifests (like dbt's) on buckets
- We use Cloud Providers' logging services
- We use NoSQL databases (Firestore, DynamoDB)

### Describe the solution you'd like
Create & Document a light setup to easily : 
- Deploy Cloud Query on FaaS & CaaS (with or without heavy lifting framework, but they may help)
- Use a "*serverless*" way to persist CloudQuery data

### Describe alternatives you've considered
- Wrap the CloudQuery CLI in a python subprocess and run it from a FaaS/CaaS
- Log Data to a logging service or store files in a bucket

### Additional context
Just want to say thank you for your awesome project and for making it open source ❤️

**Comment by bbernays** [comment]
Hi @amirbtb - Thank you for opening up this issue! We stopped supporting deploying CloudQuery to Lambda Functions because many users were hitting the 15 minute timeout limitation. But I think that running CloudQuery on ECS with Fargate nodes or using AWS Batch (also with Fargate) gives users the similar level of flexibility and also doesn't incur any cost when the sync is not running.

As for destinations, I would suggest that you investigate the new S3 plugin that is able to integrate with Athena for serverless querying of your data.

More information can be found [here](https://www.cloudquery.io/how-to-guides/how-to-load-infrastructure-data-into-athena) on how to integrate CloudQUery with S3/Athena

**Comment by amirbtb** [comment]
Hey @bbernays thank you for your quick reply and its insights, CloudQuery integration with S3 will be useful for the AWS setup we are currently prototyping.
As of now, our main prod setup is on GCP and we can make use of Cloud Run or Cloud Functions Gen2 max duration of 60 min. 

I believe this order of duration will be enough for use cases where we perform incremental data extract & load in a ELT fashion, from transactional databases or APIs to DataLake or DataWarehouse. 

We currently use boilerplate code to extract & load data using `requests` & `pandas`. We load data to Google Cloud Storage buckets (in `.parquet` partitioned files ). In our use case, Cloud Functions Gen1 with 9 min max duration are currently enough. And we know that we have an improvement margin with Cloud Functions Gen2 & Cloud Run (from 9 to 60 min).

With frameworks like Chalice & Goblet, data analysts don't need to know much about Cloud/Containers, they can deploy "extract-load" scripts, without relying on data engineers, and we like that ! 
We believe 
  the developer experience of     CloudQuery 
+ the ease of use of FaaS/CaaS services 
+ the simplicity of frameworks like Goblet & Chalice
= the perfect integration tool for light data stacks 🚀

**Comment by bbernays** [comment]
If you are interested in Parquet data in GCS buckets we also support that as a destination as well documentation can be found [here](https://www.cloudquery.io/docs/plugins/destinations/gcs/overview).


We will definitely investigate improving our documentation and guidance around deploying CloudQuery in lighter weight scenarios?

**Comment by bbernays** [comment]
I am now remembering that we do have a CloudQuery Github Action that can enable users to run CloudQuery in a GitHub action and send the data to any internet connected destination... 

https://www.cloudquery.io/docs/deployment/github-actions

**Comment by amirbtb** [comment]
I did look at your CloudQuery Github Action setup, I am thinking about a quick prototype: 
1. wrap the `f'cloudquery sync {file_name}'` call in a Python subprocess and provide `file_name` as an argument.  
2. deploy a Cloud Function with multiple CloudQuery `.yml` files using Goblet.
3. Schedule calls to the Function, each providing the right CloudQuery `.yml` file

I'm going to try it as soon as I can free some time.
