### ISSUE TITLE
`aws_iam_policies` has escaped data in the `policy_version_list` column

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#8503]
Related to https://github.com/cloudquery/plugin-sdk/issues/622

**Comment by erezrokah** [comment]
Thanks @candiduslynx, what are the steps to create the IAM policy that reproduces the issue?

**Comment by candiduslynx** [comment]
Just sync the `aws_iam_policies` table and look for entries that have non-empty `policy_version_list`.

**Comment by erezrokah** [comment]
Closing this as resolved. We discussed this internally and the document property of `policy_version_list` should be a JSON string (not an object), so this looks OK
