### ISSUE TITLE
Document how to deploy CloudQuery to ECS

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#8521]
We currently have some documentation on [how to use the terraform module and how to deploy using GitHub Actions](https://www.cloudquery.io/docs/deployment/overview), and it would be good to also add documentation on how to deploy to ECS.

**Comment by getglad** [comment]
@hermanschaaf - I could probably provide a generic terraform repository for an ECS deployment w/ Aurora if that would be of interest.
