### ISSUE TITLE
New Source Plugin: Facebook Ads

### ISSUE THREAD

**Issue by bhavaniravi** [cloudquery/cloudquery#8643]
### Why do you need this resource or plugin? Please describe.
This is one of the most requested sources as a data freelancer.

Inspired from Airflow's version of this 
https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/transfer/facebook_ads_to_gcs.html

**Comment by yevgenypats** [comment]
Thanks for opening this! We are working on that one. Duplicate of https://github.com/cloudquery/cloudquery/issues/6778

**Comment by erezrokah** [comment]
@shimonp21 can you confirm this is a duplicate?

**Comment by shimonp21** [comment]
@bhavaniravi v1.0.0 was released yesterday: https://www.cloudquery.io/docs/plugins/sources/facebookmarketing/overview
