### ISSUE TITLE
Investigate: Azure billing tables data

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#8655]
From a user (shardulind) report on Discord:

> Recently I came up with weird behaviour while syncing data from azure cost management views (report)
> - I have added custom cost management views for "last7days" , "thisMonth", "thisQuarter"
> - on running sync command, those views are getting fetched in azure_costmanagement_views 
> - but weird thing noticed is in azure_costmanagement_views_queries table,  the properties column is showing data for of this month, despite having parent_id equal to the one in azure_cost_management tables last7days column.
> In short, despite any time range for cost analysis view, the data fetched in azure_costmanagement_views_queries table is for current months billing.
> I tried experimenting with clean setup, and only having one view at a time for (last 7 days), still data being fetched is of monthly billing. 😕

https://discord.com/channels/872925471417962546/873606591335759872/1080201007960703076

**Comment by xiziouni** [comment]
6
