### ISSUE TITLE
Need table for load balancers

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#8661]
### Why do you need this resource or plugin? Please describe.
We would like to ensure that load balancers that have no backend instances attached. Some criteria we'd like to be able to detects load balancers that have no backend instances attached.

### Describe the solution you'd like
Need new database table that detects load balancers.

### Additional context
This is cloudsploit referenced api.
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview

There are cloudsploit plugin link
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/loadbalancer/lbNoInstances.js

**Comment by erezrokah** [comment]
Hi @code-vise, thanks for the issue. Can you confirm https://learn.microsoft.com/en-us/rest/api/load-balancer/load-balancers is what you're after?

**Comment by code-vise** [comment]
Yes

**Comment by nagaajay4** [comment]
can you please elaborate "Need new database table that detects load balancers." solution, 
i like to work on this but i am unable to understand the exact issue and described solution. @code-vise

**Comment by erezrokah** [comment]
Hi @code-vise I think we have this table already, see https://www.cloudquery.io/docs/plugins/sources/azure/tables/azure_network_load_balancers and relevant API https://learn.microsoft.com/en-us/rest/api/load-balancer/load-balancers/list?tabs=HTTP#loadbalancer.

I'll close this issue as resolved. If something is missing please comment and I'll re-open.

> Please note we have a [table search box now](https://www.cloudquery.io/tables), so that should make it easier to find supported tables.
