### ISSUE TITLE
Need table for list attached group policies 

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#8662]
### Why do you need this resource or plugin? Please describe.
We would like to ensure the number of IAM admins in the account are minimised. Some criteria we'd like to be able to count the number of IAM admins for list attached group policies.

### Describe the solution you'd like
Need table for list attached group policies 

### Additional context
This is cloudsploit referenced api.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#listAttachedGroupPolicies-property

There are cloudsploit plugin link
https://github.com/aquasecurity/cloudsploit/blob/master/plugins/aws/iam/iamUserAdmins.js

**Comment by bbernays** [comment]
@code-vise - Can you look to see if the field `policies` in `aws_iam_groups` has what you are looking for?

**Comment by erezrokah** [comment]
@bbernays I think we're getting [inline policies](https://docs.aws.amazon.com/cli/latest/reference/iam/list-group-policies.html) and this issue is about [attached policies](https://docs.aws.amazon.com/cli/latest/reference/iam/list-attached-group-policies.html)

**Comment by erezrokah** [comment]
Ah sorry I missed it, as @bbernays pointed out it's a column on `aws_iam_groups`, see https://github.com/cloudquery/cloudquery/blob/977137ec69fb6eb0e8fa086bfd155f579df6ec0a/plugins/source/aws/docs/tables/aws_iam_groups.md#L21

**Comment by erezrokah** [comment]
Closing as already implemented. Please comment if you have any other questions

**Comment by code-vise** [comment]
@erezrokah so  a group can have inline and attached policies. I see that there is a table for inline policies but not attached policies. Can you guide me if it already exists?

**Comment by bbernays** [comment]
The `inline` policies are not a standalone table. They are a column in the `aws_iam_groups` table.
This query should return the data you are interested in:
```sql
select policies from aws_iam_groups;
```
