### ISSUE TITLE
S3 Plugin KMS Key Encryption 

### ISSUE THREAD

**Issue by sunil494** [cloudquery/cloudquery#8730]
### Is your feature request related to a problem? Please describe.
I would like to define a KMS key when the PutObject method is called by Cloudquery after resources are fetched.

### Describe the solution you'd like
I would like the define the KMS key in the plugin YML (Ideally in the spec)

### Describe alternatives you've considered
As long as KMS key encryption is possible I guess it doesn't matter. Maybe the KMS can be inferred instead of defined in the YML but I would strongly prefer to define it in the YML.

**Comment by erezrokah** [comment]
Hi @sunil494, can you add some more context on the need to specify the key on the `PutObject` call?
Looks like you can set a default KMS key at the bucket level, see https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-default-server-side-encryption.html

For the `PutObject` call, can you confirm https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-server-side-encryption-with-kms.html is what you're after? If so it seems the use case is to override the default KMS key, for specific objects. Is that what you need, or setting the default on the bucket will work for you?

**Comment by erezrokah** [comment]
Thanks @sunil494, I think you can do it via https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-default-server-side-encryption.html as you can specify a non default KMS key to use via the bucket encryption configuration.

**Comment by erezrokah** [comment]
Hi @sunil494, I think the use case you're after is better achieved via configuring the KMS key directly on the bucket. I'll close this issue per my [latest comment](https://github.com/cloudquery/cloudquery/issues/8730#issuecomment-1468316487).

If that's not the case, please comment and I'll re-open the issue
