### ISSUE TITLE
Add aws_ec2_account_attributes resource

### ISSUE THREAD

**Issue by ukbea** [cloudquery/cloudquery#8733]
### Why do you need this resource or plugin? Please describe.
We need this resource in order to identify account attributes for the target accounts.

### Describe the solution you'd like
Add resource aws_ec2_account_attributes as a separate table.
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAccountAttributes.html

### Additional context
NA

**Comment by jsonpr** [comment]
Looks to be the same as https://github.com/cloudquery/cloudquery/issues/7635

**Comment by erezrokah** [comment]
Closing as duplicate per @jsonpr comment. Please comment if that's not the case
