### ISSUE TITLE
Panic in table rendered during policy execution

### ISSUE THREAD

**Issue by amanenk** [cloudquery/cloudquery#877]
### Describe the Bug
 sometimes cloudquery panics in github.com/olekukonko/tablewriter@v0.0.5/table.go in (*Table).printFooter at line 563 with next message `runtime error: index out of range [57] with length 57`

### Expected Behavior
it should not panic

### CloudQuery Version
0.24.11

**Comment by disq** [comment]
It doesn't seem to be in the project's issues/PRs... and tip of the repo only has few fixes, seemingly not any of them related: https://github.com/olekukonko/tablewriter/compare/v0.0.5...master

**Comment by bbernays** [comment]
Fixed in pr #995
