### ISSUE TITLE
AWS EC2 Key Pair

### ISSUE THREAD

**Issue by hobietje** [cloudquery/cloudquery#8812]
### Why do you need this resource or plugin? Please describe.

* EC2 Key Pairs are rotated every 90 days
* EC2 Key Pairs are actively in use (using SQL JOIN to EC2 instance key pair, launch template key pair)
* EC2 Key Pairs use ED25519 keys

### Describe the solution you'd like

Add additional table listing EC2 Key Pairs, including columns for date created, key type (`rsa` vs `ED25519`)

**Comment by bbernays** [comment]
@hobietje - Thank you for opening this issue I think the information you are looking for is already in the the `aws_ec2_key_pairs` table

https://www.cloudquery.io/docs/plugins/sources/aws/tables/aws_ec2_key_pairs

**Comment by erezrokah** [comment]
Closing as already done. If this is not the case please comment and we'll re-open. Also please note we have a [search box now](https://www.cloudquery.io/tables)
