### ISSUE TITLE
Fetch failure on first run

### ISSUE THREAD

**Issue by ddoshi-ah** [cloudquery/cloudquery#89]
I'm getting errors on first run, which may be from 'aws-sdk-go'.
Appreciate being pointed in the right direction.

'cloudquery gen config aws' & 'cloudquery init' worked fine.

My OS is Ubuntu 20.04.2 LTS
Linux ip-10-7-11-81 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### My AWS credentials are stored like this:
[profile1]
aws_access_key_id=XXX
aws_session_token=XXX
aws_secret_access_key=XXX
region=us-east-1

[profile2]
aws_access_key_id=YYY
aws_session_token=YYY
aws_secret_access_key=YYY
region=us-east-1

### My config.yml file looks like this:
providers:
    - name: aws
	  accounts:
	    - role_arn: arn:aws:iam::1234567891234:role/user
	    - role_arn: arn:aws:iam::1234567891234:role/user
	  regions:
            - us-east-1
      log_level: debug
      version: latest
      resources:
        - name: autoscaling.launch_configurations
		..
		..
		
### I'm using the latest version, 0.12.1
ubuntu@myhost:~/mydir$ ./cloudquery --version
cloudquery version 0.12.1

### Here's my command, postgres tables were created alright (but without any data):
ubuntu@myhost:~/mydir$ ./cloudquery -v fetch --dsn "host=myhost.rds.amazonaws.com user=username password=password database=database_name port=1234"
1:28AM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=true
1:28AM DBG reading configuration file path=./config.yml
1:28AM DBG verifying provider plugin is registered pluginName=aws version=latest
1:28AM DBG provider plugin is registered pluginName=aws version=latest
1:28AM DBG downloading checksums file path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest.checksums.txt pluginName=aws url=https://github.com/cloudquery/cq-provider-aws/releases/latest/download/checksums.txt version=latest
1:28AM DBG downloading checksums signature path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest.checksums.txt pluginName=aws url=https://github.com/cloudquery/cq-provider-aws/releases/latest/download/checksums.txt version=latest
1:28AM DBG verifying checksums signature path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest.checksums.txt pluginName=aws url=https://github.com/cloudquery/cq-provider-aws/releases/latest/download/checksums.txt version=latest
1:28AM DBG getting or creating provider provider=aws version=latest
1:28AM DBG starting plugin args=["/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest-linux-amd64"] path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest-linux-amd64
1:28AM DBG plugin started path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest-linux-amd64 pid=37140
1:28AM DBG waiting for RPC address path=/home/ubuntu/cq/.cq/providers/cloudquery/aws/latest-linux-amd64
1:28AM DBG plugin address address=/tmp/plugin156390503 network=unix timestamp=2021-05-05T01:28:54.866Z
1:28AM DBG using plugin version=1
1:28AM INF requesting provider initialize provider=aws version=latest
{"@level":"debug","@message":"creating table if not exists","@timestamp":"2021-05-05T01:28:54.898345Z","table":"aws_ec2_flow_logs"}
..
..

1:28AM INF requesting provider fetch provider=aws version=latest
Error: rpc error: code = Unknown desc = operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed
Usage:
  cloudquery fetch [flags]

Flags:
      --driver string   database driver postgresql/neo4j (env: CQ_DRIVER) (default "postgresql")
      --dsn string      database connection string (env: CQ_DSN) (example: 'host=localhost user=postgres password=pass DB.name=postgres port=5432')
  -h, --help            help for fetch
      --path string     path to configuration file. can be generated with 'gen config' command (env: CQ_CONFIG_PATH) (default "./config.yml")
      --version         version for fetch

Global Flags:
      --enableConsoleLog            Enable console logging (default true)
      --enableFileLogging           enableFileLogging makes the framework logging to a file (default true)
      --encodeLogsAsJson            EncodeLogsAsJson makes the logging framework logging JSON
      --logDirectory string         Directory to logging to to when file logging is enabled (default ".")
      --logFile string              Filename is the name of the logfile which will be placed inside the directory (default "cloudquery.log")
      --maxAge int                  MaxAge the max age in days to keep a logfile (default 3)
      --maxBackups int              MaxBackups the max number of rolled files to keep (default 3)
      --maxSize int                 MaxSize the max size in MB of the logfile before it's rolled (default 30)
      --plugin-dir string           Directory to save and load CloudQuery plugins from (env: CQ_PLUGIN_DIR) (default "/home/ubuntu/cq")
      --reattach-providers string   Path to reattach unmanaged plugins, mostly used for testing purposes (env: CQ_REATTACH_PROVIDERS)
  -v, --verbose                     Enable Verbose logging

2021/05/05 01:28:55 rpc error: code = Unknown desc = operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, failed to sign request: failed to retrieve credentials: no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed

Thanks,
dhawal

**Comment by yevgenypats** [comment]
@ddoshi-ah thanks! Can you try setting environment variable `AWS_DEFAULT_REGION` to anything? (`us-east-1` for example)

**Comment by James-Quigley** [comment]
`AWS_PROFILE` env var determines which set of credentials in your ~/.aws/credentials will be used.

The `accounts` section in the config.yml means that you can fetch from multiple accounts using IAM assume roles. In order to use this, the user to whom the credentials belong must have permissions to assume the role(s) that you put in the `accounts` section of the config

**Comment by ddoshi-ah** [comment]
If I understand correctly, you are saying that "one credential can assume roles across multiple accounts" and each of the assumed role must be added to `accounts` in the config.yml, correct?

In my case, I generate temporary static credentials (aws_access_key_id / aws_session_token / aws_secret_access_key / region) for each AWS account and write them to ~/.aws/credentials profiles. There's no assume role and STS involved anymore (I think).

But nevertheless, thanks for the quick response. Let me re-read & understand the documentation, talk to the cloud folks in my org and try this again.

**Comment by James-Quigley** [comment]
If you are generating different credentials per account that you want to fetch, you'll need to run multiple `cloudquery fetch` as you discovered

**Comment by ddoshi-ah** [comment]
Got it, I misunderstood the `accounts` section in config.yml

Thanks again.
