### ISSUE TITLE
Feedback for “Quickstart - Linux”

### ISSUE THREAD

**Issue by srijavoona-debug** [cloudquery/cloudquery#8943]
after running curl command for downloading cloudquery it is showing command not found

**Comment by yevgenypats** [comment]
Hey @srijavoona-debug can you please share the exact commands you run?

**Comment by erezrokah** [comment]
@yevgenypats I think our linux guide shows `cloudquery sync ./cloudquery-config` where it should show `./cloudquery sync ./cloudquery-config` as it instructs downloading the local binary.

I'll take a look
