### ISSUE TITLE
Makefile's missing?

### ISSUE THREAD

**Issue by take-five** [cloudquery/cloudquery#90]
Hi

I'm exploring how to deploy CloudQuery to AWS as Lambda function.

[This blog post](https://www.cloudquery.io/blog/running-cloudquery-in-aws-lambda) and the [documentation](https://docs.cloudquery.io/deployment) instruct to use `make` (e.g. `make build`), but there's no `Makefile` present in the repository.

I've found a [pull request](https://github.com/cloudquery/cloudquery/pull/83) in which the `Makefile` was removed, however I can't make out whether that was a mistake or an intentional change. If it was an intentional change - then the documentation is no longer valid.

Anyhow, I can't find a way to deploy CloudQuery without restoring the last version of `Makefile` from git history.

**Comment by roneli** [comment]
Hi, yes the makefile was removed by mistake, I will add it again

**Comment by roneli** [comment]
added back in v0.12.2, tell me if something else doesn't work. If everything is okay we can close this issue

**Comment by take-five** [comment]
It works now, thanks a lot!
