### ISSUE TITLE
feat: Add a Zoho Campaign source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#9028]
### Describe the plugin

> Zoho Campaigns provides APIs (Application Programming Interface) to access data to and from other Zoho applications such as Zoho CRM and third-party applications including accounting, ERP, ecommerce, and self-service portal software. With our APIs, you can export data in XML or JSON format and develop new applications or integrate with your existing business applications. 

### Link to API documentation

https://www.zoho.com/campaigns/help/developers/

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/zoho-campaign. Please sign up there to get a notified when the plugin is available.
