### ISSUE TITLE
Total Resource Count Does not Reflect DB

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#904]
### Describe the Bug

User runs a fetch, at the end of the fetch the summary says 0 resources

```
[90m3:37AM[0m INF Provider gcp fetch summary:  Total Resources fetched: 0      Warnings: 0      Errors: 0 [36minstance_id=[0m2b90a80f-ce22-4594-bb0d-150bb595a2df
```

while in the logs it shows that individual resources had non 0 resources found

### Expected Behavior

correct count of all resources fetched

**Comment by erezrokah** [comment]
Moving to backlog until we are able to get a consistent reproduction.
Documenting current state below:

### Observations

The logs about successful resource fetches with count are done in the context of the provider via the SDK:
https://github.com/cloudquery/cq-provider-sdk/blob/cad99838bd808307f76aaf8222c3294d15b3f668/provider/execution/execution.go#L274

Those are sent to the core that does the sum:
https://github.com/cloudquery/cq-provider-sdk/blob/cad99838bd808307f76aaf8222c3294d15b3f668/provider/provider.go#L232
https://github.com/cloudquery/cloudquery/blob/1d1a3210d9e24dc25bc86c1add7a2380538ccafa/pkg/core/fetch.go#L373

Please note we only do the sum if we don't get an error ⬆️ 

I think it's completely possible that between the time we save the results to the database in the SDK to when the summary results are received at the core, we error out on the grpc channel and lose some (all) of the messages hence the count is wrong.

Looking at the customer's logs we see an error `rpc error: code = Unavailable desc = error reading from server: EOF` which means we reach https://github.com/cloudquery/cloudquery/blob/1d1a3210d9e24dc25bc86c1add7a2380538ccafa/pkg/core/fetch.go#L404

On unknown errors we still print the summary:
https://github.com/cloudquery/cloudquery/blob/1d1a3210d9e24dc25bc86c1add7a2380538ccafa/pkg/ui/console/client.go#L244

### Thoughts

1. We should ask the user to provide a config file + run with verbose logging
2. We could get the total count from the db somehow?

**Comment by erezrokah** [comment]
Should be resolved in [v2](https://github.com/cloudquery/cloudquery/pull/1463)
