### ISSUE TITLE
feat: Add a New Relic source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#9040]
https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/

**Comment by luanrjjj** [comment]
I would like to do this integration.

**Comment by luanrjjj** [comment]
Hello, @erezrokah . I'd studied this guide and the video about the plugin XQCD creation. I will begin today this integration. Thanks for the help

**Comment by luanrjjj** [comment]
Are there currently two API's availables in New Relic: A Rest Api and  a Graphql Api. For this PR is necessary to do both? 
Obs: Graphql Api is the recommended and the Rest API must be deprecated in the future.

**Comment by yevgenypats** [comment]
> Are there currently two API's availables in New Relic: A Rest Api and a Graphql Api. For this PR is necessary to do both? Obs: Graphql Api is the recommended and the Rest API must be deprecated in the future.

Usually plugins only use one API so better to choose only one of them. Usually we work with REST API but if it's going to be deprecated then maybe GraphQL is the way to go. Take a look at https://github.com/newrelic/newrelic-client-go seems they have a Go library maybe it can be use in the plugin and will be easier then to talk to the API directly.

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/new-relic. Please sign up there to get a notified when the plugin is available.
