### ISSUE TITLE
bug: K8s documention plugin is broken

### ISSUE THREAD

**Issue by krab-skunk** [cloudquery/cloudquery#9062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you go to https://www.cloudquery.io/docs/plugins/sources/k8s/configuration, 

we only see `import Configuration from "./_configuration.mdx";`

thus forbidding us from knowing how to configure k8s plugin

### Expected Behavior

N/A

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

N/A

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Thanks for the bug report @krab-skunk! This should be fixed in https://github.com/cloudquery/cloudquery/pull/9063

**Comment by krab-skunk** [comment]
thanks you so much for the quick reactivity ;)
