### ISSUE TITLE
feat: Add a Sophos source plugin

### ISSUE THREAD

**Issue by connerlphillippi** [cloudquery/cloudquery#9131]
### Describe the plugin

The Sophos plug-in enables companies to query on users, endpoints, cloud infrastructure and firewalls, SIEM data, and horizontal threats across these resources. 

### Link to API documentation

https://developer.sophos.com/apis

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/sophos. Please sign up there to get a notified when the plugin is available.
