### ISSUE TITLE
feat: Add a Tenable source plugin

### ISSUE THREAD

**Issue by connerlphillippi** [cloudquery/cloudquery#9132]
### Describe the plugin

The Tenable plug-in enables companies to query on:

- user data
- vulnerability findings, scan details (including ASV), and remediation activity
- cloud resource resources, config drifts, violations, and metrics
- container and image resources and reports
- attack surface management details

### Link to API documentation

https://developer.tenable.com/reference/navigate

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
We're planning to prioritize this work starting with:
https://developer.tenable.com/reference/workbenches-asset-vulnerabilities
https://developer.tenable.com/reference/workbenches-assets-vulnerabilities

**Comment by pilvikala** [comment]
@erezrokah once we have access, we should re-evaluate and see how these map to some other data one could pull using other resources. The MVP should be able to map the vulnerabilities to where those occur, such as host.
