### ISSUE TITLE
feat: Add a Crowdstrike source plugin

### ISSUE THREAD

**Issue by connerlphillippi** [cloudquery/cloudquery#9133]
### Describe the plugin

The Crowdstrike plug-in enables companies to query on:

- User details
- Endpoint and host resource and group configurations
- Detection details around threat behavior, severity, and affected host
- Prevention policies 
- Sensor update policies

### Link to API documentation

https://dash.readme.com/to/crowdstrike-enterprise?redirect=%2Fcrowdstrike%2Fdocs

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by yevgenypats** [comment]
There is a community plugin right now available here - https://github.com/justmiles/cq-source-crowdstrike. Closing for now.
