### ISSUE TITLE
feat: Add a Snowflake source plugin

### ISSUE THREAD

**Issue by connerlphillippi** [cloudquery/cloudquery#9135]
### Describe the plugin

The Snowflake plug-in enables companies to query on: 

- user & login history, view grant details, role, and account details
- database resource details and configurations such as retention time
- network policies such as ip allow/block lists
- resource monitor details and configurations such as alerting
- schemata details and configurations such as retention time
- session details
- warehouse resource details and configurations

### Link to API documentation

https://docs.snowflake.com/en/api-reference

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/snowflake. Please sign up there to get a notified when the plugin is available.

**Comment by candiduslynx** [comment]
I'll take a look how we can utilize the code from the terraform provider for this: https://github.com/Snowflake-Labs/terraform-provider-snowflake

**Comment by candiduslynx** [comment]
not yet published

**Comment by candiduslynx** [comment]
Released https://hub.cloudquery.io/plugins/source/cloudquery/snowflake-config
