### ISSUE TITLE
feat: Add a SentinelOne source plugin

### ISSUE THREAD

**Issue by connerlphillippi** [cloudquery/cloudquery#9136]
### Describe the plugin

The SentinelOne plug-in enables companies to query on:

- users details
- device details and configurations
- alert policies 
- agent details 

### Link to API documentation

Need to sign up first to get access to API

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/source/cloudquery/sentinelone. Please sign up there to get a notified when the plugin is available.
