### ISSUE TITLE
feat: Use distroless for CQ image

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#9254]
### Which problem is this feature request solving?

The official CQ Image is currently just the CQ binary in an Alpine container. Alpine while it is designed to be small is larger than is 100% required to run CQ. This means there is potentially extra surface area to secure. Users that use this image should introduce as little extra attack surface as possible

### Describe the solution you'd like

Investigate packaging CQ in a distroless image

https://github.com/GoogleContainerTools/distroless

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Going to close this a won't fix as I'm not sure we'd want to maintain another image, and changing the current one might break existing workflows that rely on it. I would say that users can create whatever docker image they'd like and add the CloudQuery binary to it.
