### ISSUE TITLE
feat: Add Scale Sets VM disks to Azure source plugin

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#9348]
### Describe the resource

`azure_compute_disks` does not include `azure_compute_virtual_machine_scale_set_vms` disks (accessible by `properties -> 'storageProfile' -> 'osDisk' -> 'managedDisk' ->> 'id'`).

We got a user request to list those.

I couldn't find a way to do it via the Azure REST API yet, so needs more research

### Use Case

Correlate disk data 

### Link to API documentation

TBD

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment]
@erezrokah I've dug into this API and Azure indeed doesn't allow you to even get the disk by ID (as they really want you to have only the info of the disk model, including the size/image/etc).
We could extract this into a separate table based on `VirtualMachineScaleSetOSDisk` (and, quite possibly, on `VirtualMachineScaleSetDataDisk` as well for data disks), but currently I don't know if this is required, as the data is already there in the properties.

**Comment by yevgenypats** [comment]
Closing as stale
