### ISSUE TITLE
feat: Support Filtering Access Analyzer Findings

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#9372]
### Which problem is this feature request solving?

I have Access Analyzers created in each region. Each analyzer analyzes all IAM resources even though the IAM resources are not actually part of the region and are global resources. This means that when using the `append` write mode the `aws_accessanalyzer_analyzer_findings` table grows exceptionally quickly because the findings include `active`, `archived` and `resolved` findings

### Describe the solution you'd like

Introduce some type of configuration that enables users to specify the filter parameters that meet their use case

https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-findings-filter.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by michalz-rely** [comment]
a two filters that are worth considering

1. Don't sync archived findings by default
As you can manually archive findings and create an archive filter on the AWS for most of the time it maces no sense to sync all findings, including the archived ones

2. sync only publicly accessible resources
there's column 'is_public' which is useful, but sometimes people might need to sync only the findings of this type
