### ISSUE TITLE
feat: Add a Centrifugo destination plugin

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#9402]
### Describe the plugin

[Centrifugo](https://centrifugal.dev/) is a real-time messaging server.
Adding it to our destinations will allow users to stream data from CloudQuery to their preferred destinations filtering the data along the way. 

### Link to API documentation

https://github.com/centrifugal/centrifuge-go

### Pull request (optional)

- [X] I can submit a pull request

**Comment by pilvikala** [comment]
This plugin is now available on Hub in preview: https://hub.cloudquery.io/plugins/destination/cloudquery/centrifugo. Please sign up there to get a notified when the plugin is available.
