### ISSUE TITLE
AWS Policies: Security Group Queries

### ISSUE THREAD

**Issue by jsonpr** [cloudquery/cloudquery#9409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql is returning false positives

### Expected Behavior

https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/policies/queries/ec2/security_groups_with_open_critical_ports.sql should return proper results

### CloudQuery (redacted) config

AWS 15.3.0

### CloudQuery (redacted) logs

NA

### CloudQuery version

NA

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
Resolved by https://github.com/cloudquery/cloudquery/pull/9410
