### ISSUE TITLE
CDC Implementation from postgreSQL to Redshift using WAL

### ISSUE THREAD

**Issue by rajeshv28** [cloudquery/cloudquery#9411]
Hi, 

I am trying to see options to implement CDC by using PostgreSQL WAL logs and writing to redshift tables. I have come across cloudquery when I am googling for some options. Could you please let me know whether it is possible to implement CDC from postgres to redshift using cloduquery and if yes can suggest any documentation to refer.

Thanks,
Rajesh

**Comment by hermanschaaf** [comment]
Hi @rajeshv28, yes I believe this should be possible. Redshift is not directly supported as a destination, so I think you will need to sync the files to an S3 bucket (in parquet format) and then run the appropriate `COPY` commands to load it into Redshift. We have users successfully using Athena as a destination, but I'm not sure if anyone has tried Redshift yet. As long as your source database doesn't have GEO or other special type columns, it should work fine. 

Here is a guide you can follow for loading data from Postgres into S3 via CDC (or without CDC): https://www.cloudquery.io/integrations/postgresql/s3

You may also find the how-to guide for Athena useful, but the instructions would need to be adapted for Redshift: https://www.cloudquery.io/how-to-guides/how-to-load-infrastructure-data-into-athena

Just note that currently this method would not support row deletions, so if your database regularly deletes data this method may not work for you. If you would like to make a feature request, we can consider adding more direct support for a Redshift destination.

**Comment by rajeshv28** [comment]
Thank you for your quick response. We will look into this approach and get
back to you if we need further assistance.

Thanks,
Rajesh
