### ISSUE TITLE
Policy generates invalid SQL queries in several tables

### ISSUE THREAD

**Issue by antonbabenko** [cloudquery/cloudquery#95]
As an addition to #88, when I try to run generated policy I have errors:
* `column "arn" does not exist` in:
```
SELECT account_id, arn, password_last_used, user_name, mfa_active FROM aws_iam_users WHERE password_enabled AND NOT mfa_active
```

* `operator does not exist: boolean = integer` in:
```
SELECT account_id, require_uppercase_characters FROM aws_iam_password_policies WHERE require_uppercase_characters = 0
```

* `relation "aws_ec2_security_group_ip_ranges" does not exist` in:
```
select account_id, region, group_name, from_port, to_port, cidr_ip from aws_ec2_security_groups
    JOIN aws_ec2_security_group_ip_permissions on aws_ec2_security_groups.id = aws_ec2_security_group_ip_permissions.security_group_id
    JOIN aws_ec2_security_group_ip_ranges on aws_ec2_security_group_ip_permissions.id = aws_ec2_security_group_ip_ranges.security_group_ip_permission_id
WHERE from_port >= 0 AND to_port <= 22 AND cidr_ip = '0.0.0.0/0'`
```

PS: I was not sure if my report helps in any way :)

**Comment by yevgenypats** [comment]
Yeah, it doesn't work yet since we released a new SDK . Related issue: https://github.com/cloudquery/cloudquery/issues/88 
We are working on fixing it. Thanks for elaborating anyway!

**Comment by roneli** [comment]
Updated CIS and AWS provider tables to correctly work with all CIS queries. (Requires update to CloudQuery v0.13+ and AWS v0.4.3+ and change config to hcl format). If you need any assistance with the conversion, feel free to ask.

**Comment by antonbabenko** [comment]
Still producing an error when using 0.13.3 and the latest AWS provider (0.4.5):
>   - name: "AWS CIS 2.8 Ensure rotation for customer created CMKs is enabled (Scored)"
    query: >
      SELECT account_id, region, arn FROM aws_kms_keys WHERE rotation_enabled = FALSE AND manager = 'CUSTOMER'

Error message:
> 12:13PM ERR failed to execute policy query error="ERROR: column \"arn\" does not exist (SQLSTATE 42703)" policy="AWS CIS 2.8 Ensure rotation for customer created CMKs is enabled (Scored)"

**Comment by roneli** [comment]
Yeah, I see the problem the column name was changed from "arn" to "key_arn", updating the policy yml
