### ISSUE TITLE
Improve CQ Summary

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#951]
Possible Info to Show:
1. Number of resources that found 0
2. Number of Ignored Errors and how to view them in `verbose` mode

**Comment by shimonp21** [comment]
See also discussion at https://github.com/cloudquery/cq-provider-aws/issues/957.

(Consider duplicating this one to the other one?)

**Comment by shimonp21** [comment]
- I would consider adding the line for "number of access denied errors" rather than "number of IGNORED errors" (since other IGNORED errors may actually just be spam).
-
