### ISSUE TITLE
feat: Add aws_iam_group_attached_policies to AWS source plugin

### ISSUE THREAD

**Issue by ukbea** [cloudquery/cloudquery#9514]
### Describe the resource

Currently, it's not possible to identify managed policies attached to an IAM group.

### Use Case

In order to identify the user permissions for security gaps, attached policies for a group is required.

### Link to API documentation

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/list-attached-group-policies.html

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment]
@ukbea - Thank you for opening this issue. The data is currently available in the `policies` column in the `aws_iam_groups` table.
This query should return the data you are interested in:
```sql
select policies from aws_iam_groups;
```

We are aware that this is inconsistent with how the data is formatted for policies attached, and plan on adding nested tables to both `aws_iam_groups` and `aws_iam_roles` to hold the attached policy data


https://github.com/cloudquery/cloudquery/issues/9496

**Comment by erezrokah** [comment]
Closing this in favor of https://github.com/cloudquery/cloudquery/issues/9496
