### ISSUE TITLE
feat: Add compute VM sizes to Azure source plugin

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#9741]
### Describe the resource

We should add a table that lists VM sizes, equivalent to `az vm list-sizes` (using `armcompute.NewVirtualMachineSizesClient()`)

I could be wrong, but it seems like the CPU and RAM information provided by this call isn't available in any table right now.

### Use Case

Raised [on Discord](https://discord.com/channels/872925471417962546/873606591335759872/1093107626465833070)

### Link to API documentation

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-sizes/list?tabs=HTTP

### Pull request (optional)

- [X] I can submit a pull request

**Comment by disq** [comment]
The API seems to be deprecated according to the doc, but there's a newer one which I'm using:
> // NewListPager - This API is deprecated. Use Resources Skus [https://docs.microsoft.com/rest/api/compute/resourceskus/list]

**Comment by disq** [comment]
Which seems to be already defined - `azure_compute_skus`
