### ISSUE TITLE
Bug: Fetch duration and diagnostics account are printed too close 

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#975]
### Describe the Bug

Given a long enough fetch and high enough number of diagnostics they are printed too close:
![image](https://user-images.githubusercontent.com/26760571/175010464-0bd23334-f2bb-45bd-887f-f5eb950fd72a.png)

### Expected Behavior

There should be enough space between the two values

### CloudQuery Version

```
Version: 0.27.0-rc3
Commit: cf52adbde5c604f25c951a3f9a8c5f950a664fa0
Date: 2022-06-22T08:21:27Z
```

### Steps to Reproduce

```
cloudquery init aws
# The issue reproduces on the account we use for testing when fetching all resources
cloudquery fetch
```

### Possible fixes

- Remove diagnostics count print as we already print a summary at the end
- Move progress to a new line

**Comment by vaibhavkoshti7** [comment]
Hello @yevgenypats . Iwould liketo work on this issue . Can you assign me this?

**Comment by erezrokah** [comment]
Hi @vaibhavkoshti7, this was solved in https://github.com/cloudquery/cloudquery/pull/1829 as a part of a larger refactor.
We have https://github.com/cloudquery/cloudquery/issues/1821 if you'd like to do another contribution
