### ISSUE TITLE
feat: Add a Coinpaprika.com/api source plugin

### ISSUE THREAD

**Issue by r--w** [cloudquery/cloudquery#9752]
### Describe the plugin

Coinpaprika is a leading cryptocurrency market data platform that offers users comprehensive insights into price data, historical trends, market capitalization, trading volume, and other relevant metrics for numerous cryptocurrencies across hundreds of exchanges. 

### Link to API documentation

https://api.coinpaprika.com

### Pull request (optional)

- [X] I can submit a pull request

**Comment by r--w** [comment]
Hi, we (coinpaprika.com) would like to provide a source plugin for crypto pricing data. Let me know if you are interested in such a contribution.

**Comment by yevgenypats** [comment]
Hi 👋  @r--w, This is great! We would love to see such contribution and would love to help/guide. A CloudQuery source plugin can also be hosted on your [github](https://github.com/coinpaprika) and we can put a link under partners [here](https://www.cloudquery.io/docs/plugins/sources/overview) .

**Comment by erezrokah** [comment]
Hi @r--w, I've assigned you to the issue. If there's any additional information you need please let us know

**Comment by r--w** [comment]
Hi @erezrokah @yevgenypats

We just released a source plugin for crypto data from Coinpaprika
[https://github.com/coinpaprika/cq-source-coinpaprika](https://github.com/coinpaprika/cq-source-coinpaprika )

It would be great if you could add it to your page/documentation; we will be happy to share than with our user base.
If you need our logo, feel free to use one of these: https://coinpaprika.com/about-us/media-pack.zip 

If you have any further questions or suggestions, please let me know.

cc: @mbillewicz

**Comment by candiduslynx** [comment]
Hi @r--w!

That's really great news!
Could you also migrate the codebase to `plugin-sdk/v3`? 
We are currently migrating our source plugins to the new version (it uses Apache Arrow types now) & it would be great to have this in your plugin, too.

See #10711 for reference.

**Comment by yevgenypats** [comment]
Hi @r--w That's awesome! We will add to our integration page shortly. Re-opening the issue so we won't forget.

**Comment by yevgenypats** [comment]
Done - https://www.cloudquery.io/integrations

**Comment by erezrokah** [comment]
> Done - https://www.cloudquery.io/integrations

And https://www.cloudquery.io/docs/plugins/sources/overview#partners 🚀

**Comment by mbillewicz** [comment]
@candiduslynx plugin migrated to `plugin-sdk/v3`.
