### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [cloudquery/cloudquery#9794]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by erezrokah** [comment]
Thanks @igibek, I've enabled the feature. Have you seen our [security policy](https://github.com/cloudquery/cloudquery/security/policy)? You can send an email to [security@cloudquery.io](https://github.com/cloudquery/.github/blob/main/mailto)

**Comment by erezrokah** [comment]
Going to close this as resolved. Please report via the appropriate channels the security issue
