### ISSUE TITLE
bug: Duplicates in `wait-for-required-workflows` resulting in false-positive success

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#9797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we check for the finished checks we use paging to get all of the runs.
In the situations where we need to fetch > 100 (page size) runs, we sometimes can encounter duplicates, and the workflow finished too fast.

### Expected Behavior

Even the duplicate ID shouldn't be a problem.

### CloudQuery (redacted) config

N/A

### CloudQuery (redacted) logs

N/A

### CloudQuery version

N/A

### Additional Context

https://github.com/cloudquery/cloudquery/pull/9736#issuecomment-1501173716
https://github.com/cloudquery/cloudquery/pull/9736#issuecomment-1501606356
https://github.com/cloudquery/cloudquery/pull/9793

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment]
We still didn't address duplicates in the checks caused by paging

**Comment by candiduslynx** [comment]
strange behavior observed in the test [run](https://github.com/cloudquery/cloudquery/actions/runs/4657620765/jobs/8242394208?pr=9760)

**Comment by erezrokah** [comment]
> strange behavior observed in the test [run](https://github.com/cloudquery/cloudquery/actions/runs/4657620765/jobs/8242394208?pr=9760)

Can you explain the behavior that you observed? That would make sure we're aligned regarding it.

> We still didn't address duplicates in the checks caused by paging

I suggest we wait with any changes to the wait for all logic until we see duplicates on a PR that runs from current `main`.

**Comment by erezrokah** [comment]
> I'll work on reusing validate-release checks to trigger a lot of checks for this issue

Please no. Let's wait for the issue to reproduce first on a PR that uses the code from main and use the IDs to debug the issue

**Comment by candiduslynx** [comment]
I took a closer look at the logs for the large run:
We have duplicate entries in [this](https://github.com/cloudquery/cloudquery/actions/runs/4657620765/jobs/8242394208?pr=9760#step:4:609) line:
```json
{"id":12632893484,"name":"plugins/source/digitalocean","conclusion":"success"},
{"id":12632893484,"name":"plugins/source/digitalocean","conclusion":"success"},
```

So, we do have duplicates, observed with the same ID.
I think, #9813 will actually address that.
