### ISSUE TITLE
feat: Add an Apigee source plugin

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cloudquery#9819]
### Describe the plugin

Apigee has a bunch of APIs (ha!) that would be nice to catalog and associate with their other cloud resources

https://pkg.go.dev/google.golang.org/api/apigee/v1

### Link to API documentation

https://pkg.go.dev/google.golang.org/api/apigee/v1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by maaarcelino** [comment]
Hi @Barneyjm

Thanks for raising this issue. We have released an [official Apigee source plugin](https://hub.cloudquery.io/plugins/source/cloudquery/apigee/latest/docs). It is currently in preview and includes the API proxies table you mentioned.

If you spot any problems please raise an issue and tag me.
