### ISSUE TITLE
Logs: Add startup logs to help debug throttling stuff

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#983]
### Is your feature request related to a problem? Please describe.
We encounter a lot of throttling errors. It'd be great if on startup of cloudquery we could log a bunch of related info to help debug it:

- memory on the machine
- ullimits (soft + hard)
- kernel "open file" limits

**Comment by shimonp21** [comment]
also version

**Comment by disq** [comment]
Add them to `cmd/root.go:logInvocationParams` or make another fn and call it from `rootCmd.PersistentPreRunE` just like `go:logInvocationParams` is called.

**Comment by yevgenypats** [comment]
Im closing this for now and we can reopen once we will get those issues again given a lot was changed including more consistent logging and concurrency.
