### ISSUE TITLE
bug(azure): Cost management queries hitting rate limits - 429 Too Many Requests

### ISSUE THREAD

**Issue by disq** [cloudquery/cloudquery#9860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cost management queries seem to hit the rate limits and error out if there are many views to be queried.

### Expected Behavior

Fetch successfully

### CloudQuery (redacted) logs

```
3:05PM ERR table resolver finished with error error="POST https://management.azure.com/subscriptions/<uuid>/providers/Microsoft.CostManagement/query\n--------------------------------------------------------------------------------\nRESPONSE 429: 429 Too Many Requests\nERROR CODE: 429\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"429\",\n    \"message\": \"Too many requests. Please retry.\"\n  }\n}\n--------------------------------------------------------------------------------\n" client=subscriptions/<uuid> module=azure-src table=azure_costmanagement_view_queries
```

### CloudQuery version

azure v7.1.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment]
Sharing https://github.com/Azure/azure-sdk-for-go/blob/ef4cd3ef8f9fc2deb4240daa0f822c3c9486e665/sdk/azcore/policy/policy.go#L83 for context, as we might want to look into modifying the default retry policy for this resource

**Comment by erezrokah** [comment]
We released https://github.com/cloudquery/cloudquery/releases/tag/plugins-source-azure-v10.1.0 that allows configuring the Azure SDK retry options to help with this issue
