### ISSUE TITLE
Bug: `error creating table: ERROR: out of shared memory (SQLSTATE 53200)` during fetch

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/cloudquery#991]
### Describe the Bug

On providers with many tables and relations the CloudQuery fails with `out of shared memory (SQLSTATE 53200)`

### Expected Behavior

CloudQuery should not fail with out of memory error

### CloudQuery Version

```yml
Version: 0.27.1
Commit: 5b4bb234308aad0867419414e304dcf3926a0ee3
Date: 2022-06-22T12:06:06Z
```

### Steps to Reproduce

In one terminal

```bash
git clone git@github.com:cloudquery/cq-provider-fuzz.git
cd cq-provider-fuzz
CQ_FUZZ_NUMBER_OF_RELATIONS=10 make run
```

In another terminal

```bash
docker run -p 5432:5432 -e POSTGRES_PASSWORD=pass -d postgres:10
export CQ_REATTACH_PROVIDERS=<value-from-terminal-one>
cloudquery init fuzz --config config.yml
cloudquery fetch -v
```

See failure

### Context

Could be that using a single transaction for the drop of all tables consumes more memory https://github.com/cloudquery/cloudquery/blob/357256056b5784f386c516f5179aae857c6da921/pkg/core/sync.go#L118

**Comment by irmatov** [comment]
isn't it a PostgreSQL configuration issue?

**Comment by erezrokah** [comment]
Might be solved by configuring `postgres`, but if you remove `CQ_FUZZ_NUMBER_OF_RELATIONS=10` it works

**Comment by roneli** [comment]
the default shared memory of a postgres if very small (shared_buffers is by default 128mb) I am assuming the fuzz is inserting a lot of data?  + what exactly does the number of relations mean?

**Comment by erezrokah** [comment]
> the default shared memory of a postgres if very small (shared_buffers is by default 128mb) I am assuming the fuzz is inserting a lot of data? + what exactly does the number of relations mean?

Number of relations is how many relation tables to create per parent table:https://github.com/cloudquery/cq-provider-fuzz/blob/cbf7ccefc844e96e2ff5f9ca7e33c6a7cef5c523/resources/provider/provider.go#L147

I saw the error during the part we drop the tables (before insertion). It fails right after https://github.com/cloudquery/cloudquery/blob/357256056b5784f386c516f5179aae857c6da921/pkg/core/sync.go#L118 while trying to drop all the tables in a single transaction.

I read that it somehow related to how postgres does locking within a single transaction, but haven't dug further

**Comment by erezrokah** [comment]
Closing as stale
