### ISSUE TITLE
feat: Refactor `wait-for-required-workflows`

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#9929]
### Which problem is this feature request solving?

I think the `wait-for-required-workflows` script might require an overhaul to accommodate for #9655.

I wonder if we could move the script for wait from the workflow to the separate file (easier diff, dev): https://github.com/marketplace/actions/github-script#run-a-separate-file

Additionally, I think we could benefit from splitting the logic of the wait script into distinct parts (this can be doe either together with moving the code to separate file(s) or by splitting script step into several):
* define the list of actions to wait for
* actual waiting

> **Warning**
The previous CI issue (#9388) took a couple of weeks to get resolved.

> **Note**
Currently only @erezrokah has the expertise required to review the changes.
Additionally, the changes have to be thoroughly tested.
This makes this issue a slow one to implement as well as review.

### Describe the solution you'd like

1. Move the logic to a separate JavaScript file
2. Split the functionality from single script into several scoped scripts
3. Introduce `skip-is-ok` logic for reused steps as this allows not to use runner at all and thus, save some CPU cycles/money, too

### Pull request (optional)

- [X] I can submit a pull request

**Comment by erezrokah** [comment]
Thanks for opening the issue @candiduslynx. The changes described in this issue makes sense to me, and they are low risk and should be fast to implement, specifically:

>Describe the solution you'd like
> 1. Move the logic to a separate JavaScript file
> 2. Split the functionality from single script into several scoped scripts
> 3. Introduce skip-is-ok logic for reused steps as this allows not to use runner at all and thus, save some CPU cycles/money, too

As for https://github.com/cloudquery/cloudquery/issues/9655, the bulk of that change (and the risky part) is described in https://github.com/cloudquery/cloudquery/issues/9655#issuecomment-1503122325. While the refactoring can help with making that change, I'm not sure it will reduce the risk or complexity of it. Regardless we don't need to couple those and can still do the refactoring, WDYT?

**Comment by candiduslynx** [comment]
@erezrokah your summary is on point.
I implemented mging to a separate file & split in https://github.com/cloudquery/cloudquery/pull/10072, and I think it's ready to be merged (at the very least, reviewed).
As for the skip part - I'd like to add it in a separate PR to make it a smaller change.

**Comment by yevgenypats** [comment]
Closing given low priority. if ever becomes a high priority we will re-open.
