### ISSUE TITLE
feat: Migrate `scaffold` to `github.com/cloudquery/plugin-sdk/v2`

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#9934]
### Which problem is this feature request solving?

Part of #9846

### Describe the solution you'd like

Upgrade the code.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment]
Nothing to be done here

**Comment by pkaeding** [comment]
I'm just learning about cloudquery, and writing my first plugin, so I'm likely missing something. But shouldn't at least [this](https://github.com/cloudquery/cloudquery/blob/main/scaffold/cmd/templates/source/go.mod.tpl#L6) be updated in the scaffold to start using v2?

**Comment by hermanschaaf** [comment]
@pkaeding Yes, you are correct! I've opened a PR to update it here: https://github.com/cloudquery/cloudquery/pull/10377
